GRID 1 1 2165054. 255067. 161.1
GRID_LENGTH_UNITS FEET
GROWING_SEASON 133 268 T
SUPPRESS_SCREEN_OUTPUT
OUTPUT_FUTURE_PATH 
OUTPUT_PATH 
INITIAL_ABSTRACTION_METHOD HAWKINS
PRECIPITATION SINGLE_STATION
TEMPERATURE SINGLE_STATION
FLOW_DIRECTION CONSTANT 1
SOIL_GROUP CONSTANT 1
LAND_USE CONSTANT 1
LAND_USE_LOOKUP_TABLE LU_LOOKUP_single_cell.txt
WATER_CAPACITY CONSTANT 3.0
INITIAL_SOIL_MOISTURE CONSTANT 100
INITIAL_SNOW_COVER CONSTANT 0
RUNOFF C-N DOWNHILL
ET T-M 43
DUMP_VARIABLES 1 1
SM T-M soil-moisture-retention-extended.grd
SOLVE Coshocton_Climate_1999.txt test_ future_ T T
EOJ
