GRID   4   4  630012       5102190        630612       5102790       150.0
GRID_LENGTH_UNITS METERS
OUTPUT_PATH
OUTPUT_FUTURE_PATH
OUTPUT_DAILY_PATH
OUTPUT_ANNUAL_PATH
IMAGE_ANNUAL_PATH
IMAGE_DAILY_PATH
SUPPRESS_SCREEN_OUTPUT
GROWING_SEASON 133 268 TRUE
ANSI_COLORS FALSE
RLE_MULTIPLIER 10000
PRECIPITATION SINGLE_STATION
TEMPERATURE SINGLE_STATION
OUTPUT_GRID_SUFFIX asc
INITIAL_ABSTRACTION_METHOD HAWKINS
INITIAL_FROZEN_GROUND_INDEX CONSTANT 100.0
UPPER_LIMIT_CFGI 83.
LOWER_LIMIT_CFGI 55.
FLOW_DIRECTION ARC_GRID D8_flow_direction_ESRI.asc
SOIL_GROUP ARC_GRID soil_hydrologic_groups.asc
LAND_USE ARC_GRID land_cover.asc
OPEN_WATER_LAND_USE 11
LAND_USE_LOOKUP_TABLE LU_LOOKUP.txt
IRRIGATION_LOOKUP_TABLE IRRIGATION_LOOKUP.txt
ENABLE_IRRIGATION
WATER_CAPACITY CONSTANT 3.5
SM T-M EQUATIONS
INITIAL_SOIL_MOISTURE CONSTANT 20
INITIAL_SNOW_COVER CONSTANT 0
RUNOFF C-N NO_ROUTING
ET HARGREAVES 46.4 46.6
#ET T-M 46.5

#REFERENCE_ET_SLOPE 0.0023
REFERENCE_ET_SLOPE 0.00208
REFERENCE_ET_EXPONENT 0.52

FAO56 CROP_COEFFICIENTS_ONE_FACTOR_NONSTANDARD
IGNORE_MISSING_CLIMATE_DATA
WRITE_SSF IRRIGATION_FROM_GW 2 2
WRITE_SSF REFERENCE_ET 2 2
WRITE_SSF REFERENCE_ET_ADJ 2 2
WRITE_SSF ROOTING_DEPTH 2 2
WRITE_SSF CROP_COEFFICIENT 2 2
WRITE_SSF RECHARGE 2 2
WRITE_SSF CROP_ET 2 2
WRITE_SSF BARE_SOIL_EVAP 2 2
WRITE_SSF ACT_ET 2 2
WRITE_SSF SOIL_MOISTURE 2 2
WRITE_SSF NET_RAINFALL 2 2
WRITE_SSF GROSS_PRECIP 2 2
WRITE_SSF GDD 2 2
WRITE_SSF SNOWMELT 2 2
OUTPUT_FORMAT ARC_GRID
SOLVE Mellen_WI_1989.txt
SOLVE Mellen_WI_1990.txt
EOJ
