SWB: et_blaney_criddle Module Reference
et_blaney_criddle Module Reference
Calculates potential evapotranspiration by means of the Blaney-Criddle (1950) method, as modified by Jensen and others (1990).
Public Member Functions
subroutine et_bc_configure (sRecord)
subroutine et_bc_initialize (grd, sFileName)
subroutine et_bc_computeet (pGrd, iDayOfYear, rRH, rMinRH, rWindSpd, rSunPct)
Public Attributes
real(kind=c_float) rlatitude
real(kind=c_float) rsunannual
Detailed Description
Definition at line 8 of file et_blaney_criddle.F90.
Member Function/Subroutine Documentation
subroutine et_bc_computeet (type (t_general_grid), pointer pGrd, integer (kind=c_int), intent(in) iDayOfYear, real (kind=c_float), intent(in) rRH, real (kind=c_float), intent(in) rMinRH, real (kind=c_float), intent(in) rWindSpd, real (kind=c_float), intent(in) rSunPct)
Definition at line 87 of file et_blaney_criddle.F90.
References types::dppi, types::lu_log, types::t_basin_mask::pgrd, types::rfreezing, types::rhundred, types::rmm_per_inch, types::rzero, and meteorological_functions::solar_declination().
Referenced by model::model_processet().
subroutine et_bc_configure (character (len=*), intent(inout) sRecord)
Definition at line 49 of file et_blaney_criddle.F90.
References types::dptwopi, and types::lu_log.
subroutine et_bc_initialize (type (t_general_grid), pointer grd, character (len=*), intent(in) sFileName)
Definition at line 67 of file et_blaney_criddle.F90.
References types::dppi, types::dptwopi, and types::lu_log.
Referenced by model::model_initializeet().
Member Data Documentation
real (kind=c_float) rlatitude
Definition at line 44 of file et_blaney_criddle.F90.
real (kind=c_float) rsunannual
Definition at line 45 of file et_blaney_criddle.F90.
The documentation for this module was generated from the following file:
et_blaney_criddle.F90