SOIL-WATER-BALANCE SOURCE CODE BROWSER- USGS Wisconsin Water Science Center
USGS Home
Contact USGS
Search USGS
Soil-Water-Balance Source Code Browser
runoff_curve_number Module Reference
Updates runoff curve numbers and calculates runoff based on those curve numbers.
Public Member Functions
subroutine runoff_initializecurvenumber (pGrd, pConfig)
real(kind=c_float) function prob_runoff_enhancement (rCFGI, rLL, rUL)
subroutine runoff_updatecurvenumber (pConfig, cel, iJulDay)
real(kind=c_float) function runoff_cellrunoff_curvenumber (pConfig, cel, iJulDay)
Detailed Description
Definition at line 6 of file runoff_curve_number.F90.
Member Function/Subroutine Documentation
real (kind=c_float) function runoff_curve_number::prob_runoff_enhancement (real (kind=c_float) rCFGI, real (kind=c_float) rLL, real (kind=c_float) rUL)
Definition at line 107 of file runoff_curve_number.F90.
References types::t_cell::rcfgi, types::rone, and types::rzero.
Referenced by runoff_updatecurvenumber().
real (kind=c_float) function runoff_curve_number::runoff_cellrunoff_curvenumber (type (t_model_configuration), pointer pConfig, type (t_cell), pointer cel, integer (kind=c_int), intent(in) iJulDay)
Definition at line 224 of file runoff_curve_number.F90.
References types::config_sm_init_abstraction_hawkins, types::config_sm_init_abstraction_tr55, types::lfalse, types::t_cell::routflow, types::rpoint2, types::rpoint8, types::rten, types::rthousand, runoff_updatecurvenumber(), and types::rzero.
Referenced by model::rf_model_cellrunoff().
subroutine runoff_curve_number::runoff_initializecurvenumber (type (t_general_grid), pointer pGrd, type (t_model_configuration), pointer pConfig)
Definition at line 28 of file runoff_curve_number.F90.
References swb_grid::grid_writearcgrid(), types::iinactive_cell, types::lfalse, types::ltrue, types::lu_log, and types::t_basin_mask::pgrd.
Referenced by model::model_initializelanduserelatedparams().
subroutine runoff_curve_number::runoff_updatecurvenumber (type (t_model_configuration), pointer pConfig, type (t_cell), pointer cel, integer (kind=c_int), intent(in) iJulDay)
Definition at line 128 of file runoff_curve_number.F90.
References types::lf_model_growingseason(), prob_runoff_enhancement(), types::rhundred, types::rnear_zero, and types::rzero.
Referenced by runoff_cellrunoff_curvenumber().
The documentation for this module was generated from the following file:
runoff_curve_number.F90
USGS Home Water Resources Biology Geography Geology Geospatial SWB Home Wisconsin WSC
Accessibility FOIA Privacy Policies and Notices
U.S. Department of the Interior | U.S. Geological Survey
URL: http://wi.water.usgs.gov/Soil_Water_Balance/SWB_code_docs/index.html
Page Contact Information: webmaster@wi.water.usgs.gov
Page Last Modified: Thu May 19 2011 14:11:32
Page generated with:
1.8.2