SOIL-WATER-BALANCE SOURCE CODE BROWSER- USGS Wisconsin Water Science Center
USGS Home
Contact USGS
Search USGS
Soil-Water-Balance Source Code Browser
et_jensen_haise Module Reference
Calculates potential evapotranspiration by means of the Jensen-Haise (1963) method.
Public Member Functions
subroutine et_jh_configure (sRecord)
subroutine et_jh_initialize (grd, sFileName)
subroutine et_jh_computeet (pGrd, iDayOfYear, rRH, rMinRH, rWindSpd, rSunPct)
Public Attributes
real(kind=t_sgl) rlatitude
real(kind=t_sgl) ralbedo
real(kind=t_sgl) ras
real(kind=t_sgl) rbs
Detailed Description
Definition at line 8 of file et_jensen_haise.F90.
Member Function/Subroutine Documentation
subroutine et_jensen_haise::et_jh_computeet (type (t_general_grid), pointer pGrd, integer (kind=t_int), intent(in) iDayOfYear, real (kind=t_sgl), intent(in) rRH, real (kind=t_sgl), intent(in) rMinRH, real (kind=t_sgl), intent(in) rWindSpd, real (kind=t_sgl), intent(in) rSunPct)
Definition at line 83 of file et_jensen_haise.F90.
References types::dptwopi, types::ftoc(), types::t_model_configuration::idayofyear, types::t_basin_mask::pgrd, types::rfreezing, types::rhundred, types::t_time_series_file::rminrh, types::rone, types::t_time_series_file::rsunpct, types::t_time_series_file::rwindspd, and types::rzero.
Referenced by model::model_processet().
subroutine et_jensen_haise::et_jh_configure (character (len=*), intent(inout) sRecord)
Definition at line 40 of file et_jensen_haise.F90.
References types::dptwopi, and types::lu_log.
Referenced by control::control_setmodeloptions().
subroutine et_jensen_haise::et_jh_initialize (type (t_general_grid), pointer grd, character (len=*), intent(in) sFileName)
Definition at line 70 of file et_jensen_haise.F90.
References types::lu_log.
Referenced by model::model_initializeet().
Member Data Documentation
real (kind=t_sgl) et_jensen_haise::ralbedo
Definition at line 34 of file et_jensen_haise.F90.
real (kind=t_sgl) et_jensen_haise::ras
Definition at line 35 of file et_jensen_haise.F90.
real (kind=t_sgl) et_jensen_haise::rbs
Definition at line 36 of file et_jensen_haise.F90.
real (kind=t_sgl) et_jensen_haise::rlatitude
Definition at line 33 of file et_jensen_haise.F90.
The documentation for this module was generated from the following file:
et_jensen_haise.F90
USGS Home Water Resources Biology Geography Geology Geospatial SWB Home Wisconsin WSC
Accessibility FOIA Privacy Policies and Notices
U.S. Department of the Interior | U.S. Geological Survey
URL: http://wi.water.usgs.gov/Soil_Water_Balance/SWB_code_docs/index.html
Page Contact Information: webmaster@wi.water.usgs.gov
Page Last Modified: Thu May 19 2011 14:11:32
Page generated with:
1.8.2