SOIL-WATER-BALANCE SOURCE CODE BROWSER- USGS Wisconsin Water Science Center
USGS Home
Contact USGS
Search USGS
Soil-Water-Balance Source Code Browser
netcdf_support Module Reference
Provides support for use of NetCDF files as input for time-varying, gridded meteorlogic data, or output for any SWB-generated variable.
Data Types
type t_ellipsoid
Public Member Functions
integer(kind=t_int) function netcdf_create (sNetCDF_Filename)
integer(kind=t_int) function netcdf_open (sNetCDF_Filename)
subroutine netcdf_info (pConfig, iVarNum, iMode, sVariableName)
subroutine netcdf_chk_extent (pConfig, iVarNum, iMode, pGrd)
subroutine netcdf_read (iVarNum, iMode, pConfig, pGrd, pDataGrd, iJulianDay)
subroutine netcdf_write_attributes (iVarNum, iMode, pConfig, pGrd)
subroutine netcdf_write_variable (iVarNum, iMode, pConfig, pGrd, iTime)
subroutine netcdf_write_variable_byte (iVarNum, iMode, pConfig, rValue, pGrd, iRow, iCol, iTime)
subroutine netcdf_check (iStatus, sFilename, iLineNo, pNC, iTime, rValue)
subroutine lltoutm (pConfig, rLat, rLong, rUTMNorthing, rUTMEasting, iZoneNumber)
subroutine utmtoll (pConfig, rUTMEasting, rUTMNorthing, rLat, rLong)
Public Attributes
type(t_ellipsoid), dimension(24),
target ellipsoid (/ T_ELLIPSOID(1, "Airy", 6377563_T_DBL, 0.00667054), T_ELLIPSOID(2, "Australian National", 6378160_T_DBL, 0.006694542), T_ELLIPSOID(3, "Bessel 1841", 6377397_T_DBL, 0.006674372), T_ELLIPSOID(4, "Bessel 1841 (Nambia) ", 6377484, 0.006674372), T_ELLIPSOID(5, "Clarke 1866", 6378206, 0.006768658), T_ELLIPSOID(6, "Clarke 1880", 6378249, 0.006803511), T_ELLIPSOID(7, "Everest", 6377276, 0.006637847), T_ELLIPSOID(8, "Fischer 1960 (Mercury) ", 6378166, 0.006693422), T_ELLIPSOID(9, "Fischer 1968", 6378150, 0.006693422), T_ELLIPSOID(10, "GRS 1967", 6378160, 0.006694605), T_ELLIPSOID(11, "GRS 1980", 6378137_T_DBL, 0.00669438_T_DBL), T_ELLIPSOID(12, "Helmert 1906", 6378200, 0.006693422), T_ELLIPSOID(13, "Hough", 6378270, 0.00672267), T_ELLIPSOID(14, "International", 6378388, 0.00672267), T_ELLIPSOID(15, "Krassovsky", 6378245, 0.006693422), T_ELLIPSOID(16, "Modified Airy", 6377340, 0.00667054), T_ELLIPSOID(17, "Modified Everest", 6377304, 0.006637847), T_ELLIPSOID(18, "Modified Fischer 1960", 6378155, 0.006693422), T_ELLIPSOID(19, "South American 1969", 6378160, 0.006694542), T_ELLIPSOID(20, "WGS 60", 6378165, 0.006693422), T_ELLIPSOID(21, "WGS 66", 6378145, 0.006694542), T_ELLIPSOID(22, "WGS-72", 6378135, 0.006694318), T_ELLIPSOID(23, "WGS-84", 6378137, 0.00669438), T_ELLIPSOID(24, "Placeholder", 0, 0) /)
Detailed Description
Definition at line 7 of file netcdf_support.F90.
Member Function/Subroutine Documentation
subroutine netcdf_support::lltoutm (type (t_model_configuration), pointer pConfig, real (kind=t_dbl), intent(in) rLat, real (kind=t_dbl), intent(in) rLong, real (kind=t_dbl), intent(out) rUTMNorthing, real (kind=t_dbl), intent(out) rUTMEasting, integer (kind=t_int), intent(out) iZoneNumber)
Definition at line 1147 of file netcdf_support.F90.
References types::dppi, types::t_netcdf_file::izonenumber, types::t_irrigation_lookup::rk0, and types::t_netcdf_file::rlongorigin.
subroutine netcdf_support::netcdf_check (integer(kind=t_int), intent(in) iStatus, character(len=*), optional sFilename, integer (kind=t_int), optional iLineNo, type (t_netcdf_file), optional, pointer pNC, integer (kind=t_int), optional iTime, real(kind=t_sgl), optional rValue)
Definition at line 1101 of file netcdf_support.F90.
References types::int2char(), types::lfalse, types::real2char(), and types::t_ssf_files::sfilename.
Referenced by model::model_endofrun(), netcdf_create(), netcdf_info(), netcdf_open(), netcdf_read(), netcdf_write_attributes(), netcdf_write_variable(), and netcdf_write_variable_byte().
subroutine netcdf_support::netcdf_chk_extent (type (t_model_configuration), pointer pConfig, integer (kind=t_int) iVarNum, integer (kind=t_int) iMode, type (t_general_grid), pointer pGrd)
Definition at line 574 of file netcdf_support.F90.
References types::t_ssf_files::ivarnum, types::lfalse, types::lu_log, and types::t_basin_mask::pgrd.
Referenced by control::control_setmodeloptions().
integer(kind=t_int) function netcdf_support::netcdf_create (character(len=*) sNetCDF_Filename)
Definition at line 55 of file netcdf_support.F90.
References types::t_netcdf_file::incid, types::lu_log, and netcdf_check().
Referenced by model::model_write_netcdf_attributes().
subroutine netcdf_support::netcdf_info (type (t_model_configuration), pointer pConfig, integer (kind=t_int) iVarNum, integer (kind=t_int) iMode, character(len=*) sVariableName)
Definition at line 84 of file netcdf_support.F90.
References types::dquote(), types::gregorian_date(), types::t_model_configuration::iday, types::t_month::imonth, types::int2char(), types::t_ssf_files::ivarnum, types::t_netcdf_file::ivartype, types::t_model_configuration::iyear, types::julian_day(), types::lfalse, types::ltrue, types::lu_log, netcdf_check(), types::str_compare(), and types::t_netcdf_file::svarname.
Referenced by control::control_setmodeloptions().
integer(kind=t_int) function netcdf_support::netcdf_open (character(len=*) sNetCDF_Filename)
Definition at line 69 of file netcdf_support.F90.
References types::t_netcdf_file::incid, types::lu_log, and netcdf_check().
Referenced by control::control_setmodeloptions().
subroutine netcdf_support::netcdf_read (integer(kind=t_int) iVarNum, integer (kind=t_int) iMode, type (t_model_configuration), pointer pConfig, type (t_general_grid), pointer pGrd, type (t_general_grid), pointer pDataGrd, integer(kind=t_int) iJulianDay)
Definition at line 628 of file netcdf_support.F90.
References swb_grid::grid_conform(), types::t_ssf_files::ivarnum, netcdf_check(), types::t_basin_mask::pgrd, and types::rbigval.
Referenced by model::model_getdailyprecipvalue(), and model::model_getdailytemperaturevalue().
subroutine netcdf_support::netcdf_write_attributes (integer(kind=t_int) iVarNum, integer (kind=t_int) iMode, type (t_model_configuration), pointer pConfig, type (t_general_grid), pointer pGrd)
Definition at line 766 of file netcdf_support.F90.
References types::getsystimedate(), types::gregorian_date(), swb_grid::grid_getgridx(), swb_grid::grid_getgridy(), types::t_model_configuration::iday, types::igrid_length_units_feet, types::t_month::imonth, types::t_ssf_files::ivarnum, types::t_model_configuration::iyear, netcdf_check(), types::t_basin_mask::pgrd, and types::rone.
Referenced by model::model_write_netcdf_attributes().
subroutine netcdf_support::netcdf_write_variable (integer(kind=t_int) iVarNum, integer (kind=t_int) iMode, type (t_model_configuration), pointer pConfig, type (t_general_grid), pointer pGrd, integer (kind=t_int) iTime)
Definition at line 1021 of file netcdf_support.F90.
References types::t_ssf_files::ivarnum, netcdf_check(), and types::t_basin_mask::pgrd.
subroutine netcdf_support::netcdf_write_variable_byte (integer(kind=t_int) iVarNum, integer (kind=t_int) iMode, type (t_model_configuration), pointer pConfig, real(kind=t_sgl) rValue, type (t_general_grid), pointer pGrd, integer(kind=t_int) iRow, integer(kind=t_int) iCol, integer (kind=t_int) iTime)
Definition at line 1057 of file netcdf_support.F90.
References types::t_ssf_files::ivarnum, netcdf_check(), and types::t_basin_mask::pgrd.
Referenced by sm_thornthwaite_mather::sm_thornthwaite_mather_updatesm().
subroutine netcdf_support::utmtoll (type (t_model_configuration), pointer pConfig, real (kind=t_dbl), intent(in) rUTMEasting, real (kind=t_dbl), intent(in) rUTMNorthing, real (kind=t_dbl), intent(out) rLat, real (kind=t_dbl), intent(out) rLong)
Definition at line 1241 of file netcdf_support.F90.
References types::dppi, and types::t_irrigation_lookup::rk0.
Member Data Documentation
type (t_ellipsoid), dimension(24), target netcdf_support::ellipsoid (/ T_ELLIPSOID(1, "Airy", 6377563_T_DBL, 0.00667054), T_ELLIPSOID(2, "Australian National", 6378160_T_DBL, 0.006694542), T_ELLIPSOID(3, "Bessel 1841", 6377397_T_DBL, 0.006674372), T_ELLIPSOID(4, "Bessel 1841 (Nambia) ", 6377484, 0.006674372), T_ELLIPSOID(5, "Clarke 1866", 6378206, 0.006768658), T_ELLIPSOID(6, "Clarke 1880", 6378249, 0.006803511), T_ELLIPSOID(7, "Everest", 6377276, 0.006637847), T_ELLIPSOID(8, "Fischer 1960 (Mercury) ", 6378166, 0.006693422), T_ELLIPSOID(9, "Fischer 1968", 6378150, 0.006693422), T_ELLIPSOID(10, "GRS 1967", 6378160, 0.006694605), T_ELLIPSOID(11, "GRS 1980", 6378137_T_DBL, 0.00669438_T_DBL), T_ELLIPSOID(12, "Helmert 1906", 6378200, 0.006693422), T_ELLIPSOID(13, "Hough", 6378270, 0.00672267), T_ELLIPSOID(14, "International", 6378388, 0.00672267), T_ELLIPSOID(15, "Krassovsky", 6378245, 0.006693422), T_ELLIPSOID(16, "Modified Airy", 6377340, 0.00667054), T_ELLIPSOID(17, "Modified Everest", 6377304, 0.006637847), T_ELLIPSOID(18, "Modified Fischer 1960", 6378155, 0.006693422), T_ELLIPSOID(19, "South American 1969", 6378160, 0.006694542), T_ELLIPSOID(20, "WGS 60", 6378165, 0.006693422), T_ELLIPSOID(21, "WGS 66", 6378145, 0.006694542), T_ELLIPSOID(22, "WGS-72", 6378135, 0.006694318), T_ELLIPSOID(23, "WGS-84", 6378137, 0.00669438), T_ELLIPSOID(24, "Placeholder", 0, 0) /)
Definition at line 25 of file netcdf_support.F90.
The documentation for this module was generated from the following file:
netcdf_support.F90
USGS Home Water Resources Biology Geography Geology Geospatial SWB Home Wisconsin WSC
Accessibility FOIA Privacy Policies and Notices
U.S. Department of the Interior | U.S. Geological Survey
URL: http://wi.water.usgs.gov/Soil_Water_Balance/SWB_code_docs/index.html
Page Contact Information: webmaster@wi.water.usgs.gov
Page Last Modified: Thu May 19 2011 14:11:32
Page generated with:
1.8.2