SOIL-WATER-BALANCE SOURCE CODE BROWSER- USGS Wisconsin Water Science Center
USGS Home
Contact USGS
Search USGS
Soil-Water-Balance Source Code Browser
et_thornthwaite_mather Module Reference
Calculates potential evapotranspiration by means of the Thornthwaite-Mather (1955, 1957) method.
Public Member Functions
subroutine et_tm_configure (sRecord)
subroutine et_tm_initialize (pGrd, pConfig, sFileName)
subroutine et_tm_computeet (pGrd, pConfig, iDayOfYear, rRH, rMinRH, rWindSpd, rSunPct)
Public Attributes
real(kind=t_sgl) rlatitude
real(kind=t_sgl) rtanlatitude
real(kind=t_sgl) rannualindex
real(kind=t_sgl) rexponenta
Detailed Description
Definition at line 8 of file et_thornthwaite_mather.F90.
Member Function/Subroutine Documentation
subroutine et_thornthwaite_mather::et_tm_computeet (type (t_general_grid), pointer pGrd, type (t_model_configuration), pointer pConfig, integer (kind=t_int), intent(in) iDayOfYear, real (kind=t_sgl), intent(in) rRH, real (kind=t_sgl), intent(in) rMinRH, real (kind=t_sgl), intent(in) rWindSpd, real (kind=t_sgl), intent(in) rSunPct)
Definition at line 149 of file et_thornthwaite_mather.F90.
References types::dppi, types::dptwopi, types::t_model_configuration::idayofyear, types::t_basin_mask::pgrd, types::polynomial(), types::rfreezing, and types::rzero.
Referenced by model::model_processet().
subroutine et_thornthwaite_mather::et_tm_configure (character (len=*), intent(inout) sRecord)
Definition at line 49 of file et_thornthwaite_mather.F90.
References types::dptwopi, and types::lu_log.
Referenced by control::control_setmodeloptions().
subroutine et_thornthwaite_mather::et_tm_initialize (type (t_general_grid), pointer pGrd, type (t_model_configuration), pointer pConfig, character (len=*), intent(in) sFileName)
Definition at line 68 of file et_thornthwaite_mather.F90.
References types::cleanupcsv(), types::t_model_configuration::iday, types::t_model_configuration::idayofyear, types::t_month::imonth, types::t_model_configuration::iyear, types::lookupmonth(), types::lu_log, types::lu_temp, types::polynomial(), types::t_time_series_file::ravgt, types::rfreezing, types::t_time_series_file::rmaxt, types::t_time_series_file::rminrh, types::t_time_series_file::rmint, types::t_time_series_file::rprecip, types::t_time_series_file::rrh, types::t_time_series_file::rsunpct, types::t_time_series_file::rwindspd, types::rzero, and types::t_ssf_files::sfilename.
Referenced by model::model_initializeet().
Member Data Documentation
real (kind=t_sgl) et_thornthwaite_mather::rannualindex
Definition at line 44 of file et_thornthwaite_mather.F90.
real (kind=t_sgl) et_thornthwaite_mather::rexponenta
Definition at line 45 of file et_thornthwaite_mather.F90.
real (kind=t_sgl) et_thornthwaite_mather::rlatitude
Definition at line 40 of file et_thornthwaite_mather.F90.
real (kind=t_sgl) et_thornthwaite_mather::rtanlatitude
Definition at line 41 of file et_thornthwaite_mather.F90.
The documentation for this module was generated from the following file:
et_thornthwaite_mather.F90
USGS Home Water Resources Biology Geography Geology Geospatial SWB Home Wisconsin WSC
Accessibility FOIA Privacy Policies and Notices
U.S. Department of the Interior | U.S. Geological Survey
URL: http://wi.water.usgs.gov/Soil_Water_Balance/SWB_code_docs/index.html
Page Contact Information: webmaster@wi.water.usgs.gov
Page Last Modified: Thu May 19 2011 14:11:32
Page generated with:
1.8.2