SOIL-WATER-BALANCE SOURCE CODE BROWSER- USGS Wisconsin Water Science Center
USGS Home
Contact USGS
Search USGS
Soil-Water-Balance Source Code Browser
meteorological_functions Module Reference
Provides support functions used by evapotranspiration and snow routines.
Public Member Functions
real(kind=t_sgl) function daylight_hours (rOmega_s)
Calculates the number of daylight hours at a location.
real(kind=t_sgl) function extraterrestrial_radiation_ra (rLatitude, rDelta, rOmega_s, rDsubR)
real(kind=t_sgl) function deg2rad (rDeg)
real(kind=t_sgl) function equivalent_evaporation (rR)
real(kind=t_sgl) function row_latitude (rNorthLat, rSouthLat, iNumRows, iCurrRow)
real(kind=t_dbl) function sensible_heat_exchange_h (rTSnow, rTAvg, rWindSpd)
real(kind=t_dbl) function convective_heat_exchange_e (rTSnow, rTAvg, rWindSpd)
real(kind=t_sgl) function net_shortwave_radiation_rns (rRs, rAlbedo)
real(kind=t_sgl) function precipitation_heat_p (rPrecipAmount, rTAvg)
real(kind=t_sgl) function solar_declination (iDayOfYear, iNumDaysInYear)
real(kind=t_sgl) function rel_earth_sun_dist (iDayOfYear, iNumDaysInYear)
real(kind=t_sgl) function sunset_angle (rLatitude, rDelta)
real(kind=t_sgl) function solar_radiation_hargreaves_rs (rRa, rTMIN, rTMAX)
real(kind=t_sgl) function clear_sky_solar_radiation_rso (rRa, rAs_in, rBs_in)
real(kind=t_sgl) function clear_sky_solar_radiation_noab_rso (rRa, rElevation)
real(kind=t_sgl) function solar_radiation_rs (rRa, rAs, rBs, rPctSun)
real(kind=t_sgl) function sat_vapor_pressure_es (rT)
real(kind=t_sgl) function sat_vapor_density (rT)
real(kind=t_sgl) function dewpoint_vapor_pressure_ea (rTMIN)
real(kind=t_sgl) function minimum_rel_hum (rTMin, rTMax)
real(kind=t_sgl) function maximum_rel_hum (rTMin)
real(kind=t_sgl) function net_longwave_radiation_rnl (rTMin, rTMax, rRs, rRso)
real(kind=t_sgl) function zenith_angle (rLatitude, rDelta)
real(kind=t_sgl) function slope_sat_vapor_pressure_curve (rT)
real(kind=t_sgl) function calc_crop_coefficient (rKc_Max, rK0, rGDD_Kc_Max, rGDD_Death, rAlpha1, rGDD)
Detailed Description
Note
Many of the routines included here are based on equations given in the following reference:
Allen, R.G., and others, 2006, FAO Irrigation and Drainage Paper No. 56, "Crop Evapotranspiration (Guidelines for computing crop water requirements)", Food and Agriculture Organization, Rome, Italy.
Definition at line 13 of file meteorological_functions.F90.
Member Function/Subroutine Documentation
real (kind=t_sgl) function meteorological_functions::calc_crop_coefficient (real (kind=t_sgl) rKc_Max, real (kind=t_sgl) rK0, real (kind=t_sgl) rGDD_Kc_Max, real (kind=t_sgl) rGDD_Death, real (kind=t_sgl) rAlpha1, real (kind=t_sgl) rGDD)
Definition at line 1151 of file meteorological_functions.F90.
References types::t_irrigation_lookup::ralpha1, types::t_cell::rgdd, types::t_irrigation_lookup::rk0, and types::t_irrigation_lookup::rkc_max.
Referenced by model::model_processet().
real (kind=t_sgl) function meteorological_functions::clear_sky_solar_radiation_noab_rso (real (kind=t_sgl), intent(in) rRa, real (kind=t_sgl), intent(in) rElevation)
Definition at line 748 of file meteorological_functions.F90.
References types::t_cell::relevation.
real (kind=t_sgl) function meteorological_functions::clear_sky_solar_radiation_rso (real (kind=t_sgl), intent(in) rRa, real (kind=t_sgl), intent(in), optional rAs_in, real (kind=t_sgl), intent(in), optional rBs_in)
Definition at line 686 of file meteorological_functions.F90.
Referenced by model::model_processrainprms().
real(kind=t_dbl) function meteorological_functions::convective_heat_exchange_e (real (kind=t_sgl) rTSnow, real (kind=t_sgl) rTAvg, real (kind=t_sgl), optional rWindSpd)
Definition at line 346 of file meteorological_functions.F90.
References types::t_cell::rtavg, types::t_time_series_file::rwindspd, and sat_vapor_density().
Referenced by snow::snow_energy_balance().
real (kind=t_sgl) function meteorological_functions::daylight_hours (real (kind=t_sgl), intent(in) rOmega_s)
Parameters
rOmega_s The sunset hour angle in Radians.
Returns
rN The number of daylight hours.
Note
Implemented as equation 34, Allen and others (2006).
Allen, R.G., and others, 2006, FAO Irrigation and Drainage Paper No. 56, "Crop Evapotranspiration (Guidelines for computing crop water requirements)", Food and Agriculture Organization, Rome, Italy.
Definition at line 70 of file meteorological_functions.F90.
References types::dppi.
Referenced by model::model_processrainprms().
real (kind=t_sgl) function meteorological_functions::deg2rad (real (kind=t_sgl), intent(in) rDeg)
Definition at line 156 of file meteorological_functions.F90.
References types::dppi.
real (kind=t_sgl) function meteorological_functions::dewpoint_vapor_pressure_ea (real (kind=t_sgl), intent(in) rTMIN)
Definition at line 898 of file meteorological_functions.F90.
References types::ftoc(), and types::t_cell::rtmin.
Referenced by maximum_rel_hum(), minimum_rel_hum(), and net_longwave_radiation_rnl().
real (kind=t_sgl) function meteorological_functions::equivalent_evaporation (real (kind=t_sgl), intent(in) rR)
Definition at line 189 of file meteorological_functions.F90.
Referenced by et_hargreaves::et_hargreaves_computeet().
real (kind=t_sgl) function meteorological_functions::extraterrestrial_radiation_ra (real (kind=t_sgl), intent(in) rLatitude, real (kind=t_sgl), intent(in) rDelta, real (kind=t_sgl), intent(in) rOmega_s, real (kind=t_sgl), intent(in) rDsubR)
Definition at line 117 of file meteorological_functions.F90.
References types::dppi.
Referenced by et_hargreaves::et_hargreaves_computeet(), and model::model_processrainprms().
real (kind=t_sgl) function meteorological_functions::maximum_rel_hum (real (kind=t_sgl), intent(in) rTMin)
Definition at line 982 of file meteorological_functions.F90.
References dewpoint_vapor_pressure_ea(), types::t_cell::rtmin, and sat_vapor_pressure_es().
real (kind=t_sgl) function meteorological_functions::minimum_rel_hum (real (kind=t_sgl), intent(in) rTMin, real (kind=t_sgl), intent(in) rTMax)
Definition at line 939 of file meteorological_functions.F90.
References dewpoint_vapor_pressure_ea(), types::t_time_series_file::rminrh, types::t_cell::rtmax, types::t_cell::rtmin, and sat_vapor_pressure_es().
real(kind=t_sgl) function meteorological_functions::net_longwave_radiation_rnl (real(kind=t_sgl), intent(in) rTMin, real(kind=t_sgl), intent(in) rTMax, real(kind=t_sgl), intent(in) rRs, real(kind=t_sgl), intent(in) rRso)
Definition at line 1028 of file meteorological_functions.F90.
References dewpoint_vapor_pressure_ea(), types::ftok(), types::t_cell::rtmax, and types::t_cell::rtmin.
Referenced by model::model_processrainprms(), and snow::snow_energy_balance().
real(kind=t_sgl) function meteorological_functions::net_shortwave_radiation_rns (real(kind=t_sgl), intent(in) rRs, real(kind=t_sgl), intent(in) rAlbedo)
Definition at line 406 of file meteorological_functions.F90.
References types::rone.
Referenced by model::model_processrainprms(), and snow::snow_energy_balance().
real (kind=t_sgl) function meteorological_functions::precipitation_heat_p (real (kind=t_sgl) rPrecipAmount, real (kind=t_sgl) rTAvg)
Definition at line 466 of file meteorological_functions.F90.
References types::ftoc(), types::t_cell::rtavg, and types::rzero.
Referenced by snow::snow_energy_balance().
real (kind=t_sgl) function meteorological_functions::rel_earth_sun_dist (integer (kind=t_int), intent(in) iDayOfYear, integer (kind=t_int), intent(in) iNumDaysInYear)
Definition at line 549 of file meteorological_functions.F90.
References types::dppi, types::t_model_configuration::idayofyear, and types::t_model_configuration::inumdaysinyear.
Referenced by et_hargreaves::et_hargreaves_computeet(), and model::model_processrainprms().
real (kind=t_sgl) function meteorological_functions::row_latitude (real (kind=t_sgl), intent(in) rNorthLat, real (kind=t_sgl), intent(in) rSouthLat, integer (kind=t_int), intent(in) iNumRows, integer (kind=t_int), intent(in) iCurrRow)
Definition at line 224 of file meteorological_functions.F90.
Referenced by et_hargreaves::et_hargreaves_computeet(), and model::model_processrainprms().
real(kind=t_sgl) function meteorological_functions::sat_vapor_density (real(kind=t_sgl), intent(in) rT)
Definition at line 857 of file meteorological_functions.F90.
References types::ftoc(), and types::ftok().
Referenced by convective_heat_exchange_e().
real (kind=t_sgl) function meteorological_functions::sat_vapor_pressure_es (real (kind=t_sgl), intent(in) rT)
Definition at line 840 of file meteorological_functions.F90.
References types::ftoc().
Referenced by maximum_rel_hum(), and minimum_rel_hum().
real(kind=t_dbl) function meteorological_functions::sensible_heat_exchange_h (real (kind=t_sgl) rTSnow, real (kind=t_sgl) rTAvg, real (kind=t_sgl), optional rWindSpd)
Definition at line 268 of file meteorological_functions.F90.
References types::ftoc(), types::t_time_series_file::rrh, types::t_cell::rtavg, and types::t_time_series_file::rwindspd.
Referenced by snow::snow_energy_balance().
real (kind=t_sgl) function meteorological_functions::slope_sat_vapor_pressure_curve (real (kind=t_sgl), intent(in) rT)
Definition at line 1133 of file meteorological_functions.F90.
References types::ftoc().
real (kind=t_sgl) function meteorological_functions::solar_declination (integer (kind=t_int), intent(in) iDayOfYear, integer (kind=t_int), intent(in) iNumDaysInYear)
Definition at line 505 of file meteorological_functions.F90.
References types::dppi, types::t_model_configuration::idayofyear, and types::t_model_configuration::inumdaysinyear.
Referenced by et_hargreaves::et_hargreaves_computeet(), and model::model_processrainprms().
real (kind=t_sgl) function meteorological_functions::solar_radiation_hargreaves_rs (real (kind=t_sgl), intent(in) rRa, real (kind=t_sgl), intent(in) rTMIN, real (kind=t_sgl), intent(in) rTMAX)
Definition at line 639 of file meteorological_functions.F90.
References types::ftoc(), types::t_cell::rtmax, and types::t_cell::rtmin.
Referenced by model::model_processrainprms().
real (kind=t_sgl) function meteorological_functions::solar_radiation_rs (real (kind=t_sgl), intent(in) rRa, real (kind=t_sgl), intent(in) rAs, real (kind=t_sgl), intent(in) rBs, real (kind=t_sgl), intent(in) rPctSun)
Definition at line 795 of file meteorological_functions.F90.
real (kind=t_sgl) function meteorological_functions::sunset_angle (real (kind=t_sgl), intent(in) rLatitude, real (kind=t_sgl), intent(in) rDelta)
Definition at line 591 of file meteorological_functions.F90.
Referenced by et_hargreaves::et_hargreaves_computeet(), and model::model_processrainprms().
real (kind=t_sgl) function meteorological_functions::zenith_angle (real (kind=t_sgl), intent(in) rLatitude, real (kind=t_sgl), intent(in) rDelta)
Definition at line 1085 of file meteorological_functions.F90.
Referenced by model::model_processrainprms().
The documentation for this module was generated from the following file:
meteorological_functions.F90
USGS Home Water Resources Biology Geography Geology Geospatial SWB Home Wisconsin WSC
Accessibility FOIA Privacy Policies and Notices
U.S. Department of the Interior | U.S. Geological Survey
URL: http://wi.water.usgs.gov/Soil_Water_Balance/SWB_code_docs/index.html
Page Contact Information: webmaster@wi.water.usgs.gov
Page Last Modified: Thu May 19 2011 14:11:32
Page generated with:
1.8.2