SWB: graph Module Reference
graph Module Reference
Creates plots through calls to the DISLIN library.
Public Member Functions
subroutine makegraph (pGraph, pGrd, iVarNum)
subroutine make_shaded_contour (pGrd, sOutputFilename, sTitleTxt, sAxisTxt, rMinZVal, rMaxZVal)
subroutine makecolortable ()
Detailed Description
Definition at line 7 of file graph.F90.
Member Function/Subroutine Documentation
subroutine make_shaded_contour (type (t_general_grid), pointer pGrd, character (len=*) sOutputFilename, character (len=*) sTitleTxt, character (len=*) sAxisTxt, real (kind=c_float), optional rMinZVal, real (kind=c_float), optional rMaxZVal)
Definition at line 374 of file graph.F90.
References types::datatype_cell_grid, types::datatype_int, types::datatype_real, types::iactive_cell, types::t_general_grid::imask, types::t_general_grid::inumgridcells, types::lfalse, and types::t_basin_mask::pgrd.
Referenced by model::model_configurerunoffdownhill(), model::model_initializedatastructures(), model::model_solve(), and model::model_writegrids().
subroutine makecolortable ()
Definition at line 660 of file graph.F90.
Referenced by makegraph().
subroutine makegraph (type(t_graph_configuration), dimension(:), pointer pGraph, type (t_general_grid), pointer pGrd, integer (kind=c_int), intent(in) iVarNum)
Definition at line 18 of file graph.F90.
References types::datatype_cell_grid, types::datatype_int, types::datatype_real, types::iactive_cell, types::t_general_grid::imask, types::t_general_grid::inumgridcells, types::t_ssf_files::ivarnum, types::lfalse, makecolortable(), types::t_basin_mask::pgrd, types::t_basin_mask::rmax, types::t_basin_mask::rmean, and types::t_basin_mask::rmin.
Referenced by stats::stats_calcmeanrecharge(), and stats::stats_rewritegrids().
The documentation for this module was generated from the following file:
graph.F90