SOIL-WATER-BALANCE SOURCE CODE BROWSER- USGS Wisconsin Water Science Center
USGS Home
Contact USGS
Search USGS
Soil-Water-Balance Source Code Browser
swb_grid Module Reference
Provides support for input and output of gridded ASCII data, as well as for creation and destruction of grid data structures (defined types).
Data Types
interface grid_create
interface grid_gridtogrid
interface pj_init_and_transform
interface to C code that provides a simplified entry point to PROJ4 capabilities: it has been modified so that all C pointers are kept within the C code; no pointers are returned to fortran
type t_error_message
Public Member Functions
type(t_general_grid) function,
pointer grid_createcomplete (iNX, iNY, rX0, rY0, rX1, rY1, iDataType)
Creates a grid of a specified type.
type(t_general_grid) function,
pointer grid_createsimple (iNX, iNY, rX0, rY0, rGridCellSize, iDataType)
subroutine grid_destroy (pGrd)
type(t_general_grid) function,
pointer grid_read (sFilename, sFileType, iDataType)
subroutine grid_readexisting (sFileName, sFileType, pGrd)
type(t_general_grid) function,
pointer grid_readarcgrid_fn (sFileName, iDataType)
subroutine grid_readarcgrid_sub (sFileName, pGrd)
type(t_general_grid) function,
pointer grid_readsurfergrid_fn (sFileName, iDataType)
subroutine grid_readsurfergrid_sub (sFileName, pGrd)
subroutine grid_writegrid (sFilename, pGrd, iOutputFormat)
subroutine grid_writearcgrid (sFilename, pGrd)
subroutine grid_writesurfergrid (sFilename, pGrd)
logical(kind=c_bool) function grid_conform (pGrd1, pGrd2, rTolerance)
logical(kind=c_bool) function grid_completelycover (pBaseGrd, pOtherGrd, rTolerance)
subroutine grid_lookupcolumn (pGrd, rXval, iBefore, iAfter, rFrac)
subroutine grid_lookuprow (pGrd, rYval, iBefore, iAfter, rFrac)
subroutine grid_transform (pGrd, sFromPROJ4, sToPROJ4)
Call PROJ4 to transform coordinates.
subroutine grid_checkforproj4error (iRetVal, sFromPROJ4, sToPROJ4)
real(kind=c_float) function grid_interpolate (pGrd, rXval, rYval)
real(kind=c_float) function grid_searchcolumn (pGrd, rXval, rZval, rNoData)
real(kind=c_float) function grid_lookupreal (pGrd, rXval, rYval)
integer(kind=c_int) function grid_getgridcolnum (pGrd, rX)
integer(kind=c_int) function grid_getgridrownum (pGrd, rY)
integer(kind=c_int) function,
dimension(2) grid_getgridcolrownum (pGrd, rX, rY)
real(kind=c_double) function grid_getgridx (pGrd, iColumnNumber)
real(kind=c_double) function grid_getgridy (pGrd, iRowNumber)
subroutine grid_populatexy (pGrd)
subroutine grid_dumpgridextent (pGrd)
subroutine grid_gridtogrid_int (pGrdFrom, iArrayFrom, pGrdTo, iArrayTo)
subroutine grid_gridtogrid_short (pGrdFrom, iArrayFrom, pGrdTo, iArrayTo)
subroutine grid_gridtogrid_sgl (pGrdFrom, rArrayFrom, pGrdTo, rArrayTo)
integer(kind=c_int) function grid_majorityfilter_int (iValues, iNX, iNY, iTargetCol, iTargetRow, iNoDataValue, iSpread)
real(kind=c_float) function grid_convolve_sgl (rValues, iTargetCol, iTargetRow, rKernel, rNoDataValue)
Public Attributes
type(t_error_message),
dimension(49) terrormessage = (/ T_ERROR_MESSAGE("no arguments in initialization list ", -1), T_ERROR_MESSAGE("no options found in 'init' file ", -2), T_ERROR_MESSAGE("no colon in init= string ", -3), T_ERROR_MESSAGE("projection not named ", -4), T_ERROR_MESSAGE("unknown projection id ", -5), T_ERROR_MESSAGE("effective eccentricity = 1. ", -6), T_ERROR_MESSAGE("unknown unit conversion id ", -7), T_ERROR_MESSAGE("invalid boolean param argument ", -8), T_ERROR_MESSAGE("unknown elliptical parameter name ", -9), T_ERROR_MESSAGE("reciprocal flattening (1/f) = 0 ", -10), T_ERROR_MESSAGE("|radius reference latitude| > 90 ", -11), T_ERROR_MESSAGE("squared eccentricity < 0 ", -12), T_ERROR_MESSAGE("major axis or radius = 0 or not given ", -13), T_ERROR_MESSAGE("latitude or longitude exceeded limits ", -14), T_ERROR_MESSAGE("invalid x or y ", -15), T_ERROR_MESSAGE("improperly formed DMS value ", -16), T_ERROR_MESSAGE("non-convergent inverse meridional dist ", -17), T_ERROR_MESSAGE("non-convergent inverse phi2 ", -18), T_ERROR_MESSAGE("acos/asin: |arg| >1.+1e-14 ", -19), T_ERROR_MESSAGE("tolerance condition error ", -20), T_ERROR_MESSAGE("conic lat_1 = -lat_2 ", -21), T_ERROR_MESSAGE("lat_1 >= 90 ", -22), T_ERROR_MESSAGE("lat_1 = 0 ", -23), T_ERROR_MESSAGE("lat_ts >= 90 ", -24), T_ERROR_MESSAGE("no distance between control points ", -25), T_ERROR_MESSAGE("projection not selected to be rotated ", -26), T_ERROR_MESSAGE("W <= 0 or M <= 0 ", -27), T_ERROR_MESSAGE("lsat not in 1-5 range ", -28), T_ERROR_MESSAGE("path not in range ", -29), T_ERROR_MESSAGE("h <= 0 ", -30), T_ERROR_MESSAGE("k <= 0 ", -31), T_ERROR_MESSAGE("lat_0 = 0 or 90 or alpha = 90 ", -32), T_ERROR_MESSAGE("lat_1=lat_2 or lat_1=0 or lat_2=90 ", -33), T_ERROR_MESSAGE("elliptical usage required ", -34), T_ERROR_MESSAGE("invalid UTM zone number ", -35), T_ERROR_MESSAGE("arg(s) out of range for Tcheby eval ", -36), T_ERROR_MESSAGE("failed to find projection to be rotated ", -37), T_ERROR_MESSAGE("failed to load datum shift file ", -38), T_ERROR_MESSAGE("both n), & m must be spec'd and > 0 ", -39), T_ERROR_MESSAGE("n <= 0, n > 1 or not specified ", -40), T_ERROR_MESSAGE("lat_1 or lat_2 not specified ", -41), T_ERROR_MESSAGE("|lat_1| == |lat_2| ", -42), T_ERROR_MESSAGE("lat_0 is pi/2 from mean lat ", -43), T_ERROR_MESSAGE("unparseable coordinate system definition ", -44), T_ERROR_MESSAGE("geocentric transformation missing z or ellps ", -45), T_ERROR_MESSAGE("unknown prime meridian conversion id ", -46), T_ERROR_MESSAGE("illegal axis orientation combination ", -47), T_ERROR_MESSAGE("point not within available datum shift grids ", -48), T_ERROR_MESSAGE("invalid sweep axis, choose x or y ", -49) /)
integer(kind=c_int), parameter four_cells = 1
integer(kind=c_int), parameter eight_cells = 2
integer(kind=c_int), parameter column = 1
integer(kind=c_int), parameter row = 2
Detailed Description
Definition at line 8 of file grid.F90.
Member Function/Subroutine Documentation
subroutine swb_grid::grid_checkforproj4error (integer (kind=c_int) iRetVal, character (len=*) sFromPROJ4, character (len=*) sToPROJ4)
Definition at line 1459 of file grid.F90.
References types::dquote(), types::ascharacter::int2char(), types::lfalse, and types::ltrue.
Referenced by control::control_setmodeloptions(), and grid_transform().
logical (kind=c_bool) function swb_grid::grid_completelycover (type (t_general_grid), pointer pBaseGrd, type (t_general_grid), pointer pOtherGrd, real (kind=c_float), intent(in), optional rTolerance)
Definition at line 1203 of file grid.F90.
References types::dquote(), types::echolog(), types::lfalse, types::ltrue, and types::rzero.
logical (kind=c_bool) function swb_grid::grid_conform (type (t_general_grid), pointer pGrd1, type (t_general_grid), pointer pGrd2, real (kind=c_float), intent(in), optional rTolerance)
Definition at line 1141 of file grid.F90.
References types::lfalse, types::ltrue, and types::lu_log.
Referenced by control::control_setmodeloptions(), and swbstats_support::readbasinmasktable().
real (kind=c_float) function swb_grid::grid_convolve_sgl (real (kind=c_float), dimension(:,:) rValues, integer (kind=c_int) iTargetCol, integer (kind=c_int) iTargetRow, real (kind=c_float), dimension(:,:) rKernel, real (kind=c_float), optional rNoDataValue)
Definition at line 2304 of file grid.F90.
References types::t_ssf_files::icolnum, types::t_general_grid::inx, types::t_general_grid::iny, types::t_ssf_files::irownum, types::t_general_grid::rnodatavalue, and types::rzero.
type (t_general_grid) function, pointer swb_grid::grid_createcomplete (integer (kind=c_int), intent(in) iNX, integer (kind=c_int), intent(in) iNY, real (kind=c_double), intent(in) rX0, real (kind=c_double), intent(in) rY0, real (kind=c_double), intent(in) rX1, real (kind=c_double), intent(in) rY1, integer (kind=c_int), intent(in) iDataType)
Creates a grid pointer object and allocates memory for the data associated with the grid (REAL, INTEGER, or T_CELL).
Parameters
iNX Number of grid cells in the x direction
iNY Number of grid cells in the y direction
rX0 X coordinate for the lower left corner of the grid
rY0 Y coordinate for the lower left corner of the grid
rX1 X coordinate for the upper right corner of the grid
rY1 Y coordinate for the upper right corner of the grid
iDataType Integer value corresponding to the type of data contained in the grid
Returns
pGrd Pointer to a grid object
Definition at line 124 of file grid.F90.
References types::echolog(), types::grid_datatype_all, types::grid_datatype_cell_grid, types::grid_datatype_int, types::grid_datatype_real, types::t_general_grid::idatatype, types::t_general_grid::inx, types::t_general_grid::iny, types::lfalse, types::t_basin_mask::pgrd, types::t_general_grid::rx0, types::t_general_grid::rx1, types::t_general_grid::ry0, types::t_general_grid::ry1, and types::rzero.
type (t_general_grid) function, pointer swb_grid::grid_createsimple (integer (kind=c_int), intent(in) iNX, integer (kind=c_int), intent(in) iNY, real (kind=c_double), intent(in) rX0, real (kind=c_double), intent(in) rY0, real (kind=c_double), intent(in) rGridCellSize, integer (kind=c_int), intent(in) iDataType)
Definition at line 211 of file grid.F90.
References types::grid_datatype_all, types::grid_datatype_cell_grid, types::grid_datatype_int, types::grid_datatype_real, types::t_general_grid::idatatype, types::t_general_grid::inx, types::t_general_grid::iny, types::lfalse, types::t_basin_mask::pgrd, types::t_general_grid::rgridcellsize, types::t_general_grid::rx0, types::t_general_grid::ry0, and types::rzero.
subroutine swb_grid::grid_destroy (type (t_general_grid), pointer pGrd)
Definition at line 312 of file grid.F90.
References types::grid_datatype_all, types::grid_datatype_cell_grid, types::grid_datatype_int, types::grid_datatype_real, types::lfalse, and types::t_basin_mask::pgrd.
Referenced by control::control_setmodeloptions(), and model::model_endofrun().
subroutine swb_grid::grid_dumpgridextent (type (t_general_grid), pointer pGrd)
Definition at line 1981 of file grid.F90.
References types::dquote(), types::echolog(), types::ascharacter::int2char(), and types::t_basin_mask::pgrd.
Referenced by grid_getgridcolnum(), and grid_getgridrownum().
integer (kind=c_int) function swb_grid::grid_getgridcolnum (type (t_general_grid), pointer pGrd, real (kind=c_double) rX)
Definition at line 1768 of file grid.F90.
References grid_dumpgridextent(), types::ascharacter::int2char(), types::lfalse, types::t_basin_mask::pgrd, and types::t_general_grid::rx.
Referenced by control::control_setmodeloptions(), grid_getgridcolrownum(), grid_gridtogrid_int(), and grid_gridtogrid_sgl().
integer (kind=c_int) function, dimension(2) swb_grid::grid_getgridcolrownum (type (t_general_grid), pointer pGrd, real (kind=c_double) rX, real (kind=c_double) rY)
Definition at line 1823 of file grid.F90.
References grid_getgridcolnum(), grid_getgridrownum(), types::lfalse, types::ltrue, types::t_basin_mask::pgrd, types::rbigval, types::t_general_grid::rx, and types::t_general_grid::ry.
Referenced by grid_gridtogrid_int(), grid_gridtogrid_sgl(), and grid_gridtogrid_short().
integer (kind=c_int) function swb_grid::grid_getgridrownum (type (t_general_grid), pointer pGrd, real (kind=c_double) rY)
Definition at line 1802 of file grid.F90.
References grid_dumpgridextent(), types::ascharacter::int2char(), types::lfalse, types::t_basin_mask::pgrd, and types::t_general_grid::ry.
Referenced by control::control_setmodeloptions(), grid_getgridcolrownum(), grid_gridtogrid_int(), and grid_gridtogrid_sgl().
real (kind=c_double) function swb_grid::grid_getgridx (type (t_general_grid), pointer pGrd, integer (kind=c_int) iColumnNumber)
Definition at line 1920 of file grid.F90.
References types::t_basin_mask::pgrd, and types::t_general_grid::rx.
Referenced by grid_populatexy().
real (kind=c_double) function swb_grid::grid_getgridy (type (t_general_grid), pointer pGrd, integer (kind=c_int) iRowNumber)
Definition at line 1932 of file grid.F90.
References types::t_basin_mask::pgrd, and types::t_general_grid::ry.
Referenced by grid_populatexy().
subroutine swb_grid::grid_gridtogrid_int (type (t_general_grid), pointer pGrdFrom, integer (kind=c_int), dimension(:,:) iArrayFrom, type (t_general_grid), pointer pGrdTo, integer (kind=c_int), dimension(:,:), intent(inout) iArrayTo)
Definition at line 2004 of file grid.F90.
References types::echolog(), grid_getgridcolnum(), grid_getgridcolrownum(), grid_getgridrownum(), grid_majorityfilter_int(), grid_populatexy(), types::t_general_grid::inodatavalue, types::t_general_grid::inx, types::t_general_grid::iny, types::ltrue, types::t_basin_mask::pgrd, and types::t_general_grid::rx.
subroutine swb_grid::grid_gridtogrid_sgl (type (t_general_grid), pointer pGrdFrom, real (kind=c_float), dimension(:,:) rArrayFrom, type (t_general_grid), pointer pGrdTo, real (kind=c_float), dimension(:,:), intent(inout) rArrayTo)
Definition at line 2153 of file grid.F90.
References grid_getgridcolnum(), grid_getgridcolrownum(), grid_getgridrownum(), grid_populatexy(), types::ltrue, types::t_basin_mask::pgrd, and types::t_general_grid::rx.
subroutine swb_grid::grid_gridtogrid_short (type (t_general_grid), pointer pGrdFrom, integer (kind=c_int), dimension(:,:) iArrayFrom, type (t_general_grid), pointer pGrdTo, integer (kind=c_short), dimension(:,:), intent(inout) iArrayTo)
Definition at line 2097 of file grid.F90.
References grid_getgridcolrownum(), grid_majorityfilter_int(), grid_populatexy(), types::t_general_grid::inodatavalue, types::t_general_grid::inx, types::t_general_grid::iny, types::t_basin_mask::pgrd, and types::t_general_grid::rx.
real (kind=c_float) function swb_grid::grid_interpolate (type (t_general_grid), pointer pGrd, real (kind=c_float), intent(in) rXval, real (kind=c_float), intent(in) rYval)
Definition at line 1522 of file grid.F90.
References grid_lookupcolumn(), grid_lookuprow(), types::t_basin_mask::pgrd, types::ascharacter::real2char(), and types::rone.
Referenced by water_balance::calculate_water_balance().
subroutine swb_grid::grid_lookupcolumn (type (t_general_grid), pointer pGrd, real (kind=c_float), intent(in) rXval, integer (kind=c_int), intent(out) iBefore, integer (kind=c_int), intent(out) iAfter, real (kind=c_float), intent(out) rFrac)
Definition at line 1293 of file grid.F90.
References types::t_basin_mask::pgrd, types::rone, and types::rzero.
Referenced by grid_interpolate(), and grid_searchcolumn().
real (kind=c_float) function swb_grid::grid_lookupreal (type (t_general_grid), pointer pGrd, real (kind=c_float), intent(in) rXval, real (kind=c_float), intent(in) rYval)
Definition at line 1749 of file grid.F90.
References types::t_basin_mask::pgrd.
subroutine swb_grid::grid_lookuprow (type (t_general_grid), pointer pGrd, real (kind=c_float), intent(in) rYval, integer (kind=c_int), intent(out) iBefore, integer (kind=c_int), intent(out) iAfter, real (kind=c_float), intent(out) rFrac)
Definition at line 1361 of file grid.F90.
References types::t_basin_mask::pgrd, types::rone, and types::rzero.
Referenced by grid_interpolate().
integer (kind=c_int) function swb_grid::grid_majorityfilter_int (integer (kind=c_int), dimension(inx, iny) iValues, integer (kind=c_int) iNX, integer (kind=c_int) iNY, integer (kind=c_int) iTargetCol, integer (kind=c_int) iTargetRow, integer (kind=c_int) iNoDataValue, integer (kind=c_int) iSpread)
Definition at line 2228 of file grid.F90.
References types::t_general_grid::inodatavalue, types::t_general_grid::inx, types::t_general_grid::iny, types::lfalse, and types::ltrue.
Referenced by grid_gridtogrid_int(), and grid_gridtogrid_short().
subroutine swb_grid::grid_populatexy (type (t_general_grid), pointer pGrd)
Definition at line 1945 of file grid.F90.
References grid_getgridx(), grid_getgridy(), and types::t_basin_mask::pgrd.
Referenced by grid_gridtogrid_int(), grid_gridtogrid_sgl(), grid_gridtogrid_short(), and grid_transform().
type (t_general_grid) function, pointer swb_grid::grid_read (character (len=*), intent(in) sFilename, character (len=*), intent(in) sFileType, integer (kind=c_int), intent(in) iDataType)
Definition at line 389 of file grid.F90.
References grid_readarcgrid_fn(), grid_readsurfergrid_fn(), types::t_general_grid::idatatype, types::lfalse, types::t_basin_mask::pgrd, types::t_general_grid::sfilename, and types::t_basin_mask::sfiletype.
Referenced by control::control_setmodeloptions(), swbstats_support::readbasinmasktable(), sm_thornthwaite_mather::sm_thornthwaite_mather_configure(), and swbstats().
type (t_general_grid) function, pointer swb_grid::grid_readarcgrid_fn (character (len=*), intent(in) sFileName, integer (kind=c_int), intent(in) iDataType)
Definition at line 456 of file grid.F90.
References types::datatype_int, types::datatype_real, types::dquote(), types::t_general_grid::idatatype, types::ascharacter::int2char(), types::t_general_grid::inx, types::t_general_grid::iny, types::lfalse, types::ltrue, types::lu_grid, types::lu_log, types::t_basin_mask::pgrd, types::rhalf, types::t_general_grid::rx0, types::t_general_grid::rx1, types::t_general_grid::ry0, types::t_general_grid::ry1, types::t_general_grid::sfilename, and types::uppercase().
Referenced by grid_read().
subroutine swb_grid::grid_readarcgrid_sub (character (len=*), intent(in) sFileName, type (t_general_grid), pointer pGrd)
Definition at line 624 of file grid.F90.
References types::datatype_int, types::datatype_real, types::dquote(), types::ascharacter::int2char(), types::t_general_grid::inx, types::t_general_grid::iny, types::lfalse, types::ltrue, types::lu_grid, types::lu_log, types::t_basin_mask::pgrd, types::t_general_grid::rx0, types::t_general_grid::ry0, types::t_general_grid::sfilename, and types::uppercase().
Referenced by grid_readexisting().
subroutine swb_grid::grid_readexisting (character (len=*), intent(in) sFileName, character (len=*), intent(in) sFileType, type (t_general_grid), pointer pGrd)
Definition at line 412 of file grid.F90.
References grid_readarcgrid_sub(), grid_readsurfergrid_sub(), types::lfalse, types::t_basin_mask::pgrd, types::t_general_grid::sfilename, and types::t_basin_mask::sfiletype.
type (t_general_grid) function, pointer swb_grid::grid_readsurfergrid_fn (character (len=*), intent(in) sFileName, integer (kind=c_int), intent(in) iDataType)
Definition at line 806 of file grid.F90.
References types::datatype_int, types::datatype_real, types::dquote(), types::t_general_grid::idatatype, types::t_general_grid::inx, types::t_general_grid::iny, types::lfalse, types::lu_grid, types::t_basin_mask::pgrd, types::t_general_grid::rx0, types::t_general_grid::rx1, types::t_general_grid::ry0, types::t_general_grid::ry1, and types::t_general_grid::sfilename.
Referenced by grid_read().
subroutine swb_grid::grid_readsurfergrid_sub (character (len=*), intent(in) sFileName, type (t_general_grid), pointer pGrd)
Definition at line 876 of file grid.F90.
References types::datatype_int, types::datatype_real, types::dquote(), types::t_general_grid::inx, types::t_general_grid::iny, types::lfalse, types::lu_grid, types::t_basin_mask::pgrd, types::t_general_grid::rx0, types::t_general_grid::rx1, types::t_general_grid::ry0, types::t_general_grid::ry1, and types::t_general_grid::sfilename.
Referenced by grid_readexisting().
real (kind=c_float) function swb_grid::grid_searchcolumn (type (t_general_grid), pointer pGrd, real (kind=c_float), intent(in) rXval, real (kind=c_float), intent(in) rZval, real (kind=c_float), intent(in) rNoData)
Definition at line 1612 of file grid.F90.
References grid_lookupcolumn(), types::ascharacter::int2char(), types::lu_log, types::t_basin_mask::pgrd, types::ascharacter::real2char(), and types::rone.
Referenced by water_balance::calculate_water_balance(), and sm_thornthwaite_mather::sm_thornthwaite_mather_initialize().
subroutine swb_grid::grid_transform (type (t_general_grid), pointer pGrd, character (len=*) sFromPROJ4, character (len=*) sToPROJ4)
This subroutine calls a Fortran wrapper to the C library PROJ4. A set of input coordinates is transformed to a different coordinate system.
Parameters
[in,out] pGrd
[in] sFromPROJ4
[in] sToPROJ4
PROJ4 expects unprojected coordinates (i.e. lat lon) to be provided in RADIANS. Therefore, we convert to radians prior to the call...
Definition at line 1398 of file grid.F90.
References types::dppi_over_180, grid_checkforproj4error(), grid_populatexy(), and types::t_basin_mask::pgrd.
subroutine swb_grid::grid_writearcgrid (character (len=*), intent(in) sFilename, type (t_general_grid), pointer pGrd)
Definition at line 962 of file grid.F90.
References types::datatype_int, types::datatype_real, types::dquote(), types::ascharacter::int2char(), types::lfalse, types::lu_temp, types::t_basin_mask::pgrd, and types::t_general_grid::sfilename.
Referenced by grid_writegrid(), model::model_configurerunoffdownhill(), model::model_initializeinputandoutput(), runoff_curve_number::runoff_initializecurvenumber(), and sm_thornthwaite_mather::sm_thornthwaite_mather_initialize().
subroutine swb_grid::grid_writegrid (character (len=*), intent(in) sFilename, type (t_general_grid), pointer pGrd, integer (kind=c_int) iOutputFormat)
Definition at line 942 of file grid.F90.
References grid_writearcgrid(), grid_writesurfergrid(), types::output_arc, types::output_surfer, types::t_basin_mask::pgrd, and types::t_general_grid::sfilename.
Referenced by model::model_initializedatastructures(), model::model_solve(), model::model_writegrids(), stats::stats_calcmeanrecharge(), stats::stats_rewritegrids(), and swbstats().
subroutine swb_grid::grid_writesurfergrid (character (len=*), intent(in) sFilename, type (t_general_grid), pointer pGrd)
Definition at line 1037 of file grid.F90.
References types::datatype_int, types::datatype_real, types::dquote(), types::ascharacter::int2char(), types::lfalse, types::lu_temp, types::t_basin_mask::pgrd, types::rhalf, and types::t_general_grid::sfilename.
Referenced by grid_writegrid().
Member Data Documentation
integer (kind=c_int), parameter swb_grid::column = 1
Definition at line 103 of file grid.F90.
integer (kind=c_int), parameter swb_grid::eight_cells = 2
Definition at line 101 of file grid.F90.
integer (kind=c_int), parameter swb_grid::four_cells = 1
Definition at line 100 of file grid.F90.
integer (kind=c_int), parameter swb_grid::row = 2
Definition at line 104 of file grid.F90.
type(t_error_message), dimension(49) swb_grid::terrormessage = (/ T_ERROR_MESSAGE("no arguments in initialization list ", -1), T_ERROR_MESSAGE("no options found in 'init' file ", -2), T_ERROR_MESSAGE("no colon in init= string ", -3), T_ERROR_MESSAGE("projection not named ", -4), T_ERROR_MESSAGE("unknown projection id ", -5), T_ERROR_MESSAGE("effective eccentricity = 1. ", -6), T_ERROR_MESSAGE("unknown unit conversion id ", -7), T_ERROR_MESSAGE("invalid boolean param argument ", -8), T_ERROR_MESSAGE("unknown elliptical parameter name ", -9), T_ERROR_MESSAGE("reciprocal flattening (1/f) = 0 ", -10), T_ERROR_MESSAGE("|radius reference latitude| > 90 ", -11), T_ERROR_MESSAGE("squared eccentricity < 0 ", -12), T_ERROR_MESSAGE("major axis or radius = 0 or not given ", -13), T_ERROR_MESSAGE("latitude or longitude exceeded limits ", -14), T_ERROR_MESSAGE("invalid x or y ", -15), T_ERROR_MESSAGE("improperly formed DMS value ", -16), T_ERROR_MESSAGE("non-convergent inverse meridional dist ", -17), T_ERROR_MESSAGE("non-convergent inverse phi2 ", -18), T_ERROR_MESSAGE("acos/asin: |arg| >1.+1e-14 ", -19), T_ERROR_MESSAGE("tolerance condition error ", -20), T_ERROR_MESSAGE("conic lat_1 = -lat_2 ", -21), T_ERROR_MESSAGE("lat_1 >= 90 ", -22), T_ERROR_MESSAGE("lat_1 = 0 ", -23), T_ERROR_MESSAGE("lat_ts >= 90 ", -24), T_ERROR_MESSAGE("no distance between control points ", -25), T_ERROR_MESSAGE("projection not selected to be rotated ", -26), T_ERROR_MESSAGE("W <= 0 or M <= 0 ", -27), T_ERROR_MESSAGE("lsat not in 1-5 range ", -28), T_ERROR_MESSAGE("path not in range ", -29), T_ERROR_MESSAGE("h <= 0 ", -30), T_ERROR_MESSAGE("k <= 0 ", -31), T_ERROR_MESSAGE("lat_0 = 0 or 90 or alpha = 90 ", -32), T_ERROR_MESSAGE("lat_1=lat_2 or lat_1=0 or lat_2=90 ", -33), T_ERROR_MESSAGE("elliptical usage required ", -34), T_ERROR_MESSAGE("invalid UTM zone number ", -35), T_ERROR_MESSAGE("arg(s) out of range for Tcheby eval ", -36), T_ERROR_MESSAGE("failed to find projection to be rotated ", -37), T_ERROR_MESSAGE("failed to load datum shift file ", -38), T_ERROR_MESSAGE("both n), & m must be spec'd and > 0 ", -39), T_ERROR_MESSAGE("n <= 0, n > 1 or not specified ", -40), T_ERROR_MESSAGE("lat_1 or lat_2 not specified ", -41), T_ERROR_MESSAGE("|lat_1| == |lat_2| ", -42), T_ERROR_MESSAGE("lat_0 is pi/2 from mean lat ", -43), T_ERROR_MESSAGE("unparseable coordinate system definition ", -44), T_ERROR_MESSAGE("geocentric transformation missing z or ellps ", -45), T_ERROR_MESSAGE("unknown prime meridian conversion id ", -46), T_ERROR_MESSAGE("illegal axis orientation combination ", -47), T_ERROR_MESSAGE("point not within available datum shift grids ", -48), T_ERROR_MESSAGE("invalid sweep axis, choose x or y ", -49) /)
Definition at line 37 of file grid.F90.
The documentation for this module was generated from the following file:
grid.F90
USGS Home Water Resources Biology Geography Geology Geospatial SWB Home Wisconsin WSC
Accessibility FOIA Privacy Policies and Notices
U.S. Department of the Interior | U.S. Geological Survey
URL: http://wi.water.usgs.gov/Soil_Water_Balance/SWB_code_docs/index.html
Page Contact Information: webmaster@wi.water.usgs.gov
Page Last Modified: Thu May 19 2011 14:11:32
Page generated with:
1.8.2