SOIL-WATER-BALANCE SOURCE CODE BROWSER- USGS Wisconsin Water Science Center
USGS Home
Contact USGS
Search USGS
Soil-Water-Balance Source Code Browser
snow Module Reference
Implements snow-related calculations (i.e. albedo, snow depth), as well as a simple snow energy balance routine.
Public Member Functions
real(kind=t_sgl) function snow_depth_in (rTAvg)
real(kind=t_sgl) function snow_depth_hedstrom (rTAvg, pConfig)
subroutine snow_energy_balance (rTMin, rTMax, rTAvg, rRs, rRso, rAlbedo, rSnowcover, rNetPrecip, rSnowTemperature, rMeltAmount, i, j)
real(kind=t_sgl) function snow_albedo (rAlbedoInit, iNumDaysLastSnow, rZenithAngle)
Detailed Description
Note
These routines are only invoked when control variable pConfigiConfigureSnow is set to CONFIG_SNOW_NEW_SWB
Definition at line 10 of file snow.F90.
Member Function/Subroutine Documentation
real (kind=t_sgl) function snow::snow_albedo (real (kind=t_sgl), intent(in) rAlbedoInit, integer (kind=t_int), intent(in) iNumDaysLastSnow, real (kind=t_sgl), intent(in) rZenithAngle)
Definition at line 213 of file snow.F90.
Referenced by model::model_processrainprms().
real(kind=t_sgl) function snow::snow_depth_hedstrom (real(kind=t_sgl), intent(in) rTAvg, type (t_model_configuration), pointer pConfig)
Definition at line 38 of file snow.F90.
References types::ftoc(), and types::t_cell::rtavg.
Referenced by model::model_processrainprms().
real(kind=t_sgl) function snow::snow_depth_in (real(kind=t_sgl), intent(in) rTAvg)
Definition at line 18 of file snow.F90.
subroutine snow::snow_energy_balance (real (kind=t_sgl) rTMin, real (kind=t_sgl) rTMax, real (kind=t_sgl) rTAvg, real (kind=t_sgl) rRs, real (kind=t_sgl) rRso, real (kind=t_sgl) rAlbedo, real (kind=t_sgl) rSnowcover, real (kind=t_sgl) rNetPrecip, real (kind=t_sgl) rSnowTemperature, real (kind=t_sgl) rMeltAmount, integer (kind=t_int) i, integer (kind=t_int) j)
Definition at line 76 of file snow.F90.
References meteorological_functions::convective_heat_exchange_e(), types::ctof(), types::ftoc(), meteorological_functions::net_longwave_radiation_rnl(), meteorological_functions::net_shortwave_radiation_rns(), meteorological_functions::precipitation_heat_p(), types::t_cell::rnetprecip, types::t_cell::rsnowcover, types::t_cell::rsnowtemperature, types::t_cell::rtavg, types::t_cell::rtmax, types::t_cell::rtmin, types::rzero, and meteorological_functions::sensible_heat_exchange_h().
Referenced by model::model_processrainprms().
The documentation for this module was generated from the following file:
snow.F90
USGS Home Water Resources Biology Geography Geology Geospatial SWB Home Wisconsin WSC
Accessibility FOIA Privacy Policies and Notices
U.S. Department of the Interior | U.S. Geological Survey
URL: http://wi.water.usgs.gov/Soil_Water_Balance/SWB_code_docs/index.html
Page Contact Information: webmaster@wi.water.usgs.gov
Page Last Modified: Thu May 19 2011 14:11:32
Page generated with:
1.8.2