SOIL-WATER-BALANCE SOURCE CODE BROWSER- USGS Wisconsin Water Science Center
USGS Home
Contact USGS
Search USGS
Soil-Water-Balance Source Code Browser
control Module Reference
Reads program options from an SWB control file and sets program configuration flags.
Public Member Functions
subroutine control_setmodeloptions (sControlFile)
Reads model control file and initializes model configuration parameters and flags.
Detailed Description
Definition at line 6 of file control.F90.
Member Function/Subroutine Documentation
subroutine control::control_setmodeloptions (character (len=*), intent(in) sControlFile)
Reads model control file and initializes model configuration parameters and flags. Multiple calls to model_Solve are accomodated for multiple-year model runs.
Parameters
[in] sControlFile Name of the control file to use for the current simulation.
Return values
NONE
Definition at line 24 of file control.F90.
References types::config_et_blaney_criddle, types::config_et_hargreaves, types::config_et_jensen_haise, types::config_et_none, types::config_et_thornthwaite_mather, types::config_et_turc, types::config_landuse_constant, types::config_landuse_dynamic_arc_grid, types::config_landuse_dynamic_surfer, types::config_landuse_static_grid, types::config_precip_arc_grid, types::config_precip_netcdf, types::config_precip_single_station, types::config_precip_surfer_grid, types::config_runoff_curve_number, types::config_runoff_downhill, types::config_runoff_green_ampt, types::config_runoff_iterative, types::config_runoff_no_routing, types::config_sm_capacity_calculate, types::config_sm_capacity_fm_table, types::config_sm_init_abstraction_hawkins, types::config_sm_init_abstraction_tr55, types::config_sm_thornthwaite_mather, types::config_snow_new_swb, types::config_snow_original_swb, types::config_temperature_arc_grid, types::config_temperature_netcdf, types::config_temperature_single_station, types::config_temperature_surfer_grid, types::dquote(), et_blaney_criddle::et_bc_configure(), et_hargreaves::et_hargreaves_configure(), et_jensen_haise::et_jh_configure(), et_thornthwaite_mather::et_tm_configure(), et_turc::et_turc_configure(), types::gregorian_date(), swb_grid::grid_conform(), swb_grid::grid_create(), swb_grid::grid_destroy(), swb_grid::grid_getgridcolnum(), swb_grid::grid_getgridrownum(), swb_grid::grid_read(), types::iannual, types::iboth, types::t_ssf_files::icolnum, types::idaily, types::igraph, types::igrid, types::igrid_length_units_feet, types::igrid_length_units_meters, types::igross_precip, types::imax_temp, types::imin_temp, types::imonthly, types::inc_input, types::inone, types::int2char(), types::inum_variables, types::t_general_grid::inx, types::t_general_grid::iny, types::t_ssf_files::irownum, types::t_graph_configuration::itimeframe, types::t_ssf_files::ivarnum, types::julian_day(), types::lfalse, types::ltrue, types::lu_control, types::lu_log, types::lu_ts, model::model_endofrun(), model::model_readbasinmasktable(), model::model_readirrigationlookuptable(), model::model_readlanduselookuptable(), model::model_readtimeseriesfile(), model::model_solve(), netcdf_support::netcdf_chk_extent(), netcdf_support::netcdf_info(), netcdf_support::netcdf_open(), types::num_days_in_year(), types::output_arc, types::output_surfer, types::t_basin_mask::pgrd, types::rbigval, types::real2char(), types::t_general_grid::rgridcellsize, types::rnear_zero, types::rone, types::t_general_grid::rx0, types::t_general_grid::rx1, types::t_general_grid::ry0, types::t_general_grid::ry1, types::rzero, sm_thornthwaite_mather::sm_thornthwaite_mather_configure(), types::squote(), types::stat_info, stats::stats_calcbasinstats(), stats::stats_calcmeanrecharge(), stats::stats_calcmeanrechargebylu(), stats::stats_writeminmeanmax(), types::str_compare(), types::t_cell_grid, types::t_int, types::t_int_grid, types::t_sgl_grid, and types::uppercase().
Referenced by main().
The documentation for this module was generated from the following file:
control.F90
USGS Home Water Resources Biology Geography Geology Geospatial SWB Home Wisconsin WSC
Accessibility FOIA Privacy Policies and Notices
U.S. Department of the Interior | U.S. Geological Survey
URL: http://wi.water.usgs.gov/Soil_Water_Balance/SWB_code_docs/index.html
Page Contact Information: webmaster@wi.water.usgs.gov
Page Last Modified: Thu May 19 2011 14:11:32
Page generated with:
1.8.2