SOIL-WATER-BALANCE SOURCE CODE BROWSER- USGS Wisconsin Water Science Center
USGS Home
Contact USGS
Search USGS
Soil-Water-Balance Source Code Browser
types Module Reference
Contains types definitions and general utility functions used by the SWB code.
Data Types
interface approx_equal
interface ascharacter
interface asint
interface asreal
interface assert
interface chomp
interface ctof
interface ftoc
interface ftok
type t_basin_mask
container for basin mask table data
type t_cell
Type that contains the data for an individual grid cell.
type t_general_grid
Type that contains the data for a grid.
type t_graph_configuration
Type that holds parameters used to create graphics with the DISLIN library.
type t_grid_bounds
type t_grid_collection
Type that contains pointers to one or more grid data structures.
type t_irrigation_lookup
Type that contains information needed to calculate irrigation for each land use.
type t_landuse_lookup
Container for land-use related data.
type t_model_configuration
Type that contains model configuration data.
type t_month
Container for calendar lookup information.
type t_ssf_files
container for SSF file information
type t_stats
Type that contains parameters for graphings and stats calculations.
type t_time_series_file
data structure to hold a line of input from the classic time-series file
Public Member Functions
integer(kind=c_int) function nextunit (iLU)
character(len=len_trim(adjustl(sstring))+2)
function squote (sString)
character(len=len_trim(adjustl(sstring))+2)
function dquote (sString)
Function 'dquote' returns a character string with double quotes prepended and appended to the string that is passed.
logical(kind=c_bool) function str_compare (sString1, sString2)
subroutine assert_simple_sub (lCondition, sErrorMessage)
subroutine assert_simple_fl_sub (lCondition, sErrorMessage)
subroutine assert_module_details_sub (lCondition, sErrorMessage, sFilename, iLineNum)
subroutine assert_module_details_fl_sub (lCondition, sErrorMessage, sFilename, iLineNum)
subroutine echolog (sMessage)
echo to screen AND write to logfile
subroutine chomp_delim_sub (sRecord, sItem, sDelimiters)
subroutine chomp_default_sub (sRecord, sItem)
subroutine getsystimedate (sDateStr, sDateStrPretty)
subroutine chomp_tab (sRecord, sItem)
subroutine chomp_slash (sRecord, sItem)
integer(kind=c_int) function mmddyyyy2julian (sMMDDYYYY)
integer(kind=c_int) function mmdd2doy (sMMDD)
integer(kind=c_int) function mmddyyyy2doy (sMMDDYYYY)
character(len=len(s)) function uppercase_fn (s)
character(len=len(s)) function lowercase_fn (s)
subroutine uppercase (s)
subroutine cleanupcsv (s)
character(len=256) function clean (sRecord, sDelimiters)
subroutine cleanupslash (s)
integer function newunit (unit)
real(kind=c_double) function polynomial (x, a)
subroutine lookupmonth (iMonth, iDay, iYear, iDayOfYear, sMonthName, lMonthEnd)
logical(kind=c_bool) function approx_equal_dbl (rA, rB, rTol)
logical(kind=c_bool) function approx_equal_sgl (rA, rB, rTol)
logical(kind=c_bool) function lf_model_growingseason (pConfig, iDayOfYear)
real(kind=c_float) function ftoc_sgl_fn (rF)
real(kind=c_double) function ftoc_dbl_fn (rF)
real(kind=c_float) function ctof_sgl_fn (rC)
real(kind=c_double) function ctof_dbl_fn (rC)
real(kind=c_float) function ftok_sgl_fn (rF)
real(kind=c_double) function ftok_dbl_fn (rF)
integer(kind=c_int) function count_fields (sRecord)
real(kind=c_float) function mm_to_in (r_mm)
real(kind=c_float) function interpolate (rXT, rYT, rX)
integer(kind=c_int) function julian_day (iYear, iMonth, iDay, iOrigin)
integer(kind=c_int) function solstice (iJD)
subroutine writemultiline (sMessageText, iLU)
Write multiple lines of output to Fortran logical unit.
elemental function int2char (iValue)
Convert an integer value into a formatted character string.
elemental function short2char (iValue)
Convert a short integer value into a formatted character string.
integer(kind=c_int) function char2int (sValue)
Convert an character value into a integer.
integer(kind=c_int) function real2int (rValue)
Convert a real value into a integer.
integer(kind=c_int) function dbl2int (rValue)
Convert a double-precision value to an integer.
real(kind=c_float) function char2real (sValue)
Convert an character value into a real.
real(kind=c_float) function int2real (iValue)
Convert an int value into a real.
real(kind=c_float) function dbl2real (dpValue)
Convert an dbl value into a real.
elemental function c_size_t2char (iValue)
Convert an integer value into a formatted character string.
elemental function real2char (rValue, sFmt)
Convert a real value into a formatted character string.
elemental function dbl2char (rValue, sFmt)
Convert a double precision real value into a formatted character string.
elemental function deg2rad (rDeg)
elemental function rad2deg (rRad)
integer(kind=c_int) function num_days_in_year (iYear)
Return the number of days in the given year.
integer(kind=c_int) function day_of_year (iJD)
logical(kind=c_bool) function isleap (iYear)
subroutine gregorian_date (iJD, iYear, iMonth, iDay, iOrigin)
Convert from a Julian day number to a Gregorian date.
character(len=256) function ascsv (sText)
character(len=256) function char_ptr_to_fortran_string (cpCharacterPtr)
elemental function c_to_fortran_string (cCharacterString)
elemental function fortran_to_c_string (sText)
Public Attributes
character(len=45), parameter,
public swb_version = "1.2 BETA (geographic transformations enabled)"
character(len=15) compile_date = trim(__DATE__)
integer(kind=c_int), parameter constant_grid = 0
integer(kind=c_int), parameter static_grid = 1
integer(kind=c_int), parameter static_netcdf_grid = 2
integer(kind=c_int), parameter dynamic_grid = 3
integer(kind=c_int), parameter dynamic_netcdf_grid = 4
integer(kind=c_int), parameter datatype_int = 0
integer(kind=c_int), parameter datatype_real = 1
integer(kind=c_int), parameter datatype_cell_grid = 2
integer(kind=c_int), parameter datatype_short = 3
integer(kind=c_int), parameter datatype_double = 4
integer(kind=c_int), parameter datatype_na = -9999
integer(kind=c_int), parameter filetype_arc_ascii = 0
integer(kind=c_int), parameter filetype_surfer = 1
integer(kind=c_int), parameter filetype_netcdf = 2
integer(kind=c_int), parameter filetype_none = 3
integer(kind=c_int), parameter grid_datatype_int = 0
integer(kind=c_int), parameter grid_datatype_real = 1
integer(kind=c_int), parameter grid_datatype_cell_grid = 2
integer(kind=c_int), parameter grid_datatype_all = 3
integer(kind=c_int), parameter igrid_length_units_meters = 0
define parameter values for working with type T_GENERAL_GRID
integer(kind=c_int), parameter igrid_length_units_feet = 1
type(t_month), dimension(12),
target year_info = (/ T_MONTH('JAN','JANUARY ', 1, 31, 1, 31), T_MONTH('FEB','FEBRUARY ', 32, 59, 2, 29), T_MONTH('MAR','MARCH ', 60, 90, 3, 31), T_MONTH('APR','APRIL ', 91, 120, 4, 30), T_MONTH('MAY','MAY ', 121, 151, 5, 31), T_MONTH('JUN','JUNE ', 152, 181, 6, 30), T_MONTH('JUL','JULY ', 182, 212, 7, 31), T_MONTH('AUG','AUGUST ', 213, 243, 8, 31), T_MONTH('SEP','SEPTEMBER', 244, 273, 9, 30), T_MONTH('OCT','OCTOBER ', 274, 304, 10, 31), T_MONTH('NOV','NOVEMBER ', 305, 334, 11, 30), T_MONTH('DEC','DECEMBER ', 335, 365, 12, 31) /)
Month information.
character(len=256), public slogbuffer
integer(kind=c_int), parameter inum_months = 12
Global parameter defining the number of elements in the YEAR_INFO array.
integer(kind=c_int), parameter inum_variables = 36
integer(kind=c_int), parameter inone = 0
integer(kind=c_int), parameter igrid = 1
integer(kind=c_int), parameter igraph = 2
integer(kind=c_int), parameter iboth = 3
integer(kind=c_int), parameter istats = 4
type(t_stats), dimension(inum_variables) stat_info = [ T_STATS ('GROSS_PRECIP',0,0,1,lTRUE,lTRUE, lTRUE, 'inches','gross precipitation', 1.,0.0,iNONE,iNONE,iNONE,iNONE,'source',0,0), T_STATS ('SNOWMELT',0,0,1,lTRUE,lTRUE, lTRUE, 'inches','snowmelt', 1.,0.0,iNONE,iNONE,iNONE,iNONE,'source',0,0), T_STATS ('INFLOW',0,0,1,lTRUE,lTRUE, lTRUE, 'inches','incoming flow from adjacent cells', 1.,0.0,iNONE,iNONE,iNONE,iNONE,'source',0,0), T_STATS ('IRRIGATION_AMOUNT',0,0,1,lTRUE,lTRUE, lTRUE, 'inches','daily estimated irrigation amount', 1.,0.0,iNONE,iNONE,iNONE,iNONE,'source',0,0), T_STATS ('SNOWFALL',0,0,-1,lTRUE,lTRUE, lTRUE, 'inches','precipitation falling as snow (SWE)', 1.,0.0,iNONE,iNONE,iNONE,iNONE,'sink',0,0), T_STATS ('INTERCEPTION',0,0,-1,lTRUE,lTRUE, lTRUE, 'inches','interception', 1.,0.0,iNONE,iNONE,iNONE,iNONE,'sink',0,0), T_STATS ('OUTFLOW',0,0,-1,lTRUE,lTRUE, lTRUE, 'inches','outgoing flow to adjacent cells', 1.,0.0,iNONE,iNONE,iNONE,iNONE,'sink',0,0), T_STATS ('RUNOFF_OUTSIDE',0,0,-1,lTRUE,lTRUE, lTRUE, 'inches','runoff leaving model domain', 1.,0.0,iNONE,iNONE,iNONE,iNONE,'sink',0,0), T_STATS ('ACT_ET',0,0,-1,lTRUE,lTRUE, lTRUE, 'inches','actual evapotranspiration', 1.,0.0,iNONE,iNONE,iNONE,iNONE,'sink',0,0), T_STATS ('CHG_IN_SOIL_MOIS',0,0,-1,lTRUE,lTRUE, lTRUE, 'inches','daily change in soil moisture', 1.,0.0,iNONE,iNONE,iNONE,iNONE,'sink',0,0), T_STATS ('RECHARGE',0,0,-1,lTRUE,lTRUE, lTRUE, 'inches','daily potential recharge', 1.,0.0,iNONE,iNONE,iNONE,iNONE,'sink',0,0), T_STATS ('REJECTED_RECHARGE',0,0,-1,lTRUE,lTRUE, lTRUE, 'inches','recharge exceeding max recharge rate', 1.,0.0,iNONE,iNONE,iNONE,iNONE,'sink',0,0), T_STATS ('STREAM_CAPTURE',0,0,-1,lTRUE,lTRUE, lTRUE, 'inches','runoff or recharge captured by a stream or fracture', 1.,0.0,iNONE,iNONE,iNONE,iNONE,'sink',0,0), T_STATS ('SNOWCOVER',0,2,0,lFALSE,lTRUE, lTRUE, 'inches','water equivalent of snow cover', 1.,0.0,iNONE,iNONE,iNONE,iNONE,'info',0,0), T_STATS ('CFGI',0,2,0,lFALSE,lFALSE, lTRUE, 'unitless','continuous frozen ground index', 1.,0.0,iNONE,iNONE,iNONE,iNONE,'info',0,0), T_STATS ('MIN_TEMP',0,2,0,lFALSE,lFALSE, lTRUE, 'degrees F','minimum daily air temperature', 1.,0.0,iNONE,iNONE,iNONE,iNONE,'info',0,0), T_STATS ('MAX_TEMP',0,2,0,lFALSE,lFALSE, lTRUE, 'degrees F','maximum daily air temperature', 1.,0.0,iNONE,iNONE,iNONE,iNONE,'info',0,0), T_STATS ('AVG_TEMP',0,2,0,lFALSE,lFALSE, lTRUE, 'degrees F','mean daily air temperature', 1.,0.0,iNONE,iNONE,iNONE,iNONE,'info',0,0), T_STATS ('CHG_IN_SNOW_COV',0,2,0,lFALSE,lTRUE, lTRUE, 'inches','snowfall minus snowmelt', 1.,0.0,iNONE,iNONE,iNONE,iNONE,'info',0,0), T_STATS ('NET_RAINFALL',0,2,0,lTRUE,lTRUE, lTRUE, 'inches','gross precipitation minus interception and snowfall', 1.,0.0,iNONE,iNONE,iNONE,iNONE,'info',0,0), T_STATS ('NET_INFLOW',0,2,0,lTRUE,lTRUE, lTRUE, 'inches','sum of net precip and inflow', 1.,0.0,iNONE,iNONE,iNONE,iNONE,'info',0,0), T_STATS ('NET_INFIL',0,2,0,lTRUE,lTRUE, lTRUE, 'inches','precip and inflow minus outflow', 1.,0.0,iNONE,iNONE,iNONE,iNONE,'info',0,0), T_STATS ('REFERENCE_ET',0,2,0,lTRUE,lTRUE, lTRUE, 'inches','reference evapotranspiration (ET0)', 1.,0.0,iNONE,iNONE,iNONE,iNONE,'info',0,0), T_STATS ('REFERENCE_ET_ADJ',0,2,0,lTRUE,lTRUE, lTRUE, 'inches','adjusted reference evapotranspiration (ET0_adj)', 1.,0.0,iNONE,iNONE,iNONE,iNONE,'info',0,0), T_STATS ('CROP_ET',0,2,0,lTRUE,lTRUE, lTRUE, 'inches','crop evapotranspiration (ETc)', 1.,0.0,iNONE,iNONE,iNONE,iNONE,'info',0,0), T_STATS ('BARE_SOIL_EVAP',0,2,0,lTRUE,lTRUE, lTRUE, 'inches','evaporation from bare soil', 1.,0.0,iNONE,iNONE,iNONE,iNONE,'info',0,0), T_STATS ('P_MINUS_PET',0,2,0,lTRUE,lFALSE, lTRUE, 'inches','net inflow minus potential et', 1.,0.0,iNONE,iNONE,iNONE,iNONE,'info',0,0), T_STATS ('SM_DEFICIT',0,2,0,lFALSE,lFALSE, lTRUE, 'inches','daily soil moisture deficit', 1.,0.0,iNONE,iNONE,iNONE,iNONE,'info',0,0), T_STATS ('SM_SURPLUS',0,2,0,lFALSE,lFALSE, lTRUE, 'inches','daily soil moisture surplus', 1.,0.0,iNONE,iNONE,iNONE,iNONE,'info',0,0), T_STATS ('SM_APWL',0,2,0,lFALSE,lFALSE, lTRUE, 'inches','accumulated potential water loss', 1.,0.0,iNONE,iNONE,iNONE,iNONE,'info',0,0), T_STATS ('SOIL_MOISTURE',0,2,0,lFALSE,lTRUE, lTRUE, 'inches','daily soil moisture', 1.,0.0,iNONE,iNONE,iNONE,iNONE,'info',0,0), T_STATS ('GDD',0,2,0,lFALSE,lFALSE,lTRUE, 'degree-day','growing degree day', 1.,0.0,iNONE,iNONE,iNONE,iNONE,'info',0,0), T_STATS ('ROOTING_DEPTH',0,2,0,lFALSE,lFALSE,lTRUE, 'feet','current rooting depth', 1.,0.0,iNONE,iNONE,iNONE,iNONE,'info',0,0), T_STATS ('CROP_COEFFICIENT',0,2,0,lFALSE,lFALSE,lTRUE, 'unitless','crop coefficient (Kcb)', 1.,0.0,iNONE,iNONE,iNONE,iNONE,'info',0,0), T_STATS ('IRRIGATION_FROM_GW',0,2,0,lFALSE,lFALSE, lTRUE, 'inches','amount of water required from groundwater for irrigation', 1.,0.0,iNONE,iNONE,iNONE,iNONE,'info',0,0), T_STATS ('IRRIGATION_FROM_SW',0,2,0,lFALSE,lFALSE, lTRUE, 'inches','amount of water required from surface water for irrigation', 1.,0.0,iNONE,iNONE,iNONE,iNONE,'info',0,0) ]
Define parameter values for working with accumulator arrays.
integer(kind=c_int), parameter config_estimate_missing_data = 0
integer(kind=c_int), parameter config_end_if_missing_data = 1
integer(kind=c_int), parameter write_ascii_grid_daily = 0
integer(kind=c_int), parameter write_ascii_grid_monthly = 1
integer(kind=c_int), parameter write_ascii_grid_annual = 2
integer(kind=c_int), parameter write_ascii_grid_debug = 3
integer(kind=c_int), parameter write_ascii_grid_diagnostic = 4
integer(kind=c_int), parameter config_none = 0
generic configuration
integer(kind=c_int), parameter idaily = 1
integer(kind=c_int), parameter imonthly = 2
integer(kind=c_int), parameter iannual = 3
Variables: Fortran logical unit numbers
Global logical unit numbers for input and output
integer(kind=c_int), parameter lu_std_out = 6
integer(kind=c_int), parameter lu_log = 7
integer(kind=c_int), parameter lu_control = 12
integer(kind=c_int), parameter lu_grid = 14
integer(kind=c_int), parameter lu_lookup = 16
integer(kind=c_int), parameter lu_ts = 18
integer(kind=c_int), parameter lu_temp = 20
integer(kind=c_int), parameter lu_msb_report = 22
integer(kind=c_int), parameter lu_bin_file = 24
integer(kind=c_int), parameter lu_routing = 26
integer(kind=c_int), parameter lu_csv_min = 28
integer(kind=c_int), parameter lu_csv_mean = 30
integer(kind=c_int), parameter lu_csv_max = 32
integer(kind=c_int), parameter lu_csv_annual = 34
integer(kind=c_int), parameter lu_mask = 36
integer(kind=c_int), parameter lu_mask_file = 38
integer(kind=c_int), parameter lu_mask_stats_csv = 40
integer(kind=c_int), parameter lu_pest_stats = 42
integer(kind=c_int), parameter lu_pest_obs = 44
integer(kind=c_int), parameter lu_pest_ins = 46
Constants: General conversion factors and flags
Some useful and common conversion factors, defined here to ensure consistency throughout the code
real(kind=c_float), parameter rzero = 0.0_c_float
real(kind=c_double), parameter dpzero = 0.0_c_double
real(kind=c_float), parameter rnear_zero = 1E-9_c_float
real(kind=c_float), parameter rpoint2 = 0.2_c_float
real(kind=c_float), parameter rhalf = 0.5_c_float
real(kind=c_float), parameter dphalf = 0.5_c_double
real(kind=c_float), parameter rpoint8 = 0.8_c_float
real(kind=c_float), parameter rone = 1.0_c_float
real(kind=c_double), parameter dpone = 1.0_c_double
real(kind=c_float), parameter rfreezing = 32.0_c_float
real(kind=c_double), parameter dpfreezing = 32.0_c_double
real(kind=c_float), parameter rten = 10.0_c_float
real(kind=c_float), parameter rhundred = 100.0_c_float
real(kind=c_float), parameter rthousand = 1000.0_c_float
real(kind=c_double), parameter dpc_per_f = 5.0_c_double / 9.0_c_double
real(kind=c_double), parameter dpf_per_c = 9.0_c_double / 5.0_c_double
real(kind=c_float), parameter rm_per_foot = 0.3048_c_float
real(kind=c_float), parameter rmm_per_inch = 25.4_c_float
real(kind=c_float), parameter rcm_per_inch = 2.54_c_float
real(kind=c_double), parameter dppi = 3.141592653589793_c_double
real(kind=c_double), parameter dppi_over_180 = dpPI / 180_c_double
real(kind=c_double), parameter dptwopi = 2.0_c_double * dpPI
real(kind=c_double), parameter dpsqm_to_sqft = 10.76391_c_double
real(kind=c_float), parameter rminimum_soil_moisture = 0.51_c_float
integer(kind=c_short), parameter iactive_cell = 1
integer(kind=c_short), parameter iinactive_cell = 0
integer(kind=c_int), parameter imoving_avg_terms = 5
integer(kind=c_int), parameter iroute_cell_marked = -1
integer(kind=c_int), parameter iroute_depression = -999
integer(kind=c_int), parameter iroute_left_grid = -1000
real(kind=c_float), parameter rno_data_ncdc = -99999.
integer(kind=c_int), parameter ino_data_ncdc = -99999
integer(kind=c_int), parameter inum_digits = 3
integer(kind=c_int), parameter ifield_width = 10
integer(kind=c_int), parameter izero = 0
logical(kind=c_bool), parameter ltrue = .true._c_bool
logical(kind=c_bool), parameter lfalse = .false._c_bool
character(len=30), parameter sproj4_latlon = "+proj=lonlat +ellps=GRS80 +datum=NAD83 +no_defs"
integer(kind=c_int), parameter ieof = HUGE(iZERO)
real(kind=c_float), parameter rbigval = HUGE(rZERO)
integer(kind=c_int), parameter ibigval = HUGE(iZERO)
character(len=1), parameter stab = achar(9)
character(len=2), parameter swhitespace = achar(9)//" "
character(len=1), parameter sbackslash = achar(92)
character(len=1), parameter sforwardslash = achar(47)
character(len=1), parameter sreturn = achar(13)
Constants (flow direction): General conversion factors and flags
Some useful and common conversion factors, defined here to ensure consistency throughout the code
integer(kind=c_short), parameter idir_depression =0
integer(kind=c_short), parameter idir_right =1
integer(kind=c_short), parameter idir_down_right =2
integer(kind=c_short), parameter idir_down =4
integer(kind=c_short), parameter idir_down_left =8
integer(kind=c_short), parameter idir_left =16
integer(kind=c_short), parameter idir_up_left =32
integer(kind=c_short), parameter idir_up =64
integer(kind=c_short), parameter idir_up_right =128
Globals: Variables for run-length encoding operation
These variables store the position of the start date and end date within the binary (stream) output file.
integer(kind=c_int) istartdate_pos
integer(kind=c_int) ienddate_pos
integer(kind=c_int) iendheader_pos
Constants: Definitions for ANSI.sys-like text colors
character(len=7), parameter sred = char(27)//'[1;31m'
character(len=7), parameter sgreen =char(27)//'[1;32m'
character(len=7), parameter syellow = char(27)//'[1;33m'
character(len=7), parameter sblue = char(27)//'[1;34m'
character(len=7), parameter scyan = char(27)//'[1;36m'
character(len=7), parameter swhite = char(27)//'[0;37m'
character(len=7), parameter sboldwhite = char(27)//'[1;37m'
character(len=7), parameter sclrscr = char(27)//'[2J'
Constants: Statistics that SWB knows how to calculate and store
Index values for members of the rMonthly, rDaily, and rAnnual arrays that are global variables within module stats
integer(kind=c_int), parameter inum_stats = 5
integer(kind=c_int), parameter imin = 1
integer(kind=c_int), parameter imean = 2
integer(kind=c_int), parameter imax = 3
integer(kind=c_int), parameter isum = 4
integer(kind=c_int), parameter ilength = 5
character(len=7), dimension(inum_stats),
parameter stat_names = [ "Minimum", "Mean ", "Maximum", "Sum ", "Length " ]
Constants: Variables that SWB can output or summarize
Index values for members of the rMonthly, rDaily, and rAnnual arrays that are global variables within module stats
Note
These constants are arranged in the desired order of output for daily and annual reporting: sources first, then the sinks, and then all other informational items
integer(kind=c_int), parameter igross_precip = 1
integer(kind=c_int), parameter isnowmelt = 2
integer(kind=c_int), parameter iinflow = 3
integer(kind=c_int), parameter iirrigation = 4
integer(kind=c_int), parameter isnowfall_swe = 5
integer(kind=c_int), parameter iinterception = 6
integer(kind=c_int), parameter ioutflow = 7
integer(kind=c_int), parameter irunoff_outside = 8
integer(kind=c_int), parameter iact_et = 9
integer(kind=c_int), parameter ichg_in_soil_moist = 10
integer(kind=c_int), parameter irecharge = 11
integer(kind=c_int), parameter irejected_recharge = 12
integer(kind=c_int), parameter istream_capture = 13
integer(kind=c_int), parameter isnowcover = 14
integer(kind=c_int), parameter icfgi = 15
integer(kind=c_int), parameter imin_temp = 16
integer(kind=c_int), parameter imax_temp = 17
integer(kind=c_int), parameter iavg_temp = 18
integer(kind=c_int), parameter ichg_in_snow_cov = 19
integer(kind=c_int), parameter inet_rainfall = 20
integer(kind=c_int), parameter inet_inflow = 21
integer(kind=c_int), parameter inet_infil = 22
integer(kind=c_int), parameter ireference_et = 23
integer(kind=c_int), parameter ireference_et_adj = 24
integer(kind=c_int), parameter icrop_et = 25
integer(kind=c_int), parameter ibare_soil_evap = 26
integer(kind=c_int), parameter ip_minus_pet = 27
integer(kind=c_int), parameter ism_deficit = 28
integer(kind=c_int), parameter ism_surplus = 29
integer(kind=c_int), parameter ism_apwl = 30
integer(kind=c_int), parameter isoil_moisture = 31
integer(kind=c_int), parameter igdd = 32
integer(kind=c_int), parameter irooting_depth = 33
integer(kind=c_int), parameter icrop_coefficient = 34
integer(kind=c_int), parameter iirrigation_from_gw = 35
integer(kind=c_int), parameter iirrigation_from_sw = 36
integer(kind=c_int), parameter stream_interactions_max = 100
Constants: Runoff calculation
Options controlling the selection of a runoff calculation algorithm
integer(kind=c_int), parameter config_runoff_curve_number = 0
integer(kind=c_int), parameter config_runoff_green_ampt = 1
Constants: Runoff routing calculation
Options for routing mechanism selection
integer(kind=c_int), parameter config_runoff_iterative = 0
integer(kind=c_int), parameter config_runoff_downhill = 1
integer(kind=c_int), parameter config_runoff_no_routing = 2
Constants: Evapotranspiration algorithm
Options for specifying the choice of evapotranspiration algorithm
integer(kind=c_int), parameter config_et_none = 0
integer(kind=c_int), parameter config_et_thornthwaite_mather = 1
integer(kind=c_int), parameter config_et_turc = 2
integer(kind=c_int), parameter config_et_jensen_haise = 3
integer(kind=c_int), parameter config_et_blaney_criddle = 4
integer(kind=c_int), parameter config_et_hargreaves = 5
Constants: Precipitation data format
Options for specifying the method of input for precipitation data
integer(kind=c_int), parameter config_precip_single_station = 0
integer(kind=c_int), parameter config_precip_arc_grid = 1
integer(kind=c_int), parameter config_precip_surfer_grid = 2
integer(kind=c_int), parameter config_precip_netcdf = 3
Constants: Temperature data format
Options for specifying the method of input for temperature data
integer(kind=c_int), parameter config_temperature_single_station = 0
integer(kind=c_int), parameter config_temperature_arc_grid = 1
integer(kind=c_int), parameter config_temperature_surfer_grid = 2
integer(kind=c_int), parameter config_temperature_netcdf = 3
Constants: Landuse input data format
Options for specifying the method of input for temperature data
integer(kind=c_int), parameter config_landuse_constant = 0
integer(kind=c_int), parameter config_landuse_dynamic_arc_grid = 1
integer(kind=c_int), parameter config_landuse_dynamic_surfer = 2
integer(kind=c_int), parameter config_landuse_dynamic_netcdf = 3
integer(kind=c_int), parameter config_landuse_static_grid = 4
Constants: Snow module
Configuration for selection of snowfall and snowmelt modules
integer(kind=c_int), parameter config_snow_original_swb = 0
integer(kind=c_int), parameter config_snow_new_swb = 1
Constants: Soil-moisture input data format
Configuration information for soil-moisture capacity calculations
integer(kind=c_int), parameter config_sm_capacity_calculate = 0
integer(kind=c_int), parameter config_sm_capacity_constant = 1
integer(kind=c_int), parameter config_sm_capacity_fm_table = 2
Constants: Thornthwaite-Mather implementation method
Configuration information for Thornthwaite-Mather SM retention
integer(kind=c_int), parameter config_sm_none = 0
integer(kind=c_int), parameter config_sm_tm_lookup_table = 1
integer(kind=c_int), parameter config_sm_tm_equations = 2
Constants: FAO56 module
Configuration information for FAO56 calculations
integer(kind=c_int), parameter config_fao56_none = 0
integer(kind=c_int), parameter config_fao56_one_factor_standard = 1
integer(kind=c_int), parameter config_fao56_one_factor_nonstandard = 2
integer(kind=c_int), parameter config_fao56_two_factor_standard = 3
integer(kind=c_int), parameter config_fao56_two_factor_nonstandard = 4
Constants: SCS curve number
Configuration information for initial abstraction assumptions
integer(kind=c_int), parameter config_sm_init_abstraction_tr55 = 0
integer(kind=c_int), parameter config_sm_init_abstraction_hawkins = 1
Constants: Output grid format
Options for output formats
integer(kind=c_int), parameter output_surfer = 0
integer(kind=c_int), parameter output_arc = 1
Detailed Description
This module defines parameters and derived data types for use throughout the SWB code. This module also contains a number of utility functions that perform string manipulations, convert Celcius to Fahrenheit, and convert between Julian days and Gregorian dates.
Definition at line 11 of file types.F90.
Member Function/Subroutine Documentation
logical(kind=c_bool) function types::approx_equal_dbl (real(kind=c_double) rA, real(kind=c_double) rB, real(kind=c_double), optional rTol)
Definition at line 2146 of file types.F90.
logical(kind=c_bool) function types::approx_equal_sgl (real(kind=c_float) rA, real(kind=c_float) rB, real(kind=c_float), optional rTol)
Definition at line 2178 of file types.F90.
character (len=256) function types::ascsv (character (len=*) sText)
Definition at line 2942 of file types.F90.
subroutine types::assert_module_details_fl_sub (logical, intent(in) lCondition, character (len=*), intent(in) sErrorMessage, character (len=*) sFilename, integer (kind=c_int) iLineNum)
Definition at line 1392 of file types.F90.
References types::assert::assert_module_details_sub().
subroutine types::assert_module_details_sub (logical (kind=c_bool), intent(in) lCondition, character (len=*), intent(in) sErrorMessage, character (len=*) sFilename, integer (kind=c_int) iLineNum)
Definition at line 1359 of file types.F90.
References types::t_ssf_files::ilu, types::t_general_grid::sfilename, and writemultiline().
subroutine types::assert_simple_fl_sub (logical, intent(in) lCondition, character (len=*), intent(in) sErrorMessage)
Definition at line 1346 of file types.F90.
References types::assert::assert_simple_sub().
subroutine types::assert_simple_sub (logical (kind=c_bool), intent(in) lCondition, character (len=*), intent(in) sErrorMessage)
Definition at line 1319 of file types.F90.
References types::t_ssf_files::ilu, and writemultiline().
elemental function types::c_size_t2char (integer (kind=c_size_t), intent(in) iValue)
Definition at line 2730 of file types.F90.
elemental function types::c_to_fortran_string (character (len=*), intent(in) cCharacterString)
Definition at line 2994 of file types.F90.
Referenced by netcdf4_support::nf_populate_attribute_struct(), netcdf4_support::nf_populate_dimension_struct(), and netcdf4_support::nf_populate_variable_struct().
integer (kind=c_int) function types::char2int (character (len=*) sValue)
Definition at line 2658 of file types.F90.
real (kind=c_float) function types::char2real (character (len=*) sValue)
Definition at line 2694 of file types.F90.
character(len=256) function types::char_ptr_to_fortran_string (type(c_ptr) cpCharacterPtr)
Definition at line 2971 of file types.F90.
Referenced by netcdf4_support::nf_trap().
subroutine types::chomp_default_sub (character (len=*), intent(inout) sRecord, character (len=256), intent(out) sItem)
Definition at line 1466 of file types.F90.
References dquote(), and types::ascharacter::int2char().
subroutine types::chomp_delim_sub (character (len=*), intent(inout) sRecord, character (len=256), intent(out) sItem, character (len=*), intent(in) sDelimiters)
Definition at line 1420 of file types.F90.
References dquote(), and types::ascharacter::int2char().
subroutine types::chomp_slash (character (len=*), intent(inout) sRecord, character (len=256), intent(out) sItem)
Definition at line 1672 of file types.F90.
Referenced by mmdd2doy(), mmddyyyy2doy(), mmddyyyy2julian(), and swbstats().
subroutine types::chomp_tab (character (len=*), intent(inout) sRecord, character (len=256), intent(out) sItem)
Definition at line 1621 of file types.F90.
character (len=256) function types::clean (character (len=*), intent(inout) sRecord, character (len=*), intent(in), optional sDelimiters)
Definition at line 1932 of file types.F90.
Referenced by datetime::parse_text_to_date_sub(), and datetime::parse_text_to_time_sub().
subroutine types::cleanupcsv (character (len=*), intent(inout) s)
Definition at line 1913 of file types.F90.
Referenced by et_thornthwaite_mather::et_tm_initialize(), and model::model_readtimeseriesfile().
subroutine types::cleanupslash (character (len=*), intent(inout) s)
Definition at line 1982 of file types.F90.
integer(kind=c_int) function types::count_fields (character (len=*), intent(inout) sRecord)
Definition at line 2374 of file types.F90.
real (kind=c_double) function types::ctof_dbl_fn (real (kind=c_double), intent(in) rC)
Definition at line 2323 of file types.F90.
real (kind=c_float) function types::ctof_sgl_fn (real (kind=c_float), intent(in) rC)
Definition at line 2311 of file types.F90.
integer (kind=c_int) function types::day_of_year (integer (kind=c_int), intent(in) iJD)
Definition at line 2832 of file types.F90.
References gregorian_date(), types::t_month::imonth, and julian_day().
elemental function types::dbl2char (real (kind=c_double), intent(in) rValue, character (len=*), intent(in), optional sFmt)
Definition at line 2763 of file types.F90.
integer (kind=c_int) function types::dbl2int (real (kind=c_double) rValue)
Definition at line 2682 of file types.F90.
real (kind=c_float) function types::dbl2real (real (kind=c_double) dpValue)
Definition at line 2718 of file types.F90.
elemental function types::deg2rad (real (kind=c_double), intent(in) rDeg)
Definition at line 2784 of file types.F90.
character (len=len_trim(adjustl(sstring))+2) function types::dquote (character (len=*), intent(in) sString)
Definition at line 1284 of file types.F90.
Referenced by swbstats_support::calcmaskstats(), swbstats_support::calcmaskstatsssf(), chomp_default_sub(), chomp_delim_sub(), control::control_setmodeloptions(), swb_grid::grid_checkforproj4error(), swb_grid::grid_completelycover(), swb_grid::grid_dumpgridextent(), swb_grid::grid_readarcgrid_fn(), swb_grid::grid_readarcgrid_sub(), swb_grid::grid_readsurfergrid_fn(), swb_grid::grid_readsurfergrid_sub(), swb_grid::grid_writearcgrid(), swb_grid::grid_writesurfergrid(), model::model_readirrigationlookuptable(), netcdf4_support::netcdf_close_file(), netcdf4_support::nf_create(), netcdf4_support::nf_get_time_units(), netcdf4_support::nf_get_variable_id_and_type(), netcdf4_support::nf_julian_day_to_index_adj(), netcdf4_support::nf_open_file(), netcdf4_support::nf_return_attvalue(), netcdf4_support::nf_trap(), datetime::set_date_format_indices(), datetime::set_time_format_indices(), stats::stats_openbinaryfiles(), stats::stats_writeminmeanmax(), and str_compare().
subroutine types::echolog (character(len=*), intent(in) sMessage)
Definition at line 1408 of file types.F90.
References writemultiline().
Referenced by control::control_setmodeloptions(), et_hargreaves::et_hargreaves_configure(), swb_grid::grid_completelycover(), swb_grid::grid_createcomplete(), swb_grid::grid_dumpgridextent(), swb_grid::grid_gridtogrid_int(), model::model_createlanduseindex(), model::model_getdailyprecipvalue(), model::model_getdailytemperaturevalue(), model::model_readtimeseriesfile(), model::model_setinactivecells(), netcdf4_support::netcdf_close_file(), netcdf4_support::nf_create(), netcdf4_support::nf_open_file(), netcdf4_support::nf_return_index_double(), netcdf4_support::nf_trap(), model::rf_model_cellrunoff(), and model::rf_model_getinterception().
elemental function types::fortran_to_c_string (character (len=*), intent(in) sText)
Definition at line 3020 of file types.F90.
Referenced by netcdf4_support::nf_create(), netcdf4_support::nf_define_variable(), and netcdf4_support::nf_define_variables().
real (kind=c_double) function types::ftoc_dbl_fn (real (kind=c_double), intent(in) rF)
Definition at line 2284 of file types.F90.
real (kind=c_float) function types::ftoc_sgl_fn (real (kind=c_float), intent(in) rF)
Definition at line 2272 of file types.F90.
real (kind=c_double) function types::ftok_dbl_fn (real (kind=c_double), intent(in) rF)
Definition at line 2361 of file types.F90.
real (kind=c_float) function types::ftok_sgl_fn (real (kind=c_float), intent(in) rF)
Definition at line 2350 of file types.F90.
subroutine types::getsystimedate (character(len=256), intent(out) sDateStr, character(len=256), intent(out) sDateStrPretty)
Definition at line 1561 of file types.F90.
subroutine types::gregorian_date (integer (kind=c_int) iJD, integer (kind=c_int), intent(inout) iYear, integer (kind=c_int), intent(inout) iMonth, integer (kind=c_int), intent(inout) iDay, integer (kind=c_int), optional iOrigin)
Converts from a Julian day number to a Gregorian date. Valid for any Gregorian calendar date producing a Julian day number greater than zero.
Reference: Fliegel, H. F. and van Flandern, T. C. (1968). Communications of the ACM, Vol. 11, No. 10 (October, 1968).
Modified from code found at: http://aa.usno.navy.mil/faq/docs/JD_Formula.html
Definition at line 2895 of file types.F90.
References types::t_month::imonth, and types::t_stats::ioffset.
Referenced by datetime::calc_gregorian_date_sub(), control::control_setmodeloptions(), day_of_year(), lookupmonth(), model::model_solve(), solstice(), and swbstats().
elemental function types::int2char (integer (kind=c_int), intent(in) iValue)
Definition at line 2632 of file types.F90.
real (kind=c_float) function types::int2real (integer (kind=c_int) iValue)
Definition at line 2706 of file types.F90.
real (kind=c_float) function types::interpolate (real (kind=c_float), dimension(:), intent(in) rXT, real (kind=c_float), dimension(:), intent(in) rYT, real (kind=c_float), intent(in) rX)
Definition at line 2453 of file types.F90.
References types::t_general_grid::rx, and types::t_general_grid::ry.
logical (kind=c_bool) function types::isleap (integer (kind=c_int), intent(in) iYear)
Definition at line 2850 of file types.F90.
integer (kind=c_int) function types::julian_day (integer (kind=c_int), intent(in) iYear, integer (kind=c_int), intent(in) iMonth, integer (kind=c_int), intent(in) iDay, integer (kind=c_int), optional iOrigin)
Definition at line 2503 of file types.F90.
References types::t_month::imonth, types::ascharacter::int2char(), and types::t_stats::ioffset.
Referenced by datetime::calc_julian_day_sub(), water_balance::calculate_water_balance(), control::control_setmodeloptions(), day_of_year(), lookupmonth(), mmdd2doy(), mmddyyyy2doy(), mmddyyyy2julian(), model::model_readtimeseriesfile(), netcdf4_support::nf_calculate_time_range(), num_days_in_year(), and swbstats().
logical (kind=c_bool) function types::lf_model_growingseason (type (t_model_configuration), pointer pConfig, integer (kind=c_int), intent(in) iDayOfYear)
Definition at line 2236 of file types.F90.
Referenced by runoff_curve_number::runoff_updatecurvenumber().
subroutine types::lookupmonth (integer (kind=c_int), intent(in) iMonth, integer (kind=c_int), intent(in) iDay, integer (kind=c_int), intent(in) iYear, integer (kind=c_int), intent(out) iDayOfYear, character (len=3), intent(out) sMonthName, logical (kind=c_bool), intent(out) lMonthEnd)
Definition at line 2101 of file types.F90.
References gregorian_date(), types::t_month::imonth, and julian_day().
Referenced by et_thornthwaite_mather::et_tm_initialize(), model::model_solve(), stats::stats_rewritegrids(), and swbstats().
character(len=len(s)) function types::lowercase_fn (character (len=*), intent(in) s)
Definition at line 1856 of file types.F90.
Referenced by control::control_setmodeloptions().
real (kind=c_float) function types::mm_to_in (real (kind=c_float), intent(in) r_mm)
Definition at line 2415 of file types.F90.
integer (kind=c_int) function types::mmdd2doy (character (len=*) sMMDD)
Definition at line 1745 of file types.F90.
References chomp_slash(), types::t_month::imonth, and julian_day().
Referenced by model::model_readirrigationlookuptable().
integer (kind=c_int) function types::mmddyyyy2doy (character (len=*) sMMDDYYYY)
Definition at line 1785 of file types.F90.
References chomp_slash(), types::t_month::imonth, and julian_day().
integer (kind=c_int) function types::mmddyyyy2julian (character (len=*) sMMDDYYYY)
Definition at line 1705 of file types.F90.
References chomp_slash(), types::t_month::imonth, and julian_day().
Referenced by swbstats().
integer function types::newunit (integer, intent(out), optional unit)
Definition at line 2010 of file types.F90.
Referenced by swbstats_support::calcbasinstats(), swbstats_support::calcmaskstats(), swbstats_support::calcmaskstatsssf(), and model::model_configurerunoffdownhill().
integer (kind=c_int) function types::nextunit (integer (kind=c_int), intent(out), optional iLU)
Definition at line 1246 of file types.F90.
References types::t_ssf_files::ilu.
Referenced by stats::stats_openbinaryfiles(), stats::stats_openbinaryfilesreadonly(), and swbstats().
integer (kind=c_int) function types::num_days_in_year (integer (kind=c_int), intent(in) iYear)
This function simply returns the number of days given the current year.
Definition at line 2815 of file types.F90.
References julian_day().
Referenced by control::control_setmodeloptions(), and model::model_solve().
real (kind=c_double) function types::polynomial (real (kind=c_double), intent(in) x, real (kind=c_double), dimension(:) a)
Definition at line 2044 of file types.F90.
elemental function types::rad2deg (real (kind=c_double), intent(in) rRad)
Definition at line 2798 of file types.F90.
elemental function types::real2char (real (kind=c_float), intent(in) rValue, character (len=*), intent(in), optional sFmt)
Definition at line 2743 of file types.F90.
integer (kind=c_int) function types::real2int (real (kind=c_float) rValue)
Definition at line 2670 of file types.F90.
elemental function types::short2char (integer (kind=c_short), intent(in) iValue)
Definition at line 2645 of file types.F90.
integer (kind=c_int) function types::solstice (integer (kind=c_int), intent(in) iJD)
Definition at line 2562 of file types.F90.
References gregorian_date(), and types::t_month::imonth.
character (len=len_trim(adjustl(sstring))+2) function types::squote (character (len=*), intent(in) sString)
Definition at line 1271 of file types.F90.
Referenced by control::control_setmodeloptions().
logical (kind=c_bool) function types::str_compare (character(len=*), intent(in) sString1, character(len=*), intent(in) sString2)
Definition at line 1295 of file types.F90.
References dquote(), types::ascharacter::int2char(), and uppercase_fn().
Referenced by control::control_setmodeloptions(), model::model_readirrigationlookuptable(), model::model_readlanduselookuptable(), netcdf4_support::nf_get_scale_and_offset(), netcdf4_support::nf_get_time_units(), netcdf4_support::nf_get_variable_id_and_type(), netcdf4_support::nf_get_xyz_units(), and netcdf4_support::nf_return_attvalue().
subroutine types::uppercase (character (len=*), intent(inout) s)
Definition at line 1880 of file types.F90.
Referenced by control::control_setmodeloptions(), swb_grid::grid_readarcgrid_fn(), swb_grid::grid_readarcgrid_sub(), model::model_readbasinmasktable(), model::model_readlanduselookuptable(), and swbstats_support::readbasinmasktable().
character(len=len(s)) function types::uppercase_fn (character (len=*), intent(in) s)
Definition at line 1831 of file types.F90.
Referenced by str_compare().
subroutine types::writemultiline (character (len=*) sMessageText, integer (kind=c_int) iLU)
Writes one or more lines of an input text string to a Fortran logical unit number. To output multiple lines, insert a tilde (~) at each point in the text string where a carriage return is desired.
Parameters
[in] sMessageText Character string that contains the message to be written.
[in] iLU Integer value of the Fortran logical unit number to write to.
Definition at line 2600 of file types.F90.
References types::t_ssf_files::ilu.
Referenced by assert_module_details_sub(), assert_simple_sub(), and echolog().
Member Data Documentation
integer(kind=c_int), parameter types::iannual = 3
Definition at line 1185 of file types.F90.
integer(kind=c_int), parameter types::idaily = 1
Definition at line 1183 of file types.F90.
integer(kind=c_int), parameter types::imonthly = 2
Definition at line 1184 of file types.F90.
The documentation for this module was generated from the following file:
types.F90
USGS Home Water Resources Biology Geography Geology Geospatial SWB Home Wisconsin WSC
Accessibility FOIA Privacy Policies and Notices
U.S. Department of the Interior | U.S. Geological Survey
URL: http://wi.water.usgs.gov/Soil_Water_Balance/SWB_code_docs/index.html
Page Contact Information: webmaster@wi.water.usgs.gov
Page Last Modified: Thu May 19 2011 14:11:32
Page generated with:
1.8.2