SOIL-WATER-BALANCE SOURCE CODE BROWSER- USGS Wisconsin Water Science Center
USGS Home
Contact USGS
Search USGS
Soil-Water-Balance Source Code Browser
sm_thornthwaite_mather Module Reference
Performs the actual soil-moisture balance once precip, snowmelt, runoff, and ET have been calculated. Soil moisture for a given soil accumulated potential water loss (APWL) is determined by means of Thornthwaite and Mathers' (1957) tables.
Public Member Functions
subroutine sm_thornthwaite_mather_configure (sRecord)
subroutine sm_thornthwaite_mather_initialize (pGrd, pConfig)
subroutine sm_thornthwaite_mather_updatesm (pGrd, pConfig, iDayOfYear, iDay, iMonth, iYear)
real(kind=t_dbl) function sm_thornthwaite_mather_soil_storage (rSWC, rAPWL)
real(kind=t_dbl) function sm_thornthwaite_mather_apwl (rSWC, dpSoilStorage)
subroutine sm_thornthwaite_mather_updatepctsm (pGrd)
Public Attributes
real(kind=t_sgl), parameter apwl_cap -40.69_T_SGL
type(t_general_grid), pointer gwlt
real(kind=t_dbl), parameter rtm_slope_term 0.4787691
real(kind=t_dbl), parameter rtm_exp_term -1.036784
Detailed Description
Definition at line 8 of file sm_thornthwaite_mather.F90.
Member Function/Subroutine Documentation
real (kind=t_dbl) function sm_thornthwaite_mather::sm_thornthwaite_mather_apwl (real (kind=t_sgl), intent(in) rSWC, real (kind=t_dbl), intent(in) dpSoilStorage)
Definition at line 1151 of file sm_thornthwaite_mather.F90.
References types::dpzero, and types::rzero.
Referenced by sm_thornthwaite_mather_initialize(), and sm_thornthwaite_mather_updatesm().
subroutine sm_thornthwaite_mather::sm_thornthwaite_mather_configure (character (len=*), intent(inout) sRecord)
Definition at line 47 of file sm_thornthwaite_mather.F90.
References swb_grid::grid_read(), types::lu_log, and types::t_sgl_grid.
Referenced by control::control_setmodeloptions().
subroutine sm_thornthwaite_mather::sm_thornthwaite_mather_initialize (type (t_general_grid), pointer pGrd, type (t_model_configuration), pointer pConfig)
Definition at line 73 of file sm_thornthwaite_mather.F90.
References types::dpone, types::dpzero, swb_grid::grid_searchcolumn(), swb_grid::grid_writearcgrid(), types::lu_log, types::t_basin_mask::pgrd, types::rhundred, types::rnear_zero, types::rone, types::rzero, and sm_thornthwaite_mather_apwl().
Referenced by model::model_initializesm().
real (kind=t_dbl) function sm_thornthwaite_mather::sm_thornthwaite_mather_soil_storage (real (kind=t_sgl), intent(in) rSWC, real (kind=t_sgl), intent(in) rAPWL)
Definition at line 1126 of file sm_thornthwaite_mather.F90.
References types::dpzero, and types::rzero.
Referenced by sm_thornthwaite_mather_updatesm().
subroutine sm_thornthwaite_mather::sm_thornthwaite_mather_updatepctsm (type (t_general_grid), pointer pGrd)
Definition at line 1174 of file sm_thornthwaite_mather.F90.
References types::t_basin_mask::pgrd, types::rnear_zero, and types::rzero.
Referenced by model::model_solve().
subroutine sm_thornthwaite_mather::sm_thornthwaite_mather_updatesm (type (t_general_grid), pointer pGrd, type (t_model_configuration), pointer pConfig, integer (kind=t_int), intent(in) iDayOfYear, integer (kind=t_int), intent(in) iDay, integer (kind=t_int), intent(in) iMonth, integer (kind=t_int), intent(in) iYear)
Definition at line 146 of file sm_thornthwaite_mather.F90.
References types::config_runoff_no_routing, types::dpone, types::dpzero, swb_grid::grid_interpolate(), swb_grid::grid_searchcolumn(), types::iact_et, types::iavg_temp, types::icfgi, types::ichg_in_snow_cov, types::ichg_in_soil_moist, types::t_model_configuration::iday, types::t_model_configuration::idayofyear, types::igdd, types::igross_precip, types::iinflow, types::iinterception, types::iirrigation, types::t_cell::ilanduse, types::imax_temp, types::imin_temp, types::t_month::imonth, types::inc_output, types::inet_infil, types::inet_inflow, types::inet_precip, types::inone, types::inum_variables, types::t_general_grid::inumgridcells, types::ioutflow, types::ip_minus_pet, types::ipot_et, types::irecharge, types::irejected_recharge, types::iroute_depression, types::iroute_left_grid, types::irunoff_outside, types::ism_apwl, types::ism_deficit, types::ism_surplus, types::isnowcover, types::isnowfall_swe, types::isnowmelt, types::isoil_moisture, types::t_cell::isoilgroup, types::istream_capture, types::t_model_configuration::iyear, types::izero, types::julian_day(), types::lfalse, types::lu_log, main(), netcdf_support::netcdf_write_variable_byte(), types::t_basin_mask::pgrd, types::rhundred, rle::rle_writebyte(), types::rnear_zero, types::rone, types::rzero, sm_thornthwaite_mather_apwl(), sm_thornthwaite_mather_soil_storage(), types::stat_info, stats::stats_updateallaccumulatorsbycell(), and stats::stats_write_to_ssf_file().
Referenced by model::model_processsm().
Member Data Documentation
real (kind=t_sgl), parameter sm_thornthwaite_mather::apwl_cap -40.69_T_SGL
Definition at line 33 of file sm_thornthwaite_mather.F90.
type (t_general_grid), pointer sm_thornthwaite_mather::gwlt
Definition at line 38 of file sm_thornthwaite_mather.F90.
real (kind=t_dbl), parameter sm_thornthwaite_mather::rtm_exp_term -1.036784
Definition at line 43 of file sm_thornthwaite_mather.F90.
real (kind=t_dbl), parameter sm_thornthwaite_mather::rtm_slope_term 0.4787691
Definition at line 42 of file sm_thornthwaite_mather.F90.
The documentation for this module was generated from the following file:
sm_thornthwaite_mather.F90
USGS Home Water Resources Biology Geography Geology Geospatial SWB Home Wisconsin WSC
Accessibility FOIA Privacy Policies and Notices
U.S. Department of the Interior | U.S. Geological Survey
URL: http://wi.water.usgs.gov/Soil_Water_Balance/SWB_code_docs/index.html
Page Contact Information: webmaster@wi.water.usgs.gov
Page Last Modified: Thu May 19 2011 14:11:32
Page generated with:
1.8.2