SOIL-WATER-BALANCE SOURCE CODE BROWSER- USGS Wisconsin Water Science Center
USGS Home
Contact USGS
Search USGS
Soil-Water-Balance Source Code Browser
model Module Reference
Allocates memory to store intermediate and final calculation results, keeps track of the model date, reads tabular climate data, and calls the necessary process modules in turn.
Public Member Functions
subroutine model_solve (pGrd, pConfig, pGraph, pLandUseGrid)
subroutine model_endofrun (pGrd, pConfig, pGraph)
subroutine model_getdailyprecipvalue (pGrd, pConfig, rPrecip, iMonth, iDay, iYear, iJulianDay)
subroutine model_getdailytemperaturevalue (pGrd, pConfig, rAvgT, rMinT, rMaxT, rRH, iMonth, iDay, iYear, iJulianDay)
subroutine model_updatecontinuousfrozengroundindex (pGrd, pConfig)
subroutine model_updategrowingseason (pGrd, pConfig)
subroutine model_updategrowingdegreeday (pGrd, pConfig)
subroutine model_processrain (pGrd, pConfig, iDayOfYear, iMonth)
subroutine model_processrainprms (pGrd, pConfig, iDayOfYear, iMonth, iNumDaysInYear)
subroutine model_processrunoff (pGrd, pConfig, iDayOfYear, iMonth)
subroutine model_configurerunoffdownhill (pGrd, pConfig)
subroutine model_runoffdownhill (pGrd, pConfig, iDayOfYear, iMonth)
subroutine model_runoff_norouting (pGrd, pConfig, iDayOfYear, iMonth)
integer(kind=c_int) function if_model_runoffiteration (pGrd, pConfig, iDayOfYear, iMonth)
real(kind=c_float) function rf_model_cellrunoff (pConfig, cel, iDayOfYear)
real(kind=c_float) function rf_model_cellrunoff_greenampt (pConfig, cel, iDayOfYear)
subroutine model_initializeflowdirection (pGrd, pConfig)
subroutine model_downstreamcell (pGrd, iRow, iCol, iTgt_Row, iTgt_Col)
subroutine model_readbasinmasktable (pConfig)
subroutine model_readlanduselookuptable (pConfig)
subroutine model_readirrigationlookuptable (pConfig, pGrd)
real(kind=c_float) function rf_model_getinterception (pConfig, cel)
subroutine model_checkconfigurationsettings (pGrd, pConfig)
subroutine model_setinactivecells (pGrd, pConfig)
subroutine model_initializedatastructures (pGrd, pConfig)
subroutine model_initializeinputandoutput (pGrd, pConfig)
subroutine model_initializerunoff (pGrd, pConfig)
subroutine model_initializelanduserelatedparams (pGrd, pConfig)
subroutine model_initializeet (pGrd, pConfig)
subroutine model_processet (pGrd, pConfig, iDayOfYear, iNumDaysInYear, rRH, rMinRH, rWindSpd, rSunPct)
subroutine model_initializesm (pGrd, pConfig)
subroutine model_createlanduseindex (pGrd, pConfig)
subroutine model_createirrigationtableindex (pGrd, pConfig)
subroutine model_writegrids (pGrd, pConfig, iOutputType)
subroutine model_readtimeseriesfile (pConfig, pTS)
This subroutine reads a single line from a single-station climate data file, parses the values, and returns a pointer to a time-series data object.
Public Attributes
integer(kind=c_int) idayctr
type(t_general_grid), pointer pgenericgrd_int
type(t_general_grid), pointer pgenericgrd_sgl
integer(kind=c_int) iordercount
integer(kind=c_int), dimension(:),
allocatable iordercol
integer(kind=c_int), dimension(:),
allocatable iorderrow
real(kind=c_float) rstarttime
real(kind=c_float) rendtime
Detailed Description
Definition at line 8 of file model.F90.
Member Function/Subroutine Documentation
integer (kind=c_int) function model::if_model_runoffiteration (type (t_general_grid), pointer pGrd, type (t_model_configuration), pointer pConfig, integer (kind=c_int), intent(in) iDayOfYear, integer (kind=c_int), intent(in) iMonth)
Definition at line 1981 of file model.F90.
References types::iinactive_cell, types::ascharacter::int2char(), types::iroute_depression, types::iroute_left_grid, types::t_cell::itgt_col, types::t_cell::itgt_row, types::lfalse, model_downstreamcell(), types::t_basin_mask::pgrd, rf_model_cellrunoff(), and types::rzero.
Referenced by model_processrunoff().
subroutine model::model_checkconfigurationsettings (type (t_general_grid), pointer pGrd, type (t_model_configuration), pointer pConfig)
Definition at line 3127 of file model.F90.
References types::config_fao56_none, types::datatype_na, types::lfalse, and types::stab.
Referenced by model_solve().
subroutine model::model_configurerunoffdownhill (type (t_general_grid), pointer pGrd, type (t_model_configuration), pointer pConfig)
Definition at line 1495 of file model.F90.
References types::datatype_int, swb_grid::grid_writearcgrid(), types::iactive_cell, types::iinactive_cell, types::ascharacter::int2char(), types::t_general_grid::inumgridcells, types::iroute_cell_marked, types::t_cell::itgt_col, types::t_cell::itgt_row, types::lfalse, types::ltrue, types::lu_log, types::lu_routing, types::lu_std_out, types::lu_temp, graph::make_shaded_contour(), model_downstreamcell(), types::newunit(), and types::t_basin_mask::pgrd.
Referenced by model_initializerunoff(), and model_solve().
subroutine model::model_createirrigationtableindex (type (t_general_grid), pointer pGrd, type (t_model_configuration), pointer pConfig)
Definition at line 3624 of file model.F90.
References types::ascharacter::int2char(), types::lfalse, types::ltrue, and types::t_basin_mask::pgrd.
Referenced by model_solve().
subroutine model::model_createlanduseindex (type (t_general_grid), pointer pGrd, type (t_model_configuration), pointer pConfig)
Definition at line 3574 of file model.F90.
References types::echolog(), types::iinactive_cell, types::lfalse, types::ltrue, and types::t_basin_mask::pgrd.
Referenced by model_initializelanduserelatedparams().
subroutine model::model_downstreamcell (type (t_general_grid), pointer pGrd, integer (kind=c_int), intent(in) iRow, integer (kind=c_int), intent(in) iCol, integer (kind=c_int), intent(out) iTgt_Row, integer (kind=c_int), intent(out) iTgt_Col)
Definition at line 2375 of file model.F90.
References types::iroute_depression, types::iroute_left_grid, types::t_cell::itgt_col, types::t_cell::itgt_row, and types::t_basin_mask::pgrd.
Referenced by if_model_runoffiteration(), model_configurerunoffdownhill(), and model_runoffdownhill().
subroutine model::model_endofrun (type (t_general_grid), pointer pGrd, type (t_model_configuration), pointer pConfig, type (t_graph_configuration), dimension(:), pointer pGraph)
Definition at line 460 of file model.F90.
References swb_grid::grid_destroy(), types::ienddate_pos, types::inone, types::inum_variables, types::lu_csv_annual, types::lu_csv_max, types::lu_csv_mean, types::lu_csv_min, types::lu_log, types::lu_msb_report, types::lu_ts, netcdf4_support::netcdf_close_file(), netcdf4_support::netcdf_deallocate_data_struct(), types::t_basin_mask::pgrd, types::stat_info, stats::stats_closebinaryfiles(), and stats::stats_rewritegrids().
Referenced by control::control_setmodeloptions().
subroutine model::model_getdailyprecipvalue (type (t_general_grid), pointer pGrd, type (t_model_configuration), pointer pConfig, real (kind=c_float), intent(in) rPrecip, integer (kind=c_int), intent(in) iMonth, integer (kind=c_int), intent(in) iDay, integer (kind=c_int), intent(in) iYear, integer (kind=c_int), intent(in) iJulianDay)
Definition at line 558 of file model.F90.
References types::echolog(), types::igross_precip, types::t_month::imonth, types::ascharacter::int2char(), types::t_basin_mask::pgrd, types::ascharacter::real2char(), types::t_basin_mask::rmax, types::t_basin_mask::rmean, types::t_basin_mask::rmin, types::rzero, and stats::stats_updateallaccumulatorsbygrid().
Referenced by model_solve().
subroutine model::model_getdailytemperaturevalue (type (t_general_grid), pointer pGrd, type (t_model_configuration), pointer pConfig, real (kind=c_float), intent(in) rAvgT, real (kind=c_float), intent(in) rMinT, real (kind=c_float), intent(in) rMaxT, real (kind=c_float), intent(in) rRH, integer (kind=c_int), intent(in) iMonth, integer (kind=c_int), intent(in) iDay, integer (kind=c_int), intent(in) iYear, integer (kind=c_int), intent(in) iJulianDay)
Definition at line 660 of file model.F90.
References types::echolog(), types::t_month::imonth, types::ascharacter::int2char(), types::t_basin_mask::pgrd, and types::ascharacter::real2char().
Referenced by model_solve().
subroutine model::model_initializedatastructures (type (t_general_grid), pointer pGrd, type (t_model_configuration), pointer pConfig)
Definition at line 3190 of file model.F90.
References types::datatype_na, swb_grid::grid_writegrid(), types::iactive_cell, types::iinactive_cell, types::lu_log, graph::make_shaded_contour(), types::t_basin_mask::pgrd, and types::t_general_grid::sfilename.
Referenced by model_solve().
subroutine model::model_initializeet (type (t_general_grid), pointer pGrd, type (t_model_configuration), pointer pConfig)
Definition at line 3415 of file model.F90.
References types::config_et_blaney_criddle, types::config_et_hargreaves, types::config_et_jensen_haise, types::config_et_none, types::config_et_thornthwaite_mather, types::config_et_turc, et_blaney_criddle::et_bc_initialize(), et_jensen_haise::et_jh_initialize(), et_thornthwaite_mather::et_tm_initialize(), et_turc::et_turc_initialize(), types::lu_log, and types::t_basin_mask::pgrd.
Referenced by model_solve().
subroutine model::model_initializeflowdirection (type (t_general_grid), pointer pGrd, type (t_model_configuration), pointer pConfig)
Definition at line 2187 of file model.F90.
References types::config_runoff_no_routing, types::iinactive_cell, types::iroute_depression, types::iroute_left_grid, types::t_cell::itgt_col, types::t_cell::itgt_row, types::lu_log, and types::t_basin_mask::pgrd.
Referenced by model_initializerunoff(), and model_solve().
subroutine model::model_initializeinputandoutput (type (t_general_grid), pointer pGrd, type (t_model_configuration), pointer pConfig)
Definition at line 3319 of file model.F90.
References swb_grid::grid_writearcgrid(), types::imax, types::imean, types::imin, types::lu_csv_annual, types::lu_csv_max, types::lu_csv_mean, types::lu_csv_min, types::t_basin_mask::pgrd, stats::stats_initializevolumeconversion(), stats::stats_openbinaryfiles(), stats::stats_openmsbreport(), stats::stats_writeannualaccumulatorheadercsv(), and stats::stats_writedailyaccumulatorheadercsv().
Referenced by model_solve().
subroutine model::model_initializelanduserelatedparams (type (t_general_grid), pointer pGrd, type (t_model_configuration), pointer pConfig)
Definition at line 3393 of file model.F90.
References types::lu_log, model_createlanduseindex(), model_initializesm(), types::t_basin_mask::pgrd, and runoff_curve_number::runoff_initializecurvenumber().
Referenced by model_solve().
subroutine model::model_initializerunoff (type (t_general_grid), pointer pGrd, type (t_model_configuration), pointer pConfig)
Definition at line 3368 of file model.F90.
References types::config_runoff_downhill, types::config_runoff_no_routing, types::lu_log, model_configurerunoffdownhill(), model_initializeflowdirection(), and types::t_basin_mask::pgrd.
subroutine model::model_initializesm (type (t_general_grid), pointer pGrd, type (t_model_configuration), pointer pConfig)
must guard against segfaulting due to illegal values of soil type
Definition at line 3496 of file model.F90.
References types::config_sm_capacity_calculate, types::config_sm_none, types::config_sm_tm_equations, types::config_sm_tm_lookup_table, types::iinactive_cell, types::ascharacter::int2char(), types::lfalse, types::ltrue, types::t_basin_mask::pgrd, and sm_thornthwaite_mather::sm_thornthwaite_mather_initialize().
Referenced by model_initializelanduserelatedparams().
subroutine model::model_processet (type (t_general_grid), pointer pGrd, type (t_model_configuration), pointer pConfig, integer (kind=c_int), intent(in) iDayOfYear, integer (kind=c_int), intent(in) iNumDaysInYear, real (kind=c_float), intent(in) rRH, real (kind=c_float), intent(in) rMinRH, real (kind=c_float), intent(in) rWindSpd, real (kind=c_float), intent(in) rSunPct)
Definition at line 3446 of file model.F90.
References types::config_et_blaney_criddle, types::config_et_hargreaves, types::config_et_jensen_haise, types::config_et_none, types::config_et_thornthwaite_mather, types::config_et_turc, et_blaney_criddle::et_bc_computeet(), et_hargreaves::et_hargreaves_computeet(), et_jensen_haise::et_jh_computeet(), et_thornthwaite_mather::et_tm_computeet(), et_turc::et_turc_computeet(), and types::t_basin_mask::pgrd.
Referenced by model_solve().
subroutine model::model_processrain (type (t_general_grid), pointer pGrd, type (t_model_configuration), pointer pConfig, integer (kind=c_int), intent(in) iDayOfYear, integer (kind=c_int), intent(in) iMonth)
Definition at line 1007 of file model.F90.
References types::dpc_per_f, types::dpzero, types::ichg_in_snow_cov, types::iinactive_cell, types::t_month::imonth, types::inet_rainfall, types::ascharacter::int2char(), types::t_general_grid::inumgridcells, types::isnowcover, types::isnowfall_swe, types::isnowmelt, types::izero, types::lfalse, types::ltrue, types::t_basin_mask::pgrd, rf_model_getinterception(), types::rfreezing, types::rmm_per_inch, types::rzero, and stats::stats_updateallaccumulatorsbycell().
Referenced by model_solve().
subroutine model::model_processrainprms (type (t_general_grid), pointer pGrd, type (t_model_configuration), pointer pConfig, integer (kind=c_int), intent(in) iDayOfYear, integer (kind=c_int), intent(in) iMonth, integer (kind=c_int), intent(in) iNumDaysInYear)
Definition at line 1160 of file model.F90.
References meteorological_functions::clear_sky_solar_radiation_rso(), meteorological_functions::daylight_hours(), types::dpzero, meteorological_functions::extraterrestrial_radiation_ra(), types::ichg_in_snow_cov, types::t_month::imonth, types::inet_rainfall, types::t_general_grid::inumgridcells, types::isnowcover, types::isnowfall_swe, types::isnowmelt, meteorological_functions::net_longwave_radiation_rnl(), meteorological_functions::net_shortwave_radiation_rns(), types::t_basin_mask::pgrd, types::rcm_per_inch, meteorological_functions::rel_earth_sun_dist(), rf_model_getinterception(), types::t_cell::rinterception, types::rnear_zero, types::rone, meteorological_functions::row_latitude(), types::rzero, snow::snow_albedo(), snow::snow_depth_hedstrom(), snow::snow_energy_balance(), meteorological_functions::solar_declination(), meteorological_functions::solar_radiation_hargreaves_rs(), stats::stats_updateallaccumulatorsbycell(), meteorological_functions::sunset_angle(), and meteorological_functions::zenith_angle().
Referenced by model_solve().
subroutine model::model_processrunoff (type (t_general_grid), pointer pGrd, type (t_model_configuration), pointer pConfig, integer (kind=c_int), intent(in) iDayOfYear, integer (kind=c_int), intent(in) iMonth)
Definition at line 1398 of file model.F90.
References types::config_runoff_downhill, types::config_runoff_iterative, types::config_runoff_no_routing, if_model_runoffiteration(), types::t_month::imonth, types::imoving_avg_terms, types::ascharacter::int2char(), types::t_general_grid::inumgridcells, types::lfalse, model_runoff_norouting(), model_runoffdownhill(), types::t_basin_mask::pgrd, and types::rzero.
Referenced by model_solve().
subroutine model::model_readbasinmasktable (type (t_model_configuration), pointer pConfig)
Definition at line 2439 of file model.F90.
References types::lfalse, types::lu_log, types::lu_mask, types::stab, and types::uppercase().
Referenced by control::control_setmodeloptions().
subroutine model::model_readirrigationlookuptable (type (t_model_configuration), pointer pConfig, type (t_general_grid), pointer pGrd)
Definition at line 2770 of file model.F90.
References types::dquote(), types::t_cell::ilanduseindex, types::t_landuse_lookup::ilandusetype, types::ascharacter::int2char(), types::lfalse, types::ltrue, types::lu_log, types::lu_lookup, types::mmdd2doy(), types::stab, and types::str_compare().
Referenced by control::control_setmodeloptions().
subroutine model::model_readlanduselookuptable (type (t_model_configuration), pointer pConfig)
keep track of number of landuses for use throughout code
Definition at line 2571 of file model.F90.
References types::ascharacter::int2char(), types::lfalse, types::lu_log, types::lu_lookup, types::stab, types::str_compare(), and types::uppercase().
Referenced by control::control_setmodeloptions().
subroutine model::model_readtimeseriesfile (type (t_model_configuration), pointer pConfig, type (t_time_series_file), pointer pTS)
Todo:
Make logic at end of routine more robust; currently the logic to test for the presence of a header could mask errors reading in values from the data file.
Definition at line 3731 of file model.F90.
References types::cleanupcsv(), types::echolog(), meteorological_functions::estimate_percent_of_possible_sunshine(), types::ascharacter::int2char(), types::julian_day(), types::lfalse, types::ltrue, types::lu_log, types::lu_std_out, types::lu_ts, meteorological_functions::maximum_rel_hum(), and meteorological_functions::minimum_rel_hum().
Referenced by control::control_setmodeloptions(), and model_solve().
subroutine model::model_runoff_norouting (type (t_general_grid), pointer pGrd, type (t_model_configuration), pointer pConfig, integer (kind=c_int), intent(in) iDayOfYear, integer (kind=c_int), intent(in) iMonth)
Definition at line 1895 of file model.F90.
References types::t_basin_mask::pgrd, rf_model_cellrunoff(), and types::rzero.
Referenced by model_processrunoff().
subroutine model::model_runoffdownhill (type (t_general_grid), pointer pGrd, type (t_model_configuration), pointer pConfig, integer (kind=c_int), intent(in) iDayOfYear, integer (kind=c_int), intent(in) iMonth)
if target cell is inactive, assume that the water should be tracked as flow out of grid
Definition at line 1766 of file model.F90.
References types::iinactive_cell, types::iroute_depression, types::iroute_left_grid, types::t_cell::itgt_col, types::t_cell::itgt_row, model_downstreamcell(), types::t_basin_mask::pgrd, rf_model_cellrunoff(), types::rnear_zero, types::rone, and types::rzero.
Referenced by model_processrunoff().
subroutine model::model_setinactivecells (type (t_general_grid), pointer pGrd, type (t_model_configuration), pointer pConfig)
Definition at line 3168 of file model.F90.
References types::echolog(), types::iinactive_cell, and types::t_basin_mask::pgrd.
Referenced by model_solve().
subroutine model::model_solve (type (t_general_grid), pointer pGrd, type (t_model_configuration), pointer pConfig, type (t_graph_configuration), dimension(:), pointer pGraph, type (t_general_grid), pointer pLandUseGrid)
read in flow direction, soil group, and AWC grids
any negative values are interpreted to mean that the cell should be inactivated
Definition at line 66 of file model.F90.
References water_balance::calculate_water_balance(), types::config_fao56_none, types::config_landuse_constant, types::config_landuse_static_grid, types::config_runoff_downhill, types::config_runoff_no_routing, types::config_snow_new_swb, types::config_snow_original_swb, types::datatype_int, types::datatype_real, et_crop_coefficients::et_kc_applycropcoefficients(), types::gregorian_date(), swb_grid::grid_writegrid(), types::imax, types::imean, types::imin, types::t_month::imonth, types::ino_data_ncdc, types::inone, types::inum_variables, types::t_general_grid::inumgridcells, types::t_stats::ipos, irrigation::irrigation_updateamounts(), types::istartdate_pos, types::lfalse, types::lookupmonth(), types::lu_csv_annual, types::lu_csv_max, types::lu_csv_mean, types::lu_csv_min, types::lu_log, types::lu_std_out, types::lu_ts, graph::make_shaded_contour(), model_checkconfigurationsettings(), model_configurerunoffdownhill(), model_createirrigationtableindex(), model_getdailyprecipvalue(), model_getdailytemperaturevalue(), model_initializedatastructures(), model_initializeet(), model_initializeflowdirection(), model_initializeinputandoutput(), model_initializelanduserelatedparams(), model_processet(), model_processrain(), model_processrainprms(), model_processrunoff(), model_readtimeseriesfile(), model_setinactivecells(), model_updatecontinuousfrozengroundindex(), model_updategrowingdegreeday(), model_updategrowingseason(), model_writegrids(), types::num_days_in_year(), types::t_basin_mask::pgrd, types::sboldwhite, types::t_general_grid::sfilename, sm_thornthwaite_mather::sm_thornthwaite_mather_updatepctsm(), types::stat_info, stats::stats_dumpannualaccumulatorvalues(), stats::stats_dumpdailyaccumulatorvalues(), stats::stats_dumpmonthlyaccumulatorvalues(), stats::stats_initializeannualaccumulators(), stats::stats_initializedailyaccumulators(), stats::stats_initializemonthlyaccumulators(), stats::stats_writeannualaccumulatorvaluescsv(), stats::stats_writedailyaccumulatorvaluescsv(), stats::stats_writeminmeanmax(), stats::stats_writemsbreport(), types::swhite, types::write_ascii_grid_annual, types::write_ascii_grid_daily, and types::write_ascii_grid_monthly.
Referenced by control::control_setmodeloptions().
subroutine model::model_updatecontinuousfrozengroundindex (type (t_general_grid), pointer pGrd, type (t_model_configuration), pointer pConfig)
Definition at line 797 of file model.F90.
References types::iinactive_cell, types::t_basin_mask::pgrd, types::rcm_per_inch, types::rfreezing, and types::rzero.
Referenced by model_solve().
subroutine model::model_updategrowingdegreeday (type (t_general_grid), pointer pGrd, type (t_model_configuration), pointer pConfig)
Definition at line 902 of file model.F90.
References types::dppi, types::iinactive_cell, types::ascharacter::int2char(), types::t_basin_mask::pgrd, types::t_irrigation_lookup::rgdd_basetemp, types::t_irrigation_lookup::rgdd_maxtemp, and types::t_cell::rtmax.
Referenced by model_solve().
subroutine model::model_updategrowingseason (type (t_general_grid), pointer pGrd, type (t_model_configuration), pointer pConfig)
Definition at line 848 of file model.F90.
References types::lfalse, types::ltrue, and types::t_basin_mask::pgrd.
Referenced by model_solve().
subroutine model::model_writegrids (type (t_general_grid), pointer pGrd, type (t_model_configuration), pointer pConfig, integer (kind=c_int), intent(in) iOutputType)
Definition at line 3661 of file model.F90.
References swb_grid::grid_writegrid(), graph::make_shaded_contour(), types::t_basin_mask::pgrd, types::t_general_grid::sfilename, types::write_ascii_grid_annual, types::write_ascii_grid_daily, types::write_ascii_grid_debug, types::write_ascii_grid_diagnostic, types::write_ascii_grid_monthly, and types::year_info.
Referenced by model_solve().
real (kind=c_float) function model::rf_model_cellrunoff (type (t_model_configuration), pointer pConfig, type (t_cell), pointer cel, integer (kind=c_int), intent(in) iDayOfYear)
Definition at line 2090 of file model.F90.
References types::config_runoff_curve_number, types::config_runoff_green_ampt, types::echolog(), types::lfalse, rf_model_cellrunoff_greenampt(), types::t_cell::routflow, runoff_curve_number::runoff_cellrunoff_curvenumber(), and types::rzero.
Referenced by if_model_runoffiteration(), model_runoff_norouting(), and model_runoffdownhill().
real (kind=c_float) function model::rf_model_cellrunoff_greenampt (type (t_model_configuration), pointer pConfig, type (t_cell), pointer cel, integer (kind=c_int), intent(in) iDayOfYear)
Definition at line 2139 of file model.F90.
References types::lfalse, and types::t_cell::routflow.
Referenced by rf_model_cellrunoff().
real (kind=c_float) function model::rf_model_getinterception (type (t_model_configuration), pointer pConfig, type (t_cell), pointer cel)
Definition at line 3089 of file model.F90.
References types::echolog(), types::lfalse, and types::rzero.
Referenced by model_processrain(), and model_processrainprms().
Member Data Documentation
integer (kind=c_int) model::idayctr
Definition at line 32 of file model.F90.
integer (kind=c_int), dimension(:), allocatable model::iordercol
Definition at line 40 of file model.F90.
integer (kind=c_int) model::iordercount
Definition at line 39 of file model.F90.
integer (kind=c_int), dimension(:), allocatable model::iorderrow
Definition at line 41 of file model.F90.
type (t_general_grid), pointer model::pgenericgrd_int
Definition at line 35 of file model.F90.
type (t_general_grid), pointer model::pgenericgrd_sgl
Definition at line 36 of file model.F90.
real(kind=c_float) model::rendtime
Definition at line 42 of file model.F90.
real(kind=c_float) model::rstarttime
Definition at line 42 of file model.F90.
The documentation for this module was generated from the following file:
model.F90
USGS Home Water Resources Biology Geography Geology Geospatial SWB Home Wisconsin WSC
Accessibility FOIA Privacy Policies and Notices
U.S. Department of the Interior | U.S. Geological Survey
URL: http://wi.water.usgs.gov/Soil_Water_Balance/SWB_code_docs/index.html
Page Contact Information: webmaster@wi.water.usgs.gov
Page Last Modified: Thu May 19 2011 14:11:32
Page generated with:
1.8.2