SOIL-WATER-BALANCE SOURCE CODE BROWSER- USGS Wisconsin Water Science Center
USGS Home
Contact USGS
Search USGS
Soil-Water-Balance Source Code Browser
types
Data Types
type types::t_cell
Type that contains the data for an individual grid cell.
type types::t_general_grid
Type that contains the data for a grid.
type types::t_grid_collection
type types::t_landuse_lookup
Container for land-use related data.
type types::t_irrigation_lookup
Type that contains information needed to calculate irrigation for each land use.
type types::t_basin_mask
container for basin mask table data
type types::t_ssf_files
container for SSF file information
type types::t_netcdf_file
type types::t_month
Container for calendar lookup information.
type types::t_stats
Type that contains parameters for graphings and stats calculations.
type types::t_model_configuration
Type that contains model configuration data.
type types::t_time_series_file
data structure to hold a line of input from the classic time-series file
type types::t_graph_configuration
Type that holds parameters used to create graphics with the DISLIN library.
interface types::approx_equal
interface types::assert
interface types::chomp
Functions/Subroutines
logical(kind=t_logical) function types::approx_equal::approx_equal_sgl (rA, rB, rTol)
logical(kind=t_logical) function types::approx_equal::approx_equal_dbl (rA, rB, rTol)
subroutine types::assert::assert_simple_sub (lCondition, sErrorMessage)
subroutine types::assert::assert_module_details_sub (lCondition, sErrorMessage, sFilename, iLineNum)
subroutine types::chomp::chomp_delim_sub (sRecord, sItem, sDelimiters)
subroutine types::chomp::chomp_default_sub (sRecord, sItem)
integer(kind=t_int) function types::nextunit (iLU)
character(len=len_trim(adjustl(sstring))+2)
function types::squote (sString)
character(len=len_trim(adjustl(sstring))+2)
function types::dquote (sString)
Function 'dquote' returns a character string with double quotes prepended and appended to the string that is passed.
logical(kind=t_logical) function types::str_compare (sString1, sString2)
subroutine types::assert_simple_sub (lCondition, sErrorMessage)
subroutine types::assert_module_details_sub (lCondition, sErrorMessage, sFilename, iLineNum)
subroutine types::echolog (sMessage, sFormat)
echo to screen AND write to logfile
subroutine types::chomp_delim_sub (sRecord, sItem, sDelimiters)
subroutine types::chomp_default_sub (sRecord, sItem)
subroutine types::getsystimedate (sDateStr, sDateStrPretty)
subroutine types::chomp_tab (sRecord, sItem)
subroutine types::chomp_slash (sRecord, sItem)
integer(kind=t_int) function types::mmddyyyy2julian (sMMDDYYYY)
integer(kind=t_int) function types::mmddyyyy2doy (sMMDDYYYY)
character(len=len(s)) function types::uppercase_fn (s)
character(len=len(s)) function types::lowercase_fn (s)
subroutine types::uppercase (s)
subroutine types::cleanupcsv (s)
subroutine types::cleanupslash (s)
real(kind=t_sgl) function types::polynomial (x, a)
subroutine types::lookupmonth (iMonth, iDay, iYear, iDayOfYear, sMonthName, lMonthEnd)
logical(kind=t_logical) function types::approx_equal_dbl (rA, rB, rTol)
logical(kind=t_logical) function types::approx_equal_sgl (rA, rB, rTol)
logical(kind=t_logical) function types::lf_model_growingseason (pConfig, iDayOfYear)
real(kind=t_sgl) function types::ftoc (rF)
real(kind=t_sgl) function types::ctof (rC)
real(kind=t_sgl) function types::ftok (rF)
integer(kind=t_int) function types::count_fields (sRecord)
real(kind=t_sgl) function types::mm_to_in (r_mm)
real(kind=t_sgl) function types::interpolate (rXT, rYT, rX)
integer(kind=t_int) function types::julian_day (iYear, iMonth, iDay, iOrigin)
integer(kind=t_int) function types::solstice (iJD)
character(len=256) function types::int2char (iValue)
Convert an integer value into a formatted character string.
character(len=256) function types::real2char (rValue, iDec, iWidth)
Convert a real value into a formatted character string.
integer(kind=t_int) function types::num_days_in_year (iYear)
Return the number of days in the given year.
integer(kind=t_int) function types::day_of_year (iJD)
subroutine types::gregorian_date (iJD, iYear, iMonth, iDay, iOrigin)
Convert from a Julian day number to a Gregorian date.
Variables
character(len=16), parameter,
public types::swb_version "1.0.1"
integer, parameter, public types::t_logical 4
Define the sizes of base types used in the model.
integer, parameter, public types::t_int 4
integer, parameter, public types::t_short 2
integer, parameter, public types::t_byte 1
integer, parameter, public types::t_sgl_dislin 4
integer, parameter, public types::t_sgl SELECTED_REAL_KIND(p=6, r=37)
Define machine-independent sizes for base types.
integer, parameter, public types::t_dbl SELECTED_REAL_KIND(p=13, r=200)
integer(kind=t_int), parameter types::inc_input 1
integer(kind=t_int), parameter types::inc_output 2
integer(kind=t_int), parameter types::inc_observation 3
integer(kind=t_short) types::t_cell::iflowdir iZERO
integer(kind=t_short) types::t_cell::isoilgroup iZERO
integer(kind=t_short) types::t_cell::ilanduseindex
integer(kind=t_short) types::t_cell::ilanduse iZERO
real(kind=t_sgl) types::t_cell::relevation rZERO
real(kind=t_sgl) types::t_cell::rsoilwatercapinput rZERO
real(kind=t_sgl) types::t_cell::rsoilwatercap rZERO
real(kind=t_sgl) types::t_cell::rsoilmoisture rZERO
real(kind=t_sgl) types::t_cell::rsoilmoisturepct
real(kind=t_sgl) types::t_cell::rsm_accumpotentwatloss
real(kind=t_sgl) types::t_cell::rmaxrecharge
real(kind=t_sgl) types::t_cell::rsm_potentialet
integer(kind=t_int) types::t_cell::istreamindex iZERO
real(kind=t_sgl) types::t_cell::rstreamcapture
integer(kind=t_int) types::t_cell::itgt_row
integer(kind=t_int) types::t_cell::itgt_col
real(kind=t_sgl) types::t_cell::rbasecn
real(kind=t_sgl) types::t_cell::radjcn
real(kind=t_sgl) types::t_cell::rsmax
real(kind=t_sgl) types::t_cell::rinflow
real(kind=t_sgl) types::t_cell::routflow
real(kind=t_sgl) types::t_cell::rflowoutofgrid
real(kind=t_sgl) types::t_cell::rroutefraction rONE
real(kind=t_sgl) types::t_cell::rgrossprecip
real(kind=t_sgl) types::t_cell::rnetprecip
real(kind=t_sgl) types::t_cell::rsnowfall_swe
real(kind=t_sgl) types::t_cell::rsnowfall
real(kind=t_sgl) types::t_cell::rsnowcover
real(kind=t_sgl) types::t_cell::rsnowtemperature 23.
real(kind=t_sgl) types::t_cell::rsnowmelt
real(kind=t_sgl) types::t_cell::rtmin
real(kind=t_sgl) types::t_cell::rtmax
real(kind=t_sgl) types::t_cell::rtavg
real(kind=t_sgl) types::t_cell::rcfgi rZERO
real(kind=t_sgl) types::t_cell::rgdd_tbase 50.
real(kind=t_sgl) types::t_cell::rgdd_tmax 150.
real(kind=t_sgl) types::t_cell::rgdd rZERO
real(kind=t_sgl) types::t_cell::rirrigationamount rZERO
real(kind=t_sgl) types::t_cell::rsnowalbedo
integer(kind=t_int) types::t_cell::idayssincelastsnow 0
real(kind=t_sgl), dimension(imoving_avg_terms) types::t_cell::rnetinflowbuf
real(kind=t_sgl) types::t_cell::rdailyrecharge
real(kind=t_sgl) types::t_cell::rsum_recharge rZERO
real(kind=t_sgl) types::t_cell::rsum_rejectedrecharge rZERO
real(kind=t_sgl) types::t_cell::rmsb
integer(kind=t_short) types::t_cell::inumfilesssf 0
logical(kind=t_logical) types::t_cell::ldownhillmarked
integer(kind=t_int), parameter,
public types::t_int_grid 0
integer(kind=t_int), parameter,
public types::t_sgl_grid 1
integer(kind=t_int), parameter,
public types::t_cell_grid 2
integer(kind=t_int) types::t_general_grid::inx
integer(kind=t_int) types::t_general_grid::iny
integer(kind=t_int) types::t_general_grid::inumgridcells
integer(kind=t_int) types::t_general_grid::idatatype
real(kind=t_sgl) types::t_general_grid::rgridcellsize
integer(kind=t_int) types::t_general_grid::ilengthunits -99999
real(kind=t_dbl) types::t_general_grid::rx0
real(kind=t_dbl) types::t_general_grid::rx1
real(kind=t_dbl) types::t_general_grid::ry0
real(kind=t_dbl) types::t_general_grid::ry1
integer(kind=t_int), dimension(:,:),
pointer types::t_general_grid::idata
real(kind=t_sgl), dimension(:,:),
pointer types::t_general_grid::rdata
type(t_cell), dimension(:,:),
pointer types::t_general_grid::cells
integer(kind=t_int), parameter types::igrid_length_units_meters 0
define parameter values for working with type T_GENERAL_GRID
integer(kind=t_int), parameter types::igrid_length_units_feet 1
type(t_general_grid),
dimension(:), pointer types::t_grid_collection::grids
integer(kind=t_int) types::t_landuse_lookup::ilandusetype
Land use type; values are expected to correspond to those provided by the user in the input landuse grid.
character(len=256) types::t_landuse_lookup::slandusedescription
Land use description.
character(len=256) types::t_landuse_lookup::sassumedpercentimperviousness
Assumed percent imperviousness (not used in any calculations)
real(kind=t_sgl) types::t_landuse_lookup::rintercept_growingseason
Interception value (inches per day) during growing season.
real(kind=t_sgl) types::t_landuse_lookup::rintercept_nongrowingseason
Interception value (inches per day) outside of growing season.
integer(kind=t_int) types::t_irrigation_lookup::ilandusetype
Landuse code corresponding to the codes specified in landuse grid.
real(kind=t_sgl) types::t_irrigation_lookup::rkc_max 1.3
Maximum crop coefficient.
real(kind=t_sgl) types::t_irrigation_lookup::rk0 0.2
Crop coefficient for first phenological stage.
real(kind=t_sgl) types::t_irrigation_lookup::rgdd_kc_max 1400
GDD corresponding to Kc_Max.
real(kind=t_sgl) types::t_irrigation_lookup::rgdd_death 2000
GDD corresponding to plant death (alpha0)
real(kind=t_sgl) types::t_irrigation_lookup::ralpha1 0.65
Spread of error function around GDD_Kc_MAx range 0-1; 0 ~= Dirac delta; 1 ~= maximum spread.
real(kind=t_sgl) types::t_irrigation_lookup::rgdd_basetemp 50.
Growing degree-day base temperature (10 degrees C for corn)
real(kind=t_sgl) types::t_irrigation_lookup::rgdd_maxtemp 130.
Growing degree-day maximum temperature (cutoff; 30 degrees C for corn)
real(kind=t_sgl) types::t_irrigation_lookup::rmad 100.
integer(kind=t_int) types::t_irrigation_lookup::ibeginirrigation 120
Day of year before which no irrigation is assumed to take place.
integer(kind=t_int) types::t_irrigation_lookup::iendirrigation 240
Day of year after which no irrigation is assumed to take place.
character(len=256) types::t_basin_mask::susgs_upstreamorderid
character(len=256) types::t_basin_mask::sbasindescription
character(len=256) types::t_basin_mask::sbasinmaskfilename
character(len=256) types::t_basin_mask::sfiletype
real(kind=t_sgl) types::t_basin_mask::rpestweight 1.0
character(len=256) types::t_basin_mask::spestgroup
type(t_general_grid), pointer types::t_basin_mask::pgrd
real(kind=t_sgl) types::t_basin_mask::rqb
real(kind=t_sgl) types::t_basin_mask::rdrainagearea
integer(kind=t_int) types::t_basin_mask::ilength
real(kind=t_sgl) types::t_basin_mask::rmin
real(kind=t_sgl) types::t_basin_mask::rmax
real(kind=t_sgl) types::t_basin_mask::rmean
integer(kind=t_int) types::t_ssf_files::ilu
character(len=128) types::t_ssf_files::sfilename
integer(kind=t_int) types::t_ssf_files::irownum
integer(kind=t_int) types::t_ssf_files::icolnum
integer(kind=t_int) types::t_ssf_files::ivarnum
integer(kind=t_int) types::t_netcdf_file::incid
character(len=64) types::t_netcdf_file::sfilename
character(len=24) types::t_netcdf_file::svarname ""
character(len=24) types::t_netcdf_file::sunits
integer(kind=t_int) types::t_netcdf_file::iprojid
integer(kind=t_int) types::t_netcdf_file::ivarid
integer(kind=t_int) types::t_netcdf_file::ivartype
integer(kind=t_int) types::t_netcdf_file::ixvarid
integer(kind=t_int) types::t_netcdf_file::iyvarid
logical(kind=t_logical) types::t_netcdf_file::lyvarbeforexvar lTRUE
integer(kind=t_int) types::t_netcdf_file::ixdimid
integer(kind=t_int) types::t_netcdf_file::iydimid
integer(kind=t_int) types::t_netcdf_file::itimedimid
integer(kind=t_int) types::t_netcdf_file::itimevarid
integer(kind=t_int) types::t_netcdf_file::ioriginmonth
integer(kind=t_int) types::t_netcdf_file::ioriginday
integer(kind=t_int) types::t_netcdf_file::ioriginyear
integer(kind=t_int) types::t_netcdf_file::ioriginjulianday
integer(kind=t_int) types::t_netcdf_file::istartjulianday
integer(kind=t_int) types::t_netcdf_file::iendjulianday
real(kind=t_dbl) types::t_netcdf_file::rx_lowerleft
real(kind=t_dbl) types::t_netcdf_file::ry_lowerleft
real(kind=t_dbl) types::t_netcdf_file::rx_upperright
real(kind=t_dbl) types::t_netcdf_file::ry_upperright
real(kind=t_sgl) types::t_netcdf_file::rgridcellsize
integer(kind=t_int) types::t_netcdf_file::ix_numgridcells
integer(kind=t_int) types::t_netcdf_file::iy_numgridcells
logical(kind=t_logical) types::t_netcdf_file::linterpolate lFALSE
real(kind=t_dbl) types::t_netcdf_file::rscalefactor 1_T_DBL
real(kind=t_dbl) types::t_netcdf_file::raddoffset 0_T_DBL
character(len=24) types::t_netcdf_file::sprojectionname "wtm"
character(len=12) types::t_netcdf_file::sprojectionunits "meters"
real(kind=t_dbl) types::t_netcdf_file::rfalseeasting 520000_T_DBL
real(kind=t_dbl) types::t_netcdf_file::rfalsenorthing -4480000_T_DBL
real(kind=t_dbl) types::t_netcdf_file::rlongorigin -90_T_DBL
real(kind=t_dbl) types::t_netcdf_file::rlatorigin 0_T_DBL
integer(kind=t_int) types::t_netcdf_file::izonenumber 0
character(len=48) types::t_netcdf_file::sellipsoidname "GRS 1980"
integer(kind=t_int) types::t_netcdf_file::iellipsoidid 11
character(len=3) types::t_month::sname
character(len=9) types::t_month::sfullname
integer(kind=t_int) types::t_month::istart
integer(kind=t_int) types::t_month::iend
integer(kind=t_int) types::t_month::imonth
integer(kind=t_int) types::t_month::inumdays
type(t_month), dimension(12),
target types::year_info (/ T_MONTH('JAN','JANUARY ', 1, 31, 1, 31), T_MONTH('FEB','FEBRUARY ', 32, 59, 2, 29), T_MONTH('MAR','MARCH ', 60, 90, 3, 31), T_MONTH('APR','APRIL ', 91, 120, 4, 30), T_MONTH('MAY','MAY ', 121, 151, 5, 31), T_MONTH('JUN','JUNE ', 152, 181, 6, 30), T_MONTH('JUL','JULY ', 182, 212, 7, 31), T_MONTH('AUG','AUGUST ', 213, 243, 8, 31), T_MONTH('SEP','SEPTEMBER', 244, 273, 9, 30), T_MONTH('OCT','OCTOBER ', 274, 304, 10, 31), T_MONTH('NOV','NOVEMBER ', 305, 334, 11, 30), T_MONTH('DEC','DECEMBER ', 335, 365, 12, 31) /)
Month information.
character(len=256), public types::slogbuffer
character(len=20) types::t_stats::svariable_name
Short version of the variable name.
integer(kind=t_int) types::t_stats::ilu
Fortran logical unit for binary file writes.
integer(kind=t_int) types::t_stats::iindent
Integer number of characters to indent (on-screen display)
integer(kind=t_int) types::t_stats::imassbalanceconst
Multiplier for calculating mass balances (1=source, 0=NA, -1=sink)
logical(kind=t_logical) types::t_stats::lshowsum
Does it make sense to show the sum of this accumulator?
logical(kind=t_logical) types::t_stats::lshowdailysum
Does it make sense to show the daily sum of this accumulator?
logical(kind=t_logical) types::t_stats::lactive
Is this variable active given the compiler options?
character(len=20) types::t_stats::sunits
Text describing the unit of measure (i.e. inches)
character(len=64) types::t_stats::slongname
Long form of the variable name.
real(kind=t_dbl) types::t_stats::rnc_multfactor
Multiplication factor when writing to a NetCDF file.
real(kind=t_dbl) types::t_stats::rnc_addoffset
Offset when writing to a NetCDF file.
integer(kind=t_int) types::t_stats::idailyoutput
Type of daily output desired (0=none; 1=grid; 2=plot; 3=both; 4=stats)
integer(kind=t_int) types::t_stats::imonthlyoutput
Type of monthly output desired (0=none; 1=grid; 2=plot; 3=both; 4=stats)
integer(kind=t_int) types::t_stats::iannualoutput
Type of annual output desired (0=none; 1=grid; 2=plot; 3=both; 4=stats)
integer(kind=t_int) types::t_stats::inetcdfoutput
Is output to be written to a NetCDF file?
character(len=24) types::t_stats::smsb_note
Description of utility of variable in calculating mass balance.
integer(kind=t_int) types::t_stats::ioffset
Offset value; contains number of bytes written for a given day.
integer(kind=t_int) types::t_stats::ipos
Position value; location of current day's position marker.
integer(kind=t_int), parameter types::inum_months 12
Global parameter defining the number of elements in the YEAR_INFO array.
integer(kind=t_int), parameter types::inum_variables 29
integer(kind=t_int), parameter types::inone 0
integer(kind=t_int), parameter types::igrid 1
integer(kind=t_int), parameter types::igraph 2
integer(kind=t_int), parameter types::iboth 3
integer(kind=t_int), parameter types::istats 4
type(t_stats), dimension(inum_variables) types::stat_info [
Define parameter values for working with accumulator arrays.
integer(kind=t_int) types::t_model_configuration::iconfigurerunoff
Runoff calculation method (see defined constants).
integer(kind=t_int) types::t_model_configuration::iconfigurerunoffmode
Runoff routing solution mode (see defined constants).
integer(kind=t_int) types::t_model_configuration::iconfigureet
Reference evapotranspiration calculation method.
integer(kind=t_int) types::t_model_configuration::iconfigureprecip
Precipitation input option.
integer(kind=t_int) types::t_model_configuration::iconfiguretemperature
Temperature data input option.
integer(kind=t_int) types::t_model_configuration::iconfigurelanduse
Landuse data input option.
integer(kind=t_int) types::t_model_configuration::iconfiguresm
Soil moisture calculation option.
integer(kind=t_int) types::t_model_configuration::iconfiguresnow
Snowfall and snowmelt option.
integer(kind=t_int) types::t_model_configuration::iconfiguresmcapacity
Maximum soil water capacity option.
integer(kind=t_int) types::t_model_configuration::iconfigureinitialabstraction
Initial abstraction method: use 0.2S or 0.05S as estimate of initial abstraction.
logical(kind=t_logical) types::t_model_configuration::lwriteextrapestfiles lFALSE
Option to write extra files when using PEST.
logical(kind=t_logical) types::t_model_configuration::lansi_colors lFALSE
flag indicating whether or not screen output should include ANSI.sys-like colors
character(len=1) types::t_model_configuration::sslash sBACKSLASH
allow for alternate methods of delimiting subdirectories; needed for operation on Windows and Linux platforms
integer(kind=t_int) types::t_model_configuration::irle_mult 10000
real(kind=t_sgl) types::t_model_configuration::rrle_offset 0.
logical(kind=t_logical) types::t_model_configuration::lfirstyearofsimulation lTRUE
flag indicating whether this is the first year of a multiple-year simulation
logical(kind=t_logical) types::t_model_configuration::lfirstdayofsimulation lTRUE
integer(kind=t_int) types::t_model_configuration::istartyear
integer(kind=t_int) types::t_model_configuration::iendyear
integer(kind=t_int) types::t_model_configuration::iyear
integer(kind=t_int) types::t_model_configuration::imonth
integer(kind=t_int) types::t_model_configuration::iday
integer(kind=t_int) types::t_model_configuration::idayofyear
integer(kind=t_int) types::t_model_configuration::inumdaysinyear
integer(kind=t_int) types::t_model_configuration::istartjulianday
integer(kind=t_int) types::t_model_configuration::icurrentjulianday
integer(kind=t_int) types::t_model_configuration::iendjulianday
integer(kind=t_int) types::t_model_configuration::istartyearforcalculation -99999
integer(kind=t_int) types::t_model_configuration::iendyearforcalculation 99999
logical(kind=t_logical) types::t_model_configuration::lgriddeddata lFALSE
logical(kind=t_logical) types::t_model_configuration::luseswbread lFALSE
logical(kind=t_logical) types::t_model_configuration::lhaltifmissingclimatedata lTRUE
logical(kind=t_logical) types::t_model_configuration::ldownhillroutingtableexists lFALSE
character(len=256) types::t_model_configuration::sprecipfileprefix
character(len=256) types::t_model_configuration::stmaxfileprefix
character(len=256) types::t_model_configuration::stminfileprefix
character(len=256) types::t_model_configuration::sdynamiclandusefileprefix
real(kind=t_sgl) types::t_model_configuration::ret_slope 0.0023
real(kind=t_sgl) types::t_model_configuration::ret_exponent 0.5
real(kind=t_sgl) types::t_model_configuration::ret_constant 17.8
real(kind=t_sgl) types::t_model_configuration::rrainfall_corr_factor 1.0
real(kind=t_sgl) types::t_model_configuration::rsnowfall_swe_corr_factor 1.0
real(kind=t_sgl) types::t_model_configuration::rminvalidprecip 0.
real(kind=t_sgl) types::t_model_configuration::rminvalidtemp -100.0
real(kind=t_sgl) types::t_model_configuration::rtmaxallsnow 30.5
real(kind=t_sgl) types::t_model_configuration::rtmaxallrain 40.0
real(kind=t_sgl) types::t_model_configuration::rsnwd_slp1 51.3
real(kind=t_sgl) types::t_model_configuration::rsnwd_intcp1 67.9
real(kind=t_sgl) types::t_model_configuration::rsnwd_denom 2.6
character(len=256) types::t_model_configuration::stimeseriesfilename
character(len=256) types::t_model_configuration::slanduselookupfilename
character(len=256) types::t_model_configuration::sirrigationlookupfilename
character(len=256) types::t_model_configuration::sbasinmaskfilename
character(len=256) types::t_model_configuration::soutputfileprefix ""
character(len=256) types::t_model_configuration::sfuturefileprefix ""
character(len=256) types::t_model_configuration::soutputfilesuffix
real(kind=t_sgl) types::t_model_configuration::rdry_dormant 0.50_T_SGL
real(kind=t_sgl) types::t_model_configuration::rwet_dormant 1.10_T_SGL
real(kind=t_sgl) types::t_model_configuration::rdry_growing 1.40_T_SGL
real(kind=t_sgl) types::t_model_configuration::rwet_growing 2.10_T_SGL
integer(kind=t_int) types::t_model_configuration::ioutputformat
integer(kind=t_int) types::t_model_configuration::idayoffirstfrost
integer(kind=t_int) types::t_model_configuration::idayoflastfrost
logical(kind=t_logical) types::t_model_configuration::lnorthernhemisphere lTRUE
logical(kind=t_logical) types::t_model_configuration::lreportdaily
logical(kind=t_logical) types::t_model_configuration::lwritetoscreen
integer(kind=t_int) types::t_model_configuration::iheaderprintinterval
real(kind=t_sgl) types::t_model_configuration::riterationtolerance 1.0E-6
type(t_landuse_lookup),
dimension(:), pointer types::t_model_configuration::lu
type(t_irrigation_lookup),
dimension(:), pointer types::t_model_configuration::irrigation
type(t_basin_mask), dimension(:),
pointer types::t_model_configuration::bmask
real(kind=t_sgl), dimension(:,:),
pointer types::t_model_configuration::cn
real(kind=t_sgl), dimension(:,:),
pointer types::t_model_configuration::max_recharge
real(kind=t_sgl), dimension(:,:),
pointer types::t_model_configuration::rooting_depth
real(kind=t_sgl) types::t_model_configuration::rll_cfgi 9999.0
real(kind=t_sgl) types::t_model_configuration::rul_cfgi 9999.0
integer(kind=t_int) types::t_model_configuration::iopen_water_lu -99999
real(kind=t_sgl) types::t_model_configuration::rsouthernlatitude
real(kind=t_sgl) types::t_model_configuration::rnorthernlatitude
logical(kind=t_logical) types::t_model_configuration::lelevadjustment
real(kind=t_sgl) types::t_model_configuration::relevstationelevation
real(kind=t_sgl) types::t_model_configuration::relevdryfactor
real(kind=t_sgl) types::t_model_configuration::relevhumidfactor
real(kind=t_sgl) types::t_model_configuration::relevhumiditythreshold
type(t_ssf_files), dimension(:),
pointer types::t_model_configuration::ssf_files
type(t_netcdf_file), dimension(:,:),
pointer types::t_model_configuration::netcdf_file
character(len=48) types::t_model_configuration::sprojectionname "wtm"
real(kind=t_dbl) types::t_model_configuration::rfalseeasting 520000_T_DBL
real(kind=t_dbl) types::t_model_configuration::rfalsenorthing -4480000_T_DBL
real(kind=t_dbl) types::t_model_configuration::rlongorigin -90_T_DBL
real(kind=t_dbl) types::t_model_configuration::rlatorigin 0_T_DBL
integer(kind=t_int) types::t_model_configuration::izonenumber 0
character(len=48) types::t_model_configuration::sellipsoidname "GRS 1980"
integer(kind=t_int) types::t_model_configuration::iellipsoidid 11
real(kind=t_sgl), dimension(stream_interactions_max) types::t_model_configuration::rstreammaxinflow
real(kind=t_sgl), dimension(stream_interactions_max) types::t_model_configuration::rstreammaxcapture
integer(kind=t_int) types::t_time_series_file::imonth
integer(kind=t_int) types::t_time_series_file::iday
integer(kind=t_int) types::t_time_series_file::iyear
real(kind=t_sgl) types::t_time_series_file::ravgt
real(kind=t_sgl) types::t_time_series_file::rprecip
real(kind=t_sgl) types::t_time_series_file::rrh
real(kind=t_sgl) types::t_time_series_file::rmaxt
real(kind=t_sgl) types::t_time_series_file::rmint
real(kind=t_sgl) types::t_time_series_file::rwindspd
real(kind=t_sgl) types::t_time_series_file::rminrh
real(kind=t_sgl) types::t_time_series_file::rsunpct
logical(kind=t_logical) types::t_time_series_file::leof lFALSE
character(len=256) types::t_graph_configuration::csetfil "DEFAULT_FILENAME"
character(len=256) types::t_graph_configuration::ccdev "PNG"
character(len=256) types::t_graph_configuration::cpaper_size "USAP"
character(len=256) types::t_graph_configuration::ctitle "NO TITLE"
character(len=256) types::t_graph_configuration::cz_axis_title "Z-AXIS TITLE"
character(len=256) types::t_graph_configuration::cx_axis_title "X-AXIS TITLE"
character(len=256) types::t_graph_configuration::cy_axis_title "Y-AXIS TITLE"
character(len=256) types::t_graph_configuration::cfont_name "HELVE"
character(len=256) types::t_graph_configuration::ccolor_table "SPEC"
integer(kind=t_int) types::t_graph_configuration::iwinsizex 768
integer(kind=t_int) types::t_graph_configuration::iwinsizey 1024
integer(kind=t_int) types::t_graph_configuration::itimeframe 1
real(kind=t_sgl), dimension(3) types::t_graph_configuration::rza 0.
real(kind=t_sgl), dimension(3) types::t_graph_configuration::rze 10.
real(kind=t_sgl), dimension(3) types::t_graph_configuration::rzor 0.
real(kind=t_sgl), dimension(3) types::t_graph_configuration::rzstep 1.
logical(kind=t_logical) types::t_graph_configuration::lenabledislinmessages lTRUE
integer(kind=t_int), parameter types::idaily 1
integer(kind=t_int), parameter types::imonthly 2
integer(kind=t_int), parameter types::iannual 3
integer(kind=t_int), parameter types::config_landuse_constant 0
Configuration information for landuse input {.
integer(kind=t_int), parameter types::config_landuse_dynamic_arc_grid 1
integer(kind=t_int), parameter types::config_landuse_dynamic_surfer 2
integer(kind=t_int), parameter types::config_landuse_dynamic_netcdf 3
integer(kind=t_int), parameter types::config_landuse_static_grid 4
integer(kind=t_int), parameter types::config_snow_original_swb 0
integer(kind=t_int), parameter types::config_snow_new_swb 1
integer(kind=t_int), parameter types::config_sm_capacity_calculate 0
integer(kind=t_int), parameter types::config_sm_capacity_constant 1
integer(kind=t_int), parameter types::config_sm_capacity_fm_table 2
integer(kind=t_int), parameter types::config_sm_none 0
integer(kind=t_int), parameter types::config_sm_thornthwaite_mather 1
integer(kind=t_int), parameter types::config_sm_init_abstraction_tr55 0
integer(kind=t_int), parameter types::config_sm_init_abstraction_hawkins 1
integer(kind=t_int), parameter types::config_estimate_missing_data 0
integer(kind=t_int), parameter types::config_end_if_missing_data 1
integer(kind=t_int), parameter types::output_surfer 0
integer(kind=t_int), parameter types::output_arc 1
Variables: Fortran logical unit numbers
Global logical unit numbers for input and output
integer(kind=t_int), parameter types::lu_std_out 6
integer(kind=t_int), parameter types::lu_control 12
integer(kind=t_int), parameter types::lu_grid 14
integer(kind=t_int), parameter types::lu_lookup 16
integer(kind=t_int), parameter types::lu_ts 18
integer(kind=t_int), parameter types::lu_temp 20
integer(kind=t_int), parameter types::lu_msb_report 22
integer(kind=t_int), parameter types::lu_bin_file 24
integer(kind=t_int), parameter types::lu_routing 26
integer(kind=t_int), parameter types::lu_csv_min 28
integer(kind=t_int), parameter types::lu_csv_mean 30
integer(kind=t_int), parameter types::lu_csv_max 32
integer(kind=t_int), parameter types::lu_csv_annual 34
integer(kind=t_int), parameter types::lu_mask 36
integer(kind=t_int), parameter types::lu_mask_file 38
integer(kind=t_int), parameter types::lu_mask_stats_csv 40
integer(kind=t_int), parameter types::lu_pest_stats 42
integer(kind=t_int), parameter types::lu_pest_obs 44
integer(kind=t_int), parameter types::lu_pest_ins 46
integer(kind=t_int), parameter types::lu_log 48
Constants: General conversion factors and flags
Some useful and common conversion factors, defined here to ensure consistency throughout the code
real(kind=t_sgl), parameter types::rzero 0.0_T_SGL
real(kind=t_dbl), parameter types::dpzero 0.0_T_DBL
real(kind=t_sgl), parameter types::rnear_zero 1E-9_T_SGL
real(kind=t_sgl), parameter types::rpoint2 0.2_T_SGL
real(kind=t_sgl), parameter types::rhalf 0.5_T_SGL
real(kind=t_sgl), parameter types::rpoint8 0.8_T_SGL
real(kind=t_sgl), parameter types::rone 1.0_T_SGL
real(kind=t_dbl), parameter types::dpone 1.0_T_DBL
real(kind=t_sgl), parameter types::rfreezing 32.0_T_SGL
real(kind=t_sgl), parameter types::rten 10.0_T_SGL
real(kind=t_sgl), parameter types::rhundred 100.0_T_SGL
real(kind=t_sgl), parameter types::rthousand 1000.0_T_SGL
real(kind=t_dbl), parameter types::dpc_per_f 5.0_T_DBL / 9.0_T_DBL
real(kind=t_dbl), parameter types::dpf_per_c 9.0_T_DBL / 5.0_T_DBL
real(kind=t_sgl), parameter types::rmm_per_inch 25.4_T_SGL
real(kind=t_sgl), parameter types::rcm_per_inch 2.54_T_SGL
real(kind=t_dbl), parameter types::dppi 3.14159265_T_DBL
real(kind=t_dbl), parameter types::dptwopi 2.0_T_DBL * dpPI
real(kind=t_dbl), parameter types::dpsqm_to_sqft 10.76391_T_DBL
integer(kind=t_int), parameter types::imoving_avg_terms 5
integer(kind=t_int), parameter types::iroute_cell_marked -1
integer(kind=t_int), parameter types::iroute_depression -999
integer(kind=t_int), parameter types::iroute_left_grid -1000
integer(kind=t_int), parameter types::ino_data_ncdc -99999
integer(kind=t_int), parameter types::inum_digits 3
integer(kind=t_int), parameter types::ifield_width 10
integer(kind=t_int), parameter types::izero 0
logical(kind=t_logical), parameter types::ltrue .true._T_LOGICAL
logical(kind=t_logical), parameter types::lfalse .false._T_LOGICAL
integer(kind=t_int), parameter types::ieof HUGE(iZERO)
real(kind=t_sgl), parameter types::rbigval HUGE(rZERO)
character(len=1), parameter types::stab achar(9)
character(len=2), parameter types::swhitespace achar(9)//" "
character(len=1), parameter types::sbackslash achar(92)
character(len=1), parameter types::sforwardslash achar(47)
Globals: Variables for run-length encoding operation
These variables store the position of the start date and end date within the binary (stream) output file.
integer(kind=t_int) types::istartdate_pos
integer(kind=t_int) types::ienddate_pos
integer(kind=t_int) types::iendheader_pos
Constants: Definitions for ANSI.sys-like text colors
character(len=7), parameter types::sred char(27)//'[1;31m'
character(len=7), parameter types::sgreen char(27)//'[1;32m'
character(len=7), parameter types::syellow char(27)//'[1;33m'
character(len=7), parameter types::sblue char(27)//'[1;34m'
character(len=7), parameter types::scyan char(27)//'[1;36m'
character(len=7), parameter types::swhite char(27)//'[0;37m'
character(len=7), parameter types::sboldwhite char(27)//'[1;37m'
character(len=7), parameter types::sclrscr char(27)//'[2J'
Constants: Statistics that SWB knows how to calculate and store
Index values for members of the rMonthly, rDaily, and rAnnual arrays that are global variables within module stats
integer(kind=t_int), parameter types::inum_stats 5
integer(kind=t_int), parameter types::imin 1
integer(kind=t_int), parameter types::imean 2
integer(kind=t_int), parameter types::imax 3
integer(kind=t_int), parameter types::isum 4
integer(kind=t_int), parameter types::ilength 5
character(len=7), dimension(inum_stats),
parameter types::stat_names [ "Minimum"
Constants: Variables that SWB can output or summarize
Index values for members of the rMonthly, rDaily, and rAnnual arrays that are global variables within module stats
Note
These constants are arranged in the desired order of output for daily and annual reporting: sources first, then the sinks, and then all other informational items
integer(kind=t_int), parameter types::igross_precip 1
integer(kind=t_int), parameter types::isnowmelt 2
integer(kind=t_int), parameter types::iinflow 3
integer(kind=t_int), parameter types::iirrigation 4
integer(kind=t_int), parameter types::isnowfall_swe 5
integer(kind=t_int), parameter types::iinterception 6
integer(kind=t_int), parameter types::ioutflow 7
integer(kind=t_int), parameter types::irunoff_outside 8
integer(kind=t_int), parameter types::iact_et 9
integer(kind=t_int), parameter types::ichg_in_soil_moist 10
integer(kind=t_int), parameter types::irecharge 11
integer(kind=t_int), parameter types::irejected_recharge 12
integer(kind=t_int), parameter types::istream_capture 13
integer(kind=t_int), parameter types::isnowcover 14
integer(kind=t_int), parameter types::icfgi 15
integer(kind=t_int), parameter types::imin_temp 16
integer(kind=t_int), parameter types::imax_temp 17
integer(kind=t_int), parameter types::iavg_temp 18
integer(kind=t_int), parameter types::ichg_in_snow_cov 19
integer(kind=t_int), parameter types::inet_precip 20
integer(kind=t_int), parameter types::inet_inflow 21
integer(kind=t_int), parameter types::inet_infil 22
integer(kind=t_int), parameter types::ipot_et 23
integer(kind=t_int), parameter types::ip_minus_pet 24
integer(kind=t_int), parameter types::ism_deficit 25
integer(kind=t_int), parameter types::ism_surplus 26
integer(kind=t_int), parameter types::ism_apwl 27
integer(kind=t_int), parameter types::isoil_moisture 28
integer(kind=t_int), parameter types::igdd 29
integer(kind=t_int), parameter types::stream_interactions_max 100
Constants: Runoff calculation
Options controlling the selection of a runoff calculation algorithm
integer(kind=t_int), parameter types::config_runoff_curve_number 0
integer(kind=t_int), parameter types::config_runoff_green_ampt 1
Constants: Runoff routing calculation
Options for routing mechanism selection
integer(kind=t_int), parameter types::config_runoff_iterative 0
integer(kind=t_int), parameter types::config_runoff_downhill 1
integer(kind=t_int), parameter types::config_runoff_no_routing 2
Constants: Evapotranspiration algorithm
Options for specifying the choice of evapotranspiration algorithm
integer(kind=t_int), parameter types::config_et_none 0
integer(kind=t_int), parameter types::config_et_thornthwaite_mather 1
integer(kind=t_int), parameter types::config_et_turc 2
integer(kind=t_int), parameter types::config_et_jensen_haise 3
integer(kind=t_int), parameter types::config_et_blaney_criddle 4
integer(kind=t_int), parameter types::config_et_hargreaves 5
Constants: Precipitation data format
Options for specifying the method of input for precipitation data
integer(kind=t_int), parameter types::config_precip_single_station 0
integer(kind=t_int), parameter types::config_precip_arc_grid 1
integer(kind=t_int), parameter types::config_precip_surfer_grid 2
integer(kind=t_int), parameter types::config_precip_netcdf 3
Constants: Temperature data format
Options for specifying the method of input for temperature data
integer(kind=t_int), parameter types::config_temperature_single_station 0
integer(kind=t_int), parameter types::config_temperature_arc_grid 1
integer(kind=t_int), parameter types::config_temperature_surfer_grid 2
integer(kind=t_int), parameter types::config_temperature_netcdf 3
Detailed Description
Function/Subroutine Documentation
logical(kind=t_logical) function types::approx_equal_dbl (real(kind=t_dbl) rA, real(kind=t_dbl) rB, real(kind=t_dbl), optional rTol)
Definition at line 1867 of file types.F90.
logical(kind=t_logical) function types::approx_equal::approx_equal_dbl (real(kind=t_dbl) rA, real(kind=t_dbl) rB, real(kind=t_dbl), optional rTol)
Definition at line 1867 of file types.F90.
logical(kind=t_logical) function types::approx_equal_sgl (real(kind=t_sgl) rA, real(kind=t_sgl) rB, real(kind=t_sgl), optional rTol)
Definition at line 1899 of file types.F90.
logical(kind=t_logical) function types::approx_equal::approx_equal_sgl (real(kind=t_sgl) rA, real(kind=t_sgl) rB, real(kind=t_sgl), optional rTol)
Definition at line 1899 of file types.F90.
subroutine types::assert_module_details_sub (logical (kind=t_logical), intent(in) lCondition, character (len=*), intent(in) sErrorMessage, character (len=*) sFilename, integer (kind=t_int) iLineNum)
Definition at line 1172 of file types.F90.
References types::t_month::iend, types::t_ssf_files::ilu, and types::t_ssf_files::sfilename.
subroutine types::assert::assert_module_details_sub (logical (kind=t_logical), intent(in) lCondition, character (len=*), intent(in) sErrorMessage, character (len=*) sFilename, integer (kind=t_int) iLineNum)
Definition at line 1172 of file types.F90.
subroutine types::assert_simple_sub (logical (kind=t_logical), intent(in) lCondition, character (len=*), intent(in) sErrorMessage)
Definition at line 1129 of file types.F90.
References types::t_month::iend, and types::t_ssf_files::ilu.
subroutine types::assert::assert_simple_sub (logical (kind=t_logical), intent(in) lCondition, character (len=*), intent(in) sErrorMessage)
Definition at line 1129 of file types.F90.
subroutine types::chomp_default_sub (character (len=*), intent(inout) sRecord, character (len=256), intent(out) sItem)
Definition at line 1294 of file types.F90.
References dquote(), and int2char().
subroutine types::chomp::chomp_default_sub (character (len=*), intent(inout) sRecord, character (len=256), intent(out) sItem)
Definition at line 1294 of file types.F90.
subroutine types::chomp_delim_sub (character (len=*), intent(inout) sRecord, character (len=256), intent(out) sItem, character (len=*), intent(in) sDelimiters)
Definition at line 1248 of file types.F90.
References dquote(), and int2char().
subroutine types::chomp::chomp_delim_sub (character (len=*), intent(inout) sRecord, character (len=256), intent(out) sItem, character (len=*), intent(in) sDelimiters)
Definition at line 1248 of file types.F90.
subroutine types::chomp_slash (character (len=*), intent(inout) sRecord, character (len=256), intent(out) sItem)
Definition at line 1500 of file types.F90.
Referenced by mmddyyyy2doy(), and mmddyyyy2julian().
subroutine types::chomp_tab (character (len=*), intent(inout) sRecord, character (len=256), intent(out) sItem)
Definition at line 1449 of file types.F90.
subroutine types::cleanupcsv (character (len=*), intent(inout) s)
Definition at line 1701 of file types.F90.
Referenced by et_thornthwaite_mather::et_tm_initialize(), and model::model_readtimeseriesfile().
subroutine types::cleanupslash (character (len=*), intent(inout) s)
Definition at line 1736 of file types.F90.
integer(kind=t_int) function types::count_fields (character (len=*), intent(inout) sRecord)
Definition at line 2063 of file types.F90.
real (kind=t_sgl) function types::ctof (real (kind=t_sgl), intent(in) rC)
Definition at line 2021 of file types.F90.
Referenced by snow::snow_energy_balance().
integer (kind=t_int) function types::day_of_year (integer (kind=t_int), intent(in) iJD)
Definition at line 2357 of file types.F90.
References gregorian_date(), types::t_model_configuration::iday, types::t_month::imonth, types::t_model_configuration::iyear, and julian_day().
character (len=len_trim(adjustl(sstring))+2) function types::dquote (character (len=*), intent(in) sString)
Definition at line 1094 of file types.F90.
Referenced by chomp_default_sub(), chomp_delim_sub(), control::control_setmodeloptions(), swb_grid::grid_readarcgrid_fn(), swb_grid::grid_readarcgrid_sub(), swb_grid::grid_readsurfergrid_fn(), swb_grid::grid_readsurfergrid_sub(), netcdf_support::netcdf_info(), and str_compare().
subroutine types::echolog (character(len=*), intent(in) sMessage, character(len=*), intent(in), optional sFormat)
Definition at line 1224 of file types.F90.
Referenced by model::model_getdailyprecipvalue(), and model::model_getdailytemperaturevalue().
real (kind=t_sgl) function types::ftoc (real (kind=t_sgl), intent(in) rF)
Definition at line 1993 of file types.F90.
Referenced by meteorological_functions::dewpoint_vapor_pressure_ea(), et_hargreaves::et0_hargreaves(), et_blaney_criddle::et_bc_computeet(), et_jensen_haise::et_jh_computeet(), et_turc::et_turc_computeet(), model::model_processrainprms(), model::model_updatecontinuousfrozengroundindex(), meteorological_functions::precipitation_heat_p(), meteorological_functions::sat_vapor_density(), meteorological_functions::sat_vapor_pressure_es(), meteorological_functions::sensible_heat_exchange_h(), meteorological_functions::slope_sat_vapor_pressure_curve(), snow::snow_depth_hedstrom(), snow::snow_energy_balance(), and meteorological_functions::solar_radiation_hargreaves_rs().
real (kind=t_sgl) function types::ftok (real (kind=t_sgl), intent(in) rF)
Definition at line 2049 of file types.F90.
Referenced by et_hargreaves::et0_hargreaves(), meteorological_functions::net_longwave_radiation_rnl(), and meteorological_functions::sat_vapor_density().
subroutine types::getsystimedate (character(len=256), intent(out) sDateStr, character(len=256), intent(out) sDateStrPretty)
Definition at line 1389 of file types.F90.
Referenced by netcdf_support::netcdf_write_attributes().
subroutine types::gregorian_date (integer (kind=t_int) iJD, integer (kind=t_int), intent(inout) iYear, integer (kind=t_int), intent(inout) iMonth, integer (kind=t_int), intent(inout) iDay, integer (kind=t_int), optional iOrigin)
Converts from a Julian day number to a Gregorian date. Valid for any Gregorian calendar date producing a Julian day number greater than zero.
Reference: Fliegel, H. F. and van Flandern, T. C. (1968). Communications of the ACM, Vol. 11, No. 10 (October, 1968).
Modified from code found at: http://aa.usno.navy.mil/faq/docs/JD_Formula.html
Definition at line 2410 of file types.F90.
References types::t_model_configuration::iday, types::t_month::imonth, types::t_stats::ioffset, and types::t_model_configuration::iyear.
Referenced by control::control_setmodeloptions(), day_of_year(), lookupmonth(), model::model_solve(), netcdf_support::netcdf_info(), netcdf_support::netcdf_write_attributes(), and solstice().
character(len=256) function types::int2char (integer (kind=t_int) iValue)
Definition at line 2286 of file types.F90.
Referenced by chomp_default_sub(), chomp_delim_sub(), control::control_setmodeloptions(), swb_grid::grid_readarcgrid_fn(), swb_grid::grid_readarcgrid_sub(), swb_grid::grid_writearcgrid(), swb_grid::grid_writesurfergrid(), julian_day(), main(), model::model_configurerunoffdownhill(), model::model_getdailyprecipvalue(), model::model_getdailytemperaturevalue(), model::model_initializesm(), model::model_processrain(), model::model_processrunoff(), model::model_readlanduselookuptable(), model::model_solve(), netcdf_support::netcdf_check(), netcdf_support::netcdf_info(), real2char(), stats::stats_closebinaryfiles(), stats::stats_openbinaryfiles(), stats::stats_openbinaryfilesreadonly(), stats::stats_write_to_ssf_file(), and str_compare().
real (kind=t_sgl) function types::interpolate (real (kind=t_sgl), dimension(:), intent(in) rXT, real (kind=t_sgl), dimension(:), intent(in) rYT, real (kind=t_sgl), intent(in) rX)
Definition at line 2142 of file types.F90.
integer (kind=t_int) function types::julian_day (integer (kind=t_int), intent(in) iYear, integer (kind=t_int), intent(in) iMonth, integer (kind=t_int), intent(in) iDay, integer (kind=t_int), optional iOrigin)
Definition at line 2192 of file types.F90.
References types::t_model_configuration::iday, types::t_month::imonth, int2char(), types::t_stats::ioffset, and types::t_model_configuration::iyear.
Referenced by control::control_setmodeloptions(), day_of_year(), lookupmonth(), mmddyyyy2doy(), mmddyyyy2julian(), model::model_getdailyprecipvalue(), model::model_getdailytemperaturevalue(), model::model_solve(), netcdf_support::netcdf_info(), num_days_in_year(), and sm_thornthwaite_mather::sm_thornthwaite_mather_updatesm().
logical (kind=t_logical) function types::lf_model_growingseason (type (t_model_configuration), pointer pConfig, integer (kind=t_int), intent(in) iDayOfYear)
Definition at line 1957 of file types.F90.
References types::t_model_configuration::idayofyear.
Referenced by model::rf_model_getinterception(), and runoff_curve_number::runoff_updatecurvenumber().
subroutine types::lookupmonth (integer (kind=t_int), intent(in) iMonth, integer (kind=t_int), intent(in) iDay, integer (kind=t_int), intent(in) iYear, integer (kind=t_int), intent(out) iDayOfYear, character (len=3), intent(out) sMonthName, logical (kind=t_logical), intent(out) lMonthEnd)
Definition at line 1822 of file types.F90.
References gregorian_date(), types::t_model_configuration::iday, types::t_model_configuration::idayofyear, types::t_month::imonth, types::t_model_configuration::iyear, and julian_day().
Referenced by et_thornthwaite_mather::et_tm_initialize(), model::model_solve(), and stats::stats_rewritegrids().
character(len=len(s)) function types::lowercase_fn (character (len=*), intent(in) s)
Definition at line 1644 of file types.F90.
real (kind=t_sgl) function types::mm_to_in (real (kind=t_sgl), intent(in) r_mm)
Definition at line 2104 of file types.F90.
integer (kind=t_int) function types::mmddyyyy2doy (character (len=*) sMMDDYYYY)
Definition at line 1573 of file types.F90.
References chomp_slash(), types::t_model_configuration::iday, types::t_month::imonth, types::t_model_configuration::iyear, and julian_day().
Referenced by model::model_readirrigationlookuptable().
integer (kind=t_int) function types::mmddyyyy2julian (character (len=*) sMMDDYYYY)
Definition at line 1533 of file types.F90.
References chomp_slash(), types::t_model_configuration::iday, types::t_month::imonth, types::t_model_configuration::iyear, and julian_day().
integer (kind=t_int) function types::nextunit (integer (kind=t_int), intent(out), optional iLU)
Definition at line 1056 of file types.F90.
References types::t_ssf_files::ilu.
Referenced by stats::stats_openbinaryfiles(), and stats::stats_openbinaryfilesreadonly().
integer (kind=t_int) function types::num_days_in_year (integer (kind=t_int), intent(in) iYear)
This function simply returns the number of days given the current year.
Definition at line 2340 of file types.F90.
References types::t_model_configuration::inumdaysinyear, types::t_model_configuration::iyear, and julian_day().
Referenced by control::control_setmodeloptions(), and model::model_solve().
real (kind=t_sgl) function types::polynomial (real (kind=t_sgl), intent(in) x, real (kind=t_sgl), dimension(:) a)
Definition at line 1773 of file types.F90.
Referenced by et_thornthwaite_mather::et_tm_computeet(), and et_thornthwaite_mather::et_tm_initialize().
character(len=256) function types::real2char (real (kind=t_sgl) rValue, integer (kind=t_int), optional iDec, integer (kind=t_int), optional iWidth)
Definition at line 2301 of file types.F90.
References int2char().
Referenced by control::control_setmodeloptions(), swb_grid::grid_writearcgrid(), swb_grid::grid_writesurfergrid(), model::model_getdailyprecipvalue(), model::model_getdailytemperaturevalue(), and netcdf_support::netcdf_check().
integer (kind=t_int) function types::solstice (integer (kind=t_int), intent(in) iJD)
Definition at line 2253 of file types.F90.
References gregorian_date(), types::t_model_configuration::iday, types::t_month::imonth, and types::t_model_configuration::iyear.
character (len=len_trim(adjustl(sstring))+2) function types::squote (character (len=*), intent(in) sString)
Definition at line 1081 of file types.F90.
Referenced by control::control_setmodeloptions().
logical (kind=t_logical) function types::str_compare (character(len=*), intent(in) sString1, character(len=*), intent(in) sString2)
Definition at line 1105 of file types.F90.
References dquote(), int2char(), and uppercase_fn().
Referenced by control::control_setmodeloptions(), model::model_readlanduselookuptable(), and netcdf_support::netcdf_info().
subroutine types::uppercase (character (len=*), intent(inout) s)
Definition at line 1668 of file types.F90.
Referenced by control::control_setmodeloptions(), swb_grid::grid_readarcgrid_fn(), swb_grid::grid_readarcgrid_sub(), model::model_readbasinmasktable(), model::model_readirrigationlookuptable(), and model::model_readlanduselookuptable().
character(len=len(s)) function types::uppercase_fn (character (len=*), intent(in) s)
Definition at line 1619 of file types.F90.
Referenced by str_compare().
Variable Documentation
type (t_basin_mask), dimension(:), pointer types::t_model_configuration::bmask
Definition at line 814 of file types.F90.
Referenced by model::model_readbasinmasktable().
character(len=256) types::t_graph_configuration::ccdev "PNG"
Definition at line 927 of file types.F90.
character(len=256) types::t_graph_configuration::ccolor_table "SPEC"
Definition at line 934 of file types.F90.
type (t_cell), dimension(:,:), pointer types::t_general_grid::cells
Definition at line 225 of file types.F90.
character(len=256) types::t_graph_configuration::cfont_name "HELVE"
Definition at line 933 of file types.F90.
real (kind=t_sgl), dimension(:,:), pointer types::t_model_configuration::cn
Definition at line 817 of file types.F90.
integer (kind=t_int), parameter types::config_end_if_missing_data 1
Definition at line 1027 of file types.F90.
integer (kind=t_int), parameter types::config_estimate_missing_data 0
Definition at line 1026 of file types.F90.
integer (kind=t_int), parameter types::config_et_blaney_criddle 4
Definition at line 979 of file types.F90.
Referenced by control::control_setmodeloptions(), model::model_initializeet(), and model::model_processet().
integer (kind=t_int), parameter types::config_et_hargreaves 5
Definition at line 980 of file types.F90.
Referenced by control::control_setmodeloptions(), model::model_initializeet(), and model::model_processet().
integer (kind=t_int), parameter types::config_et_jensen_haise 3
Definition at line 978 of file types.F90.
Referenced by control::control_setmodeloptions(), model::model_initializeet(), and model::model_processet().
integer (kind=t_int), parameter types::config_et_none 0
Definition at line 975 of file types.F90.
Referenced by control::control_setmodeloptions(), model::model_initializeet(), and model::model_processet().
integer (kind=t_int), parameter types::config_et_thornthwaite_mather 1
Definition at line 976 of file types.F90.
Referenced by control::control_setmodeloptions(), model::model_initializeet(), and model::model_processet().
integer (kind=t_int), parameter types::config_et_turc 2
Definition at line 977 of file types.F90.
Referenced by control::control_setmodeloptions(), model::model_initializeet(), and model::model_processet().
integer (kind=t_int), parameter types::config_landuse_constant 0
Definition at line 1002 of file types.F90.
Referenced by control::control_setmodeloptions().
integer (kind=t_int), parameter types::config_landuse_dynamic_arc_grid 1
Definition at line 1003 of file types.F90.
Referenced by control::control_setmodeloptions(), model::if_getdynamiclandusevalue(), and model::model_solve().
integer (kind=t_int), parameter types::config_landuse_dynamic_netcdf 3
Definition at line 1005 of file types.F90.
integer (kind=t_int), parameter types::config_landuse_dynamic_surfer 2
Definition at line 1004 of file types.F90.
Referenced by control::control_setmodeloptions(), model::if_getdynamiclandusevalue(), and model::model_solve().
integer (kind=t_int), parameter types::config_landuse_static_grid 4
Definition at line 1006 of file types.F90.
Referenced by control::control_setmodeloptions().
integer (kind=t_int), parameter types::config_precip_arc_grid 1
Definition at line 987 of file types.F90.
Referenced by control::control_setmodeloptions(), and model::model_getdailyprecipvalue().
integer (kind=t_int), parameter types::config_precip_netcdf 3
Definition at line 989 of file types.F90.
Referenced by control::control_setmodeloptions(), and model::model_getdailyprecipvalue().
integer (kind=t_int), parameter types::config_precip_single_station 0
Definition at line 986 of file types.F90.
Referenced by control::control_setmodeloptions(), and model::model_getdailyprecipvalue().
integer (kind=t_int), parameter types::config_precip_surfer_grid 2
Definition at line 988 of file types.F90.
Referenced by control::control_setmodeloptions(), and model::model_getdailyprecipvalue().
integer (kind=t_int), parameter types::config_runoff_curve_number 0
Definition at line 958 of file types.F90.
Referenced by control::control_setmodeloptions(), and model::rf_model_cellrunoff().
integer (kind=t_int), parameter types::config_runoff_downhill 1
Definition at line 967 of file types.F90.
Referenced by control::control_setmodeloptions(), model::model_processrunoff(), and model::model_solve().
integer (kind=t_int), parameter types::config_runoff_green_ampt 1
Definition at line 959 of file types.F90.
Referenced by control::control_setmodeloptions(), and model::rf_model_cellrunoff().
integer (kind=t_int), parameter types::config_runoff_iterative 0
Definition at line 966 of file types.F90.
Referenced by control::control_setmodeloptions(), and model::model_processrunoff().
integer (kind=t_int), parameter types::config_runoff_no_routing 2
Definition at line 968 of file types.F90.
Referenced by control::control_setmodeloptions(), model::model_initializeflowdirection(), model::model_processrunoff(), model::model_solve(), and sm_thornthwaite_mather::sm_thornthwaite_mather_updatesm().
integer (kind=t_int), parameter types::config_sm_capacity_calculate 0
Definition at line 1013 of file types.F90.
Referenced by control::control_setmodeloptions(), and model::model_initializesm().
integer (kind=t_int), parameter types::config_sm_capacity_constant 1
Definition at line 1014 of file types.F90.
integer (kind=t_int), parameter types::config_sm_capacity_fm_table 2
Definition at line 1015 of file types.F90.
Referenced by control::control_setmodeloptions().
integer (kind=t_int), parameter types::config_sm_init_abstraction_hawkins 1
Definition at line 1023 of file types.F90.
Referenced by control::control_setmodeloptions(), and runoff_curve_number::runoff_cellrunoff_curvenumber().
integer (kind=t_int), parameter types::config_sm_init_abstraction_tr55 0
Definition at line 1022 of file types.F90.
Referenced by control::control_setmodeloptions(), and runoff_curve_number::runoff_cellrunoff_curvenumber().
integer (kind=t_int), parameter types::config_sm_none 0
Definition at line 1018 of file types.F90.
Referenced by model::model_initializesm(), and model::model_processsm().
integer (kind=t_int), parameter types::config_sm_thornthwaite_mather 1
Definition at line 1019 of file types.F90.
Referenced by control::control_setmodeloptions(), model::model_initializesm(), and model::model_processsm().
integer (kind=t_int), parameter types::config_snow_new_swb 1
Definition at line 1010 of file types.F90.
Referenced by control::control_setmodeloptions(), and model::model_solve().
integer (kind=t_int), parameter types::config_snow_original_swb 0
Definition at line 1009 of file types.F90.
Referenced by control::control_setmodeloptions(), and model::model_solve().
integer (kind=t_int), parameter types::config_temperature_arc_grid 1
Definition at line 996 of file types.F90.
Referenced by control::control_setmodeloptions(), and model::model_getdailytemperaturevalue().
integer (kind=t_int), parameter types::config_temperature_netcdf 3
Definition at line 998 of file types.F90.
Referenced by control::control_setmodeloptions(), and model::model_getdailytemperaturevalue().
integer (kind=t_int), parameter types::config_temperature_single_station 0
Definition at line 995 of file types.F90.
Referenced by control::control_setmodeloptions(), and model::model_getdailytemperaturevalue().
integer (kind=t_int), parameter types::config_temperature_surfer_grid 2
Definition at line 997 of file types.F90.
Referenced by control::control_setmodeloptions(), and model::model_getdailytemperaturevalue().
character(len=256) types::t_graph_configuration::cpaper_size "USAP"
Definition at line 928 of file types.F90.
character(len=256) types::t_graph_configuration::csetfil "DEFAULT_FILENAME"
Definition at line 926 of file types.F90.
character(len=256) types::t_graph_configuration::ctitle "NO TITLE"
Definition at line 929 of file types.F90.
character(len=256) types::t_graph_configuration::cx_axis_title "X-AXIS TITLE"
Definition at line 931 of file types.F90.
character(len=256) types::t_graph_configuration::cy_axis_title "Y-AXIS TITLE"
Definition at line 932 of file types.F90.
character(len=256) types::t_graph_configuration::cz_axis_title "Z-AXIS TITLE"
Definition at line 930 of file types.F90.
real (kind=t_dbl), parameter types::dpc_per_f 5.0_T_DBL / 9.0_T_DBL
Definition at line 78 of file types.F90.
Referenced by model::model_processrain().
real (kind=t_dbl), parameter types::dpf_per_c 9.0_T_DBL / 5.0_T_DBL
Definition at line 79 of file types.F90.
real (kind=t_dbl), parameter types::dpone 1.0_T_DBL
Definition at line 73 of file types.F90.
Referenced by sm_thornthwaite_mather::sm_thornthwaite_mather_initialize(), sm_thornthwaite_mather::sm_thornthwaite_mather_updatesm(), and stats::stats_initializevolumeconversion().
real (kind=t_dbl), parameter types::dppi 3.14159265_T_DBL
Definition at line 82 of file types.F90.
Referenced by meteorological_functions::daylight_hours(), meteorological_functions::deg2rad(), et_blaney_criddle::et_bc_computeet(), et_blaney_criddle::et_bc_initialize(), et_thornthwaite_mather::et_tm_computeet(), meteorological_functions::extraterrestrial_radiation_ra(), netcdf_support::lltoutm(), model::model_updategrowingdegreeday(), meteorological_functions::rel_earth_sun_dist(), meteorological_functions::solar_declination(), and netcdf_support::utmtoll().
real (kind=t_dbl), parameter types::dpsqm_to_sqft 10.76391_T_DBL
Definition at line 84 of file types.F90.
real (kind=t_dbl), parameter types::dptwopi 2.0_T_DBL * dpPI
Definition at line 83 of file types.F90.
Referenced by et_blaney_criddle::et_bc_computeet(), et_blaney_criddle::et_bc_configure(), et_blaney_criddle::et_bc_initialize(), et_hargreaves::et_hargreaves_configure(), et_jensen_haise::et_jh_computeet(), et_jensen_haise::et_jh_configure(), et_thornthwaite_mather::et_tm_computeet(), et_thornthwaite_mather::et_tm_configure(), et_turc::et_turc_computeet(), and et_turc::et_turc_configure().
real (kind=t_dbl), parameter types::dpzero 0.0_T_DBL
Definition at line 67 of file types.F90.
Referenced by model::model_processrain(), model::model_processrainprms(), sm_thornthwaite_mather::sm_thornthwaite_mather_apwl(), sm_thornthwaite_mather::sm_thornthwaite_mather_initialize(), sm_thornthwaite_mather::sm_thornthwaite_mather_soil_storage(), and sm_thornthwaite_mather::sm_thornthwaite_mather_updatesm().
type (t_general_grid), dimension(:), pointer types::t_grid_collection::grids
Definition at line 237 of file types.F90.
integer (kind=t_int), parameter types::iact_et 9
Definition at line 634 of file types.F90.
Referenced by sm_thornthwaite_mather::sm_thornthwaite_mather_updatesm(), and stats::stats_writemsbreport().
integer(kind=t_int), parameter types::iannual 3
Definition at line 952 of file types.F90.
Referenced by control::control_setmodeloptions(), stats::stats_calcmeanrecharge(), and stats::stats_rewritegrids().
integer(kind=t_int) types::t_stats::iannualoutput
Definition at line 444 of file types.F90.
integer (kind=t_int), parameter types::iavg_temp 18
Definition at line 643 of file types.F90.
Referenced by sm_thornthwaite_mather::sm_thornthwaite_mather_updatesm().
integer (kind=t_int) types::t_irrigation_lookup::ibeginirrigation 120
Definition at line 300 of file types.F90.
integer(kind=t_int), parameter types::iboth 3
Definition at line 463 of file types.F90.
Referenced by control::control_setmodeloptions(), and stats::stats_rewritegrids().
integer (kind=t_int), parameter types::icfgi 15
Definition at line 640 of file types.F90.
Referenced by sm_thornthwaite_mather::sm_thornthwaite_mather_updatesm().
integer (kind=t_int), parameter types::ichg_in_snow_cov 19
Definition at line 644 of file types.F90.
Referenced by model::model_processrain(), model::model_processrainprms(), sm_thornthwaite_mather::sm_thornthwaite_mather_updatesm(), and stats::stats_writemsbreport().
integer (kind=t_int), parameter types::ichg_in_soil_moist 10
Definition at line 635 of file types.F90.
Referenced by sm_thornthwaite_mather::sm_thornthwaite_mather_updatesm(), and stats::stats_writemsbreport().
integer (kind=t_int) types::t_ssf_files::icolnum
Definition at line 331 of file types.F90.
Referenced by control::control_setmodeloptions().
integer (kind=t_int) types::t_model_configuration::iconfigureet
Definition at line 674 of file types.F90.
integer (kind=t_int) types::t_model_configuration::iconfigureinitialabstraction
Definition at line 688 of file types.F90.
integer (kind=t_int) types::t_model_configuration::iconfigurelanduse
Definition at line 680 of file types.F90.
integer (kind=t_int) types::t_model_configuration::iconfigureprecip
Definition at line 676 of file types.F90.
integer (kind=t_int) types::t_model_configuration::iconfigurerunoff
Definition at line 670 of file types.F90.
integer (kind=t_int) types::t_model_configuration::iconfigurerunoffmode
Definition at line 672 of file types.F90.
integer (kind=t_int) types::t_model_configuration::iconfiguresm
Definition at line 682 of file types.F90.
integer (kind=t_int) types::t_model_configuration::iconfiguresmcapacity
Definition at line 686 of file types.F90.
integer (kind=t_int) types::t_model_configuration::iconfiguresnow
Definition at line 684 of file types.F90.
integer (kind=t_int) types::t_model_configuration::iconfiguretemperature
Definition at line 678 of file types.F90.
integer (kind=t_int) types::t_model_configuration::icurrentjulianday
Definition at line 715 of file types.F90.
integer(kind=t_int), parameter types::idaily 1
Definition at line 950 of file types.F90.
Referenced by control::control_setmodeloptions(), and stats::stats_rewritegrids().
integer(kind=t_int) types::t_stats::idailyoutput
Definition at line 440 of file types.F90.
integer (kind=t_int), dimension(:,:), pointer types::t_general_grid::idata
Definition at line 223 of file types.F90.
integer (kind=t_int) types::t_general_grid::idatatype
Definition at line 218 of file types.F90.
Referenced by swb_grid::grid_create(), swb_grid::grid_read(), swb_grid::grid_readarcgrid_fn(), swb_grid::grid_readsurfergrid_fn(), and stats::stats_openbinaryfilesreadonly().
integer (kind=t_int) types::t_model_configuration::iday
Definition at line 711 of file types.F90.
Referenced by day_of_year(), et_blaney_criddle::et_bc_initialize(), et_thornthwaite_mather::et_tm_initialize(), gregorian_date(), julian_day(), lookupmonth(), mmddyyyy2doy(), mmddyyyy2julian(), model::model_getdailyprecipvalue(), model::model_getdailytemperaturevalue(), model::model_processsm(), model::model_writegrids(), netcdf_support::netcdf_info(), netcdf_support::netcdf_write_attributes(), sm_thornthwaite_mather::sm_thornthwaite_mather_updatesm(), solstice(), stats::stats_rewritegrids(), stats::stats_write_to_ssf_file(), stats::stats_writedailyaccumulatorvaluescsv(), and stats::stats_writemsbreport().
integer (kind=t_int) types::t_time_series_file::iday
Definition at line 899 of file types.F90.
integer (kind=t_int) types::t_model_configuration::idayoffirstfrost
Definition at line 790 of file types.F90.
integer (kind=t_int) types::t_model_configuration::idayoflastfrost
Definition at line 791 of file types.F90.
integer (kind=t_int) types::t_model_configuration::idayofyear
Definition at line 712 of file types.F90.
Referenced by et_blaney_criddle::et_bc_computeet(), et_hargreaves::et_hargreaves_computeet(), et_jensen_haise::et_jh_computeet(), et_thornthwaite_mather::et_tm_computeet(), et_thornthwaite_mather::et_tm_initialize(), et_turc::et_turc_computeet(), model::if_model_runoffiteration(), lf_model_growingseason(), lookupmonth(), model::model_processet(), model::model_processrain(), model::model_processrainprms(), model::model_processrunoff(), model::model_processsm(), model::model_runoff_norouting(), model::model_runoffdownhill(), model::model_writegrids(), meteorological_functions::rel_earth_sun_dist(), model::rf_model_cellrunoff(), model::rf_model_getinterception(), sm_thornthwaite_mather::sm_thornthwaite_mather_updatesm(), meteorological_functions::solar_declination(), stats::stats_rewritegrids(), and stats::stats_writemsbreport().
integer (kind=t_int) types::t_cell::idayssincelastsnow 0
Definition at line 189 of file types.F90.
integer (kind=t_int) types::t_model_configuration::iellipsoidid 11
Definition at line 860 of file types.F90.
integer (kind=t_int) types::t_netcdf_file::iellipsoidid 11
Definition at line 378 of file types.F90.
integer (kind=t_int) types::t_month::iend
Definition at line 388 of file types.F90.
Referenced by assert_module_details_sub(), and assert_simple_sub().
integer(kind=t_int) types::ienddate_pos
Definition at line 108 of file types.F90.
Referenced by model::model_endofrun(), stats::stats_openbinaryfiles(), and stats::stats_openbinaryfilesreadonly().
integer(kind=t_int) types::iendheader_pos
Definition at line 109 of file types.F90.
Referenced by stats::stats_openbinaryfiles(), stats::stats_openbinaryfilesreadonly(), and stats::stats_rewritegrids().
integer (kind=t_int) types::t_irrigation_lookup::iendirrigation 240
Definition at line 303 of file types.F90.
integer (kind=t_int) types::t_model_configuration::iendjulianday
Definition at line 716 of file types.F90.
integer(kind=t_int) types::t_netcdf_file::iendjulianday
Definition at line 359 of file types.F90.
integer (kind=t_int) types::t_model_configuration::iendyear
Definition at line 708 of file types.F90.
integer (kind=t_int) types::t_model_configuration::iendyearforcalculation 99999
Definition at line 718 of file types.F90.
integer(kind=t_int), parameter types::ieof HUGE(iZERO)
Definition at line 95 of file types.F90.
Referenced by model::if_getdynamiclandusevalue(), rle::rle_readbyte(), and rle::rle_writebyte().
integer (kind=t_int), parameter types::ifield_width 10
Definition at line 91 of file types.F90.
Referenced by swb_grid::grid_writearcgrid(), and swb_grid::grid_writesurfergrid().
integer (kind=t_short) types::t_cell::iflowdir iZERO
Definition at line 137 of file types.F90.
integer (kind=t_int), parameter types::igdd 29
Definition at line 654 of file types.F90.
Referenced by sm_thornthwaite_mather::sm_thornthwaite_mather_updatesm().
integer(kind=t_int), parameter types::igraph 2
Definition at line 462 of file types.F90.
Referenced by control::control_setmodeloptions(), and stats::stats_rewritegrids().
integer(kind=t_int), parameter types::igrid 1
Definition at line 461 of file types.F90.
Referenced by control::control_setmodeloptions(), and stats::stats_rewritegrids().
integer (kind=t_int), parameter types::igrid_length_units_feet 1
Definition at line 231 of file types.F90.
Referenced by control::control_setmodeloptions(), netcdf_support::netcdf_write_attributes(), and stats::stats_initializevolumeconversion().
integer (kind=t_int), parameter types::igrid_length_units_meters 0
Definition at line 230 of file types.F90.
Referenced by control::control_setmodeloptions(), and stats::stats_initializevolumeconversion().
integer (kind=t_int), parameter types::igross_precip 1
Definition at line 626 of file types.F90.
Referenced by control::control_setmodeloptions(), model::model_getdailyprecipvalue(), sm_thornthwaite_mather::sm_thornthwaite_mather_updatesm(), and stats::stats_writemsbreport().
integer (kind=t_int) types::t_model_configuration::iheaderprintinterval
Definition at line 798 of file types.F90.
integer (kind=t_int) types::t_stats::iindent
Definition at line 422 of file types.F90.
integer (kind=t_int), parameter types::iinflow 3
Definition at line 628 of file types.F90.
Referenced by sm_thornthwaite_mather::sm_thornthwaite_mather_updatesm(), and stats::stats_writemsbreport().
integer (kind=t_int), parameter types::iinterception 6
Definition at line 631 of file types.F90.
Referenced by model::model_processrain(), model::model_processrainprms(), sm_thornthwaite_mather::sm_thornthwaite_mather_updatesm(), and stats::stats_writemsbreport().
integer (kind=t_int), parameter types::iirrigation 4
Definition at line 629 of file types.F90.
Referenced by sm_thornthwaite_mather::sm_thornthwaite_mather_updatesm(), and stats::stats_writemsbreport().
integer (kind=t_short) types::t_cell::ilanduse iZERO
Definition at line 140 of file types.F90.
Referenced by sm_thornthwaite_mather::sm_thornthwaite_mather_updatesm().
integer (kind=t_short) types::t_cell::ilanduseindex
Definition at line 139 of file types.F90.
integer (kind=t_int) types::t_landuse_lookup::ilandusetype
Definition at line 248 of file types.F90.
Referenced by model::model_readirrigationlookuptable().
integer (kind=t_int) types::t_irrigation_lookup::ilandusetype
Definition at line 272 of file types.F90.
integer (kind=t_int), parameter types::ilength 5
Definition at line 614 of file types.F90.
integer (kind=t_int) types::t_basin_mask::ilength
Definition at line 320 of file types.F90.
Referenced by stats::stats_initializedailyaccumulators(), and stats::stats_updateallaccumulatorsbycell().
integer (kind=t_int) types::t_general_grid::ilengthunits -99999
Definition at line 220 of file types.F90.
Referenced by stats::stats_openbinaryfilesreadonly().
integer (kind=t_int) types::t_ssf_files::ilu
Definition at line 328 of file types.F90.
Referenced by assert_module_details_sub(), assert_simple_sub(), nextunit(), rle::rle_readbyte(), rle::rle_writebyte(), stats::stats_dumpannualaccumulatorvalues(), stats::stats_dumpdailyaccumulatorvalues(), stats::stats_dumpmonthlyaccumulatorvalues(), stats::stats_writeannualaccumulatorheadercsv(), stats::stats_writeannualaccumulatorvaluescsv(), stats::stats_writedailyaccumulatorheadercsv(), stats::stats_writedailyaccumulatorvaluescsv(), and stats::stats_writeminmeanmax().
integer(kind=t_int) types::t_stats::ilu
Definition at line 420 of file types.F90.
integer(kind=t_int) types::t_stats::imassbalanceconst
Definition at line 424 of file types.F90.
integer (kind=t_int), parameter types::imax 3
Definition at line 612 of file types.F90.
Referenced by model::model_solve(), stats::stats_formattextstring(), stats::stats_initializedailyaccumulators(), stats::stats_updateallaccumulatorsbycell(), stats::stats_updateallaccumulatorsbygrid(), and stats::stats_writedailyaccumulatorvaluescsv().
integer (kind=t_int), parameter types::imax_temp 17
Definition at line 642 of file types.F90.
Referenced by control::control_setmodeloptions(), model::model_getdailytemperaturevalue(), and sm_thornthwaite_mather::sm_thornthwaite_mather_updatesm().
integer (kind=t_int), parameter types::imean 2
Definition at line 611 of file types.F90.
Referenced by model::model_solve(), stats::stats_initializedailyaccumulators(), stats::stats_updateallaccumulatorsbycell(), stats::stats_updateallaccumulatorsbygrid(), stats::stats_writeannualaccumulatorheadercsv(), stats::stats_writeannualaccumulatorvaluescsv(), and stats::stats_writedailyaccumulatorvaluescsv().
integer (kind=t_int), parameter types::imin 1
Definition at line 610 of file types.F90.
Referenced by model::model_solve(), stats::stats_formattextstring(), stats::stats_initializedailyaccumulators(), stats::stats_updateallaccumulatorsbycell(), stats::stats_updateallaccumulatorsbygrid(), and stats::stats_writedailyaccumulatorvaluescsv().
integer (kind=t_int), parameter types::imin_temp 16
Definition at line 641 of file types.F90.
Referenced by control::control_setmodeloptions(), model::model_getdailytemperaturevalue(), and sm_thornthwaite_mather::sm_thornthwaite_mather_updatesm().
integer (kind=t_int) types::t_model_configuration::imonth
Definition at line 710 of file types.F90.
integer (kind=t_int) types::t_time_series_file::imonth
Definition at line 898 of file types.F90.
integer (kind=t_int) types::t_month::imonth
Definition at line 389 of file types.F90.
Referenced by day_of_year(), et_thornthwaite_mather::et_tm_initialize(), gregorian_date(), julian_day(), lookupmonth(), mmddyyyy2doy(), mmddyyyy2julian(), model::model_getdailyprecipvalue(), model::model_getdailytemperaturevalue(), model::model_processrain(), model::model_processrainprms(), model::model_processrunoff(), model::model_processsm(), model::model_writegrids(), netcdf_support::netcdf_info(), netcdf_support::netcdf_write_attributes(), sm_thornthwaite_mather::sm_thornthwaite_mather_updatesm(), solstice(), stats::stats_dumpmonthlyaccumulatorvalues(), stats::stats_rewritegrids(), stats::stats_write_to_ssf_file(), stats::stats_writedailyaccumulatorvaluescsv(), and stats::stats_writemsbreport().
integer(kind=t_int), parameter types::imonthly 2
Definition at line 951 of file types.F90.
Referenced by control::control_setmodeloptions(), and stats::stats_rewritegrids().
integer(kind=t_int) types::t_stats::imonthlyoutput
Definition at line 442 of file types.F90.
integer (kind=t_int), parameter types::imoving_avg_terms 5
Definition at line 85 of file types.F90.
Referenced by model::model_processrunoff().
integer (kind=t_int), parameter types::inc_input 1
Definition at line 113 of file types.F90.
Referenced by control::control_setmodeloptions(), model::model_getdailyprecipvalue(), and model::model_getdailytemperaturevalue().
integer (kind=t_int), parameter types::inc_observation 3
Definition at line 115 of file types.F90.
integer (kind=t_int), parameter types::inc_output 2
Definition at line 114 of file types.F90.
Referenced by model::model_endofrun(), model::model_write_netcdf_attributes(), and sm_thornthwaite_mather::sm_thornthwaite_mather_updatesm().
integer(kind=t_int) types::t_netcdf_file::incid
Definition at line 337 of file types.F90.
Referenced by netcdf_support::netcdf_create(), and netcdf_support::netcdf_open().
integer (kind=t_int), parameter types::inet_infil 22
Definition at line 647 of file types.F90.
Referenced by sm_thornthwaite_mather::sm_thornthwaite_mather_updatesm().
integer (kind=t_int), parameter types::inet_inflow 21
Definition at line 646 of file types.F90.
Referenced by sm_thornthwaite_mather::sm_thornthwaite_mather_updatesm().
integer (kind=t_int), parameter types::inet_precip 20
Definition at line 645 of file types.F90.
Referenced by model::model_processrain(), model::model_processrainprms(), sm_thornthwaite_mather::sm_thornthwaite_mather_updatesm(), and stats::stats_writemsbreport().
integer(kind=t_int) types::t_stats::inetcdfoutput
Definition at line 446 of file types.F90.
integer (kind=t_int), parameter types::ino_data_ncdc -99999
Definition at line 89 of file types.F90.
Referenced by model::model_solve().
integer(kind=t_int), parameter types::inone 0
Definition at line 460 of file types.F90.
Referenced by control::control_setmodeloptions(), model::model_endofrun(), model::model_processrain(), model::model_processrainprms(), model::model_solve(), model::model_write_netcdf_attributes(), sm_thornthwaite_mather::sm_thornthwaite_mather_updatesm(), stats::stats_closebinaryfiles(), stats::stats_openbinaryfiles(), stats::stats_openbinaryfilesreadonly(), and stats::stats_rewritegrids().
integer (kind=t_int), parameter types::inum_digits 3
Definition at line 90 of file types.F90.
Referenced by swb_grid::grid_writearcgrid(), and swb_grid::grid_writesurfergrid().
integer (kind=t_int), parameter types::inum_months 12
Definition at line 456 of file types.F90.
integer (kind=t_int), parameter types::inum_stats 5
Definition at line 609 of file types.F90.
integer(kind=t_int), parameter types::inum_variables 29
Definition at line 457 of file types.F90.
Referenced by control::control_setmodeloptions(), model::model_endofrun(), model::model_solve(), model::model_write_netcdf_attributes(), sm_thornthwaite_mather::sm_thornthwaite_mather_updatesm(), stats::stats_closebinaryfiles(), stats::stats_dumpannualaccumulatorvalues(), stats::stats_dumpdailyaccumulatorvalues(), stats::stats_dumpmonthlyaccumulatorvalues(), stats::stats_openbinaryfiles(), stats::stats_openbinaryfilesreadonly(), stats::stats_rewritegrids(), stats::stats_writeannualaccumulatorheadercsv(), stats::stats_writeannualaccumulatorvaluescsv(), stats::stats_writedailyaccumulatorheadercsv(), and stats::stats_writedailyaccumulatorvaluescsv().
integer (kind=t_int) types::t_month::inumdays
Definition at line 390 of file types.F90.
integer (kind=t_int) types::t_model_configuration::inumdaysinyear
Definition at line 713 of file types.F90.
Referenced by et_hargreaves::et_hargreaves_computeet(), model::model_processet(), model::model_processrainprms(), num_days_in_year(), meteorological_functions::rel_earth_sun_dist(), and meteorological_functions::solar_declination().
integer(kind=t_short) types::t_cell::inumfilesssf 0
Definition at line 196 of file types.F90.
integer (kind=t_int) types::t_general_grid::inumgridcells
Definition at line 217 of file types.F90.
Referenced by swb_grid::grid_create(), graph::make_shaded_contour(), graph::makegraph(), model::model_configurerunoffdownhill(), model::model_processrain(), model::model_processrainprms(), model::model_processrunoff(), model::model_solve(), sm_thornthwaite_mather::sm_thornthwaite_mather_updatesm(), stats::stats_calcbasinstats(), stats::stats_calcmeanrechargebylu(), stats::stats_rewritegrids(), stats::stats_updateallaccumulatorsbycell(), and stats::stats_writeminmeanmax().
integer (kind=t_int) types::t_general_grid::inx
Definition at line 215 of file types.F90.
Referenced by control::control_setmodeloptions(), swb_grid::grid_create(), swb_grid::grid_readarcgrid_fn(), swb_grid::grid_readarcgrid_sub(), swb_grid::grid_readsurfergrid_fn(), swb_grid::grid_readsurfergrid_sub(), stats::stats_openbinaryfilesreadonly(), and stats::stats_rewritegrids().
integer (kind=t_int) types::t_general_grid::iny
Definition at line 216 of file types.F90.
Referenced by control::control_setmodeloptions(), swb_grid::grid_create(), swb_grid::grid_readarcgrid_fn(), swb_grid::grid_readarcgrid_sub(), swb_grid::grid_readsurfergrid_fn(), swb_grid::grid_readsurfergrid_sub(), stats::stats_openbinaryfilesreadonly(), and stats::stats_rewritegrids().
integer (kind=t_int) types::t_stats::ioffset
Definition at line 450 of file types.F90.
Referenced by gregorian_date(), and julian_day().
integer(kind=t_int) types::t_model_configuration::iopen_water_lu -99999
Definition at line 831 of file types.F90.
integer(kind=t_int) types::t_netcdf_file::ioriginday
Definition at line 355 of file types.F90.
integer(kind=t_int) types::t_netcdf_file::ioriginjulianday
Definition at line 357 of file types.F90.
integer(kind=t_int) types::t_netcdf_file::ioriginmonth
Definition at line 354 of file types.F90.
integer(kind=t_int) types::t_netcdf_file::ioriginyear
Definition at line 356 of file types.F90.
integer (kind=t_int), parameter types::ioutflow 7
Definition at line 632 of file types.F90.
Referenced by sm_thornthwaite_mather::sm_thornthwaite_mather_updatesm(), and stats::stats_writemsbreport().
integer (kind=t_int) types::t_model_configuration::ioutputformat
Definition at line 787 of file types.F90.
integer (kind=t_int), parameter types::ip_minus_pet 24
Definition at line 649 of file types.F90.
Referenced by sm_thornthwaite_mather::sm_thornthwaite_mather_updatesm().
integer (kind=t_int) types::t_stats::ipos
Definition at line 452 of file types.F90.
Referenced by model::model_solve().
integer (kind=t_int), parameter types::ipot_et 23
Definition at line 648 of file types.F90.
Referenced by sm_thornthwaite_mather::sm_thornthwaite_mather_updatesm().
integer(kind=t_int) types::t_netcdf_file::iprojid
Definition at line 341 of file types.F90.
integer (kind=t_int), parameter types::irecharge 11
Definition at line 636 of file types.F90.
Referenced by sm_thornthwaite_mather::sm_thornthwaite_mather_updatesm(), stats::stats_calcmeanrecharge(), and stats::stats_writemsbreport().
integer (kind=t_int), parameter types::irejected_recharge 12
Definition at line 637 of file types.F90.
Referenced by sm_thornthwaite_mather::sm_thornthwaite_mather_updatesm(), and stats::stats_writemsbreport().
integer(kind=t_int) types::t_model_configuration::irle_mult 10000
Definition at line 700 of file types.F90.
Referenced by rle::rle_writebyte(), and stats::stats_openbinaryfilesreadonly().
integer (kind=t_int), parameter types::iroute_cell_marked -1
Definition at line 86 of file types.F90.
Referenced by model::model_configurerunoffdownhill().
integer (kind=t_int), parameter types::iroute_depression -999
Definition at line 87 of file types.F90.
Referenced by model::if_model_runoffiteration(), model::model_downstreamcell(), model::model_initializeflowdirection(), model::model_runoffdownhill(), and sm_thornthwaite_mather::sm_thornthwaite_mather_updatesm().
integer (kind=t_int), parameter types::iroute_left_grid -1000
Definition at line 88 of file types.F90.
Referenced by model::if_model_runoffiteration(), model::model_downstreamcell(), model::model_initializeflowdirection(), model::model_runoffdownhill(), and sm_thornthwaite_mather::sm_thornthwaite_mather_updatesm().
integer (kind=t_int) types::t_ssf_files::irownum
Definition at line 330 of file types.F90.
Referenced by control::control_setmodeloptions().
type (t_irrigation_lookup), dimension(:), pointer types::t_model_configuration::irrigation
Definition at line 810 of file types.F90.
integer (kind=t_int), parameter types::irunoff_outside 8
Definition at line 633 of file types.F90.
Referenced by sm_thornthwaite_mather::sm_thornthwaite_mather_updatesm(), and stats::stats_writemsbreport().
integer (kind=t_int), parameter types::ism_apwl 27
Definition at line 652 of file types.F90.
Referenced by sm_thornthwaite_mather::sm_thornthwaite_mather_updatesm().
integer (kind=t_int), parameter types::ism_deficit 25
Definition at line 650 of file types.F90.
Referenced by sm_thornthwaite_mather::sm_thornthwaite_mather_updatesm().
integer (kind=t_int), parameter types::ism_surplus 26
Definition at line 651 of file types.F90.
Referenced by sm_thornthwaite_mather::sm_thornthwaite_mather_updatesm().
integer (kind=t_int), parameter types::isnowcover 14
Definition at line 639 of file types.F90.
Referenced by model::model_processrain(), model::model_processrainprms(), sm_thornthwaite_mather::sm_thornthwaite_mather_updatesm(), and stats::stats_writemsbreport().
integer (kind=t_int), parameter types::isnowfall_swe 5
Definition at line 630 of file types.F90.
Referenced by model::model_processrain(), model::model_processrainprms(), sm_thornthwaite_mather::sm_thornthwaite_mather_updatesm(), and stats::stats_writemsbreport().
integer (kind=t_int), parameter types::isnowmelt 2
Definition at line 627 of file types.F90.
Referenced by model::model_processrain(), model::model_processrainprms(), sm_thornthwaite_mather::sm_thornthwaite_mather_updatesm(), and stats::stats_writemsbreport().
integer (kind=t_int), parameter types::isoil_moisture 28
Definition at line 653 of file types.F90.
Referenced by sm_thornthwaite_mather::sm_thornthwaite_mather_updatesm(), and stats::stats_writemsbreport().
integer (kind=t_short) types::t_cell::isoilgroup iZERO
Definition at line 138 of file types.F90.
Referenced by sm_thornthwaite_mather::sm_thornthwaite_mather_updatesm().
integer (kind=t_int) types::t_month::istart
Definition at line 387 of file types.F90.
integer(kind=t_int) types::istartdate_pos
Definition at line 107 of file types.F90.
Referenced by model::model_solve(), stats::stats_openbinaryfiles(), and stats::stats_openbinaryfilesreadonly().
integer (kind=t_int) types::t_model_configuration::istartjulianday
Definition at line 714 of file types.F90.
integer(kind=t_int) types::t_netcdf_file::istartjulianday
Definition at line 358 of file types.F90.
integer (kind=t_int) types::t_model_configuration::istartyear
Definition at line 707 of file types.F90.
Referenced by stats::stats_rewritegrids().
integer (kind=t_int) types::t_model_configuration::istartyearforcalculation -99999
Definition at line 717 of file types.F90.
integer(kind=t_int), parameter types::istats 4
Definition at line 464 of file types.F90.
integer (kind=t_int), parameter types::istream_capture 13
Definition at line 638 of file types.F90.
Referenced by sm_thornthwaite_mather::sm_thornthwaite_mather_updatesm(), and stats::stats_writemsbreport().
integer (kind=t_int) types::t_cell::istreamindex iZERO
Definition at line 155 of file types.F90.
integer (kind=t_int), parameter types::isum 4
Definition at line 613 of file types.F90.
Referenced by stats::stats_dumpannualaccumulatorvalues(), stats::stats_dumpdailyaccumulatorvalues(), stats::stats_dumpmonthlyaccumulatorvalues(), stats::stats_formattextstring(), stats::stats_initializedailyaccumulators(), stats::stats_updateallaccumulatorsbycell(), stats::stats_updateallaccumulatorsbygrid(), stats::stats_writeannualaccumulatorheadercsv(), stats::stats_writeannualaccumulatorvaluescsv(), and stats::stats_writemsbreport().
integer (kind=t_int) types::t_cell::itgt_col
Definition at line 160 of file types.F90.
Referenced by model::if_model_runoffiteration(), model::model_configurerunoffdownhill(), model::model_downstreamcell(), model::model_initializeflowdirection(), and model::model_runoffdownhill().
integer (kind=t_int) types::t_cell::itgt_row
Definition at line 159 of file types.F90.
Referenced by model::if_model_runoffiteration(), model::model_configurerunoffdownhill(), model::model_downstreamcell(), model::model_initializeflowdirection(), and model::model_runoffdownhill().
integer(kind=t_int) types::t_netcdf_file::itimedimid
Definition at line 352 of file types.F90.
integer(kind=t_int) types::t_graph_configuration::itimeframe 1
Definition at line 939 of file types.F90.
Referenced by control::control_setmodeloptions().
integer(kind=t_int) types::t_netcdf_file::itimevarid
Definition at line 353 of file types.F90.
integer(kind=t_int) types::t_netcdf_file::ivarid
Definition at line 343 of file types.F90.
integer (kind=t_int) types::t_ssf_files::ivarnum
Definition at line 332 of file types.F90.
Referenced by control::control_setmodeloptions(), graph::makegraph(), netcdf_support::netcdf_chk_extent(), netcdf_support::netcdf_info(), netcdf_support::netcdf_read(), netcdf_support::netcdf_write_attributes(), netcdf_support::netcdf_write_variable(), netcdf_support::netcdf_write_variable_byte(), rle::rle_writebyte(), stats::stats_formattextstring(), stats::stats_updateallaccumulatorsbycell(), and stats::stats_updateallaccumulatorsbygrid().
integer(kind=t_int) types::t_netcdf_file::ivartype
Definition at line 344 of file types.F90.
Referenced by netcdf_support::netcdf_info().
integer(kind=t_int) types::t_graph_configuration::iwinsizex 768
Definition at line 936 of file types.F90.
integer(kind=t_int) types::t_graph_configuration::iwinsizey 1024
Definition at line 937 of file types.F90.
integer(kind=t_int) types::t_netcdf_file::ix_numgridcells
Definition at line 365 of file types.F90.
integer(kind=t_int) types::t_netcdf_file::ixdimid
Definition at line 350 of file types.F90.
integer(kind=t_int) types::t_netcdf_file::ixvarid
Definition at line 347 of file types.F90.
integer(kind=t_int) types::t_netcdf_file::iy_numgridcells
Definition at line 366 of file types.F90.
integer(kind=t_int) types::t_netcdf_file::iydimid
Definition at line 351 of file types.F90.
integer (kind=t_int) types::t_model_configuration::iyear
Definition at line 709 of file types.F90.
Referenced by day_of_year(), et_thornthwaite_mather::et_tm_initialize(), gregorian_date(), model::if_getdynamiclandusevalue(), julian_day(), lookupmonth(), mmddyyyy2doy(), mmddyyyy2julian(), model::model_getdailyprecipvalue(), model::model_getdailytemperaturevalue(), model::model_processsm(), model::model_writegrids(), netcdf_support::netcdf_info(), netcdf_support::netcdf_write_attributes(), num_days_in_year(), sm_thornthwaite_mather::sm_thornthwaite_mather_updatesm(), solstice(), stats::stats_dumpannualaccumulatorvalues(), stats::stats_rewritegrids(), stats::stats_write_to_ssf_file(), stats::stats_writeannualaccumulatorvaluescsv(), stats::stats_writedailyaccumulatorvaluescsv(), and stats::stats_writemsbreport().
integer (kind=t_int) types::t_time_series_file::iyear
Definition at line 900 of file types.F90.
integer(kind=t_int) types::t_netcdf_file::iyvarid
Definition at line 348 of file types.F90.
integer (kind=t_int), parameter types::izero 0
Definition at line 92 of file types.F90.
Referenced by model::model_processrain(), and sm_thornthwaite_mather::sm_thornthwaite_mather_updatesm().
integer (kind=t_int) types::t_model_configuration::izonenumber 0
Definition at line 858 of file types.F90.
integer (kind=t_int) types::t_netcdf_file::izonenumber 0
Definition at line 376 of file types.F90.
Referenced by netcdf_support::lltoutm().
logical (kind=t_logical) types::t_stats::lactive
Definition at line 430 of file types.F90.
logical (kind=t_logical) types::t_model_configuration::lansi_colors lFALSE
Definition at line 694 of file types.F90.
logical (kind=t_logical) types::t_cell::ldownhillmarked
Definition at line 198 of file types.F90.
logical (kind=t_logical) types::t_model_configuration::ldownhillroutingtableexists lFALSE
Definition at line 724 of file types.F90.
logical (kind=t_logical) types::t_model_configuration::lelevadjustment
Definition at line 839 of file types.F90.
logical (kind=t_logical) types::t_graph_configuration::lenabledislinmessages lTRUE
Definition at line 946 of file types.F90.
logical (kind=t_logical) types::t_time_series_file::leof lFALSE
Definition at line 909 of file types.F90.
Referenced by rle::rle_readbyte(), and stats::stats_rewritegrids().
logical (kind=t_logical), parameter types::lfalse .false._T_LOGICAL
Definition at line 94 of file types.F90.
Referenced by control::control_setmodeloptions(), swb_grid::grid_conform(), swb_grid::grid_destroy(), swb_grid::grid_read(), swb_grid::grid_read_sub(), swb_grid::grid_readarcgrid_fn(), swb_grid::grid_readarcgrid_sub(), swb_grid::grid_readsurfergrid_fn(), swb_grid::grid_readsurfergrid_sub(), model::if_getdynamiclandusevalue(), graph::make_shaded_contour(), graph::makegraph(), model::model_configurerunoffdownhill(), model::model_getdailyprecipvalue(), model::model_getdailytemperaturevalue(), model::model_initializemaxinfil(), model::model_initializesm(), model::model_processrain(), model::model_processrunoff(), model::model_readbasinmasktable(), model::model_readirrigationlookuptable(), model::model_readlanduselookuptable(), model::model_readtimeseriesfile(), model::model_solve(), netcdf_support::netcdf_check(), netcdf_support::netcdf_chk_extent(), netcdf_support::netcdf_info(), model::rf_model_cellrunoff_greenampt(), rle::rle_readbyte(), rle::rle_writebyte(), runoff_curve_number::runoff_cellrunoff_curvenumber(), runoff_curve_number::runoff_initializecurvenumber(), sm_thornthwaite_mather::sm_thornthwaite_mather_updatesm(), and stats::stats_initializevolumeconversion().
logical (kind=t_logical) types::t_model_configuration::lfirstdayofsimulation lTRUE
Definition at line 706 of file types.F90.
logical (kind=t_logical) types::t_model_configuration::lfirstyearofsimulation lTRUE
Definition at line 705 of file types.F90.
logical (kind=t_logical) types::t_model_configuration::lgriddeddata lFALSE
Definition at line 719 of file types.F90.
logical (kind=t_logical) types::t_model_configuration::lhaltifmissingclimatedata lTRUE
Definition at line 721 of file types.F90.
logical(kind=t_logical) types::t_netcdf_file::linterpolate lFALSE
Definition at line 367 of file types.F90.
logical (kind=t_logical) types::t_model_configuration::lnorthernhemisphere lTRUE
Definition at line 792 of file types.F90.
logical (kind=t_logical) types::t_model_configuration::lreportdaily
Definition at line 795 of file types.F90.
logical(kind=t_logical) types::t_stats::lshowdailysum
Definition at line 428 of file types.F90.
logical(kind=t_logical) types::t_stats::lshowsum
Definition at line 426 of file types.F90.
logical (kind=t_logical), parameter types::ltrue .true._T_LOGICAL
Definition at line 93 of file types.F90.
Referenced by control::control_setmodeloptions(), swb_grid::grid_conform(), swb_grid::grid_readarcgrid_fn(), swb_grid::grid_readarcgrid_sub(), model::model_configurerunoffdownhill(), model::model_initializemaxinfil(), model::model_initializesm(), model::model_processrain(), model::model_readtimeseriesfile(), netcdf_support::netcdf_info(), rle::rle_readbyte(), rle::rle_writebyte(), and runoff_curve_number::runoff_initializecurvenumber().
type (t_landuse_lookup), dimension(:), pointer types::t_model_configuration::lu
Definition at line 806 of file types.F90.
integer (kind=t_int), parameter types::lu_bin_file 24
Definition at line 47 of file types.F90.
integer (kind=t_int), parameter types::lu_control 12
Definition at line 41 of file types.F90.
Referenced by control::control_setmodeloptions().
integer (kind=t_int), parameter types::lu_csv_annual 34
Definition at line 52 of file types.F90.
Referenced by model::model_endofrun(), and model::model_solve().
integer (kind=t_int), parameter types::lu_csv_max 32
Definition at line 51 of file types.F90.
Referenced by model::model_endofrun(), and model::model_solve().
integer (kind=t_int), parameter types::lu_csv_mean 30
Definition at line 50 of file types.F90.
Referenced by model::model_endofrun(), and model::model_solve().
integer (kind=t_int), parameter types::lu_csv_min 28
Definition at line 49 of file types.F90.
Referenced by model::model_endofrun(), and model::model_solve().
integer (kind=t_int), parameter types::lu_grid 14
Definition at line 42 of file types.F90.
Referenced by swb_grid::grid_readarcgrid_fn(), swb_grid::grid_readarcgrid_sub(), swb_grid::grid_readsurfergrid_fn(), and swb_grid::grid_readsurfergrid_sub().
integer (kind=t_int), parameter types::lu_log 48
Definition at line 59 of file types.F90.
Referenced by control::control_setmodeloptions(), et_blaney_criddle::et_bc_configure(), et_blaney_criddle::et_bc_initialize(), et_hargreaves::et_hargreaves_configure(), et_hargreaves::et_hargreaves_initialize(), et_jensen_haise::et_jh_configure(), et_jensen_haise::et_jh_initialize(), et_thornthwaite_mather::et_tm_configure(), et_thornthwaite_mather::et_tm_initialize(), et_turc::et_turc_configure(), et_turc::et_turc_initialize(), swb_grid::grid_create(), swb_grid::grid_readarcgrid_fn(), swb_grid::grid_readarcgrid_sub(), model::if_getdynamiclandusevalue(), main(), model::model_configurerunoffdownhill(), model::model_endofrun(), model::model_initializeet(), model::model_initializeflowdirection(), model::model_initializemaxinfil(), model::model_readbasinmasktable(), model::model_readirrigationlookuptable(), model::model_readlanduselookuptable(), model::model_readtimeseriesfile(), model::model_solve(), model::model_write_netcdf_attributes(), netcdf_support::netcdf_chk_extent(), netcdf_support::netcdf_create(), netcdf_support::netcdf_info(), netcdf_support::netcdf_open(), rle::rle_writebyte(), runoff_curve_number::runoff_initializecurvenumber(), sm_thornthwaite_mather::sm_thornthwaite_mather_configure(), sm_thornthwaite_mather::sm_thornthwaite_mather_initialize(), sm_thornthwaite_mather::sm_thornthwaite_mather_updatesm(), stats::stats_calcbasinstats(), stats::stats_calcmeanrecharge(), stats::stats_calcmeanrechargebylu(), stats::stats_closebinaryfiles(), stats::stats_openbinaryfiles(), stats::stats_openbinaryfilesreadonly(), and stats::stats_rewritegrids().
integer (kind=t_int), parameter types::lu_lookup 16
Definition at line 43 of file types.F90.
Referenced by model::model_readirrigationlookuptable(), and model::model_readlanduselookuptable().
integer (kind=t_int), parameter types::lu_mask 36
Definition at line 53 of file types.F90.
Referenced by model::model_readbasinmasktable().
integer (kind=t_int), parameter types::lu_mask_file 38
Definition at line 54 of file types.F90.
Referenced by stats::stats_calcbasinstats().
integer (kind=t_int), parameter types::lu_mask_stats_csv 40
Definition at line 55 of file types.F90.
Referenced by stats::stats_calcbasinstats().
integer (kind=t_int), parameter types::lu_msb_report 22
Definition at line 46 of file types.F90.
Referenced by model::model_endofrun(), stats::stats_openmsbreport(), and stats::stats_writemsbreport().
integer (kind=t_int), parameter types::lu_pest_ins 46
Definition at line 58 of file types.F90.
Referenced by stats::stats_calcbasinstats().
integer (kind=t_int), parameter types::lu_pest_obs 44
Definition at line 57 of file types.F90.
Referenced by stats::stats_calcbasinstats().
integer (kind=t_int), parameter types::lu_pest_stats 42
Definition at line 56 of file types.F90.
Referenced by stats::stats_calcbasinstats().
integer (kind=t_int), parameter types::lu_routing 26
Definition at line 48 of file types.F90.
Referenced by model::model_configurerunoffdownhill().
integer (kind=t_int), parameter types::lu_std_out 6
Definition at line 40 of file types.F90.
Referenced by model::model_configurerunoffdownhill(), model::model_solve(), stats::stats_dumpannualaccumulatorvalues(), stats::stats_dumpdailyaccumulatorvalues(), and stats::stats_dumpmonthlyaccumulatorvalues().
integer (kind=t_int), parameter types::lu_temp 20
Definition at line 45 of file types.F90.
Referenced by et_thornthwaite_mather::et_tm_initialize(), swb_grid::grid_writearcgrid(), and swb_grid::grid_writesurfergrid().
integer (kind=t_int), parameter types::lu_ts 18
Definition at line 44 of file types.F90.
Referenced by control::control_setmodeloptions(), model::model_endofrun(), model::model_readtimeseriesfile(), and model::model_solve().
logical (kind=t_logical) types::t_model_configuration::luseswbread lFALSE
Definition at line 720 of file types.F90.
logical (kind=t_logical) types::t_model_configuration::lwriteextrapestfiles lFALSE
Definition at line 690 of file types.F90.
logical (kind=t_logical) types::t_model_configuration::lwritetoscreen
Definition at line 796 of file types.F90.
logical(kind=t_logical) types::t_netcdf_file::lyvarbeforexvar lTRUE
Definition at line 349 of file types.F90.
real (kind=t_sgl), dimension(:,:), pointer types::t_model_configuration::max_recharge
Definition at line 820 of file types.F90.
type (t_netcdf_file), dimension(:,:), pointer types::t_model_configuration::netcdf_file
Definition at line 852 of file types.F90.
integer (kind=t_int), parameter types::output_arc 1
Definition at line 1031 of file types.F90.
Referenced by control::control_setmodeloptions(), and model::model_writegrids().
integer (kind=t_int), parameter types::output_surfer 0
Definition at line 1030 of file types.F90.
Referenced by control::control_setmodeloptions(), model::model_writegrids(), and stats::stats_rewritegrids().
type(t_general_grid), pointer types::t_basin_mask::pgrd
Definition at line 316 of file types.F90.
Referenced by control::control_setmodeloptions(), et_blaney_criddle::et_bc_computeet(), et_hargreaves::et_hargreaves_computeet(), et_jensen_haise::et_jh_computeet(), et_thornthwaite_mather::et_tm_computeet(), et_turc::et_turc_computeet(), swb_grid::grid_create(), swb_grid::grid_destroy(), swb_grid::grid_getgridcolnum(), swb_grid::grid_getgridrownum(), swb_grid::grid_getgridx(), swb_grid::grid_getgridy(), swb_grid::grid_interpolate(), swb_grid::grid_lookupcolumn(), swb_grid::grid_lookupreal(), swb_grid::grid_lookuprow(), swb_grid::grid_read(), swb_grid::grid_read_sub(), swb_grid::grid_readarcgrid_fn(), swb_grid::grid_readarcgrid_sub(), swb_grid::grid_readsurfergrid_fn(), swb_grid::grid_readsurfergrid_sub(), swb_grid::grid_searchcolumn(), model::if_getdynamiclandusevalue(), model::if_model_runoffiteration(), graph::make_shaded_contour(), graph::makegraph(), model::model_configurerunoffdownhill(), model::model_downstreamcell(), model::model_endofrun(), model::model_getdailyprecipvalue(), model::model_getdailytemperaturevalue(), model::model_initializeet(), model::model_initializeflowdirection(), model::model_initializegrowingdegreeday(), model::model_initializemaxinfil(), model::model_initializesm(), model::model_processet(), model::model_processrain(), model::model_processrainprms(), model::model_processrunoff(), model::model_processsm(), model::model_runoff_norouting(), model::model_runoffdownhill(), model::model_solve(), model::model_updatecontinuousfrozengroundindex(), model::model_updategrowingdegreeday(), model::model_write_netcdf_attributes(), model::model_writegrids(), netcdf_support::netcdf_chk_extent(), netcdf_support::netcdf_read(), netcdf_support::netcdf_write_attributes(), netcdf_support::netcdf_write_variable(), netcdf_support::netcdf_write_variable_byte(), runoff_curve_number::runoff_initializecurvenumber(), sm_thornthwaite_mather::sm_thornthwaite_mather_initialize(), sm_thornthwaite_mather::sm_thornthwaite_mather_updatepctsm(), sm_thornthwaite_mather::sm_thornthwaite_mather_updatesm(), stats::stats_calcbasinstats(), stats::stats_calcmeanrecharge(), stats::stats_calcmeanrechargebylu(), stats::stats_initializevolumeconversion(), stats::stats_openbinaryfiles(), stats::stats_rewritegrids(), stats::stats_writemsbreport(), and irrigation::update_irrigation_amounts().
real (kind=t_dbl) types::t_netcdf_file::raddoffset 0_T_DBL
Definition at line 369 of file types.F90.
real (kind=t_sgl) types::t_cell::radjcn
Definition at line 163 of file types.F90.
real (kind=t_sgl) types::t_irrigation_lookup::ralpha1 0.65
Definition at line 288 of file types.F90.
Referenced by meteorological_functions::calc_crop_coefficient().
real (kind=t_sgl) types::t_time_series_file::ravgt
Definition at line 901 of file types.F90.
Referenced by et_thornthwaite_mather::et_tm_initialize(), and model::model_getdailytemperaturevalue().
real (kind=t_sgl) types::t_cell::rbasecn
Definition at line 162 of file types.F90.
real (kind=t_sgl), parameter types::rbigval HUGE(rZERO)
Definition at line 96 of file types.F90.
Referenced by control::control_setmodeloptions(), and netcdf_support::netcdf_read().
real (kind=t_sgl) types::t_cell::rcfgi rZERO
Definition at line 181 of file types.F90.
Referenced by runoff_curve_number::prob_runoff_enhancement().
real (kind=t_sgl), parameter types::rcm_per_inch 2.54_T_SGL
Definition at line 81 of file types.F90.
Referenced by model::model_processrainprms(), and model::model_updatecontinuousfrozengroundindex().
real (kind=t_sgl) types::t_cell::rdailyrecharge
Definition at line 192 of file types.F90.
real (kind=t_sgl), dimension(:,:), pointer types::t_general_grid::rdata
Definition at line 224 of file types.F90.
Referenced by stats::stats_writeminmeanmax().
real (kind=t_sgl) types::t_basin_mask::rdrainagearea
Definition at line 319 of file types.F90.
real (kind=t_sgl) types::t_model_configuration::rdry_dormant 0.50_T_SGL
Definition at line 780 of file types.F90.
real (kind=t_sgl) types::t_model_configuration::rdry_growing 1.40_T_SGL
Definition at line 782 of file types.F90.
real (kind=t_sgl) types::t_cell::relevation rZERO
Definition at line 141 of file types.F90.
Referenced by meteorological_functions::clear_sky_solar_radiation_noab_rso().
real (kind=t_sgl) types::t_model_configuration::relevdryfactor
Definition at line 841 of file types.F90.
real (kind=t_sgl) types::t_model_configuration::relevhumidfactor
Definition at line 842 of file types.F90.
real (kind=t_sgl) types::t_model_configuration::relevhumiditythreshold
Definition at line 843 of file types.F90.
real (kind=t_sgl) types::t_model_configuration::relevstationelevation
Definition at line 840 of file types.F90.
real (kind=t_sgl) types::t_model_configuration::ret_constant 17.8
Definition at line 739 of file types.F90.
real (kind=t_sgl) types::t_model_configuration::ret_exponent 0.5
Definition at line 738 of file types.F90.
real (kind=t_sgl) types::t_model_configuration::ret_slope 0.0023
Definition at line 737 of file types.F90.
real (kind=t_dbl) types::t_model_configuration::rfalseeasting 520000_T_DBL
Definition at line 854 of file types.F90.
real (kind=t_dbl) types::t_netcdf_file::rfalseeasting 520000_T_DBL
Definition at line 372 of file types.F90.
real (kind=t_dbl) types::t_model_configuration::rfalsenorthing -4480000_T_DBL
Definition at line 855 of file types.F90.
real (kind=t_dbl) types::t_netcdf_file::rfalsenorthing -4480000_T_DBL
Definition at line 373 of file types.F90.
real (kind=t_sgl) types::t_cell::rflowoutofgrid
Definition at line 167 of file types.F90.
real (kind=t_sgl), parameter types::rfreezing 32.0_T_SGL
Definition at line 74 of file types.F90.
Referenced by et_blaney_criddle::et_bc_computeet(), et_jensen_haise::et_jh_computeet(), et_thornthwaite_mather::et_tm_computeet(), et_thornthwaite_mather::et_tm_initialize(), et_turc::et_turc_computeet(), model::model_processrain(), and model::model_updatecontinuousfrozengroundindex().
real (kind=t_sgl) types::t_cell::rgdd rZERO
Definition at line 185 of file types.F90.
Referenced by meteorological_functions::calc_crop_coefficient().
real (kind=t_sgl) types::t_irrigation_lookup::rgdd_basetemp 50.
Definition at line 291 of file types.F90.
real (kind=t_sgl) types::t_irrigation_lookup::rgdd_death 2000
Definition at line 284 of file types.F90.
real (kind=t_sgl) types::t_irrigation_lookup::rgdd_kc_max 1400
Definition at line 281 of file types.F90.
real (kind=t_sgl) types::t_irrigation_lookup::rgdd_maxtemp 130.
Definition at line 294 of file types.F90.
real (kind=t_sgl) types::t_cell::rgdd_tbase 50.
Definition at line 183 of file types.F90.
real (kind=t_sgl) types::t_cell::rgdd_tmax 150.
Definition at line 184 of file types.F90.
real (kind=t_sgl) types::t_general_grid::rgridcellsize
Definition at line 219 of file types.F90.
Referenced by control::control_setmodeloptions(), and stats::stats_openbinaryfilesreadonly().
real(kind=t_sgl) types::t_netcdf_file::rgridcellsize
Definition at line 364 of file types.F90.
real (kind=t_sgl) types::t_cell::rgrossprecip
Definition at line 169 of file types.F90.
real (kind=t_sgl), parameter types::rhalf 0.5_T_SGL
Definition at line 70 of file types.F90.
Referenced by swb_grid::grid_readarcgrid_fn(), and swb_grid::grid_readarcgrid_sub().
real (kind=t_sgl), parameter types::rhundred 100.0_T_SGL
Definition at line 76 of file types.F90.
Referenced by et_blaney_criddle::et_bc_computeet(), et_jensen_haise::et_jh_computeet(), et_turc::et_turc_computeet(), runoff_curve_number::runoff_updatecurvenumber(), sm_thornthwaite_mather::sm_thornthwaite_mather_initialize(), and sm_thornthwaite_mather::sm_thornthwaite_mather_updatesm().
real (kind=t_sgl) types::t_cell::rinflow
Definition at line 165 of file types.F90.
real (kind=t_sgl) types::t_landuse_lookup::rintercept_growingseason
Definition at line 254 of file types.F90.
real (kind=t_sgl) types::t_landuse_lookup::rintercept_nongrowingseason
Definition at line 256 of file types.F90.
real (kind=t_sgl) types::t_cell::rirrigationamount rZERO
Definition at line 186 of file types.F90.
Referenced by irrigation::update_irrigation_amounts().
real (kind=t_sgl) types::t_model_configuration::riterationtolerance 1.0E-6
Definition at line 803 of file types.F90.
real (kind=t_sgl) types::t_irrigation_lookup::rk0 0.2
Definition at line 278 of file types.F90.
Referenced by meteorological_functions::calc_crop_coefficient(), netcdf_support::lltoutm(), and netcdf_support::utmtoll().
real (kind=t_sgl) types::t_irrigation_lookup::rkc_max 1.3
Definition at line 275 of file types.F90.
Referenced by meteorological_functions::calc_crop_coefficient().
real (kind=t_dbl) types::t_model_configuration::rlatorigin 0_T_DBL
Definition at line 857 of file types.F90.
real (kind=t_dbl) types::t_netcdf_file::rlatorigin 0_T_DBL
Definition at line 375 of file types.F90.
real (kind=t_sgl) types::t_model_configuration::rll_cfgi 9999.0
Definition at line 826 of file types.F90.
real (kind=t_dbl) types::t_model_configuration::rlongorigin -90_T_DBL
Definition at line 856 of file types.F90.
real (kind=t_dbl) types::t_netcdf_file::rlongorigin -90_T_DBL
Definition at line 374 of file types.F90.
Referenced by netcdf_support::lltoutm().
real (kind=t_sgl) types::t_irrigation_lookup::rmad 100.
Definition at line 297 of file types.F90.
real (kind=t_sgl) types::t_basin_mask::rmax
Definition at line 322 of file types.F90.
Referenced by model::model_getdailyprecipvalue(), stats::stats_calcbasinstats(), and stats::stats_updateallaccumulatorsbygrid().
real (kind=t_sgl) types::t_cell::rmaxrecharge
Definition at line 149 of file types.F90.
real (kind=t_sgl) types::t_time_series_file::rmaxt
Definition at line 904 of file types.F90.
Referenced by et_thornthwaite_mather::et_tm_initialize(), and model::model_getdailytemperaturevalue().
real (kind=t_sgl) types::t_basin_mask::rmean
Definition at line 323 of file types.F90.
Referenced by model::model_getdailyprecipvalue(), and stats::stats_updateallaccumulatorsbygrid().
real (kind=t_sgl) types::t_basin_mask::rmin
Definition at line 321 of file types.F90.
Referenced by model::model_getdailyprecipvalue(), stats::stats_calcbasinstats(), and stats::stats_updateallaccumulatorsbygrid().
real (kind=t_sgl) types::t_time_series_file::rminrh
Definition at line 907 of file types.F90.
Referenced by et_blaney_criddle::et_bc_computeet(), et_jensen_haise::et_jh_computeet(), et_thornthwaite_mather::et_tm_initialize(), meteorological_functions::minimum_rel_hum(), and model::model_processet().
real (kind=t_sgl) types::t_time_series_file::rmint
Definition at line 905 of file types.F90.
Referenced by et_thornthwaite_mather::et_tm_initialize(), and model::model_getdailytemperaturevalue().
real (kind=t_sgl) types::t_model_configuration::rminvalidprecip 0.
Definition at line 746 of file types.F90.
real (kind=t_sgl) types::t_model_configuration::rminvalidtemp -100.0
Definition at line 747 of file types.F90.
real (kind=t_sgl), parameter types::rmm_per_inch 25.4_T_SGL
Definition at line 80 of file types.F90.
Referenced by et_hargreaves::et0_hargreaves(), et_blaney_criddle::et_bc_computeet(), and model::model_processrain().
real (kind=t_sgl) types::t_cell::rmsb
Definition at line 195 of file types.F90.
real (kind=t_dbl) types::t_stats::rnc_addoffset
Definition at line 438 of file types.F90.
real (kind=t_dbl) types::t_stats::rnc_multfactor
Definition at line 436 of file types.F90.
real (kind=t_sgl), parameter types::rnear_zero 1E-9_T_SGL
Definition at line 68 of file types.F90.
Referenced by control::control_setmodeloptions(), model::model_processet(), model::model_processrainprms(), model::model_runoffdownhill(), runoff_curve_number::runoff_updatecurvenumber(), sm_thornthwaite_mather::sm_thornthwaite_mather_initialize(), sm_thornthwaite_mather::sm_thornthwaite_mather_updatepctsm(), sm_thornthwaite_mather::sm_thornthwaite_mather_updatesm(), stats::stats_calcmeanrecharge(), and stats::stats_formattextstring().
real (kind=t_sgl), dimension(imoving_avg_terms) types::t_cell::rnetinflowbuf
Definition at line 191 of file types.F90.
real (kind=t_sgl) types::t_cell::rnetprecip
Definition at line 171 of file types.F90.
Referenced by snow::snow_energy_balance().
real (kind=t_sgl) types::t_model_configuration::rnorthernlatitude
Definition at line 835 of file types.F90.
real (kind=t_sgl), parameter types::rone 1.0_T_SGL
Definition at line 72 of file types.F90.
Referenced by control::control_setmodeloptions(), et_jensen_haise::et_jh_computeet(), et_turc::et_turc_computeet(), swb_grid::grid_interpolate(), swb_grid::grid_lookupcolumn(), swb_grid::grid_lookuprow(), swb_grid::grid_searchcolumn(), model::model_processrainprms(), model::model_runoffdownhill(), meteorological_functions::net_shortwave_radiation_rns(), netcdf_support::netcdf_write_attributes(), runoff_curve_number::prob_runoff_enhancement(), sm_thornthwaite_mather::sm_thornthwaite_mather_initialize(), and sm_thornthwaite_mather::sm_thornthwaite_mather_updatesm().
real (kind=t_sgl), dimension(:,:), pointer types::t_model_configuration::rooting_depth
Definition at line 823 of file types.F90.
real (kind=t_sgl) types::t_cell::routflow
Definition at line 166 of file types.F90.
Referenced by model::rf_model_cellrunoff(), model::rf_model_cellrunoff_greenampt(), and runoff_curve_number::runoff_cellrunoff_curvenumber().
real (kind=t_sgl) types::t_basin_mask::rpestweight 1.0
Definition at line 313 of file types.F90.
real (kind=t_sgl), parameter types::rpoint2 0.2_T_SGL
Definition at line 69 of file types.F90.
Referenced by runoff_curve_number::runoff_cellrunoff_curvenumber().
real (kind=t_sgl), parameter types::rpoint8 0.8_T_SGL
Definition at line 71 of file types.F90.
Referenced by runoff_curve_number::runoff_cellrunoff_curvenumber().
real (kind=t_sgl) types::t_time_series_file::rprecip
Definition at line 902 of file types.F90.
Referenced by et_thornthwaite_mather::et_tm_initialize(), and model::model_getdailyprecipvalue().
real (kind=t_sgl) types::t_basin_mask::rqb
Definition at line 318 of file types.F90.
real (kind=t_sgl) types::t_model_configuration::rrainfall_corr_factor 1.0
Definition at line 742 of file types.F90.
real (kind=t_sgl) types::t_time_series_file::rrh
Definition at line 903 of file types.F90.
Referenced by et_thornthwaite_mather::et_tm_initialize(), et_turc::et_turc_computeet(), model::model_getdailytemperaturevalue(), model::model_processet(), and meteorological_functions::sensible_heat_exchange_h().
real (kind=t_sgl) types::t_model_configuration::rrle_offset 0.
Definition at line 701 of file types.F90.
Referenced by rle::rle_writebyte(), and stats::stats_openbinaryfilesreadonly().
real (kind=t_sgl) types::t_cell::rroutefraction rONE
Definition at line 168 of file types.F90.
real (kind=t_dbl) types::t_netcdf_file::rscalefactor 1_T_DBL
Definition at line 368 of file types.F90.
real (kind=t_sgl) types::t_cell::rsm_accumpotentwatloss
Definition at line 147 of file types.F90.
real (kind=t_sgl) types::t_cell::rsm_potentialet
Definition at line 151 of file types.F90.
real (kind=t_sgl) types::t_cell::rsmax
Definition at line 164 of file types.F90.
real (kind=t_sgl) types::t_cell::rsnowalbedo
Definition at line 188 of file types.F90.
real (kind=t_sgl) types::t_cell::rsnowcover
Definition at line 174 of file types.F90.
Referenced by snow::snow_energy_balance().
real (kind=t_sgl) types::t_cell::rsnowfall
Definition at line 173 of file types.F90.
real (kind=t_sgl) types::t_cell::rsnowfall_swe
Definition at line 172 of file types.F90.
real (kind=t_sgl) types::t_model_configuration::rsnowfall_swe_corr_factor 1.0
Definition at line 743 of file types.F90.
real (kind=t_sgl) types::t_cell::rsnowmelt
Definition at line 177 of file types.F90.
real (kind=t_sgl) types::t_cell::rsnowtemperature 23.
Definition at line 175 of file types.F90.
Referenced by snow::snow_energy_balance().
real (kind=t_sgl) types::t_model_configuration::rsnwd_denom 2.6
Definition at line 756 of file types.F90.
real (kind=t_sgl) types::t_model_configuration::rsnwd_intcp1 67.9
Definition at line 755 of file types.F90.
real (kind=t_sgl) types::t_model_configuration::rsnwd_slp1 51.3
Definition at line 754 of file types.F90.
real (kind=t_sgl) types::t_cell::rsoilmoisture rZERO
Definition at line 144 of file types.F90.
real (kind=t_sgl) types::t_cell::rsoilmoisturepct
Definition at line 146 of file types.F90.
real (kind=t_sgl) types::t_cell::rsoilwatercap rZERO
Definition at line 143 of file types.F90.
real (kind=t_sgl) types::t_cell::rsoilwatercapinput rZERO
Definition at line 142 of file types.F90.
real (kind=t_sgl) types::t_model_configuration::rsouthernlatitude
Definition at line 834 of file types.F90.
real (kind=t_sgl) types::t_cell::rstreamcapture
Definition at line 156 of file types.F90.
real (kind=t_sgl), dimension(stream_interactions_max) types::t_model_configuration::rstreammaxcapture
Definition at line 891 of file types.F90.
real (kind=t_sgl), dimension(stream_interactions_max) types::t_model_configuration::rstreammaxinflow
Definition at line 890 of file types.F90.
real (kind=t_sgl) types::t_cell::rsum_recharge rZERO
Definition at line 193 of file types.F90.
real (kind=t_sgl) types::t_cell::rsum_rejectedrecharge rZERO
Definition at line 194 of file types.F90.
real (kind=t_sgl) types::t_time_series_file::rsunpct
Definition at line 908 of file types.F90.
Referenced by et_blaney_criddle::et_bc_computeet(), et_jensen_haise::et_jh_computeet(), et_thornthwaite_mather::et_tm_initialize(), et_turc::et_turc_computeet(), and model::model_processet().
real (kind=t_sgl) types::t_cell::rtavg
Definition at line 180 of file types.F90.
Referenced by meteorological_functions::convective_heat_exchange_e(), et_hargreaves::et0_hargreaves(), meteorological_functions::precipitation_heat_p(), meteorological_functions::sensible_heat_exchange_h(), snow::snow_depth_hedstrom(), and snow::snow_energy_balance().
real (kind=t_sgl), parameter types::rten 10.0_T_SGL
Definition at line 75 of file types.F90.
Referenced by runoff_curve_number::runoff_cellrunoff_curvenumber().
real (kind=t_sgl), parameter types::rthousand 1000.0_T_SGL
Definition at line 77 of file types.F90.
Referenced by runoff_curve_number::runoff_cellrunoff_curvenumber().
real (kind=t_sgl) types::t_cell::rtmax
Definition at line 179 of file types.F90.
Referenced by meteorological_functions::minimum_rel_hum(), model::model_updategrowingdegreeday(), meteorological_functions::net_longwave_radiation_rnl(), snow::snow_energy_balance(), and meteorological_functions::solar_radiation_hargreaves_rs().
real (kind=t_sgl) types::t_model_configuration::rtmaxallrain 40.0
Definition at line 751 of file types.F90.
real (kind=t_sgl) types::t_model_configuration::rtmaxallsnow 30.5
Definition at line 750 of file types.F90.
real (kind=t_sgl) types::t_cell::rtmin
Definition at line 178 of file types.F90.
Referenced by meteorological_functions::dewpoint_vapor_pressure_ea(), meteorological_functions::maximum_rel_hum(), meteorological_functions::minimum_rel_hum(), meteorological_functions::net_longwave_radiation_rnl(), snow::snow_energy_balance(), and meteorological_functions::solar_radiation_hargreaves_rs().
real (kind=t_sgl) types::t_model_configuration::rul_cfgi 9999.0
Definition at line 828 of file types.F90.
real (kind=t_sgl) types::t_model_configuration::rwet_dormant 1.10_T_SGL
Definition at line 781 of file types.F90.
real (kind=t_sgl) types::t_model_configuration::rwet_growing 2.10_T_SGL
Definition at line 783 of file types.F90.
real (kind=t_sgl) types::t_time_series_file::rwindspd
Definition at line 906 of file types.F90.
Referenced by meteorological_functions::convective_heat_exchange_e(), et_blaney_criddle::et_bc_computeet(), et_jensen_haise::et_jh_computeet(), et_thornthwaite_mather::et_tm_initialize(), model::model_processet(), and meteorological_functions::sensible_heat_exchange_h().
real (kind=t_dbl) types::t_general_grid::rx0
Definition at line 221 of file types.F90.
Referenced by control::control_setmodeloptions(), swb_grid::grid_create(), swb_grid::grid_readarcgrid_fn(), swb_grid::grid_readarcgrid_sub(), swb_grid::grid_readsurfergrid_fn(), swb_grid::grid_readsurfergrid_sub(), stats::stats_openbinaryfilesreadonly(), and stats::stats_rewritegrids().
real (kind=t_dbl) types::t_general_grid::rx1
Definition at line 221 of file types.F90.
Referenced by control::control_setmodeloptions(), swb_grid::grid_create(), swb_grid::grid_readarcgrid_fn(), swb_grid::grid_readarcgrid_sub(), swb_grid::grid_readsurfergrid_fn(), swb_grid::grid_readsurfergrid_sub(), stats::stats_openbinaryfilesreadonly(), and stats::stats_rewritegrids().
real(kind=t_dbl) types::t_netcdf_file::rx_lowerleft
Definition at line 360 of file types.F90.
real(kind=t_dbl) types::t_netcdf_file::rx_upperright
Definition at line 362 of file types.F90.
real (kind=t_dbl) types::t_general_grid::ry0
Definition at line 222 of file types.F90.
Referenced by control::control_setmodeloptions(), swb_grid::grid_create(), swb_grid::grid_readarcgrid_fn(), swb_grid::grid_readarcgrid_sub(), swb_grid::grid_readsurfergrid_fn(), swb_grid::grid_readsurfergrid_sub(), stats::stats_openbinaryfilesreadonly(), and stats::stats_rewritegrids().
real (kind=t_dbl) types::t_general_grid::ry1
Definition at line 222 of file types.F90.
Referenced by control::control_setmodeloptions(), swb_grid::grid_create(), swb_grid::grid_readarcgrid_fn(), swb_grid::grid_readarcgrid_sub(), swb_grid::grid_readsurfergrid_fn(), swb_grid::grid_readsurfergrid_sub(), stats::stats_openbinaryfilesreadonly(), and stats::stats_rewritegrids().
real(kind=t_dbl) types::t_netcdf_file::ry_lowerleft
Definition at line 361 of file types.F90.
real(kind=t_dbl) types::t_netcdf_file::ry_upperright
Definition at line 363 of file types.F90.
real(kind=t_sgl), dimension(3) types::t_graph_configuration::rza 0.
Definition at line 941 of file types.F90.
real(kind=t_sgl), dimension(3) types::t_graph_configuration::rze 10.
Definition at line 942 of file types.F90.
real (kind=t_sgl), parameter types::rzero 0.0_T_SGL
Definition at line 66 of file types.F90.
Referenced by control::control_setmodeloptions(), et_hargreaves::et0_hargreaves(), et_blaney_criddle::et_bc_computeet(), et_jensen_haise::et_jh_computeet(), et_thornthwaite_mather::et_tm_computeet(), et_thornthwaite_mather::et_tm_initialize(), et_turc::et_turc_computeet(), swb_grid::grid_create(), swb_grid::grid_lookupcolumn(), swb_grid::grid_lookuprow(), model::if_model_runoffiteration(), model::model_getdailyprecipvalue(), model::model_processet(), model::model_processrain(), model::model_processrainprms(), model::model_processrunoff(), model::model_runoff_norouting(), model::model_runoffdownhill(), model::model_updatecontinuousfrozengroundindex(), meteorological_functions::precipitation_heat_p(), runoff_curve_number::prob_runoff_enhancement(), model::rf_model_cellrunoff(), model::rf_model_getinterception(), runoff_curve_number::runoff_cellrunoff_curvenumber(), runoff_curve_number::runoff_updatecurvenumber(), sm_thornthwaite_mather::sm_thornthwaite_mather_apwl(), sm_thornthwaite_mather::sm_thornthwaite_mather_initialize(), sm_thornthwaite_mather::sm_thornthwaite_mather_soil_storage(), sm_thornthwaite_mather::sm_thornthwaite_mather_updatepctsm(), sm_thornthwaite_mather::sm_thornthwaite_mather_updatesm(), snow::snow_energy_balance(), stats::stats_initializeannualaccumulators(), stats::stats_initializedailyaccumulators(), stats::stats_initializemonthlyaccumulators(), stats::stats_rewritegrids(), and irrigation::update_irrigation_amounts().
real(kind=t_sgl), dimension(3) types::t_graph_configuration::rzor 0.
Definition at line 943 of file types.F90.
real(kind=t_sgl), dimension(3) types::t_graph_configuration::rzstep 1.
Definition at line 944 of file types.F90.
character (len=256) types::t_landuse_lookup::sassumedpercentimperviousness
Definition at line 252 of file types.F90.
character (len=1), parameter types::sbackslash achar(92)
Definition at line 99 of file types.F90.
character(len=256) types::t_basin_mask::sbasindescription
Definition at line 310 of file types.F90.
character (len=256) types::t_model_configuration::sbasinmaskfilename
Definition at line 770 of file types.F90.
character(len=256) types::t_basin_mask::sbasinmaskfilename
Definition at line 311 of file types.F90.
character (len=7), parameter types::sblue char(27)//'[1;34m'
Definition at line 123 of file types.F90.
character (len=7), parameter types::sboldwhite char(27)//'[1;37m'
Definition at line 126 of file types.F90.
Referenced by model::model_solve(), and stats::stats_formattextstring().
character (len=7), parameter types::sclrscr char(27)//'[2J'
Definition at line 127 of file types.F90.
character (len=7), parameter types::scyan char(27)//'[1;36m'
Definition at line 124 of file types.F90.
character (len=256) types::t_model_configuration::sdynamiclandusefileprefix
Definition at line 734 of file types.F90.
character(len=48) types::t_netcdf_file::sellipsoidname "GRS 1980"
Definition at line 377 of file types.F90.
character(len=48) types::t_model_configuration::sellipsoidname "GRS 1980"
Definition at line 859 of file types.F90.
character(len=64) types::t_netcdf_file::sfilename
Definition at line 338 of file types.F90.
character (len=128) types::t_ssf_files::sfilename
Definition at line 329 of file types.F90.
Referenced by assert_module_details_sub(), et_thornthwaite_mather::et_tm_initialize(), swb_grid::grid_read(), swb_grid::grid_read_sub(), swb_grid::grid_readarcgrid_fn(), swb_grid::grid_readarcgrid_sub(), swb_grid::grid_readsurfergrid_fn(), swb_grid::grid_readsurfergrid_sub(), and netcdf_support::netcdf_check().
character(len=256) types::t_basin_mask::sfiletype
Definition at line 312 of file types.F90.
Referenced by swb_grid::grid_read(), and swb_grid::grid_read_sub().
character (len=1), parameter types::sforwardslash achar(47)
Definition at line 100 of file types.F90.
character (len=9) types::t_month::sfullname
Definition at line 386 of file types.F90.
character (len=256) types::t_model_configuration::sfuturefileprefix ""
Definition at line 774 of file types.F90.
character (len=7), parameter types::sgreen char(27)//'[1;32m'
Definition at line 121 of file types.F90.
Referenced by stats::stats_dumpmonthlyaccumulatorvalues(), and stats::stats_formattextstring().
character (len=256) types::t_model_configuration::sirrigationlookupfilename
Definition at line 766 of file types.F90.
character (len=256) types::t_landuse_lookup::slandusedescription
Definition at line 250 of file types.F90.
character (len=256) types::t_model_configuration::slanduselookupfilename
Definition at line 762 of file types.F90.
character (len=256), public types::slogbuffer
Definition at line 409 of file types.F90.
character(len=64) types::t_stats::slongname
Definition at line 434 of file types.F90.
character (len=24) types::t_stats::smsb_note
Definition at line 448 of file types.F90.
character (len=3) types::t_month::sname
Definition at line 385 of file types.F90.
character (len=256) types::t_model_configuration::soutputfileprefix ""
Definition at line 773 of file types.F90.
character (len=256) types::t_model_configuration::soutputfilesuffix
Definition at line 777 of file types.F90.
character (len=256) types::t_basin_mask::spestgroup
Definition at line 314 of file types.F90.
character (len=256) types::t_model_configuration::sprecipfileprefix
Definition at line 727 of file types.F90.
character(len=48) types::t_model_configuration::sprojectionname "wtm"
Definition at line 853 of file types.F90.
character(len=24) types::t_netcdf_file::sprojectionname "wtm"
Definition at line 370 of file types.F90.
character(len=12) types::t_netcdf_file::sprojectionunits "meters"
Definition at line 371 of file types.F90.
character (len=7), parameter types::sred char(27)//'[1;31m'
Definition at line 120 of file types.F90.
Referenced by stats::stats_formattextstring().
type (t_ssf_files), dimension(:), pointer types::t_model_configuration::ssf_files
Definition at line 848 of file types.F90.
character(len=1) types::t_model_configuration::sslash sBACKSLASH
Definition at line 698 of file types.F90.
character (len=1), parameter types::stab achar(9)
Definition at line 97 of file types.F90.
Referenced by model::model_readbasinmasktable(), model::model_readirrigationlookuptable(), model::model_readlanduselookuptable(), and stats::stats_calcbasinstats().
type (t_stats), dimension(inum_variables) types::stat_info [
Definition at line 467 of file types.F90.
Referenced by control::control_setmodeloptions(), model::model_endofrun(), model::model_processrain(), model::model_processrainprms(), model::model_solve(), model::model_write_netcdf_attributes(), sm_thornthwaite_mather::sm_thornthwaite_mather_updatesm(), stats::stats_closebinaryfiles(), stats::stats_dumpannualaccumulatorvalues(), stats::stats_dumpdailyaccumulatorvalues(), stats::stats_dumpmonthlyaccumulatorvalues(), stats::stats_formattextstring(), stats::stats_openbinaryfiles(), stats::stats_openbinaryfilesreadonly(), stats::stats_rewritegrids(), stats::stats_writeannualaccumulatorheadercsv(), stats::stats_writeannualaccumulatorvaluescsv(), stats::stats_writedailyaccumulatorheadercsv(), and stats::stats_writedailyaccumulatorvaluescsv().
character(len=7), dimension(inum_stats), parameter types::stat_names [ "Minimum"
Definition at line 615 of file types.F90.
Referenced by stats::stats_writeannualaccumulatorheadercsv(), and stats::stats_writedailyaccumulatorheadercsv().
character (len=256) types::t_model_configuration::stimeseriesfilename
Definition at line 759 of file types.F90.
character (len=256) types::t_model_configuration::stmaxfileprefix
Definition at line 730 of file types.F90.
character (len=256) types::t_model_configuration::stminfileprefix
Definition at line 731 of file types.F90.
integer (kind=t_int), parameter types::stream_interactions_max 100
Definition at line 658 of file types.F90.
character (len=20) types::t_stats::sunits
Definition at line 432 of file types.F90.
character(len=24) types::t_netcdf_file::sunits
Definition at line 340 of file types.F90.
character(len=256) types::t_basin_mask::susgs_upstreamorderid
Definition at line 309 of file types.F90.
character (len=20) types::t_stats::svariable_name
Definition at line 418 of file types.F90.
character(len=24) types::t_netcdf_file::svarname ""
Definition at line 339 of file types.F90.
Referenced by netcdf_support::netcdf_info().
character(len=16), parameter, public types::swb_version "1.0.1"
Definition at line 22 of file types.F90.
Referenced by main().
character (len=7), parameter types::swhite char(27)//'[0;37m'
Definition at line 125 of file types.F90.
Referenced by model::model_solve(), stats::stats_dumpannualaccumulatorvalues(), stats::stats_dumpdailyaccumulatorvalues(), stats::stats_dumpmonthlyaccumulatorvalues(), and stats::stats_formattextstring().
character (len=2), parameter types::swhitespace achar(9)//" "
Definition at line 98 of file types.F90.
character (len=7), parameter types::syellow char(27)//'[1;33m'
Definition at line 122 of file types.F90.
Referenced by stats::stats_dumpannualaccumulatorvalues(), stats::stats_dumpdailyaccumulatorvalues(), and stats::stats_dumpmonthlyaccumulatorvalues().
integer, parameter, public types::t_byte 1
Definition at line 29 of file types.F90.
integer (kind=t_int), parameter, public types::t_cell_grid 2
Definition at line 204 of file types.F90.
Referenced by control::control_setmodeloptions(), swb_grid::grid_create(), swb_grid::grid_destroy(), graph::make_shaded_contour(), and graph::makegraph().
integer, parameter, public types::t_dbl SELECTED_REAL_KIND(p=13, r=200)
Definition at line 35 of file types.F90.
integer, parameter, public types::t_int 4
Definition at line 27 of file types.F90.
Referenced by control::control_setmodeloptions(), swb_grid::grid_getgridcolnum(), swb_grid::grid_getgridrownum(), model::model_initializemaxinfil(), model::model_initializesm(), stats::stats_calcbasinstats(), and stats::stats_calcmeanrechargebylu().
integer (kind=t_int), parameter, public types::t_int_grid 0
Definition at line 202 of file types.F90.
Referenced by control::control_setmodeloptions(), swb_grid::grid_create(), swb_grid::grid_destroy(), swb_grid::grid_readarcgrid_fn(), swb_grid::grid_readarcgrid_sub(), swb_grid::grid_readsurfergrid_fn(), swb_grid::grid_readsurfergrid_sub(), model::if_getdynamiclandusevalue(), graph::make_shaded_contour(), graph::makegraph(), and model::model_configurerunoffdownhill().
integer, parameter, public types::t_logical 4
Definition at line 26 of file types.F90.
integer, parameter, public types::t_sgl SELECTED_REAL_KIND(p=6, r=37)
Definition at line 34 of file types.F90.
integer, parameter, public types::t_sgl_dislin 4
Definition at line 30 of file types.F90.
integer (kind=t_int), parameter, public types::t_sgl_grid 1
Definition at line 203 of file types.F90.
Referenced by control::control_setmodeloptions(), swb_grid::grid_create(), swb_grid::grid_destroy(), swb_grid::grid_readarcgrid_fn(), swb_grid::grid_readarcgrid_sub(), swb_grid::grid_readsurfergrid_fn(), swb_grid::grid_readsurfergrid_sub(), graph::make_shaded_contour(), graph::makegraph(), model::model_solve(), sm_thornthwaite_mather::sm_thornthwaite_mather_configure(), stats::stats_calcbasinstats(), stats::stats_calcmeanrecharge(), stats::stats_calcmeanrechargebylu(), stats::stats_openbinaryfiles(), and stats::stats_rewritegrids().
integer, parameter, public types::t_short 2
Definition at line 28 of file types.F90.
type (t_month), dimension(12), target types::year_info (/ T_MONTH('JAN','JANUARY ', 1, 31, 1, 31), T_MONTH('FEB','FEBRUARY ', 32, 59, 2, 29), T_MONTH('MAR','MARCH ', 60, 90, 3, 31), T_MONTH('APR','APRIL ', 91, 120, 4, 30), T_MONTH('MAY','MAY ', 121, 151, 5, 31), T_MONTH('JUN','JUNE ', 152, 181, 6, 30), T_MONTH('JUL','JULY ', 182, 212, 7, 31), T_MONTH('AUG','AUGUST ', 213, 243, 8, 31), T_MONTH('SEP','SEPTEMBER', 244, 273, 9, 30), T_MONTH('OCT','OCTOBER ', 274, 304, 10, 31), T_MONTH('NOV','NOVEMBER ', 305, 334, 11, 30), T_MONTH('DEC','DECEMBER ', 335, 365, 12, 31) /)
Definition at line 394 of file types.F90.
Referenced by stats::stats_rewritegrids().
USGS Home Water Resources Biology Geography Geology Geospatial SWB Home Wisconsin WSC
Accessibility FOIA Privacy Policies and Notices
U.S. Department of the Interior | U.S. Geological Survey
URL: http://wi.water.usgs.gov/Soil_Water_Balance/SWB_code_docs/index.html
Page Contact Information: webmaster@wi.water.usgs.gov
Page Last Modified: Thu May 19 2011 14:11:32
Page generated with:
1.8.2