SOIL-WATER-BALANCE SOURCE CODE BROWSER- USGS Wisconsin Water Science Center
USGS Home
Contact USGS
Search USGS
Soil-Water-Balance Source Code Browser
stats
Functions/Subroutines
subroutine stats::stats_initializevolumeconversion (pGrd)
subroutine stats::stats_initializedailyaccumulators ()
subroutine stats::stats_initializemonthlyaccumulators ()
subroutine stats::stats_initializeannualaccumulators ()
subroutine stats::stats_formattextstring (sText, rValue, pConfig, iVarNum, sFormattedText)
subroutine stats::stats_writedailyaccumulatorvaluescsv (iLU, iMonth, iDay, iYear, iStatistic)
subroutine stats::stats_writeannualaccumulatorvaluescsv (iLU, iYear)
subroutine stats::stats_writedailyaccumulatorheadercsv (iLU, iStatistic)
subroutine stats::stats_writeannualaccumulatorheadercsv (iLU)
subroutine stats::stats_dumpdailyaccumulatorvalues (iLU, pConfig)
subroutine stats::stats_dumpmonthlyaccumulatorvalues (iLU, iMonth, sMonthName, pConfig)
subroutine stats::stats_dumpannualaccumulatorvalues (iLU, pConfig, iYear)
subroutine stats::stats_updateallaccumulatorsbycell (rValue, iVarNum, iMonthNum, iNumGridCells)
subroutine stats::stats_updateallaccumulatorsbygrid (rMin, rMean, rMax, rSum, iVarNum, iMonthNum)
subroutine stats::stats_calcmonthlymeans (iMonthNum, iDaysInMonth)
Calculates and writes out monthly min, max, and mean of 2D variable array.
subroutine stats::stats_writeminmeanmax (iLU, sText, rData, iCount)
Writes out the min, max, and mean of 2D variable array.
subroutine stats::stats_openmsbreport ()
subroutine stats::stats_writemsbreport (pGrd, iMonth, iDay, iYear, iDayOfYear)
subroutine stats::stats_rewritegrids (iNX, iNY, rX0, rY0, rX1, rY1, pConfig, pGraph)
subroutine stats::stats_calcbasinstats (pGrd, pConfig, pGraph)
subroutine stats::stats_calcmeanrecharge (pGrd, pConfig, pGraph)
subroutine stats::stats_calcmeanrechargebylu (pGrd, pConfig, pGraph)
subroutine stats::stats_write_to_ssf_file (pConfig, iSSFindex, iMonth, iDay, iYear, rValue)
subroutine stats::stats_setbinaryfileposition (pConfig, pGrd)
subroutine stats::stats_timestampbinaryfile (pConfig)
subroutine stats::stats_openbinaryfiles (pConfig, pGrd)
subroutine stats::stats_openbinaryfilesreadonly (pConfig, pGrd)
subroutine stats::stats_closebinaryfiles ()
Variables
real(kind=t_dbl), public stats::dpvolconvert
real(kind=t_dbl), dimension(inum_months,
inum_stats, inum_variables),
public stats::rmonthly
real(kind=t_dbl), dimension(inum_stats,
inum_variables), public stats::rdaily
real(kind=t_dbl), dimension(inum_stats,
inum_variables), public stats::rannual
Detailed Description
Function/Subroutine Documentation
subroutine stats::stats_calcbasinstats (type (t_general_grid), pointer pGrd, type (t_model_configuration), pointer pConfig, type (t_graph_configuration), dimension(:), pointer pGraph)
Definition at line 1076 of file stats.F90.
References types::datatype_real, swb_grid::grid_conform(), swb_grid::grid_read(), types::t_general_grid::inumgridcells, types::lu_log, types::lu_mask_file, types::lu_mask_stats_csv, types::lu_pest_ins, types::lu_pest_obs, types::lu_pest_stats, types::t_basin_mask::pgrd, types::t_basin_mask::rmax, types::t_basin_mask::rmin, types::stab, and types::t_int.
Referenced by control::control_setmodeloptions().
subroutine stats::stats_calcmeanrecharge (type (t_general_grid), pointer pGrd, type (t_model_configuration), pointer pConfig, type (t_graph_configuration), dimension(:), pointer pGraph)
Definition at line 1241 of file stats.F90.
References types::datatype_real, swb_grid::grid_writegrid(), types::irecharge, types::lu_log, graph::makegraph(), types::t_basin_mask::pgrd, types::rnear_zero, and stats_writeminmeanmax().
Referenced by control::control_setmodeloptions().
subroutine stats::stats_calcmeanrechargebylu (type (t_general_grid), pointer pGrd, type (t_model_configuration), pointer pConfig, type (t_graph_configuration), dimension(:), pointer pGraph)
Definition at line 1315 of file stats.F90.
References types::datatype_real, types::t_general_grid::inumgridcells, types::lu_log, types::t_basin_mask::pgrd, and types::t_int.
Referenced by control::control_setmodeloptions().
subroutine stats::stats_calcmonthlymeans (integer(kind=t_int), intent(in) iMonthNum, integer(kind=t_int), intent(in) iDaysInMonth)
Parameters
[in] iMonthNum Numerical index (1-12) of the month for which statistics are reported.
[in] iDaysInMonth Number of days in the reporting month.
Deprecated:
This subroutine will be eliminated in future version of SWB.
Definition at line 586 of file stats.F90.
subroutine stats::stats_closebinaryfiles ()
Definition at line 1694 of file stats.F90.
References types::inone, types::ascharacter::int2char(), types::inum_variables, types::lu_log, and types::stat_info.
Referenced by model::model_endofrun().
subroutine stats::stats_dumpannualaccumulatorvalues (integer (kind=t_int), intent(in) iLU, type (t_model_configuration), pointer pConfig, integer (kind=t_int), intent(in) iYear)
Definition at line 442 of file stats.F90.
References types::t_ssf_files::ilu, types::inum_variables, types::isum, types::lu_std_out, types::stat_info, stats_formattextstring(), types::swhite, and types::syellow.
Referenced by model::model_solve().
subroutine stats::stats_dumpdailyaccumulatorvalues (integer (kind=t_int), intent(in) iLU, type (t_model_configuration), pointer pConfig)
Definition at line 330 of file stats.F90.
References types::t_ssf_files::ilu, types::inum_variables, types::isum, types::lu_std_out, types::stat_info, stats_formattextstring(), types::swhite, and types::syellow.
Referenced by model::model_solve().
subroutine stats::stats_dumpmonthlyaccumulatorvalues (integer (kind=t_int), intent(in) iLU, integer (kind=t_int), intent(in) iMonth, character (len=3), intent(in) sMonthName, type (t_model_configuration), pointer pConfig)
Definition at line 383 of file stats.F90.
References types::t_ssf_files::ilu, types::t_month::imonth, types::inum_variables, types::isum, types::lu_std_out, types::sgreen, types::stat_info, stats_formattextstring(), types::swhite, and types::syellow.
Referenced by model::model_solve().
subroutine stats::stats_formattextstring (character(len=*), intent(in) sText, real(kind=t_sgl), dimension(:), intent(in) rValue, type (t_model_configuration), pointer pConfig, integer(kind=t_int), intent(in) iVarNum, character(len=256), dimension(size(rvalue)) sFormattedText)
Definition at line 107 of file stats.F90.
References types::imax, types::imin, types::isum, types::t_ssf_files::ivarnum, types::rnear_zero, types::sboldwhite, types::sgreen, types::sred, types::stat_info, and types::swhite.
Referenced by stats_dumpannualaccumulatorvalues(), stats_dumpdailyaccumulatorvalues(), and stats_dumpmonthlyaccumulatorvalues().
subroutine stats::stats_initializeannualaccumulators ()
Definition at line 100 of file stats.F90.
References types::rzero.
Referenced by model::model_solve().
subroutine stats::stats_initializedailyaccumulators ()
Definition at line 79 of file stats.F90.
References types::t_basin_mask::ilength, types::imax, types::imean, types::imin, types::isum, and types::rzero.
Referenced by model::model_solve().
subroutine stats::stats_initializemonthlyaccumulators ()
Definition at line 91 of file stats.F90.
References types::rzero.
Referenced by model::model_solve().
subroutine stats::stats_initializevolumeconversion (type (t_general_grid), pointer pGrd)
Definition at line 47 of file stats.F90.
References types::dpone, types::igrid_length_units_feet, types::igrid_length_units_meters, types::lfalse, and types::t_basin_mask::pgrd.
Referenced by model::model_initializeinputandoutput(), and model::model_solve().
subroutine stats::stats_openbinaryfiles (type (t_model_configuration), pointer pConfig, type (t_general_grid), pointer pGrd)
Definition at line 1559 of file stats.F90.
References types::datatype_real, types::dquote(), types::ienddate_pos, types::iendheader_pos, types::inone, types::ascharacter::int2char(), types::inum_variables, types::istartdate_pos, types::lu_log, types::nextunit(), types::t_basin_mask::pgrd, types::t_general_grid::sfilename, and types::stat_info.
Referenced by model::model_initializeinputandoutput().
subroutine stats::stats_openbinaryfilesreadonly (type (t_model_configuration), pointer pConfig, type (t_general_grid), pointer pGrd)
Definition at line 1628 of file stats.F90.
References types::t_general_grid::idatatype, types::ienddate_pos, types::iendheader_pos, types::t_general_grid::ilengthunits, types::inone, types::ascharacter::int2char(), types::inum_variables, types::t_general_grid::inx, types::t_general_grid::iny, types::istartdate_pos, types::lu_log, types::nextunit(), types::t_general_grid::rgridcellsize, types::t_general_grid::rx0, types::t_general_grid::rx1, types::t_general_grid::ry0, types::t_general_grid::ry1, and types::stat_info.
Referenced by stats_rewritegrids().
subroutine stats::stats_openmsbreport ()
Definition at line 646 of file stats.F90.
References types::lu_msb_report.
Referenced by model::model_initializeinputandoutput().
subroutine stats::stats_rewritegrids (integer (kind=t_int), intent(in) iNX, integer (kind=t_int), intent(in) iNY, real (kind=t_dbl), intent(in) rX0, real (kind=t_dbl), intent(in) rY0, real (kind=t_dbl), intent(in) rX1, real (kind=t_dbl), intent(in) rY1, type (t_model_configuration), pointer pConfig, type (t_graph_configuration), dimension(:), pointer pGraph)
Definition at line 759 of file stats.F90.
References types::datatype_real, swb_grid::grid_writegrid(), types::iboth, types::iendheader_pos, types::igraph, types::igrid, types::t_month::imonth, types::inone, types::inum_variables, types::t_general_grid::inumgridcells, types::t_general_grid::inx, types::t_general_grid::iny, types::lookupmonth(), types::lu_log, graph::makegraph(), types::t_basin_mask::pgrd, rle::rle_readbyte(), types::t_general_grid::rx0, types::t_general_grid::rx1, types::t_general_grid::ry0, types::t_general_grid::ry1, types::rzero, types::stat_info, and stats_openbinaryfilesreadonly().
Referenced by model::model_endofrun().
subroutine stats::stats_setbinaryfileposition (type (t_model_configuration), pointer pConfig, type (t_general_grid), pointer pGrd)
Definition at line 1503 of file stats.F90.
References types::inone, types::inum_variables, types::t_stats::ipos, types::istartdate_pos, types::lfalse, and types::stat_info.
subroutine stats::stats_timestampbinaryfile (type (t_model_configuration), pointer pConfig)
Definition at line 1537 of file stats.F90.
References types::inone, types::inum_variables, and types::stat_info.
subroutine stats::stats_updateallaccumulatorsbycell (real (kind=t_dbl), intent(in) rValue, integer (kind=t_int), intent(in) iVarNum, integer (kind=t_int), intent(in) iMonthNum, integer (kind=t_int), intent(in) iNumGridCells)
Definition at line 492 of file stats.F90.
References types::t_basin_mask::ilength, types::imax, types::imean, types::imin, types::t_general_grid::inumgridcells, types::isum, types::t_ssf_files::ivarnum, and types::t_int.
Referenced by model::model_processrain(), model::model_processrainprms(), output::output_finalize_accumulators(), and output::output_update_accumulators().
subroutine stats::stats_updateallaccumulatorsbygrid (real (kind=t_dbl), intent(in) rMin, real (kind=t_dbl), intent(in) rMean, real (kind=t_dbl), intent(in) rMax, real (kind=t_dbl), intent(in) rSum, integer (kind=t_int), intent(in) iVarNum, integer (kind=t_int), intent(in) iMonthNum)
Definition at line 546 of file stats.F90.
References types::imax, types::imean, types::imin, types::isum, types::t_ssf_files::ivarnum, types::t_basin_mask::rmax, types::t_basin_mask::rmean, and types::t_basin_mask::rmin.
Referenced by model::model_getdailyprecipvalue().
subroutine stats::stats_write_to_ssf_file (type (t_model_configuration), pointer pConfig, integer (kind=t_int), intent(in) iSSFindex, integer (kind=t_int), intent(in) iMonth, integer (kind=t_int), intent(in) iDay, integer (kind=t_int), intent(in) iYear, real (kind=t_sgl), intent(in) rValue)
Definition at line 1451 of file stats.F90.
References types::t_month::imonth, and types::ascharacter::int2char().
Referenced by output::output_to_ssf().
subroutine stats::stats_writeannualaccumulatorheadercsv (integer (kind=t_int), intent(in) iLU)
Definition at line 293 of file stats.F90.
References types::t_ssf_files::ilu, types::imean, types::inum_variables, types::isum, types::stat_info, and types::stat_names.
Referenced by model::model_initializeinputandoutput().
subroutine stats::stats_writeannualaccumulatorvaluescsv (integer (kind=t_int), intent(in) iLU, integer (kind=t_int), intent(in) iYear)
Definition at line 233 of file stats.F90.
References types::t_ssf_files::ilu, types::imean, types::inum_variables, types::isum, and types::stat_info.
Referenced by model::model_solve().
subroutine stats::stats_writedailyaccumulatorheadercsv (integer (kind=t_int), intent(in) iLU, integer (kind=t_int), intent(in) iStatistic)
Definition at line 258 of file stats.F90.
References types::t_ssf_files::ilu, types::inum_variables, types::stat_info, and types::stat_names.
Referenced by model::model_initializeinputandoutput().
subroutine stats::stats_writedailyaccumulatorvaluescsv (integer (kind=t_int), intent(in) iLU, integer (kind=t_int), intent(in) iMonth, integer (kind=t_int), intent(in) iDay, integer (kind=t_int), intent(in) iYear, integer (kind=t_int), intent(in) iStatistic)
Definition at line 188 of file stats.F90.
References types::t_ssf_files::ilu, types::imax, types::imean, types::imin, types::t_month::imonth, types::inum_variables, and types::stat_info.
Referenced by model::model_solve().
subroutine stats::stats_writeminmeanmax (integer (kind=t_int), intent(in) iLU, character (len=*) sText, real (kind=t_sgl), dimension(:,:) rData, integer (kind=t_int), optional iCount)
Parameters
[in] iLU Fortran logical unit number to write output to.
[in] sText Descriptive text associated with the statistics.
[in] rData 2-d array of values for which statistics are calculated.
[in] iCount {Optional} User-supplied divisor for use in calculating the mean.
Definition at line 611 of file stats.F90.
References types::t_ssf_files::ilu, types::t_general_grid::inumgridcells, and types::t_general_grid::rdata.
Referenced by control::control_setmodeloptions(), model::model_solve(), and stats_calcmeanrecharge().
subroutine stats::stats_writemsbreport (type (t_general_grid), pointer pGrd, integer (kind=t_int), intent(in) iMonth, integer (kind=t_int), intent(in) iDay, integer (kind=t_int), intent(in) iYear, integer (kind=t_int), intent(in) iDayOfYear)
Definition at line 689 of file stats.F90.
References types::iact_et, types::ichg_in_snow_cov, types::ichg_in_soil_moist, types::igross_precip, types::iinflow, types::iinterception, types::iirrigation_from_gw, types::iirrigation_from_sw, types::t_month::imonth, types::inet_rainfall, types::ioutflow, types::irecharge, types::irejected_recharge, types::irunoff_outside, types::isnowcover, types::isnowfall_swe, types::isnowmelt, types::isoil_moisture, types::istream_capture, types::isum, types::lu_msb_report, and types::t_basin_mask::pgrd.
Referenced by model::model_solve().
Variable Documentation
real (kind=t_dbl), public stats::dpvolconvert
Definition at line 31 of file stats.F90.
real (kind=t_dbl), dimension(inum_stats,inum_variables), public stats::rannual
Definition at line 40 of file stats.F90.
real (kind=t_dbl), dimension(inum_stats,inum_variables), public stats::rdaily
Definition at line 37 of file stats.F90.
real (kind=t_dbl), dimension(inum_months,inum_stats,inum_variables), public stats::rmonthly
Definition at line 34 of file stats.F90.
USGS Home Water Resources Biology Geography Geology Geospatial SWB Home Wisconsin WSC
Accessibility FOIA Privacy Policies and Notices
U.S. Department of the Interior | U.S. Geological Survey
URL: http://wi.water.usgs.gov/Soil_Water_Balance/SWB_code_docs/index.html
Page Contact Information: webmaster@wi.water.usgs.gov
Page Last Modified: Thu May 19 2011 14:11:32
Page generated with:
1.8.2