SWB: sm_thornthwaite_mather Module Reference
sm_thornthwaite_mather Module Reference
Functions/Subroutines
subroutine sm_thornthwaite_mather_Configure (sRecord)
subroutine sm_thornthwaite_mather_Initialize (pGrd, pConfig)
subroutine sm_thornthwaite_mather_UpdateSM (pGrd, pConfig, iDayOfYear, iDay, iMonth, iYear)
real(kind=T_SGL) sm_thornthwaite_mather_soil_storage (rSWC, rAPWL)
real(kind=T_SGL) sm_thornthwaite_mather_APWL (rSWC, rSoilStorage)
Variables
real(kind=T_SGL), parameter APWL_Cap = -40.69_T_SGL
type(T_GENERAL_GRID), pointer gWLT
real(kind=T_DBL), parameter rTM_slope_term = 0.4787691
real(kind=T_DBL), parameter rTM_exp_term = -1.036784
Function/Subroutine Documentation
real (kind=T_SGL) sm_thornthwaite_mather::sm_thornthwaite_mather_APWL (real (kind=T_SGL),intent(in) rSWC, real (kind=T_SGL),intent(in) rSoilStorage)
Definition at line 1122 of file sm_thornthwaite_mather.F90.
Referenced by sm_thornthwaite_mather_Initialize(), and sm_thornthwaite_mather_UpdateSM().
subroutine sm_thornthwaite_mather::sm_thornthwaite_mather_Configure (character (len=*),intent(inout) sRecord)
Definition at line 40 of file sm_thornthwaite_mather.F90.
subroutine sm_thornthwaite_mather::sm_thornthwaite_mather_Initialize (type (T_GENERAL_GRID),pointer pGrd, type (T_MODEL_CONFIGURATION),pointer pConfig)
Definition at line 68 of file sm_thornthwaite_mather.F90.
Referenced by model::model_InitializeSM().
real (kind=T_SGL) sm_thornthwaite_mather::sm_thornthwaite_mather_soil_storage (real (kind=T_SGL),intent(in) rSWC, real (kind=T_SGL),intent(in) rAPWL)
Definition at line 1104 of file sm_thornthwaite_mather.F90.
Referenced by sm_thornthwaite_mather_UpdateSM().
subroutine sm_thornthwaite_mather::sm_thornthwaite_mather_UpdateSM (type (T_GENERAL_GRID),pointer pGrd, type (T_MODEL_CONFIGURATION),pointer pConfig, integer (kind=T_INT),intent(in) iDayOfYear, integer (kind=T_INT),intent(in) iDay, integer (kind=T_INT),intent(in) iMonth, integer (kind=T_INT),intent(in) iYear)
Definition at line 143 of file sm_thornthwaite_mather.F90.
Referenced by model::model_ProcessSM().
Variable Documentation
real (kind=T_SGL),parameter sm_thornthwaite_mather::APWL_Cap = -40.69_T_SGL
Definition at line 26 of file sm_thornthwaite_mather.F90.
Referenced by sm_thornthwaite_mather_UpdateSM().
type (T_GENERAL_GRID),pointer sm_thornthwaite_mather::gWLT
Definition at line 31 of file sm_thornthwaite_mather.F90.
Referenced by sm_thornthwaite_mather_Configure(), sm_thornthwaite_mather_Initialize(), and sm_thornthwaite_mather_UpdateSM().
real (kind=T_DBL),parameter sm_thornthwaite_mather::rTM_exp_term = -1.036784
Definition at line 36 of file sm_thornthwaite_mather.F90.
real (kind=T_DBL),parameter sm_thornthwaite_mather::rTM_slope_term = 0.4787691
Definition at line 35 of file sm_thornthwaite_mather.F90.