SWB: model Module Reference
model Module Reference
Functions/Subroutines
subroutine model_Solve (pGrd, pConfig, pGraph)
subroutine model_EndOfRun (pGrd, pConfig, pGraph)
subroutine model_GetDynamicLanduseValue (pGrd, pConfig, iYear)
subroutine model_GetDailyPrecipValue (pGrd, pConfig, rPrecip, iMonth, iDay, iYear)
subroutine model_GetDailyTemperatureValue (pGrd, pConfig, rAvgT, rMinT, rMaxT, rRH, iMonth, iDay, iYear)
subroutine model_UpdateContinuousFrozenGroundIndex (pGrd, pConfig)
subroutine model_ProcessRain (pGrd, pConfig, iDayOfYear, iMonth)
subroutine model_ProcessRainPRMS (pGrd, pConfig, iDayOfYear, iMonth, iNumDaysInYear)
subroutine model_ProcessRunoff (pGrd, pConfig, iDayOfYear, iMonth)
subroutine model_ConfigureRunoffDownhill (pGrd, pConfig)
subroutine model_RunoffDownhill (pGrd, pConfig, iDayOfYear, iMonth)
subroutine model_Runoff_NoRouting (pGrd, pConfig, iDayOfYear, iMonth)
integer(kind=T_INT) if_model_RunoffIteration (pGrd, pConfig, iDayOfYear, iMonth)
real(kind=T_SGL) rf_model_CellRunoff (pConfig, cel, iDayOfYear)
real(kind=T_SGL) rf_model_CellRunoff_GreenAmpt (pConfig, cel, iDayOfYear)
subroutine model_InitializeFlowDirection (pGrd, pConfig)
subroutine model_DownstreamCell (pGrd, iRow, iCol, iTgt_Row, iTgt_Col)
subroutine model_ReadBasinMaskTable (pConfig)
subroutine model_ReadLanduseLookupTable (pConfig)
real(kind=T_SGL) rf_model_GetInterception (pConfig, iType, iDayOfYear)
subroutine model_InitializeET (pGrd, pConfig)
subroutine model_ProcessET (pGrd, pConfig, iDayOfYear, iNumDaysInYear, rRH, rMinRH, rWindSpd, rSunPct)
subroutine model_ProcessSM (pGrd, pConfig, iDayOfYear, iDay, iMonth, iYear)
subroutine model_InitializeSM (pGrd, pConfig)
subroutine model_InitializeMaxInfil (pGrd, pConfig)
subroutine model_WriteGrids (pGrd, pConfig, sMonthName, iDay, iMonth, iYear, iDayOfYear)
subroutine model_write_NetCDF_attributes (pConfig, pGrd)
subroutine model_ReadTimeSeriesFile (pTS)
Variables
integer(kind=T_INT) iDayCtr
integer(kind=T_INT) iOrderCount
integer(kind=T_INT), dimension(:),
allocatable iOrderCol
integer(kind=T_INT), dimension(:),
allocatable iOrderRow
real(kind=T_SGL) rStartTime
real(kind=T_SGL) rEndTime
Function/Subroutine Documentation
integer (kind=T_INT) model::if_model_RunoffIteration (type (T_GENERAL_GRID),pointer pGrd, type (T_MODEL_CONFIGURATION),pointer pConfig, integer (kind=T_INT),intent(in) iDayOfYear, integer (kind=T_INT),intent(in) iMonth)
Definition at line 2088 of file model.F90.
Referenced by model_ProcessRunoff().
subroutine model::model_ConfigureRunoffDownhill (type (T_GENERAL_GRID),pointer pGrd, type (T_MODEL_CONFIGURATION),pointer pConfig)
Definition at line 1649 of file model.F90.
Referenced by model_Solve().
subroutine model::model_DownstreamCell (type (T_GENERAL_GRID),pointer pGrd, integer (kind=T_INT),intent(in) iRow, integer (kind=T_INT),intent(in) iCol, integer (kind=T_INT),intent(out) iTgt_Row, integer (kind=T_INT),intent(out) iTgt_Col)
Definition at line 2460 of file model.F90.
Referenced by if_model_RunoffIteration(), model_ConfigureRunoffDownhill(), and model_RunoffDownhill().
subroutine model::model_EndOfRun (type (T_GENERAL_GRID),pointer pGrd, type (T_MODEL_CONFIGURATION),pointer pConfig, type (T_GRAPH_CONFIGURATION),dimension(:),pointer pGraph)
Definition at line 534 of file model.F90.
Referenced by control::control_setModelOptions().
subroutine model::model_GetDailyPrecipValue (type (T_GENERAL_GRID),pointer pGrd, type (T_MODEL_CONFIGURATION),pointer pConfig, real (kind=T_SGL),intent(in) rPrecip, integer (kind=T_INT),intent(in) iMonth, integer (kind=T_INT),intent(in) iDay, integer (kind=T_INT),intent(in) iYear)
Definition at line 700 of file model.F90.
Referenced by model_Solve().
subroutine model::model_GetDailyTemperatureValue (type (T_GENERAL_GRID),pointer pGrd, type (T_MODEL_CONFIGURATION),pointer pConfig, real (kind=T_SGL),intent(in) rAvgT, real (kind=T_SGL),intent(in) rMinT, real (kind=T_SGL),intent(in) rMaxT, real (kind=T_SGL),intent(in) rRH, integer (kind=T_INT),intent(in) iMonth, integer (kind=T_INT),intent(in) iDay, integer (kind=T_INT),intent(in) iYear)
Definition at line 809 of file model.F90.
Referenced by model_Solve().
subroutine model::model_GetDynamicLanduseValue (type (T_GENERAL_GRID),pointer pGrd, type (T_MODEL_CONFIGURATION),pointer pConfig, integer (kind=T_INT),intent(in) iYear)
Definition at line 622 of file model.F90.
Referenced by model_Solve().
subroutine model::model_InitializeET (type (T_GENERAL_GRID),pointer pGrd, type (T_MODEL_CONFIGURATION),pointer pConfig)
Definition at line 3043 of file model.F90.
Referenced by model_Solve().
subroutine model::model_InitializeFlowDirection (type (T_GENERAL_GRID),pointer pGrd, type (T_MODEL_CONFIGURATION),pointer pConfig)
Definition at line 2285 of file model.F90.
Referenced by model_Solve().
subroutine model::model_InitializeMaxInfil (type (T_GENERAL_GRID),pointer pGrd, type (T_MODEL_CONFIGURATION),pointer pConfig)
Definition at line 3237 of file model.F90.
Referenced by model_Solve().
subroutine model::model_InitializeSM (type (T_GENERAL_GRID),pointer pGrd, type (T_MODEL_CONFIGURATION),pointer pConfig)
Definition at line 3167 of file model.F90.
Referenced by model_Solve().
subroutine model::model_ProcessET (type (T_GENERAL_GRID),pointer pGrd, type (T_MODEL_CONFIGURATION),pointer pConfig, integer (kind=T_INT),intent(in) iDayOfYear, integer (kind=T_INT),intent(in) iNumDaysInYear, real (kind=T_SGL),intent(in) rRH, real (kind=T_SGL),intent(in) rMinRH, real (kind=T_SGL),intent(in) rWindSpd, real (kind=T_SGL),intent(in) rSunPct)
Definition at line 3075 of file model.F90.
Referenced by model_Solve().
subroutine model::model_ProcessRain (type (T_GENERAL_GRID),pointer pGrd, type (T_MODEL_CONFIGURATION),pointer pConfig, integer (kind=T_INT),intent(in) iDayOfYear, integer (kind=T_INT),intent(in) iMonth)
Definition at line 1185 of file model.F90.
Referenced by model_Solve().
subroutine model::model_ProcessRainPRMS (type (T_GENERAL_GRID),pointer pGrd, type (T_MODEL_CONFIGURATION),pointer pConfig, integer (kind=T_INT),intent(in) iDayOfYear, integer (kind=T_INT),intent(in) iMonth, integer (kind=T_INT),intent(in) iNumDaysInYear)
Definition at line 1309 of file model.F90.
Referenced by model_Solve().
subroutine model::model_ProcessRunoff (type (T_GENERAL_GRID),pointer pGrd, type (T_MODEL_CONFIGURATION),pointer pConfig, integer (kind=T_INT),intent(in) iDayOfYear, integer (kind=T_INT),intent(in) iMonth)
Definition at line 1562 of file model.F90.
Referenced by model_Solve().
subroutine model::model_ProcessSM (type (T_GENERAL_GRID),pointer pGrd, type (T_MODEL_CONFIGURATION),pointer pConfig, integer (kind=T_INT),intent(in) iDayOfYear, integer (kind=T_INT),intent(in) iDay, integer (kind=T_INT),intent(in) iMonth, integer (kind=T_INT),intent(in) iYear)
Definition at line 3139 of file model.F90.
Referenced by model_Solve().
subroutine model::model_ReadBasinMaskTable (type (T_MODEL_CONFIGURATION),pointer pConfig)
Definition at line 2524 of file model.F90.
Referenced by control::control_setModelOptions().
subroutine model::model_ReadLanduseLookupTable (type (T_MODEL_CONFIGURATION),pointer pConfig)
Definition at line 2656 of file model.F90.
Referenced by control::control_setModelOptions().
subroutine model::model_ReadTimeSeriesFile (type (T_TIME_SERIES_FILE),pointer pTS)
Definition at line 3484 of file model.F90.
Referenced by control::control_setModelOptions(), and model_Solve().
subroutine model::model_Runoff_NoRouting (type (T_GENERAL_GRID),pointer pGrd, type (T_MODEL_CONFIGURATION),pointer pConfig, integer (kind=T_INT),intent(in) iDayOfYear, integer (kind=T_INT),intent(in) iMonth)
Definition at line 2001 of file model.F90.
Referenced by model_ProcessRunoff().
subroutine model::model_RunoffDownhill (type (T_GENERAL_GRID),pointer pGrd, type (T_MODEL_CONFIGURATION),pointer pConfig, integer (kind=T_INT),intent(in) iDayOfYear, integer (kind=T_INT),intent(in) iMonth)
Definition at line 1884 of file model.F90.
Referenced by model_ProcessRunoff().
subroutine model::model_Solve (type (T_GENERAL_GRID),pointer pGrd, type (T_MODEL_CONFIGURATION),pointer pConfig, type (T_GRAPH_CONFIGURATION),dimension(:),pointer pGraph)
Definition at line 72 of file model.F90.
Referenced by control::control_setModelOptions().
subroutine model::model_UpdateContinuousFrozenGroundIndex (type (T_GENERAL_GRID),pointer pGrd, type (T_MODEL_CONFIGURATION),pointer pConfig)
Definition at line 967 of file model.F90.
Referenced by model_Solve().
subroutine model::model_write_NetCDF_attributes (type (T_MODEL_CONFIGURATION),pointer pConfig, type (T_GENERAL_GRID),pointer pGrd)
Definition at line 3447 of file model.F90.
Referenced by model_Solve().
subroutine model::model_WriteGrids (type (T_GENERAL_GRID),pointer pGrd, type (T_MODEL_CONFIGURATION),pointer pConfig, character (len=*),intent(in) sMonthName, integer (kind=T_INT),intent(in) iDay, integer (kind=T_INT),intent(in) iMonth, integer (kind=T_INT),intent(in) iYear, integer (kind=T_INT),intent(in) iDayOfYear)
Definition at line 3284 of file model.F90.
Referenced by model_Solve().
real (kind=T_SGL) model::rf_model_CellRunoff (type (T_MODEL_CONFIGURATION),pointer pConfig, type (T_CELL),pointer cel, integer (kind=T_INT),intent(in) iDayOfYear)
Definition at line 2191 of file model.F90.
Referenced by if_model_RunoffIteration(), model_Runoff_NoRouting(), and model_RunoffDownhill().
real (kind=T_SGL) model::rf_model_CellRunoff_GreenAmpt (type (T_MODEL_CONFIGURATION),pointer pConfig, type (T_CELL),pointer cel, integer (kind=T_INT),intent(in) iDayOfYear)
Definition at line 2237 of file model.F90.
Referenced by rf_model_CellRunoff().
real (kind=T_SGL) model::rf_model_GetInterception (type (T_MODEL_CONFIGURATION),pointer pConfig, integer (kind=T_SHORT),intent(in) iType, integer (kind=T_INT),intent(in) iDayOfYear)
Definition at line 3007 of file model.F90.
Referenced by model_ProcessRain(), and model_ProcessRainPRMS().
Variable Documentation
integer (kind=T_INT) model::iDayCtr
Definition at line 42 of file model.F90.
Referenced by control::control_setModelOptions(), and model_ProcessRunoff().
integer (kind=T_INT),dimension(:),allocatable model::iOrderCol
Definition at line 46 of file model.F90.
Referenced by model_ConfigureRunoffDownhill(), and model_RunoffDownhill().
integer (kind=T_INT) model::iOrderCount
Definition at line 45 of file model.F90.
Referenced by model_ConfigureRunoffDownhill(), and model_RunoffDownhill().
integer (kind=T_INT),dimension(:),allocatable model::iOrderRow
Definition at line 47 of file model.F90.
Referenced by model_ConfigureRunoffDownhill(), and model_RunoffDownhill().
real(kind=T_SGL) model::rEndTime
Definition at line 48 of file model.F90.
Referenced by model_EndOfRun().
real(kind=T_SGL) model::rStartTime
Definition at line 48 of file model.F90.
Referenced by model_EndOfRun(), and model_Solve().