SWB: et_blaney_criddle Module Reference
et_blaney_criddle Module Reference
Functions/Subroutines
subroutine et_bc_configure (sRecord)
subroutine et_bc_initialize (grd, sFileName)
subroutine et_bc_ComputeET (pGrd, iDayOfYear, rRH, rMinRH, rWindSpd, rSunPct)
Variables
real(kind=T_SGL) rLatitude
real(kind=T_SGL) rSunAnnual
Function/Subroutine Documentation
subroutine et_blaney_criddle::et_bc_ComputeET (type (T_GENERAL_GRID),pointer pGrd, integer (kind=T_INT),intent(in) iDayOfYear, real (kind=T_SGL),intent(in) rRH, real (kind=T_SGL),intent(in) rMinRH, real (kind=T_SGL),intent(in) rWindSpd, real (kind=T_SGL),intent(in) rSunPct)
Definition at line 79 of file et_blaney_criddle.F90.
Referenced by model::model_ProcessET().
subroutine et_blaney_criddle::et_bc_configure (character (len=*),intent(inout) sRecord)
Definition at line 40 of file et_blaney_criddle.F90.
subroutine et_blaney_criddle::et_bc_initialize (type (T_GENERAL_GRID),pointer grd, character (len=*),intent(in) sFileName)
Definition at line 58 of file et_blaney_criddle.F90.
Referenced by model::model_InitializeET().
Variable Documentation
real (kind=T_SGL) et_blaney_criddle::rLatitude
Definition at line 35 of file et_blaney_criddle.F90.
Referenced by et_bc_ComputeET(), et_bc_configure(), and et_bc_initialize().
real (kind=T_SGL) et_blaney_criddle::rSunAnnual
Definition at line 36 of file et_blaney_criddle.F90.
Referenced by et_bc_ComputeET(), and et_bc_initialize().