SWB: et_turc Module Reference
et_turc Module Reference
Functions/Subroutines
subroutine et_turc_configure (sRecord)
subroutine et_turc_initialize (grd, sFileName)
subroutine et_turc_ComputeET (pGrd, iDayOfYear, rRH, rSunPct)
Variables
real(kind=T_SGL) rLatitude
real(kind=T_SGL) rAlbedo
real(kind=T_SGL) rAs
real(kind=T_SGL) rBs
Function/Subroutine Documentation
subroutine et_turc::et_turc_ComputeET (type (T_GENERAL_GRID),pointer pGrd, integer (kind=T_INT),intent(in) iDayOfYear, real (kind=T_SGL),intent(in) rRH, real (kind=T_SGL),intent(in) rSunPct)
Definition at line 75 of file et_turc.F90.
Referenced by model::model_ProcessET().
subroutine et_turc::et_turc_configure (character (len=*),intent(inout) sRecord)
Definition at line 32 of file et_turc.F90.
subroutine et_turc::et_turc_initialize (type (T_GENERAL_GRID),pointer grd, character (len=*),intent(in) sFileName)
Definition at line 62 of file et_turc.F90.
Referenced by model::model_InitializeET().
Variable Documentation
real (kind=T_SGL) et_turc::rAlbedo
Definition at line 26 of file et_turc.F90.
Referenced by et_turc_ComputeET(), and et_turc_configure().
real (kind=T_SGL) et_turc::rAs
Definition at line 27 of file et_turc.F90.
Referenced by et_turc_ComputeET(), and et_turc_configure().
real (kind=T_SGL) et_turc::rBs
Definition at line 28 of file et_turc.F90.
Referenced by et_turc_configure().
real (kind=T_SGL) et_turc::rLatitude
Definition at line 25 of file et_turc.F90.
Referenced by et_turc_ComputeET(), and et_turc_configure().