SWB: et_jensen_haise Module Reference
et_jensen_haise Module Reference
Functions/Subroutines
subroutine et_jh_configure (sRecord)
subroutine et_jh_initialize (grd, sFileName)
subroutine et_jh_ComputeET (pGrd, iDayOfYear, rRH, rMinRH, rWindSpd, rSunPct)
Variables
real(kind=T_SGL) rLatitude
real(kind=T_SGL) rAlbedo
real(kind=T_SGL) rAs
real(kind=T_SGL) rBs
Function/Subroutine Documentation
subroutine et_jensen_haise::et_jh_ComputeET (type (T_GENERAL_GRID),pointer pGrd, integer (kind=T_INT),intent(in) iDayOfYear, real (kind=T_SGL),intent(in) rRH, real (kind=T_SGL),intent(in) rMinRH, real (kind=T_SGL),intent(in) rWindSpd, real (kind=T_SGL),intent(in) rSunPct)
Definition at line 76 of file et_jensen_haise.F90.
Referenced by model::model_ProcessET().
subroutine et_jensen_haise::et_jh_configure (character (len=*),intent(inout) sRecord)
Definition at line 33 of file et_jensen_haise.F90.
subroutine et_jensen_haise::et_jh_initialize (type (T_GENERAL_GRID),pointer grd, character (len=*),intent(in) sFileName)
Definition at line 63 of file et_jensen_haise.F90.
Referenced by model::model_InitializeET().
Variable Documentation
real (kind=T_SGL) et_jensen_haise::rAlbedo
Definition at line 27 of file et_jensen_haise.F90.
Referenced by et_jh_ComputeET(), and et_jh_configure().
real (kind=T_SGL) et_jensen_haise::rAs
Definition at line 28 of file et_jensen_haise.F90.
Referenced by et_jh_ComputeET(), and et_jh_configure().
real (kind=T_SGL) et_jensen_haise::rBs
Definition at line 29 of file et_jensen_haise.F90.
Referenced by et_jh_configure().
real (kind=T_SGL) et_jensen_haise::rLatitude
Definition at line 26 of file et_jensen_haise.F90.
Referenced by et_jh_ComputeET(), and et_jh_configure().