SWB: et_thornthwaite_mather Module Reference
et_thornthwaite_mather Module Reference
Functions/Subroutines
subroutine et_tm_configure (sRecord)
subroutine et_tm_initialize (pGrd, pConfig, sFileName)
subroutine et_tm_ComputeET (pGrd, pConfig, iDayOfYear, rRH, rMinRH, rWindSpd, rSunPct)
Variables
real(kind=T_SGL) rLatitude
real(kind=T_SGL) rTanLatitude
real(kind=T_SGL) rAnnualIndex
real(kind=T_SGL) rExponentA
Function/Subroutine Documentation
subroutine et_thornthwaite_mather::et_tm_ComputeET (type (T_GENERAL_GRID),pointer pGrd, type (T_MODEL_CONFIGURATION),pointer pConfig, integer (kind=T_INT),intent(in) iDayOfYear, real (kind=T_SGL),intent(in) rRH, real (kind=T_SGL),intent(in) rMinRH, real (kind=T_SGL),intent(in) rWindSpd, real (kind=T_SGL),intent(in) rSunPct)
Definition at line 143 of file et_thornthwaite_mather.F90.
Referenced by model::model_ProcessET().
subroutine et_thornthwaite_mather::et_tm_configure (character (len=*),intent(inout) sRecord)
Definition at line 42 of file et_thornthwaite_mather.F90.
subroutine et_thornthwaite_mather::et_tm_initialize (type (T_GENERAL_GRID),pointer pGrd, type (T_MODEL_CONFIGURATION),pointer pConfig, character (len=*),intent(in) sFileName)
Definition at line 61 of file et_thornthwaite_mather.F90.
Referenced by model::model_InitializeET().
Variable Documentation
real (kind=T_SGL) et_thornthwaite_mather::rAnnualIndex
Definition at line 37 of file et_thornthwaite_mather.F90.
Referenced by et_tm_ComputeET(), and et_tm_initialize().
real (kind=T_SGL) et_thornthwaite_mather::rExponentA
Definition at line 38 of file et_thornthwaite_mather.F90.
Referenced by et_tm_ComputeET(), and et_tm_initialize().
real (kind=T_SGL) et_thornthwaite_mather::rLatitude
Definition at line 33 of file et_thornthwaite_mather.F90.
Referenced by et_tm_configure().
real (kind=T_SGL) et_thornthwaite_mather::rTanLatitude
Definition at line 34 of file et_thornthwaite_mather.F90.
Referenced by et_tm_ComputeET(), and et_tm_configure().