SWB: runoff_curve_number Module Reference
runoff_curve_number Module Reference
Functions/Subroutines
subroutine runoff_InitializeCurveNumber (pGrd, pConfig)
real(kind=T_SGL) prob_runoff_enhancement (rCFGI, rLL, rUL)
subroutine runoff_UpdateCurveNumber (pConfig, cel, iJulDay)
real(kind=T_SGL) runoff_CellRunoff_CurveNumber (pConfig, cel, iJulDay)
Function/Subroutine Documentation
real (kind=T_SGL) runoff_curve_number::prob_runoff_enhancement (real (kind=T_SGL) rCFGI, real (kind=T_SGL) rLL, real (kind=T_SGL) rUL)
Definition at line 86 of file runoff_curve_number.F90.
Referenced by runoff_UpdateCurveNumber().
real (kind=T_SGL) runoff_curve_number::runoff_CellRunoff_CurveNumber (type (T_MODEL_CONFIGURATION),pointer pConfig, type (T_CELL),pointer cel, integer (kind=T_INT),intent(in) iJulDay)
Definition at line 202 of file runoff_curve_number.F90.
Referenced by model::rf_model_CellRunoff().
subroutine runoff_curve_number::runoff_InitializeCurveNumber (type (T_GENERAL_GRID),pointer pGrd, type (T_MODEL_CONFIGURATION),pointer pConfig)
Definition at line 22 of file runoff_curve_number.F90.
Referenced by model::model_Solve().
subroutine runoff_curve_number::runoff_UpdateCurveNumber (type (T_MODEL_CONFIGURATION),pointer pConfig, type (T_CELL),pointer cel, integer (kind=T_INT),intent(in) iJulDay)
Definition at line 105 of file runoff_curve_number.F90.
Referenced by runoff_CellRunoff_CurveNumber().