SWB: netcdf_support Module Reference
netcdf_support Module Reference
Data Types
type T_ELLIPSOID
Functions/Subroutines
integer(kind=T_INT) netcdf_create (sNetCDF_Filename)
integer(kind=T_INT) netcdf_open (sNetCDF_Filename)
subroutine netcdf_info (pConfig, iVarNum, iMode, sVariableName)
subroutine netcdf_chk_extent (pConfig, iVarNum, iMode, pGrd)
subroutine netcdf_read (iVarNum, iMode, pConfig, pGrd, pOutGrd, iJulianDay)
subroutine netcdf_write_attributes (iVarNum, iMode, pConfig, pGrd)
subroutine netcdf_write_variable (iVarNum, iMode, pConfig, pGrd, iTime)
subroutine netcdf_write_variable_byte (iVarNum, iMode, pConfig, rValue, pGrd, i, j, iTime)
subroutine netcdf_check (iStatus, sFilename, iLineNo, pNC, iTime, rValue)
subroutine LLtoUTM (pConfig, rLat, rLong, rUTMNorthing, rUTMEasting, iZoneNumber)
subroutine UTMtoLL (pConfig, rUTMEasting, rUTMNorthing, rLat, rLong)
Variables
type(T_ELLIPSOID), dimension(24),
target Ellipsoid = (/ T_ELLIPSOID(1, "Airy", 6377563_T_DBL, 0.00667054), T_ELLIPSOID(2, "Australian National", 6378160_T_DBL, 0.006694542), T_ELLIPSOID(3, "Bessel 1841", 6377397_T_DBL, 0.006674372), T_ELLIPSOID(4, "Bessel 1841 (Nambia) ", 6377484, 0.006674372), T_ELLIPSOID(5, "Clarke 1866", 6378206, 0.006768658), T_ELLIPSOID(6, "Clarke 1880", 6378249, 0.006803511), T_ELLIPSOID(7, "Everest", 6377276, 0.006637847), T_ELLIPSOID(8, "Fischer 1960 (Mercury) ", 6378166, 0.006693422), T_ELLIPSOID(9, "Fischer 1968", 6378150, 0.006693422), T_ELLIPSOID(10, "GRS 1967", 6378160, 0.006694605), T_ELLIPSOID(11, "GRS 1980", 6378137_T_DBL, 0.00669438_T_DBL), T_ELLIPSOID(12, "Helmert 1906", 6378200, 0.006693422), T_ELLIPSOID(13, "Hough", 6378270, 0.00672267), T_ELLIPSOID(14, "International", 6378388, 0.00672267), T_ELLIPSOID(15, "Krassovsky", 6378245, 0.006693422), T_ELLIPSOID(16, "Modified Airy", 6377340, 0.00667054), T_ELLIPSOID(17, "Modified Everest", 6377304, 0.006637847), T_ELLIPSOID(18, "Modified Fischer 1960", 6378155, 0.006693422), T_ELLIPSOID(19, "South American 1969", 6378160, 0.006694542), T_ELLIPSOID(20, "WGS 60", 6378165, 0.006693422), T_ELLIPSOID(21, "WGS 66", 6378145, 0.006694542), T_ELLIPSOID(22, "WGS-72", 6378135, 0.006694318), T_ELLIPSOID(23, "WGS-84", 6378137, 0.00669438), T_ELLIPSOID(24, "Placeholder", 0, 0) /)
Function/Subroutine Documentation
subroutine netcdf_support::LLtoUTM (type (T_MODEL_CONFIGURATION),pointer pConfig, real (kind=T_DBL),intent(in) rLat, real (kind=T_DBL),intent(in) rLong, real (kind=T_DBL),intent(out) rUTMNorthing, real (kind=T_DBL),intent(out) rUTMEasting, integer (kind=T_INT),intent(out) iZoneNumber)
Definition at line 1115 of file netcdf_support.F90.
subroutine netcdf_support::netcdf_check (integer(kind=T_INT),intent(in) iStatus, character(len=*),optional sFilename, integer (kind=T_INT),optional iLineNo, type (T_NETCDF_FILE),optional,pointer pNC, integer (kind=T_INT),optional iTime, real(kind=T_SGL),optional rValue)
Definition at line 1069 of file netcdf_support.F90.
Referenced by model::model_EndOfRun(), netcdf_create(), netcdf_info(), netcdf_open(), netcdf_read(), netcdf_write_attributes(), netcdf_write_variable(), and netcdf_write_variable_byte().
subroutine netcdf_support::netcdf_chk_extent (type (T_MODEL_CONFIGURATION),pointer pConfig, integer (kind=T_INT) iVarNum, integer (kind=T_INT) iMode, type (T_GENERAL_GRID),pointer pGrd)
Definition at line 521 of file netcdf_support.F90.
integer(kind=T_INT) netcdf_support::netcdf_create (character(len=*) sNetCDF_Filename)
Definition at line 49 of file netcdf_support.F90.
Referenced by model::model_write_NetCDF_attributes().
subroutine netcdf_support::netcdf_info (type (T_MODEL_CONFIGURATION),pointer pConfig, integer (kind=T_INT) iVarNum, integer (kind=T_INT) iMode, character(len=*) sVariableName)
Definition at line 78 of file netcdf_support.F90.
integer(kind=T_INT) netcdf_support::netcdf_open (character(len=*) sNetCDF_Filename)
Definition at line 63 of file netcdf_support.F90.
subroutine netcdf_support::netcdf_read (integer(kind=T_INT) iVarNum, integer (kind=T_INT) iMode, type (T_MODEL_CONFIGURATION),pointer pConfig, type (T_GENERAL_GRID),pointer pGrd, type (T_GENERAL_GRID),pointer pOutGrd, integer(kind=T_INT) iJulianDay)
Definition at line 585 of file netcdf_support.F90.
Referenced by model::model_GetDailyPrecipValue(), and model::model_GetDailyTemperatureValue().
subroutine netcdf_support::netcdf_write_attributes (integer(kind=T_INT) iVarNum, integer (kind=T_INT) iMode, type (T_MODEL_CONFIGURATION),pointer pConfig, type (T_GENERAL_GRID),pointer pGrd)
Definition at line 745 of file netcdf_support.F90.
Referenced by model::model_write_NetCDF_attributes().
subroutine netcdf_support::netcdf_write_variable (integer(kind=T_INT) iVarNum, integer (kind=T_INT) iMode, type (T_MODEL_CONFIGURATION),pointer pConfig, type (T_GENERAL_GRID),pointer pGrd, integer (kind=T_INT) iTime)
Definition at line 989 of file netcdf_support.F90.
subroutine netcdf_support::netcdf_write_variable_byte (integer(kind=T_INT) iVarNum, integer (kind=T_INT) iMode, type (T_MODEL_CONFIGURATION),pointer pConfig, real(kind=T_SGL) rValue, type (T_GENERAL_GRID),pointer pGrd, integer(kind=T_INT) i, integer(kind=T_INT) j, integer (kind=T_INT) iTime)
Definition at line 1025 of file netcdf_support.F90.
Referenced by sm_thornthwaite_mather::sm_thornthwaite_mather_UpdateSM().
subroutine netcdf_support::UTMtoLL (type (T_MODEL_CONFIGURATION),pointer pConfig, real (kind=T_DBL),intent(in) rUTMEasting, real (kind=T_DBL),intent(in) rUTMNorthing, real (kind=T_DBL),intent(out) rLat, real (kind=T_DBL),intent(out) rLong)
Definition at line 1209 of file netcdf_support.F90.
Referenced by netcdf_write_attributes().
Variable Documentation
type (T_ELLIPSOID),dimension(24),target netcdf_support::Ellipsoid = (/ T_ELLIPSOID(1, "Airy", 6377563_T_DBL, 0.00667054), T_ELLIPSOID(2, "Australian National", 6378160_T_DBL, 0.006694542), T_ELLIPSOID(3, "Bessel 1841", 6377397_T_DBL, 0.006674372), T_ELLIPSOID(4, "Bessel 1841 (Nambia) ", 6377484, 0.006674372), T_ELLIPSOID(5, "Clarke 1866", 6378206, 0.006768658), T_ELLIPSOID(6, "Clarke 1880", 6378249, 0.006803511), T_ELLIPSOID(7, "Everest", 6377276, 0.006637847), T_ELLIPSOID(8, "Fischer 1960 (Mercury) ", 6378166, 0.006693422), T_ELLIPSOID(9, "Fischer 1968", 6378150, 0.006693422), T_ELLIPSOID(10, "GRS 1967", 6378160, 0.006694605), T_ELLIPSOID(11, "GRS 1980", 6378137_T_DBL, 0.00669438_T_DBL), T_ELLIPSOID(12, "Helmert 1906", 6378200, 0.006693422), T_ELLIPSOID(13, "Hough", 6378270, 0.00672267), T_ELLIPSOID(14, "International", 6378388, 0.00672267), T_ELLIPSOID(15, "Krassovsky", 6378245, 0.006693422), T_ELLIPSOID(16, "Modified Airy", 6377340, 0.00667054), T_ELLIPSOID(17, "Modified Everest", 6377304, 0.006637847), T_ELLIPSOID(18, "Modified Fischer 1960", 6378155, 0.006693422), T_ELLIPSOID(19, "South American 1969", 6378160, 0.006694542), T_ELLIPSOID(20, "WGS 60", 6378165, 0.006693422), T_ELLIPSOID(21, "WGS 66", 6378145, 0.006694542), T_ELLIPSOID(22, "WGS-72", 6378135, 0.006694318), T_ELLIPSOID(23, "WGS-84", 6378137, 0.00669438), T_ELLIPSOID(24, "Placeholder", 0, 0) /)
Definition at line 19 of file netcdf_support.F90.
Referenced by LLtoUTM(), and UTMtoLL().