SWB: swb_stats Module Reference
swb_stats Module Reference
Calculates daily, monthly, and annual statistics for an SWB model run.
Functions/Subroutines
subroutine stats_InitializeVolumeConversion (pGrd)
subroutine stats_InitializeDailyAccumulators ()
subroutine stats_InitializeMonthlyAccumulators ()
subroutine stats_InitializeAnnualAccumulators ()
subroutine stats_FormatTextString (sText, rValue, pConfig, iVarNum, sFormattedText)
subroutine stats_WriteDailyAccumulatorValuesCSV (iLU, iMonth, iDay, iYear)
subroutine stats_WriteAnnualAccumulatorValuesCSV (iLU, iYear)
subroutine stats_WriteDailyAccumulatorHeaderCSV (iLU)
subroutine stats_WriteAnnualAccumulatorHeaderCSV (iLU)
subroutine stats_DumpDailyAccumulatorValues (iLU, pConfig)
subroutine stats_DumpMonthlyAccumulatorValues (iLU, iMonth, sMonthName, pConfig)
subroutine stats_DumpAnnualAccumulatorValues (iLU, pConfig, iYear)
subroutine stats_UpdateAllAccumulatorsByCell (rValue, iVarNum, iMonthNum, iNumGridCells)
subroutine stats_UpdateAllAccumulatorsByGrid (rMin, rMean, rMax, rSum, iVarNum, iMonthNum)
subroutine stats_CalcMonthlyMeans (iMonthNum, iDaysInMonth)
Calculates and writes out monthly min, max, and mean of 2D variable array.
subroutine stats_WriteMinMeanMax (iLU, sText, rData, iCount)
Writes out the min, max, and mean of 2D variable array.
subroutine stats_WriteMSBReport (pGrd, iMonth, iDay, iYear, iDayOfYear)
subroutine stats_RewriteGrids (iNX, iNY, rX0, rY0, rX1, rY1, pConfig, pGraph)
subroutine stats_CalcBasinStats (pGrd, pConfig, pGraph)
subroutine stats_CalcMeanRecharge (pGrd, pConfig, pGraph)
subroutine stats_CalcMeanRechargebyLU (pGrd, pConfig, pGraph)
subroutine stats_write_to_SSF_file (pConfig, iSSFindex, iMonth, iDay, iYear, rValue)
subroutine stats_OpenBinaryFiles (pConfig, pGrd)
subroutine stats_CloseBinaryFiles ()
Variables
real(kind=T_DBL), public rVolConvert
real(kind=T_DBL), dimension(inum_months,
inum_stats, inum_variables),
public rMonthly
real(kind=T_DBL), dimension(inum_stats,
inum_variables), public rDaily
real(kind=T_DBL), dimension(inum_stats,
inum_variables), public rAnnual
Detailed Description
Calculates daily, monthly, and annual statistics for an SWB model run.
Calculates daily, monthly, and annual statistics for an SWB model run. Also contains routines to:
Extract data from a compressed binary file in order to output grids or plots
Write to a PEST *.ssf file
Calculate statistics for a subset of the model domain (i.e. catchment, county)
Write daily, annual, and mass balance reports
Function/Subroutine Documentation
subroutine swb_stats::stats_CalcBasinStats (type (T_GENERAL_GRID),pointer pGrd, type (T_MODEL_CONFIGURATION),pointer pConfig, type (T_GRAPH_CONFIGURATION),dimension(:),pointer pGraph)
Definition at line 1108 of file stats.F90.
Referenced by control::control_setModelOptions().
subroutine swb_stats::stats_CalcMeanRecharge (type (T_GENERAL_GRID),pointer pGrd, type (T_MODEL_CONFIGURATION),pointer pConfig, type (T_GRAPH_CONFIGURATION),dimension(:),pointer pGraph)
Definition at line 1273 of file stats.F90.
Referenced by control::control_setModelOptions().
subroutine swb_stats::stats_CalcMeanRechargebyLU (type (T_GENERAL_GRID),pointer pGrd, type (T_MODEL_CONFIGURATION),pointer pConfig, type (T_GRAPH_CONFIGURATION),dimension(:),pointer pGraph)
Definition at line 1349 of file stats.F90.
Referenced by control::control_setModelOptions().
subroutine swb_stats::stats_CalcMonthlyMeans (integer(kind=T_INT),intent(in) iMonthNum, integer(kind=T_INT),intent(in) iDaysInMonth)
Calculates and writes out monthly min, max, and mean of 2D variable array.
Parameters:
[in] iMonthNum Numerical index (1-12) of the month for which statistics are reported.
[in] iDaysInMonth Number of days in the reporting month.
Deprecated:
This subroutine will be eliminated in future version of SWB.
Definition at line 528 of file stats.F90.
subroutine swb_stats::stats_CloseBinaryFiles ()
Definition at line 1590 of file stats.F90.
Referenced by model::model_EndOfRun().
subroutine swb_stats::stats_DumpAnnualAccumulatorValues (integer (kind=T_INT),intent(in) iLU, type (T_MODEL_CONFIGURATION),pointer pConfig, integer (kind=T_INT),intent(in) iYear)
Definition at line 383 of file stats.F90.
Referenced by model::model_Solve().
subroutine swb_stats::stats_DumpDailyAccumulatorValues (integer (kind=T_INT),intent(in) iLU, type (T_MODEL_CONFIGURATION),pointer pConfig)
Definition at line 272 of file stats.F90.
Referenced by model::model_Solve().
subroutine swb_stats::stats_DumpMonthlyAccumulatorValues (integer (kind=T_INT),intent(in) iLU, integer (kind=T_INT),intent(in) iMonth, character (len=3),intent(in) sMonthName, type (T_MODEL_CONFIGURATION),pointer pConfig)
Definition at line 323 of file stats.F90.
Referenced by model::model_Solve().
subroutine swb_stats::stats_FormatTextString (character(len=*),intent(in) sText, real(kind=T_SGL),dimension(inum_stats),intent(in) rValue, type (T_MODEL_CONFIGURATION),pointer pConfig, integer(kind=T_INT),intent(in) iVarNum, character(len=256),dimension(inum_stats) sFormattedText)
Definition at line 100 of file stats.F90.
Referenced by stats_DumpAnnualAccumulatorValues(), stats_DumpDailyAccumulatorValues(), and stats_DumpMonthlyAccumulatorValues().
subroutine swb_stats::stats_InitializeAnnualAccumulators ()
Definition at line 93 of file stats.F90.
Referenced by model::model_Solve().
subroutine swb_stats::stats_InitializeDailyAccumulators ()
Definition at line 72 of file stats.F90.
Referenced by model::model_Solve().
subroutine swb_stats::stats_InitializeMonthlyAccumulators ()
Definition at line 84 of file stats.F90.
Referenced by model::model_Solve().
subroutine swb_stats::stats_InitializeVolumeConversion (type (T_GENERAL_GRID),pointer pGrd)
Definition at line 40 of file stats.F90.
Referenced by model::model_Solve().
subroutine swb_stats::stats_OpenBinaryFiles (type (T_MODEL_CONFIGURATION),pointer pConfig, type (T_GENERAL_GRID),pointer pGrd)
Definition at line 1537 of file stats.F90.
Referenced by model::model_Solve().
subroutine swb_stats::stats_RewriteGrids (integer (kind=T_INT),intent(in) iNX, integer (kind=T_INT),intent(in) iNY, real (kind=T_DBL),intent(in) rX0, real (kind=T_DBL),intent(in) rY0, real (kind=T_DBL),intent(in) rX1, real (kind=T_DBL),intent(in) rY1, type (T_MODEL_CONFIGURATION),pointer pConfig, type (T_GRAPH_CONFIGURATION),dimension(:),pointer pGraph)
Definition at line 694 of file stats.F90.
Referenced by model::model_EndOfRun().
subroutine swb_stats::stats_UpdateAllAccumulatorsByCell (real (kind=T_DBL),intent(in) rValue, integer (kind=T_INT),intent(in) iVarNum, integer (kind=T_INT),intent(in) iMonthNum, integer (kind=T_INT),intent(in) iNumGridCells)
Definition at line 434 of file stats.F90.
Referenced by model::model_ProcessRain(), model::model_ProcessRainPRMS(), and sm_thornthwaite_mather::sm_thornthwaite_mather_UpdateSM().
subroutine swb_stats::stats_UpdateAllAccumulatorsByGrid (real (kind=T_DBL),intent(in) rMin, real (kind=T_DBL),intent(in) rMean, real (kind=T_DBL),intent(in) rMax, real (kind=T_DBL),intent(in) rSum, integer (kind=T_INT),intent(in) iVarNum, integer (kind=T_INT),intent(in) iMonthNum)
Definition at line 488 of file stats.F90.
Referenced by model::model_GetDailyPrecipValue().
subroutine swb_stats::stats_write_to_SSF_file (type (T_MODEL_CONFIGURATION),pointer pConfig, integer (kind=T_INT),intent(in) iSSFindex, integer (kind=T_INT),intent(in) iMonth, integer (kind=T_INT),intent(in) iDay, integer (kind=T_INT),intent(in) iYear, real (kind=T_SGL),intent(in) rValue)
Definition at line 1485 of file stats.F90.
Referenced by sm_thornthwaite_mather::sm_thornthwaite_mather_UpdateSM().
subroutine swb_stats::stats_WriteAnnualAccumulatorHeaderCSV (integer (kind=T_INT),intent(in) iLU)
Definition at line 252 of file stats.F90.
Referenced by model::model_Solve().
subroutine swb_stats::stats_WriteAnnualAccumulatorValuesCSV (integer (kind=T_INT),intent(in) iLU, integer (kind=T_INT),intent(in) iYear)
Definition at line 206 of file stats.F90.
Referenced by model::model_Solve().
subroutine swb_stats::stats_WriteDailyAccumulatorHeaderCSV (integer (kind=T_INT),intent(in) iLU)
Definition at line 227 of file stats.F90.
Referenced by model::model_Solve().
subroutine swb_stats::stats_WriteDailyAccumulatorValuesCSV (integer (kind=T_INT),intent(in) iLU, integer (kind=T_INT),intent(in) iMonth, integer (kind=T_INT),intent(in) iDay, integer (kind=T_INT),intent(in) iYear)
Definition at line 181 of file stats.F90.
Referenced by model::model_Solve().
subroutine swb_stats::stats_WriteMinMeanMax (integer (kind=T_INT),intent(in) iLU, character (len=*) sText, real (kind=T_SGL),dimension(:,:) rData, integer (kind=T_INT),optional iCount)
Writes out the min, max, and mean of 2D variable array.
Parameters:
[in] iLU Fortran logical unit number to write output to.
[in] sText Descriptive text associated with the statistics.
[in] rData 2-d array of values for which statistics are calculated.
[in] iCount {Optional} User-supplied divisor for use in calculating the mean.
Definition at line 553 of file stats.F90.
Referenced by model::model_Solve(), stats_CalcMeanRecharge(), stats_RewriteGrids(), swbread(), and swbstats().
subroutine swb_stats::stats_WriteMSBReport (type (T_GENERAL_GRID),pointer pGrd, integer (kind=T_INT),intent(in) iMonth, integer (kind=T_INT),intent(in) iDay, integer (kind=T_INT),intent(in) iYear, integer (kind=T_INT),intent(in) iDayOfYear)
Definition at line 587 of file stats.F90.
Referenced by model::model_Solve().
Variable Documentation
real (kind=T_DBL),dimension(inum_stats,inum_variables),public swb_stats::rAnnual
Definition at line 33 of file stats.F90.
Referenced by stats_DumpAnnualAccumulatorValues(), stats_InitializeAnnualAccumulators(), stats_UpdateAllAccumulatorsByCell(), stats_UpdateAllAccumulatorsByGrid(), and stats_WriteAnnualAccumulatorValuesCSV().
real (kind=T_DBL),dimension(inum_stats,inum_variables),public swb_stats::rDaily
Definition at line 30 of file stats.F90.
Referenced by stats_DumpDailyAccumulatorValues(), stats_InitializeDailyAccumulators(), stats_UpdateAllAccumulatorsByCell(), stats_UpdateAllAccumulatorsByGrid(), stats_WriteDailyAccumulatorValuesCSV(), and stats_WriteMSBReport().
real (kind=T_DBL),dimension(inum_months,inum_stats,inum_variables),public swb_stats::rMonthly
Definition at line 27 of file stats.F90.
Referenced by stats_DumpMonthlyAccumulatorValues(), stats_InitializeMonthlyAccumulators(), stats_UpdateAllAccumulatorsByCell(), and stats_UpdateAllAccumulatorsByGrid().
real (kind=T_DBL),public swb_stats::rVolConvert
Definition at line 24 of file stats.F90.
Referenced by stats_DumpAnnualAccumulatorValues(), stats_DumpMonthlyAccumulatorValues(), stats_InitializeVolumeConversion(), and stats_WriteMSBReport().