SWB: swb_grid Module Reference
swb_grid Module Reference
Functions/Subroutines
type(T_GENERAL_GRID), pointer grid_Create (iNX, iNY, rX0, rY0, rX1, rY1, iDataType)
subroutine grid_Destroy (pGrd)
type(T_GENERAL_GRID), pointer grid_Read (sFileName, sFileType, iDataType)
type(T_GENERAL_GRID), pointer grid_ReadArcGrid (sFileName, iDataType)
type(T_GENERAL_GRID), pointer grid_ReadSurferGrid (sFileName, iDataType)
subroutine grid_WriteArcGrid (cFilename, rXmin, rXmax, rYmin, rYmax, rValues, rNoData)
subroutine grid_WriteSurferGrid (cFilename, rXmin, rXmax, rYmin, rYmax, rValues)
logical(kind=T_LOGICAL) grid_Conform (pGrd1, pGrd2, rTolerance)
subroutine grid_LookupColumn (pGrd, rXval, iBefore, iAfter, rFrac)
subroutine grid_LookupRow (pGrd, rYval, iBefore, iAfter, rFrac)
real(kind=T_SGL) grid_Interpolate (pGrd, rXval, rYval)
real(kind=T_SGL) grid_SearchColumn (pGrd, rXval, rZval, rNoData)
real(kind=T_SGL) grid_LookupReal (pGrd, rXval, rYval)
integer(kind=T_INT) grid_GetGridColNum (pGrd, rX)
integer(kind=T_INT) grid_GetGridRowNum (pGrd, rY)
real(kind=T_SGL) grid_GetGridX (pGrd, iColumnNumber)
real(kind=T_SGL) grid_GetGridY (pGrd, iRowNumber)
Function/Subroutine Documentation
logical (kind=T_LOGICAL) swb_grid::grid_Conform (type (T_GENERAL_GRID),pointer pGrd1, type (T_GENERAL_GRID),pointer pGrd2, real (kind=T_SGL),intent(in),optional rTolerance)
Definition at line 645 of file grid.F90.
Referenced by control::control_setModelOptions(), model::model_GetDailyPrecipValue(), model::model_GetDailyTemperatureValue(), model::model_GetDynamicLanduseValue(), swbstats_support::ReadBasinMaskTable(), and swb_stats::stats_CalcBasinStats().
type (T_GENERAL_GRID),pointer swb_grid::grid_Create (integer (kind=T_INT),intent(in) iNX, integer (kind=T_INT),intent(in) iNY, real (kind=T_DBL),intent(in) rX0, real (kind=T_DBL),intent(in) rY0, real (kind=T_DBL),intent(in) rX1, real (kind=T_DBL),intent(in) rY1, integer (kind=T_INT),intent(in) iDataType)
Definition at line 48 of file grid.F90.
Referenced by control::control_setModelOptions(), grid_ReadArcGrid(), grid_ReadSurferGrid(), model::model_ConfigureRunoffDownhill(), netcdf_support::netcdf_read(), swb_stats::stats_CalcBasinStats(), swb_stats::stats_CalcMeanRecharge(), swb_stats::stats_CalcMeanRechargebyLU(), swb_stats::stats_RewriteGrids(), swbread(), and swbstats().
subroutine swb_grid::grid_Destroy (type (T_GENERAL_GRID),pointer pGrd)
Definition at line 154 of file grid.F90.
Referenced by control::control_setModelOptions(), model::model_EndOfRun(), model::model_GetDailyPrecipValue(), model::model_GetDailyTemperatureValue(), and model::model_GetDynamicLanduseValue().
integer (kind=T_INT) swb_grid::grid_GetGridColNum (type (T_GENERAL_GRID),pointer pGrd, real (kind=T_DBL) rX)
Definition at line 1057 of file grid.F90.
Referenced by control::control_setModelOptions().
integer (kind=T_INT) swb_grid::grid_GetGridRowNum (type (T_GENERAL_GRID),pointer pGrd, real (kind=T_DBL) rY)
Definition at line 1071 of file grid.F90.
Referenced by control::control_setModelOptions().
real (kind=T_SGL) swb_grid::grid_GetGridX (type (T_GENERAL_GRID),pointer pGrd, integer (kind=T_INT) iColumnNumber)
Definition at line 1085 of file grid.F90.
Referenced by netcdf_support::netcdf_write_attributes().
real (kind=T_SGL) swb_grid::grid_GetGridY (type (T_GENERAL_GRID),pointer pGrd, integer (kind=T_INT) iRowNumber)
Definition at line 1099 of file grid.F90.
Referenced by netcdf_support::netcdf_write_attributes().
real (kind=T_SGL) swb_grid::grid_Interpolate (type (T_GENERAL_GRID),pointer pGrd, real (kind=T_SGL),intent(in) rXval, real (kind=T_SGL),intent(in) rYval)
Definition at line 844 of file grid.F90.
Referenced by sm_thornthwaite_mather::sm_thornthwaite_mather_UpdateSM().
subroutine swb_grid::grid_LookupColumn (type (T_GENERAL_GRID),pointer pGrd, real (kind=T_SGL),intent(in) rXval, integer (kind=T_INT),intent(out) iBefore, integer (kind=T_INT),intent(out) iAfter, real (kind=T_SGL),intent(out) rFrac)
Definition at line 722 of file grid.F90.
Referenced by grid_Interpolate(), and grid_SearchColumn().
real (kind=T_SGL) swb_grid::grid_LookupReal (type (T_GENERAL_GRID),pointer pGrd, real (kind=T_SGL),intent(in) rXval, real (kind=T_SGL),intent(in) rYval)
Definition at line 1038 of file grid.F90.
subroutine swb_grid::grid_LookupRow (type (T_GENERAL_GRID),pointer pGrd, real (kind=T_SGL),intent(in) rYval, integer (kind=T_INT),intent(out) iBefore, integer (kind=T_INT),intent(out) iAfter, real (kind=T_SGL),intent(out) rFrac)
Definition at line 791 of file grid.F90.
Referenced by grid_Interpolate().
type (T_GENERAL_GRID),pointer swb_grid::grid_Read (character (len=*),intent(in) sFileName, character (len=*),intent(in) sFileType, integer (kind=T_INT),intent(in) iDataType)
Definition at line 207 of file grid.F90.
Referenced by control::control_setModelOptions(), model::model_GetDailyPrecipValue(), model::model_GetDailyTemperatureValue(), model::model_GetDynamicLanduseValue(), swbstats_support::ReadBasinMaskTable(), sm_thornthwaite_mather::sm_thornthwaite_mather_Configure(), and swb_stats::stats_CalcBasinStats().
type (T_GENERAL_GRID),pointer swb_grid::grid_ReadArcGrid (character (len=*),intent(in) sFileName, integer (kind=T_INT),intent(in) iDataType)
Definition at line 251 of file grid.F90.
Referenced by grid_Read().
type (T_GENERAL_GRID),pointer swb_grid::grid_ReadSurferGrid (character (len=*),intent(in) sFileName, integer (kind=T_INT),intent(in) iDataType)
Definition at line 416 of file grid.F90.
Referenced by grid_Read().
real (kind=T_SGL) swb_grid::grid_SearchColumn (type (T_GENERAL_GRID),pointer pGrd, real (kind=T_SGL),intent(in) rXval, real (kind=T_SGL),intent(in) rZval, real (kind=T_SGL),intent(in) rNoData)
Definition at line 920 of file grid.F90.
Referenced by sm_thornthwaite_mather::sm_thornthwaite_mather_Initialize(), and sm_thornthwaite_mather::sm_thornthwaite_mather_UpdateSM().
subroutine swb_grid::grid_WriteArcGrid (character (len=*),intent(in) cFilename, real (kind=T_DBL),intent(in) rXmin, real (kind=T_DBL),intent(in) rXmax, real (kind=T_DBL),intent(in) rYmin, real (kind=T_DBL),intent(in) rYmax, real (kind=T_SGL),dimension(:,:),intent(in) rValues, real (kind=T_SGL),intent(in),optional rNoData)
Definition at line 508 of file grid.F90.
Referenced by model::model_ConfigureRunoffDownhill(), model::model_Solve(), model::model_WriteGrids(), runoff_curve_number::runoff_InitializeCurveNumber(), sm_thornthwaite_mather::sm_thornthwaite_mather_Initialize(), swb_stats::stats_CalcMeanRecharge(), swb_stats::stats_RewriteGrids(), swbread(), and swbstats().
subroutine swb_grid::grid_WriteSurferGrid (character (len=*),intent(in) cFilename, real (kind=T_DBL),intent(in) rXmin, real (kind=T_DBL),intent(in) rXmax, real (kind=T_DBL),intent(in) rYmin, real (kind=T_DBL),intent(in) rYmax, real (kind=T_SGL),dimension(:,:),intent(in) rValues)
Definition at line 584 of file grid.F90.
Referenced by model::model_WriteGrids(), swb_stats::stats_RewriteGrids(), swbread(), and swbstats().