SWB: graph Module Reference
graph Module Reference
Functions/Subroutines
subroutine makegraph (pGraph, pGrd, iVarNum)
subroutine make_shaded_contour (pGrd, sOutputFilename, sTitleTxt, sAxisTxt)
Function/Subroutine Documentation
subroutine graph::make_shaded_contour (type (T_GENERAL_GRID),pointer pGrd, character (len=*) sOutputFilename, character (len=*) sTitleTxt, character (len=*) sAxisTxt)
Definition at line 322 of file graph.F90.
Referenced by swbread(), and swbstats().
subroutine graph::makegraph (type(T_GRAPH_CONFIGURATION),dimension(:),pointer pGraph, type (T_GENERAL_GRID),pointer pGrd, integer (kind=T_INT),intent(in) iVarNum)
Definition at line 24 of file graph.F90.
Referenced by swb_stats::stats_CalcMeanRecharge(), and swb_stats::stats_RewriteGrids().