SWB: meteorological_functions Module Reference
meteorological_functions Module Reference
Functions/Subroutines
real(kind=T_SGL) daylight_hours (rOmega_s)
Calculates the number of daylight hours at a location.
real(kind=T_SGL) extraterrestrial_radiation_Ra (rLatitude, rDelta, rOmega_s, rDsubR)
real(kind=T_SGL) deg2rad (rDeg)
real(kind=T_SGL) equivalent_evaporation (rR)
real(kind=T_SGL) row_latitude (rNorthLat, rSouthLat, iNumRows, iCurrRow)
real(kind=T_DBL) sensible_heat_exchange_h (rTSnow, rTAvg, rWindSpd)
real(kind=T_DBL) convective_heat_exchange_e (rTSnow, rTAvg, rWindSpd)
real(kind=T_SGL) net_shortwave_radiation_Rns (rRs, rAlbedo)
real(kind=T_SGL) precipitation_heat_p (rPrecipAmount, rTAvg)
real(kind=T_SGL) solar_declination (iDayOfYear, iNumDaysInYear)
real(kind=T_SGL) rel_Earth_Sun_dist (iDayOfYear, iNumDaysInYear)
real(kind=T_SGL) sunset_angle (rLatitude, rDelta)
real(kind=T_SGL) solar_radiation_Hargreaves_Rs (rRa, rTMIN, rTMAX)
real(kind=T_SGL) clear_sky_solar_radiation_Rso (rRa, rAs_in, rBs_in)
real(kind=T_SGL) clear_sky_solar_radiation_noAB_Rso (rRa, rElevation)
real(kind=T_SGL) solar_radiation_Rs (rRa, rAs, rBs, rPctSun)
real(kind=T_SGL) sat_vapor_pressure_es (rT)
real(kind=T_SGL) sat_vapor_density (rT)
real(kind=T_SGL) dewpoint_vapor_pressure_ea (rTMIN)
real(kind=T_SGL) minimum_rel_hum (rTMin, rTMax)
real(kind=T_SGL) maximum_rel_hum (rTMin)
real(kind=T_SGL) net_longwave_radiation_Rnl (rTMin, rTMax, rRs, rRso)
real(kind=T_SGL) zenith_angle (rLatitude, rDelta)
real(kind=T_SGL) slope_sat_vapor_pressure_curve (rT)
real(kind=T_SGL) calc_crop_coefficient (rKc_Max, rK0, rGDD_Kc_Max, rGDD_Death, rAlpha1, rGDD)
Function/Subroutine Documentation
real (kind=T_SGL) meteorological_functions::calc_crop_coefficient (real (kind=T_SGL) rKc_Max, real (kind=T_SGL) rK0, real (kind=T_SGL) rGDD_Kc_Max, real (kind=T_SGL) rGDD_Death, real (kind=T_SGL) rAlpha1, real (kind=T_SGL) rGDD)
Definition at line 1149 of file meteorological_functions.F90.
real (kind=T_SGL) meteorological_functions::clear_sky_solar_radiation_noAB_Rso (real (kind=T_SGL),intent(in) rRa, real (kind=T_SGL),intent(in) rElevation)
Definition at line 746 of file meteorological_functions.F90.
real (kind=T_SGL) meteorological_functions::clear_sky_solar_radiation_Rso (real (kind=T_SGL),intent(in) rRa, real (kind=T_SGL),intent(in),optional rAs_in, real (kind=T_SGL),intent(in),optional rBs_in)
Definition at line 684 of file meteorological_functions.F90.
real(kind=T_DBL) meteorological_functions::convective_heat_exchange_e (real (kind=T_SGL) rTSnow, real (kind=T_SGL) rTAvg, real (kind=T_SGL),optional rWindSpd)
Definition at line 344 of file meteorological_functions.F90.
Referenced by snow::snow_energy_balance().
real (kind=T_SGL) meteorological_functions::daylight_hours (real (kind=T_SGL),intent(in) rOmega_s)
Calculates the number of daylight hours at a location.
Parameters:
rOmega_s The sunset hour angle in Radians.
Returns:
rN The number of daylight hours.
The distance between and is .
Note:
Implemented as equation 34, Allen and others (2006).
Allen, R.G., and others, 2006, FAO Irrigation and Drainage Paper No. 56, "Crop Evapotranspiration (Guidelines for computing crop water requirements)", Food and Agriculture Organization, Rome, Italy.
Definition at line 68 of file meteorological_functions.F90.
real (kind=T_SGL) meteorological_functions::deg2rad (real (kind=T_SGL),intent(in) rDeg)
Definition at line 154 of file meteorological_functions.F90.
real (kind=T_SGL) meteorological_functions::dewpoint_vapor_pressure_ea (real (kind=T_SGL),intent(in) rTMIN)
Definition at line 896 of file meteorological_functions.F90.
Referenced by maximum_rel_hum(), minimum_rel_hum(), and net_longwave_radiation_Rnl().
real (kind=T_SGL) meteorological_functions::equivalent_evaporation (real (kind=T_SGL),intent(in) rR)
Definition at line 187 of file meteorological_functions.F90.
Referenced by et_hargreaves::et_hargreaves_ComputeET().
real (kind=T_SGL) meteorological_functions::extraterrestrial_radiation_Ra (real (kind=T_SGL),intent(in) rLatitude, real (kind=T_SGL),intent(in) rDelta, real (kind=T_SGL),intent(in) rOmega_s, real (kind=T_SGL),intent(in) rDsubR)
Definition at line 115 of file meteorological_functions.F90.
Referenced by et_hargreaves::et_hargreaves_ComputeET().
real (kind=T_SGL) meteorological_functions::maximum_rel_hum (real (kind=T_SGL),intent(in) rTMin)
Definition at line 980 of file meteorological_functions.F90.
real (kind=T_SGL) meteorological_functions::minimum_rel_hum (real (kind=T_SGL),intent(in) rTMin, real (kind=T_SGL),intent(in) rTMax)
Definition at line 937 of file meteorological_functions.F90.
real(kind=T_SGL) meteorological_functions::net_longwave_radiation_Rnl (real(kind=T_SGL),intent(in) rTMin, real(kind=T_SGL),intent(in) rTMax, real(kind=T_SGL),intent(in) rRs, real(kind=T_SGL),intent(in) rRso)
Definition at line 1026 of file meteorological_functions.F90.
Referenced by snow::snow_energy_balance().
real(kind=T_SGL) meteorological_functions::net_shortwave_radiation_Rns (real(kind=T_SGL),intent(in) rRs, real(kind=T_SGL),intent(in) rAlbedo)
Definition at line 404 of file meteorological_functions.F90.
Referenced by snow::snow_energy_balance().
real (kind=T_SGL) meteorological_functions::precipitation_heat_p (real (kind=T_SGL) rPrecipAmount, real (kind=T_SGL) rTAvg)
Definition at line 464 of file meteorological_functions.F90.
Referenced by snow::snow_energy_balance().
real (kind=T_SGL) meteorological_functions::rel_Earth_Sun_dist (integer (kind=T_INT),intent(in) iDayOfYear, integer (kind=T_INT),intent(in) iNumDaysInYear)
Definition at line 547 of file meteorological_functions.F90.
Referenced by et_hargreaves::et_hargreaves_ComputeET().
real (kind=T_SGL) meteorological_functions::row_latitude (real (kind=T_SGL),intent(in) rNorthLat, real (kind=T_SGL),intent(in) rSouthLat, integer (kind=T_INT),intent(in) iNumRows, integer (kind=T_INT),intent(in) iCurrRow)
Definition at line 222 of file meteorological_functions.F90.
Referenced by et_hargreaves::et_hargreaves_ComputeET().
real(kind=T_SGL) meteorological_functions::sat_vapor_density (real(kind=T_SGL),intent(in) rT)
Definition at line 855 of file meteorological_functions.F90.
Referenced by convective_heat_exchange_e().
real (kind=T_SGL) meteorological_functions::sat_vapor_pressure_es (real (kind=T_SGL),intent(in) rT)
Definition at line 838 of file meteorological_functions.F90.
Referenced by maximum_rel_hum(), and minimum_rel_hum().
real(kind=T_DBL) meteorological_functions::sensible_heat_exchange_h (real (kind=T_SGL) rTSnow, real (kind=T_SGL) rTAvg, real (kind=T_SGL),optional rWindSpd)
Definition at line 266 of file meteorological_functions.F90.
Referenced by snow::snow_energy_balance().
real (kind=T_SGL) meteorological_functions::slope_sat_vapor_pressure_curve (real (kind=T_SGL),intent(in) rT)
Definition at line 1131 of file meteorological_functions.F90.
real (kind=T_SGL) meteorological_functions::solar_declination (integer (kind=T_INT),intent(in) iDayOfYear, integer (kind=T_INT),intent(in) iNumDaysInYear)
Definition at line 503 of file meteorological_functions.F90.
Referenced by et_hargreaves::et_hargreaves_ComputeET().
real (kind=T_SGL) meteorological_functions::solar_radiation_Hargreaves_Rs (real (kind=T_SGL),intent(in) rRa, real (kind=T_SGL),intent(in) rTMIN, real (kind=T_SGL),intent(in) rTMAX)
Definition at line 637 of file meteorological_functions.F90.
real (kind=T_SGL) meteorological_functions::solar_radiation_Rs (real (kind=T_SGL),intent(in) rRa, real (kind=T_SGL),intent(in) rAs, real (kind=T_SGL),intent(in) rBs, real (kind=T_SGL),intent(in) rPctSun)
Definition at line 793 of file meteorological_functions.F90.
real (kind=T_SGL) meteorological_functions::sunset_angle (real (kind=T_SGL),intent(in) rLatitude, real (kind=T_SGL),intent(in) rDelta)
Definition at line 589 of file meteorological_functions.F90.
Referenced by et_hargreaves::et_hargreaves_ComputeET().
real (kind=T_SGL) meteorological_functions::zenith_angle (real (kind=T_SGL),intent(in) rLatitude, real (kind=T_SGL),intent(in) rDelta)
Definition at line 1083 of file meteorological_functions.F90.