SWB: et_hargreaves Module Reference
et_hargreaves Module Reference
Functions/Subroutines
subroutine et_hargreaves_configure (pConfig, sRecord)
subroutine et_hargreaves_initialize (pGrd, sFileName)
subroutine et_hargreaves_ComputeET (pGrd, pConfig, iDayOfYear, iNumDaysInYear)
real(kind=T_SGL) ET0_hargreaves (pConfig, rRa, rTMinF, rTMaxF)
Function/Subroutine Documentation
real (kind=T_SGL) et_hargreaves::ET0_hargreaves (type (T_MODEL_CONFIGURATION),pointer pConfig, real (kind=T_SGL),intent(in) rRa, real (kind=T_SGL),intent(in) rTMinF, real (kind=T_SGL),intent(in) rTMaxF)
Definition at line 146 of file et_hargreaves.F90.
Referenced by et_hargreaves_ComputeET().
subroutine et_hargreaves::et_hargreaves_ComputeET (type (T_GENERAL_GRID),pointer pGrd, type (T_MODEL_CONFIGURATION),pointer pConfig, integer (kind=T_INT),intent(in) iDayOfYear, integer (kind=T_INT),intent(in) iNumDaysInYear)
Definition at line 71 of file et_hargreaves.F90.
Referenced by model::model_ProcessET().
subroutine et_hargreaves::et_hargreaves_configure (type (T_MODEL_CONFIGURATION),pointer pConfig, character (len=*),intent(inout) sRecord)
Definition at line 29 of file et_hargreaves.F90.
subroutine et_hargreaves::et_hargreaves_initialize (type (T_GENERAL_GRID),pointer pGrd, character (len=*),intent(in) sFileName)
Definition at line 56 of file et_hargreaves.F90.
Referenced by model::model_InitializeET().