SWB: types Module Reference
types Module Reference
User-defined types for the SWB code.
Data Types
type T_CELL
Type that contains the data for an individual grid cell.
type T_GENERAL_GRID
Type that contains the data for a grid.
type T_GRID_COLLECTION
type T_LANDUSE_LOOKUP
Container for land-use related data.
type T_IRRIGATION_LOOKUP
type T_BASIN_MASK
container for basin mask table data
type T_SSF_FILES
container for SSF file information
type T_NETCDF_FILE
type T_MONTH
Container for calendar lookup information.
type T_STATS
Type that contains parameters for graphings and stats calculations.
type T_MODEL_CONFIGURATION
Type that contains model configuration data.
type T_TIME_SERIES_FILE
data structure to hold a line of input from the classic time-series file
type T_GRAPH_CONFIGURATION
Type that holds parameters used to create graphics with the DISLIN library.
interface approx_equal
Functions/Subroutines
subroutine Assert (lCondition, sErrorMessage, sFilename, iLineNo)
General-purpose error-checking routine.
subroutine Chomp (sRecord, sItem)
subroutine GetSysTimeDate (sDateStr, sDateStrPretty)
subroutine Chomp_tab (sRecord, sItem)
subroutine Chomp_slash (sRecord, sItem)
integer(kind=T_INT) mmddyyyy2julian (sMMDDYYYY)
integer(kind=T_INT) mmddyyyy2doy (sMMDDYYYY)
subroutine Uppercase (s)
subroutine CleanUpCsv (s)
subroutine CleanUpSlash (s)
real(kind=T_SGL) polynomial (x, a)
subroutine LookupMonth (iMonth, iDay, iYear, iDayOfYear, sMonthName, lMonthEnd)
logical(kind=T_LOGICAL) approx_equal_dbl (rA, rB, rTol)
logical(kind=T_LOGICAL) approx_equal_sgl (rA, rB, rTol)
logical(kind=T_LOGICAL) lf_model_GrowingSeason (pConfig, iDayOfYear)
real(kind=T_SGL) FtoC (rF)
real(kind=T_SGL) CtoF (rC)
real(kind=T_SGL) FtoK (rF)
integer(kind=T_INT) count_fields (sRecord)
real(kind=T_SGL) mm_to_in (r_mm)
real(kind=T_SGL) interpolate (rXT, rYT, rX)
integer(kind=T_INT) julian_day (iYear, iMonth, iDay, iOrigin)
integer(kind=T_INT) solstice (iJD)
character(len=256) int2char (iValue)
Convert an integer value into a formatted character string.
character(len=256) real2char (rValue, iDec, iWidth)
Convert a real value into a formatted character string.
integer(kind=T_INT) num_days_in_year (iYear)
Return the number of days in the given year.
integer(kind=T_INT) day_of_year (iJD)
subroutine gregorian_date (iJD, iYear, iMonth, iDay, iOrigin)
Convert from a Julian day number to a Gregorian date.
Variables
integer, parameter, public T_LOGICAL = 4
Define the sizes of base types used in the model.
integer, parameter, public T_INT = 4
integer, parameter, public T_SHORT = 2
integer, parameter, public T_BYTE = 1
integer, parameter, public T_SGL_DISLIN = 4
integer, parameter, public T_SGL = SELECTED_REAL_KIND(p=6, r=37)
Define machine-independent sizes for base types.
integer, parameter, public T_DBL = SELECTED_REAL_KIND(p=13, r=200)
integer(kind=T_INT), parameter,
public LU_STD_OUT = 6
I/O Units.
integer(kind=T_INT), parameter,
public LU_CONTROL = 100
integer(kind=T_INT), parameter,
public LU_GRID = 101
integer(kind=T_INT), parameter,
public LU_LOOKUP = 102
integer(kind=T_INT), parameter,
public LU_TS = 103
integer(kind=T_INT), parameter,
public LU_TEMP = 104
integer(kind=T_INT), parameter,
public LU_MSB_REPORT = 105
integer(kind=T_INT), parameter,
public LU_BIN_FILE = 106
integer(kind=T_INT), parameter,
public LU_ROUTING = 107
integer(kind=T_INT), parameter,
public LU_CSV = 108
integer(kind=T_INT), parameter,
public LU_CSV_SERIES = 109
integer(kind=T_INT), parameter,
public LU_CSV_ANNUAL = 110
integer(kind=T_INT), parameter,
public LU_MASK = 111
integer(kind=T_INT), parameter,
public LU_MASK_FILE = 112
integer(kind=T_INT), parameter,
public LU_MASK_STATS_CSV = 113
integer(kind=T_INT), parameter,
public LU_PEST_STATS = 114
integer(kind=T_INT), parameter,
public LU_PEST_OBS = 115
integer(kind=T_INT), parameter,
public LU_PEST_INS = 116
integer(kind=T_INT), parameter,
public LU_LOG = 117
character(len=1), parameter, public sTAB = achar(9)
character(len=1), parameter, public sBACKSLASH = achar(92)
character(len=1), parameter, public sFORWARDSLASH = achar(47)
real(kind=T_SGL), parameter, public rZERO = 0.0_T_SGL
Some useful typed constants (to ensure accurate computations)
real(kind=T_DBL), parameter, public rD_ZERO = 0.0_T_DBL
real(kind=T_SGL), parameter, public rNEAR_ZERO = 1E-9_T_SGL
real(kind=T_SGL), parameter, public rPOINT2 = 0.2_T_SGL
real(kind=T_SGL), parameter, public rHALF = 0.5_T_SGL
real(kind=T_SGL), parameter, public rPOINT8 = 0.8_T_SGL
real(kind=T_SGL), parameter, public rONE = 1.0_T_SGL
real(kind=T_DBL), parameter, public rD_ONE = 1.0_T_DBL
real(kind=T_SGL), parameter, public rFREEZING = 32.0_T_SGL
real(kind=T_SGL), parameter, public rTEN = 10.0_T_SGL
real(kind=T_SGL), parameter, public rHUNDRED = 100.0_T_SGL
real(kind=T_SGL), parameter, public rTHOUSAND = 1000.0_T_SGL
real(kind=T_DBL), parameter, public rC_PER_F = 5.0_T_DBL / 9.0_T_DBL
real(kind=T_DBL), parameter, public rF_PER_C = 9.0_T_DBL / 5.0_T_DBL
real(kind=T_SGL), parameter, public rMM_PER_INCH = 25.4_T_SGL
real(kind=T_SGL), parameter, public rCM_PER_INCH = 2.54_T_SGL
real(kind=T_DBL), parameter, public rPI = 3.14159265_T_DBL
real(kind=T_DBL), parameter, public rTWOPI = 2.0_T_DBL * rPI
real(kind=T_DBL), parameter, public rSQM_to_SQFT = 10.76391_T_DBL
integer(kind=T_INT), parameter,
public iMOVING_AVG_TERMS = 5
integer(kind=T_INT), parameter,
public iROUTE_CELL_MARKED = -1
integer(kind=T_INT), parameter,
public iROUTE_DEPRESSION = -999
integer(kind=T_INT), parameter,
public iROUTE_LEFT_GRID = -1000
integer(kind=T_INT), parameter,
public iNO_DATA_NCDC = -99999
integer(kind=T_INT), parameter,
public iNUM_DIGITS = 3
integer(kind=T_INT), parameter,
public iFIELD_WIDTH = 10
integer(kind=T_INT), parameter,
public iZERO = 0
logical(kind=T_LOGICAL),
parameter, public lTRUE = .true._T_LOGICAL
logical(kind=T_LOGICAL),
parameter, public lFALSE = .false._T_LOGICAL
integer(kind=T_INT), parameter iEOF = HUGE(iZERO)
real(kind=T_SGL), parameter, public rBIGVAL = 1.0e20_T_SGL
integer(kind=T_INT), public iSTARTDATE_POS
integer(kind=T_INT), public iENDDATE_POS
integer(kind=T_INT), public iENDHEADER_POS
integer(kind=T_INT), parameter,
public iNC_INPUT = 1
integer(kind=T_INT), parameter,
public iNC_OUTPUT = 2
integer(kind=T_INT), parameter,
public iNC_OBSERVATION = 3
character(len=7), parameter sRED = char(27)//'[1;31m'
Define ANSI.sys-like text colors.
character(len=7), parameter sGREEN = char(27)//'[1;32m'
character(len=7), parameter sYELLOW = char(27)//'[1;33m'
character(len=7), parameter sBLUE = char(27)//'[1;34m'
character(len=7), parameter sCYAN = char(27)//'[1;36m'
character(len=7), parameter sWHITE = char(27)//'[0;37m'
character(len=7), parameter sBOLDWHITE = char(27)//'[1;37m'
character(len=7), parameter sCLRSCR = char(27)//'[2J'
integer(kind=T_INT), parameter,
public T_INT_GRID = 0
integer(kind=T_INT), parameter,
public T_SGL_GRID = 1
integer(kind=T_INT), parameter,
public T_CELL_GRID = 2
integer(kind=T_INT), parameter iGRID_LENGTH_UNITS_METERS = 0
define parameter values for working with type T_GENERAL_GRID
integer(kind=T_INT), parameter iGRID_LENGTH_UNITS_FEET = 1
type(T_MONTH), dimension(12),
target YEAR_INFO = (/ T_MONTH('JAN','JANUARY ', 1, 31, 1, 31), T_MONTH('FEB','FEBRUARY ', 32, 59, 2, 29), T_MONTH('MAR','MARCH ', 60, 90, 3, 31), T_MONTH('APR','APRIL ', 91, 120, 4, 30), T_MONTH('MAY','MAY ', 121, 151, 5, 31), T_MONTH('JUN','JUNE ', 152, 181, 6, 30), T_MONTH('JUL','JULY ', 182, 212, 7, 31), T_MONTH('AUG','AUGUST ', 213, 243, 8, 31), T_MONTH('SEP','SEPTEMBER', 244, 273, 9, 30), T_MONTH('OCT','OCTOBER ', 274, 304, 10, 31), T_MONTH('NOV','NOVEMBER ', 305, 334, 11, 30), T_MONTH('DEC','DECEMBER ', 335, 365, 12, 31) /)
Month information.
character(len=256), public sLogBuffer
integer(kind=T_INT), parameter iNUM_MONTHS = 12
integer(kind=T_INT), parameter iNONE = 0
integer(kind=T_INT), parameter iGRID = 1
integer(kind=T_INT), parameter iGRAPH = 2
integer(kind=T_INT), parameter iBOTH = 3
integer(kind=T_INT), parameter iSTATS = 4
integer(kind=T_INT), parameter iNUM_VARIABLES = 29
type(T_STATS), dimension(inum_variables) STAT_INFO = (/ T_STATS ('GROSS_PRECIP',201,2,0,lTRUE,lTRUE, 'inches','gross precipitation', 1.,0.0, iNONE,iNONE,iNONE,iNONE), T_STATS ('SNOWFALL',202,0,1,lTRUE,lTRUE, 'inches','precipitation falling as snow', 1.,0.0, iNONE,iNONE,iNONE,iNONE), T_STATS ('SNOWCOVER',203,2,0,lFALSE,lTRUE, 'inches','water equivalent of snow cover', 1.,0.0, iNONE,iNONE,iNONE,iNONE), T_STATS ('CFGI',204,2,0,lFALSE,lFALSE, 'unitless','continuous frozen ground index', 1.,0.0, iNONE,iNONE,iNONE,iNONE), T_STATS ('MIN_TEMP',205,2,0,lFALSE,lFALSE, 'degrees F','minimum daily air temperature', 1.,0.0, iNONE,iNONE,iNONE,iNONE), T_STATS ('MAX_TEMP',206,2,0,lFALSE,lFALSE, 'degrees F','maximum daily air temperature', 1.,0.0, iNONE,iNONE,iNONE,iNONE), T_STATS ('AVG_TEMP',207,2,0,lFALSE,lFALSE, 'degrees F','mean daily air temperature', 1.,0.0, iNONE,iNONE,iNONE,iNONE), T_STATS ('CHG_IN_SNOW_COV',208,0,-1,lTRUE,lTRUE, 'inches','snowfall minus snowmelt', 1.,0.0, iNONE,iNONE,iNONE,iNONE), T_STATS ('SNOWMELT',209,2,0,lTRUE,lTRUE, 'inches','snowmelt', 1.,0.0, iNONE,iNONE,iNONE,iNONE), T_STATS ('INTERCEPTION',210,2,0,lTRUE,lTRUE, 'inches','interception', 1.,0.0, iNONE,iNONE,iNONE,iNONE), T_STATS ('NET_PRECIP',211,0,1,lTRUE,lTRUE, 'inches','gross precipitation minus interception', 1.,0.0, iNONE,iNONE,iNONE,iNONE), T_STATS ('INFLOW',212,0,1,lTRUE,lTRUE, 'inches','incoming flow from adjacent cells', 1.,0.0, iNONE,iNONE,iNONE,iNONE), T_STATS ('OUTFLOW',213,0,-1,lTRUE,lTRUE, 'inches','outgoing flow to adjacent cells', 1.,0.0, iNONE,iNONE,iNONE,iNONE), T_STATS ('RUNOFF_OUTSIDE',214,0,-1,lTRUE,lTRUE, 'inches','runoff leaving model domain', 1.,0.0, iNONE,iNONE,iNONE,iNONE), T_STATS ('REJECTED_RECHARGE',215,0,-1,lTRUE,lTRUE, 'inches','recharge exceeding max recharge rate', 1.,0.0, iNONE,iNONE,iNONE,iNONE), T_STATS ('NET_INFLOW',216,2,0,lTRUE,lTRUE, 'inches','sum of net precip and inflow', 1.,0.0, iNONE,iNONE,iNONE,iNONE), T_STATS ('NET_INFIL',217,2,0,lTRUE,lTRUE, 'inches','precip and inflow minus outflow', 1.,0.0, iNONE,iNONE,iNONE,iNONE), T_STATS ('POT_ET',218,2,0,lTRUE,lTRUE, 'inches','potential evapotranspiration', 1.,0.0, iNONE,iNONE,iNONE,iNONE), T_STATS ('ACT_ET',219,0,-1,lTRUE,lTRUE, 'inches','actual evapotranspiration', 1.,0.0, iNONE,iNONE,iNONE,iNONE), T_STATS ('P_MINUS_PET',220,2,0,lTRUE,lFALSE, 'inches','net inflow minus potential et', 1.,0.0, iNONE,iNONE,iNONE,iNONE), T_STATS ('SM_DEFICIT',221,2,0,lTRUE,lFALSE, 'inches','daily soil moisture deficit', 1.,0.0, iNONE,iNONE,iNONE,iNONE), T_STATS ('SM_SURPLUS',222,2,0,lTRUE,lFALSE, 'inches','daily soil moisture surplus', 1.,0.0, iNONE,iNONE,iNONE,iNONE), T_STATS ('SM_APWL',223,2,0,lFALSE,lFALSE, 'inches','accumulated potential water loss', 1.,0.0, iNONE,iNONE,iNONE,iNONE), T_STATS ('SOIL_MOISTURE',224,2,0,lFALSE,lTRUE, 'inches','daily soil moisture', 1.,0.0, iNONE,iNONE,iNONE,iNONE), T_STATS ('CHG_IN_SOIL_MOIS',225,0,-1,lTRUE,lTRUE, 'inches','daily change in soil moisture', 1.,0.0, iNONE,iNONE,iNONE,iNONE), T_STATS ('RECHARGE',226,0,-1,lTRUE,lTRUE, 'inches','daily potential recharge', 1.,0.0, iNONE,iNONE,iNONE,iNONE), T_STATS ('GDD',227,2,0,lFALSE,lFALSE, 'degree-day','growing degree day', 1.,0.0, iNONE,iNONE,iNONE,iNONE), T_STATS ('IRRIGATION_AMOUNT',228,0,1,lTRUE,lTRUE, 'inches','daily estimated irrigation amount', 1.,0.0, iNONE,iNONE,iNONE,iNONE) ,T_STATS ('STREAM_CAPTURE',229,0,-1,lTRUE,lTRUE, 'inches','runoff or recharge captured by a stream or fracture', 1.,0.0, iNONE,iNONE,iNONE,iNONE)/)
integer(kind=T_INT), parameter iNUM_STATS = 5
integer(kind=T_INT), parameter iMIN = 1
integer(kind=T_INT), parameter iMEAN = 2
integer(kind=T_INT), parameter iMAX = 3
integer(kind=T_INT), parameter iSUM = 4
integer(kind=T_INT), parameter iLENGTH = 5
integer(kind=T_INT), parameter iGROSS_PRECIP = 1
integer(kind=T_INT), parameter iSNOWFALL = 2
integer(kind=T_INT), parameter iSNOWCOVER = 3
integer(kind=T_INT), parameter iCFGI = 4
integer(kind=T_INT), parameter iMIN_TEMP = 5
integer(kind=T_INT), parameter iMAX_TEMP = 6
integer(kind=T_INT), parameter iAVG_TEMP = 7
integer(kind=T_INT), parameter iCHG_IN_SNOW_COV = 8
integer(kind=T_INT), parameter iSNOWMELT = 9
integer(kind=T_INT), parameter iINTERCEPTION = 10
integer(kind=T_INT), parameter iNET_PRECIP = 11
integer(kind=T_INT), parameter iINFLOW = 12
integer(kind=T_INT), parameter iOUTFLOW = 13
integer(kind=T_INT), parameter iRUNOFF_OUTSIDE = 14
integer(kind=T_INT), parameter iREJECTED_RECHARGE = 15
integer(kind=T_INT), parameter iNET_INFLOW = 16
integer(kind=T_INT), parameter iNET_INFIL = 17
integer(kind=T_INT), parameter iPOT_ET = 18
integer(kind=T_INT), parameter iACT_ET = 19
integer(kind=T_INT), parameter iP_MINUS_PET = 20
integer(kind=T_INT), parameter iSM_DEFICIT = 21
integer(kind=T_INT), parameter iSM_SURPLUS = 22
integer(kind=T_INT), parameter iSM_APWL = 23
integer(kind=T_INT), parameter iSOIL_MOISTURE = 24
integer(kind=T_INT), parameter iCHG_IN_SOIL_MOIST = 25
integer(kind=T_INT), parameter iRECHARGE = 26
integer(kind=T_INT), parameter iGDD = 27
integer(kind=T_INT), parameter iIRRIGATION = 28
integer(kind=T_INT), parameter iSTREAM_CAPTURE = 29
integer(kind=T_INT), parameter STREAM_INTERACTIONS_MAX = 100
integer(kind=T_INT), parameter iDAILY = 1
integer(kind=T_INT), parameter iMONTHLY = 2
integer(kind=T_INT), parameter iANNUAL = 3
integer(kind=T_INT), parameter CONFIG_RUNOFF_CURVE_NUMBER = 0
integer(kind=T_INT), parameter CONFIG_RUNOFF_GREEN_AMPT = 1
integer(kind=T_INT), parameter CONFIG_RUNOFF_ITERATIVE = 0
integer(kind=T_INT), parameter CONFIG_RUNOFF_DOWNHILL = 1
integer(kind=T_INT), parameter CONFIG_RUNOFF_NO_ROUTING = 2
integer(kind=T_INT), parameter CONFIG_ET_NONE = 0
integer(kind=T_INT), parameter CONFIG_ET_THORNTHWAITE_MATHER = 1
integer(kind=T_INT), parameter CONFIG_ET_TURC = 2
integer(kind=T_INT), parameter CONFIG_ET_JENSEN_HAISE = 3
integer(kind=T_INT), parameter CONFIG_ET_BLANEY_CRIDDLE = 4
integer(kind=T_INT), parameter CONFIG_ET_HARGREAVES = 5
integer(kind=T_INT), parameter CONFIG_PRECIP_SINGLE_STATION = 0
integer(kind=T_INT), parameter CONFIG_PRECIP_ARC_GRID = 1
integer(kind=T_INT), parameter CONFIG_PRECIP_SURFER_GRID = 2
integer(kind=T_INT), parameter CONFIG_PRECIP_NETCDF = 3
integer(kind=T_INT), parameter CONFIG_TEMPERATURE_SINGLE_STATION = 0
integer(kind=T_INT), parameter CONFIG_TEMPERATURE_ARC_GRID = 1
integer(kind=T_INT), parameter CONFIG_TEMPERATURE_SURFER_GRID = 2
integer(kind=T_INT), parameter CONFIG_TEMPERATURE_NETCDF = 3
integer(kind=T_INT), parameter CONFIG_LANDUSE_CONSTANT = 0
integer(kind=T_INT), parameter CONFIG_LANDUSE_DYNAMIC_ARC_GRID = 1
integer(kind=T_INT), parameter CONFIG_LANDUSE_DYNAMIC_SURFER = 2
integer(kind=T_INT), parameter CONFIG_LANDUSE_DYNAMIC_NETCDF = 3
integer(kind=T_INT), parameter CONFIG_LANDUSE_STATIC_GRID = 4
integer(kind=T_INT), parameter CONFIG_SNOW_ORIGINAL_SWB = 0
integer(kind=T_INT), parameter CONFIG_SNOW_NEW_SWB = 1
integer(kind=T_INT), parameter CONFIG_SM_CAPACITY_CALCULATE = 0
integer(kind=T_INT), parameter CONFIG_SM_CAPACITY_CONSTANT = 1
integer(kind=T_INT), parameter CONFIG_SM_CAPACITY_FM_TABLE = 2
integer(kind=T_INT), parameter CONFIG_SM_NONE = 0
integer(kind=T_INT), parameter CONFIG_SM_THORNTHWAITE_MATHER = 1
integer(kind=T_INT), parameter CONFIG_SM_INIT_ABSTRACTION_TR55 = 0
integer(kind=T_INT), parameter CONFIG_SM_INIT_ABSTRACTION_HAWKINS = 1
integer(kind=T_INT), parameter CONFIG_ESTIMATE_MISSING_DATA = 0
integer(kind=T_INT), parameter CONFIG_END_IF_MISSING_DATA = 1
integer(kind=T_INT), parameter OUTPUT_SURFER = 0
integer(kind=T_INT), parameter OUTPUT_ARC = 1
Detailed Description
User-defined types for the SWB code.
This module defines parameters and project specific data types for the SWB model. This module also contains a number of utility functions that perform string manipulations, convert Celcius to Fahrenheit, and convert between Julian days and Gregorian dates.
Function/Subroutine Documentation
logical(kind=T_LOGICAL) types::approx_equal_dbl (real(kind=T_DBL) rA, real(kind=T_DBL) rB, real(kind=T_DBL),optional rTol)
Definition at line 1442 of file types.F90.
logical(kind=T_LOGICAL) types::approx_equal_sgl (real(kind=T_SGL) rA, real(kind=T_SGL) rB, real(kind=T_SGL),optional rTol)
Definition at line 1474 of file types.F90.
subroutine types::Assert (logical (kind=T_LOGICAL),intent(in) lCondition, character (len=*),intent(in) sErrorMessage, character (len=*),optional sFilename, integer (kind=T_INT),optional iLineNo)
General-purpose error-checking routine.
General-purpose error-checking routine. If lCondition is .false., prints the error message and stops!
Definition at line 894 of file types.F90.
Referenced by swbstats_support::CalcBasinStats(), control::control_setModelOptions(), et_blaney_criddle::et_bc_ComputeET(), et_blaney_criddle::et_bc_configure(), et_hargreaves::et_hargreaves_configure(), et_jensen_haise::et_jh_ComputeET(), et_jensen_haise::et_jh_configure(), et_thornthwaite_mather::et_tm_configure(), et_thornthwaite_mather::et_tm_initialize(), et_turc::et_turc_ComputeET(), et_turc::et_turc_configure(), swb_grid::grid_Create(), swb_grid::grid_Destroy(), swb_grid::grid_Interpolate(), swb_grid::grid_Read(), swb_grid::grid_ReadArcGrid(), swb_grid::grid_ReadSurferGrid(), swb_grid::grid_SearchColumn(), swb_grid::grid_WriteArcGrid(), swb_grid::grid_WriteSurferGrid(), model::if_model_RunoffIteration(), interpolate(), julian_day(), graph::make_shaded_contour(), graph::makegraph(), mmddyyyy2doy(), mmddyyyy2julian(), model::model_ConfigureRunoffDownhill(), model::model_GetDailyPrecipValue(), model::model_GetDailyTemperatureValue(), model::model_GetDynamicLanduseValue(), model::model_InitializeET(), model::model_InitializeMaxInfil(), model::model_InitializeSM(), model::model_ProcessET(), model::model_ProcessRain(), model::model_ProcessRunoff(), model::model_ProcessSM(), model::model_ReadBasinMaskTable(), model::model_ReadLanduseLookupTable(), model::model_ReadTimeSeriesFile(), model::model_RunoffDownhill(), model::model_Solve(), model::model_WriteGrids(), netcdf_support::netcdf_check(), netcdf_support::netcdf_chk_extent(), netcdf_support::netcdf_info(), netcdf_support::netcdf_read(), runoff_curve_number::prob_runoff_enhancement(), swbstats_support::ReadBasinMaskTable(), model::rf_model_CellRunoff(), model::rf_model_CellRunoff_GreenAmpt(), model::rf_model_GetInterception(), RLE::RLE_readByte(), runoff_curve_number::runoff_CellRunoff_CurveNumber(), runoff_curve_number::runoff_InitializeCurveNumber(), sm_thornthwaite_mather::sm_thornthwaite_mather_Configure(), sm_thornthwaite_mather::sm_thornthwaite_mather_UpdateSM(), swb_stats::stats_CalcBasinStats(), swb_stats::stats_CalcMeanRechargebyLU(), swb_stats::stats_InitializeVolumeConversion(), swb_stats::stats_UpdateAllAccumulatorsByCell(), swb_stats::stats_UpdateAllAccumulatorsByGrid(), swb_stats::stats_write_to_SSF_file(), meteorological_functions::sunset_angle(), swbread(), swbstats(), and meteorological_functions::zenith_angle().
subroutine types::Chomp (character (len=*),intent(inout) sRecord, character (len=256),intent(out) sItem)
Definition at line 955 of file types.F90.
Referenced by control::control_setModelOptions(), et_blaney_criddle::et_bc_configure(), et_hargreaves::et_hargreaves_configure(), et_jensen_haise::et_jh_configure(), et_thornthwaite_mather::et_tm_configure(), et_turc::et_turc_configure(), swb_grid::grid_ReadArcGrid(), netcdf_support::netcdf_info(), and sm_thornthwaite_mather::sm_thornthwaite_mather_Configure().
subroutine types::Chomp_slash (character (len=*),intent(inout) sRecord, character (len=256),intent(out) sItem)
Definition at line 1099 of file types.F90.
Referenced by mmddyyyy2doy(), mmddyyyy2julian(), swbread(), and swbstats().
subroutine types::Chomp_tab (character (len=*),intent(inout) sRecord, character (len=256),intent(out) sItem)
Definition at line 1047 of file types.F90.
Referenced by count_fields(), model::model_ReadBasinMaskTable(), model::model_ReadLanduseLookupTable(), and swbstats_support::ReadBasinMaskTable().
subroutine types::CleanUpCsv (character (len=*),intent(inout) s)
Definition at line 1265 of file types.F90.
Referenced by et_thornthwaite_mather::et_tm_initialize(), and model::model_ReadTimeSeriesFile().
subroutine types::CleanUpSlash (character (len=*),intent(inout) s)
Definition at line 1300 of file types.F90.
integer(kind=T_INT) types::count_fields (character (len=*),intent(inout) sRecord)
Definition at line 1638 of file types.F90.
real (kind=T_SGL) types::CtoF (real (kind=T_SGL),intent(in) rC)
Definition at line 1596 of file types.F90.
Referenced by snow::snow_energy_balance().
integer (kind=T_INT) types::day_of_year (integer (kind=T_INT),intent(in) iJD)
Definition at line 1932 of file types.F90.
real (kind=T_SGL) types::FtoC (real (kind=T_SGL),intent(in) rF)
Definition at line 1568 of file types.F90.
Referenced by meteorological_functions::dewpoint_vapor_pressure_ea(), et_hargreaves::ET0_hargreaves(), et_blaney_criddle::et_bc_ComputeET(), et_jensen_haise::et_jh_ComputeET(), et_turc::et_turc_ComputeET(), model::model_ProcessRainPRMS(), model::model_UpdateContinuousFrozenGroundIndex(), meteorological_functions::precipitation_heat_p(), meteorological_functions::sat_vapor_density(), meteorological_functions::sat_vapor_pressure_es(), meteorological_functions::sensible_heat_exchange_h(), meteorological_functions::slope_sat_vapor_pressure_curve(), snow::snow_depth_Hedstrom(), snow::snow_energy_balance(), and meteorological_functions::solar_radiation_Hargreaves_Rs().
real (kind=T_SGL) types::FtoK (real (kind=T_SGL),intent(in) rF)
Definition at line 1624 of file types.F90.
Referenced by et_hargreaves::ET0_hargreaves(), meteorological_functions::net_longwave_radiation_Rnl(), and meteorological_functions::sat_vapor_density().
subroutine types::GetSysTimeDate (character(len=256),intent(out) sDateStr, character(len=256),intent(out) sDateStrPretty)
Definition at line 987 of file types.F90.
Referenced by netcdf_support::netcdf_write_attributes().
subroutine types::gregorian_date (integer (kind=T_INT) iJD, integer (kind=T_INT),intent(inout) iYear, integer (kind=T_INT),intent(inout) iMonth, integer (kind=T_INT),intent(inout) iDay, integer (kind=T_INT),optional iOrigin)
Convert from a Julian day number to a Gregorian date.
Converts from a Julian day number to a Gregorian date. Valid for any Gregorian calendar date producing a Julian day number greater than zero.
Reference: Fliegel, H. F. and van Flandern, T. C. (1968). Communications of the ACM, Vol. 11, No. 10 (October, 1968).
Modified from code found at: http://aa.usno.navy.mil/faq/docs/JD_Formula.html
Definition at line 1985 of file types.F90.
Referenced by control::control_setModelOptions(), day_of_year(), LookupMonth(), model::model_Solve(), netcdf_support::netcdf_info(), netcdf_support::netcdf_write_attributes(), solstice(), swbread(), and swbstats().
character(len=256) types::int2char (integer (kind=T_INT) iValue)
Convert an integer value into a formatted character string.
Definition at line 1861 of file types.F90.
Referenced by control::control_setModelOptions(), swb_grid::grid_ReadArcGrid(), swb_grid::grid_WriteArcGrid(), swb_grid::grid_WriteSurferGrid(), julian_day(), main(), model::model_ConfigureRunoffDownhill(), model::model_ProcessRunoff(), model::model_Solve(), netcdf_support::netcdf_check(), netcdf_support::netcdf_info(), real2char(), swb_stats::stats_CloseBinaryFiles(), swb_stats::stats_OpenBinaryFiles(), swb_stats::stats_write_to_SSF_file(), swbread(), and swbstats().
real (kind=T_SGL) types::interpolate (real (kind=T_SGL),dimension(:),intent(in) rXT, real (kind=T_SGL),dimension(:),intent(in) rYT, real (kind=T_SGL),intent(in) rX)
Definition at line 1717 of file types.F90.
integer (kind=T_INT) types::julian_day (integer (kind=T_INT),intent(in) iYear, integer (kind=T_INT),intent(in) iMonth, integer (kind=T_INT),intent(in) iDay, integer (kind=T_INT),optional iOrigin)
Definition at line 1767 of file types.F90.
Referenced by control::control_setModelOptions(), day_of_year(), LookupMonth(), mmddyyyy2doy(), mmddyyyy2julian(), model::model_Solve(), netcdf_support::netcdf_info(), num_days_in_year(), sm_thornthwaite_mather::sm_thornthwaite_mather_UpdateSM(), swbread(), and swbstats().
logical (kind=T_LOGICAL) types::lf_model_GrowingSeason (type (T_MODEL_CONFIGURATION),pointer pConfig, integer (kind=T_INT),intent(in) iDayOfYear)
Definition at line 1532 of file types.F90.
Referenced by model::rf_model_GetInterception(), and runoff_curve_number::runoff_UpdateCurveNumber().
subroutine types::LookupMonth (integer (kind=T_INT),intent(in) iMonth, integer (kind=T_INT),intent(in) iDay, integer (kind=T_INT),intent(in) iYear, integer (kind=T_INT),intent(out) iDayOfYear, character (len=3),intent(out) sMonthName, logical (kind=T_LOGICAL),intent(out) lMonthEnd)
Definition at line 1386 of file types.F90.
Referenced by et_thornthwaite_mather::et_tm_initialize(), model::model_Solve(), swb_stats::stats_RewriteGrids(), swbread(), and swbstats().
real (kind=T_SGL) types::mm_to_in (real (kind=T_SGL),intent(in) r_mm)
Definition at line 1679 of file types.F90.
integer (kind=T_INT) types::mmddyyyy2doy (character (len=*) sMMDDYYYY)
Definition at line 1172 of file types.F90.
Referenced by model::model_ReadLanduseLookupTable().
integer (kind=T_INT) types::mmddyyyy2julian (character (len=*) sMMDDYYYY)
Definition at line 1132 of file types.F90.
Referenced by swbread(), and swbstats().
integer (kind=T_INT) types::num_days_in_year (integer (kind=T_INT),intent(in) iYear)
Return the number of days in the given year.
This function simply returns the number of days given the current year.
Definition at line 1915 of file types.F90.
Referenced by control::control_setModelOptions(), model::model_Solve(), swbread(), and swbstats().
real (kind=T_SGL) types::polynomial (real (kind=T_SGL),intent(in) x, real (kind=T_SGL),dimension(:) a)
Definition at line 1337 of file types.F90.
Referenced by et_thornthwaite_mather::et_tm_ComputeET(), and et_thornthwaite_mather::et_tm_initialize().
character(len=256) types::real2char (real (kind=T_SGL) rValue, integer (kind=T_INT),optional iDec, integer (kind=T_INT),optional iWidth)
Convert a real value into a formatted character string.
Definition at line 1876 of file types.F90.
Referenced by swb_grid::grid_WriteArcGrid(), swb_grid::grid_WriteSurferGrid(), netcdf_support::netcdf_check(), and netcdf_support::netcdf_read().
integer (kind=T_INT) types::solstice (integer (kind=T_INT),intent(in) iJD)
Definition at line 1828 of file types.F90.
subroutine types::Uppercase (character (len=*),intent(inout) s)
Definition at line 1231 of file types.F90.
Referenced by control::control_setModelOptions(), swb_grid::grid_ReadArcGrid(), model::model_ReadBasinMaskTable(), model::model_ReadLanduseLookupTable(), and swbstats_support::ReadBasinMaskTable().
Variable Documentation
integer (kind=T_INT),parameter types::CONFIG_END_IF_MISSING_DATA = 1
Definition at line 873 of file types.F90.
Referenced by control::control_setModelOptions().
integer (kind=T_INT),parameter types::CONFIG_ESTIMATE_MISSING_DATA = 0
Definition at line 872 of file types.F90.
integer (kind=T_INT),parameter types::CONFIG_ET_BLANEY_CRIDDLE = 4
Definition at line 831 of file types.F90.
Referenced by control::control_setModelOptions(), model::model_InitializeET(), and model::model_ProcessET().
integer (kind=T_INT),parameter types::CONFIG_ET_HARGREAVES = 5
Definition at line 832 of file types.F90.
Referenced by control::control_setModelOptions(), model::model_InitializeET(), and model::model_ProcessET().
integer (kind=T_INT),parameter types::CONFIG_ET_JENSEN_HAISE = 3
Definition at line 830 of file types.F90.
Referenced by control::control_setModelOptions(), model::model_InitializeET(), and model::model_ProcessET().
integer (kind=T_INT),parameter types::CONFIG_ET_NONE = 0
Definition at line 827 of file types.F90.
Referenced by control::control_setModelOptions(), model::model_InitializeET(), and model::model_ProcessET().
integer (kind=T_INT),parameter types::CONFIG_ET_THORNTHWAITE_MATHER = 1
Definition at line 828 of file types.F90.
Referenced by control::control_setModelOptions(), model::model_InitializeET(), and model::model_ProcessET().
integer (kind=T_INT),parameter types::CONFIG_ET_TURC = 2
Definition at line 829 of file types.F90.
Referenced by control::control_setModelOptions(), model::model_InitializeET(), and model::model_ProcessET().
integer (kind=T_INT),parameter types::CONFIG_LANDUSE_CONSTANT = 0
Definition at line 848 of file types.F90.
Referenced by control::control_setModelOptions().
integer (kind=T_INT),parameter types::CONFIG_LANDUSE_DYNAMIC_ARC_GRID = 1
Definition at line 849 of file types.F90.
Referenced by control::control_setModelOptions(), model::model_GetDynamicLanduseValue(), and model::model_Solve().
integer (kind=T_INT),parameter types::CONFIG_LANDUSE_DYNAMIC_NETCDF = 3
Definition at line 851 of file types.F90.
integer (kind=T_INT),parameter types::CONFIG_LANDUSE_DYNAMIC_SURFER = 2
Definition at line 850 of file types.F90.
Referenced by control::control_setModelOptions(), model::model_GetDynamicLanduseValue(), and model::model_Solve().
integer (kind=T_INT),parameter types::CONFIG_LANDUSE_STATIC_GRID = 4
Definition at line 852 of file types.F90.
Referenced by control::control_setModelOptions().
integer (kind=T_INT),parameter types::CONFIG_PRECIP_ARC_GRID = 1
Definition at line 836 of file types.F90.
Referenced by control::control_setModelOptions(), and model::model_GetDailyPrecipValue().
integer (kind=T_INT),parameter types::CONFIG_PRECIP_NETCDF = 3
Definition at line 838 of file types.F90.
Referenced by control::control_setModelOptions(), and model::model_GetDailyPrecipValue().
integer (kind=T_INT),parameter types::CONFIG_PRECIP_SINGLE_STATION = 0
Definition at line 835 of file types.F90.
Referenced by control::control_setModelOptions(), and model::model_GetDailyPrecipValue().
integer (kind=T_INT),parameter types::CONFIG_PRECIP_SURFER_GRID = 2
Definition at line 837 of file types.F90.
Referenced by control::control_setModelOptions(), and model::model_GetDailyPrecipValue().
integer (kind=T_INT),parameter types::CONFIG_RUNOFF_CURVE_NUMBER = 0
Definition at line 818 of file types.F90.
Referenced by control::control_setModelOptions(), and model::rf_model_CellRunoff().
integer (kind=T_INT),parameter types::CONFIG_RUNOFF_DOWNHILL = 1
Definition at line 823 of file types.F90.
Referenced by control::control_setModelOptions(), model::model_ProcessRunoff(), and model::model_Solve().
integer (kind=T_INT),parameter types::CONFIG_RUNOFF_GREEN_AMPT = 1
Definition at line 819 of file types.F90.
Referenced by control::control_setModelOptions(), and model::rf_model_CellRunoff().
integer (kind=T_INT),parameter types::CONFIG_RUNOFF_ITERATIVE = 0
Definition at line 822 of file types.F90.
Referenced by control::control_setModelOptions(), and model::model_ProcessRunoff().
integer (kind=T_INT),parameter types::CONFIG_RUNOFF_NO_ROUTING = 2
Definition at line 824 of file types.F90.
Referenced by control::control_setModelOptions(), model::model_InitializeFlowDirection(), model::model_ProcessRunoff(), model::model_Solve(), and sm_thornthwaite_mather::sm_thornthwaite_mather_UpdateSM().
integer (kind=T_INT),parameter types::CONFIG_SM_CAPACITY_CALCULATE = 0
Definition at line 859 of file types.F90.
Referenced by control::control_setModelOptions(), and model::model_InitializeSM().
integer (kind=T_INT),parameter types::CONFIG_SM_CAPACITY_CONSTANT = 1
Definition at line 860 of file types.F90.
integer (kind=T_INT),parameter types::CONFIG_SM_CAPACITY_FM_TABLE = 2
Definition at line 861 of file types.F90.
Referenced by control::control_setModelOptions().
integer (kind=T_INT),parameter types::CONFIG_SM_INIT_ABSTRACTION_HAWKINS = 1
Definition at line 869 of file types.F90.
Referenced by control::control_setModelOptions(), and runoff_curve_number::runoff_CellRunoff_CurveNumber().
integer (kind=T_INT),parameter types::CONFIG_SM_INIT_ABSTRACTION_TR55 = 0
Definition at line 868 of file types.F90.
Referenced by control::control_setModelOptions(), and runoff_curve_number::runoff_CellRunoff_CurveNumber().
integer (kind=T_INT),parameter types::CONFIG_SM_NONE = 0
Definition at line 864 of file types.F90.
Referenced by model::model_InitializeSM(), and model::model_ProcessSM().
integer (kind=T_INT),parameter types::CONFIG_SM_THORNTHWAITE_MATHER = 1
Definition at line 865 of file types.F90.
Referenced by control::control_setModelOptions(), model::model_InitializeSM(), and model::model_ProcessSM().
integer (kind=T_INT),parameter types::CONFIG_SNOW_NEW_SWB = 1
Definition at line 856 of file types.F90.
Referenced by control::control_setModelOptions(), and model::model_Solve().
integer (kind=T_INT),parameter types::CONFIG_SNOW_ORIGINAL_SWB = 0
Definition at line 855 of file types.F90.
Referenced by control::control_setModelOptions(), and model::model_Solve().
integer (kind=T_INT),parameter types::CONFIG_TEMPERATURE_ARC_GRID = 1
Definition at line 842 of file types.F90.
Referenced by control::control_setModelOptions(), and model::model_GetDailyTemperatureValue().
integer (kind=T_INT),parameter types::CONFIG_TEMPERATURE_NETCDF = 3
Definition at line 844 of file types.F90.
Referenced by control::control_setModelOptions(), and model::model_GetDailyTemperatureValue().
integer (kind=T_INT),parameter types::CONFIG_TEMPERATURE_SINGLE_STATION = 0
Definition at line 841 of file types.F90.
Referenced by control::control_setModelOptions(), and model::model_GetDailyTemperatureValue().
integer (kind=T_INT),parameter types::CONFIG_TEMPERATURE_SURFER_GRID = 2
Definition at line 843 of file types.F90.
Referenced by control::control_setModelOptions(), and model::model_GetDailyTemperatureValue().
integer (kind=T_INT),parameter types::iACT_ET = 19
Definition at line 534 of file types.F90.
Referenced by sm_thornthwaite_mather::sm_thornthwaite_mather_UpdateSM(), and swb_stats::stats_WriteMSBReport().
integer(kind=T_INT),parameter types::iANNUAL = 3
Definition at line 815 of file types.F90.
Referenced by control::control_setModelOptions(), swb_stats::stats_CalcMeanRecharge(), and swb_stats::stats_RewriteGrids().
integer (kind=T_INT),parameter types::iAVG_TEMP = 7
Definition at line 522 of file types.F90.
Referenced by sm_thornthwaite_mather::sm_thornthwaite_mather_UpdateSM().
integer(kind=T_INT),parameter types::iBOTH = 3
Definition at line 371 of file types.F90.
Referenced by control::control_setModelOptions(), and swb_stats::stats_RewriteGrids().
integer (kind=T_INT),parameter types::iCFGI = 4
Definition at line 519 of file types.F90.
Referenced by sm_thornthwaite_mather::sm_thornthwaite_mather_UpdateSM().
integer (kind=T_INT),parameter types::iCHG_IN_SNOW_COV = 8
Definition at line 523 of file types.F90.
Referenced by sm_thornthwaite_mather::sm_thornthwaite_mather_UpdateSM(), and swb_stats::stats_WriteMSBReport().
integer (kind=T_INT),parameter types::iCHG_IN_SOIL_MOIST = 25
Definition at line 540 of file types.F90.
Referenced by sm_thornthwaite_mather::sm_thornthwaite_mather_UpdateSM(), and swb_stats::stats_WriteMSBReport().
integer(kind=T_INT),parameter types::iDAILY = 1
Definition at line 813 of file types.F90.
Referenced by control::control_setModelOptions(), and swb_stats::stats_RewriteGrids().
integer(kind=T_INT),public types::iENDDATE_POS
Definition at line 85 of file types.F90.
Referenced by model::model_EndOfRun(), and swb_stats::stats_OpenBinaryFiles().
integer(kind=T_INT),public types::iENDHEADER_POS
Definition at line 86 of file types.F90.
Referenced by swb_stats::stats_OpenBinaryFiles(), and swb_stats::stats_RewriteGrids().
integer(kind=T_INT),parameter types::iEOF = HUGE(iZERO)
Definition at line 82 of file types.F90.
Referenced by RLE::RLE_writeByte().
integer (kind=T_INT),parameter,public types::iFIELD_WIDTH = 10
Definition at line 78 of file types.F90.
Referenced by swb_grid::grid_WriteArcGrid().
integer (kind=T_INT),parameter types::iGDD = 27
Definition at line 542 of file types.F90.
Referenced by sm_thornthwaite_mather::sm_thornthwaite_mather_UpdateSM().
integer(kind=T_INT),parameter types::iGRAPH = 2
Definition at line 370 of file types.F90.
Referenced by control::control_setModelOptions(), swb_stats::stats_RewriteGrids(), swbread(), and swbstats().
integer(kind=T_INT),parameter types::iGRID = 1
Definition at line 369 of file types.F90.
Referenced by control::control_setModelOptions(), swb_stats::stats_RewriteGrids(), swbread(), and swbstats().
integer (kind=T_INT),parameter types::iGRID_LENGTH_UNITS_FEET = 1
Definition at line 204 of file types.F90.
Referenced by control::control_setModelOptions(), netcdf_support::netcdf_write_attributes(), and swb_stats::stats_InitializeVolumeConversion().
integer (kind=T_INT),parameter types::iGRID_LENGTH_UNITS_METERS = 0
define parameter values for working with type T_GENERAL_GRID
Definition at line 203 of file types.F90.
Referenced by control::control_setModelOptions(), and swb_stats::stats_InitializeVolumeConversion().
integer (kind=T_INT),parameter types::iGROSS_PRECIP = 1
Definition at line 516 of file types.F90.
Referenced by control::control_setModelOptions(), model::model_GetDailyPrecipValue(), sm_thornthwaite_mather::sm_thornthwaite_mather_UpdateSM(), and swb_stats::stats_WriteMSBReport().
integer (kind=T_INT),parameter types::iINFLOW = 12
Definition at line 527 of file types.F90.
Referenced by sm_thornthwaite_mather::sm_thornthwaite_mather_UpdateSM(), and swb_stats::stats_WriteMSBReport().
integer (kind=T_INT),parameter types::iINTERCEPTION = 10
Definition at line 525 of file types.F90.
Referenced by sm_thornthwaite_mather::sm_thornthwaite_mather_UpdateSM(), and swb_stats::stats_WriteMSBReport().
integer (kind=T_INT),parameter types::iIRRIGATION = 28
Definition at line 543 of file types.F90.
Referenced by sm_thornthwaite_mather::sm_thornthwaite_mather_UpdateSM().
integer (kind=T_INT),parameter types::iLENGTH = 5
Definition at line 513 of file types.F90.
Referenced by swb_stats::stats_InitializeDailyAccumulators(), and swb_stats::stats_UpdateAllAccumulatorsByCell().
integer (kind=T_INT),parameter types::iMAX = 3
Definition at line 511 of file types.F90.
Referenced by swb_stats::stats_FormatTextString(), swb_stats::stats_InitializeDailyAccumulators(), swb_stats::stats_UpdateAllAccumulatorsByCell(), swb_stats::stats_UpdateAllAccumulatorsByGrid(), and swb_stats::stats_WriteDailyAccumulatorValuesCSV().
integer (kind=T_INT),parameter types::iMAX_TEMP = 6
Definition at line 521 of file types.F90.
Referenced by control::control_setModelOptions(), model::model_GetDailyTemperatureValue(), and sm_thornthwaite_mather::sm_thornthwaite_mather_UpdateSM().
integer (kind=T_INT),parameter types::iMEAN = 2
Definition at line 510 of file types.F90.
Referenced by swb_stats::stats_InitializeDailyAccumulators(), swb_stats::stats_UpdateAllAccumulatorsByCell(), swb_stats::stats_UpdateAllAccumulatorsByGrid(), swb_stats::stats_WriteAnnualAccumulatorValuesCSV(), and swb_stats::stats_WriteDailyAccumulatorValuesCSV().
integer (kind=T_INT),parameter types::iMIN = 1
Definition at line 509 of file types.F90.
Referenced by swb_stats::stats_FormatTextString(), swb_stats::stats_InitializeDailyAccumulators(), swb_stats::stats_UpdateAllAccumulatorsByCell(), swb_stats::stats_UpdateAllAccumulatorsByGrid(), and swb_stats::stats_WriteDailyAccumulatorValuesCSV().
integer (kind=T_INT),parameter types::iMIN_TEMP = 5
Definition at line 520 of file types.F90.
Referenced by control::control_setModelOptions(), model::model_GetDailyTemperatureValue(), and sm_thornthwaite_mather::sm_thornthwaite_mather_UpdateSM().
integer(kind=T_INT),parameter types::iMONTHLY = 2
Definition at line 814 of file types.F90.
Referenced by control::control_setModelOptions(), and swb_stats::stats_RewriteGrids().
integer (kind=T_INT),parameter,public types::iMOVING_AVG_TERMS = 5
Definition at line 72 of file types.F90.
Referenced by model::model_ProcessRunoff().
integer (kind=T_INT),parameter,public types::iNC_INPUT = 1
Definition at line 89 of file types.F90.
Referenced by control::control_setModelOptions(), model::model_GetDailyPrecipValue(), and model::model_GetDailyTemperatureValue().
integer (kind=T_INT),parameter,public types::iNC_OBSERVATION = 3
Definition at line 91 of file types.F90.
integer (kind=T_INT),parameter,public types::iNC_OUTPUT = 2
Definition at line 90 of file types.F90.
Referenced by model::model_EndOfRun(), model::model_write_NetCDF_attributes(), and sm_thornthwaite_mather::sm_thornthwaite_mather_UpdateSM().
integer (kind=T_INT),parameter types::iNET_INFIL = 17
Definition at line 532 of file types.F90.
Referenced by sm_thornthwaite_mather::sm_thornthwaite_mather_UpdateSM().
integer (kind=T_INT),parameter types::iNET_INFLOW = 16
Definition at line 531 of file types.F90.
Referenced by sm_thornthwaite_mather::sm_thornthwaite_mather_UpdateSM().
integer (kind=T_INT),parameter types::iNET_PRECIP = 11
Definition at line 526 of file types.F90.
Referenced by sm_thornthwaite_mather::sm_thornthwaite_mather_UpdateSM(), and swb_stats::stats_WriteMSBReport().
integer (kind=T_INT),parameter,public types::iNO_DATA_NCDC = -99999
Definition at line 76 of file types.F90.
Referenced by model::model_Solve().
integer(kind=T_INT),parameter types::iNONE = 0
Definition at line 368 of file types.F90.
Referenced by control::control_setModelOptions(), model::model_EndOfRun(), model::model_ProcessRain(), model::model_ProcessRainPRMS(), model::model_Solve(), model::model_write_NetCDF_attributes(), sm_thornthwaite_mather::sm_thornthwaite_mather_UpdateSM(), swb_stats::stats_CloseBinaryFiles(), swb_stats::stats_OpenBinaryFiles(), swb_stats::stats_RewriteGrids(), swbread(), and swbstats().
integer (kind=T_INT),parameter,public types::iNUM_DIGITS = 3
Definition at line 77 of file types.F90.
Referenced by swb_grid::grid_WriteArcGrid().
integer (kind=T_INT),parameter types::iNUM_MONTHS = 12
Definition at line 366 of file types.F90.
integer (kind=T_INT),parameter types::iNUM_STATS = 5
Definition at line 508 of file types.F90.
integer (kind=T_INT),parameter types::iNUM_VARIABLES = 29
Definition at line 376 of file types.F90.
Referenced by control::control_setModelOptions(), model::model_EndOfRun(), model::model_Solve(), model::model_write_NetCDF_attributes(), sm_thornthwaite_mather::sm_thornthwaite_mather_UpdateSM(), swb_stats::stats_CloseBinaryFiles(), swb_stats::stats_DumpAnnualAccumulatorValues(), swb_stats::stats_DumpDailyAccumulatorValues(), swb_stats::stats_DumpMonthlyAccumulatorValues(), swb_stats::stats_OpenBinaryFiles(), swb_stats::stats_RewriteGrids(), swb_stats::stats_WriteAnnualAccumulatorHeaderCSV(), swb_stats::stats_WriteAnnualAccumulatorValuesCSV(), swb_stats::stats_WriteDailyAccumulatorHeaderCSV(), and swb_stats::stats_WriteDailyAccumulatorValuesCSV().
integer (kind=T_INT),parameter types::iOUTFLOW = 13
Definition at line 528 of file types.F90.
Referenced by sm_thornthwaite_mather::sm_thornthwaite_mather_UpdateSM(), and swb_stats::stats_WriteMSBReport().
integer (kind=T_INT),parameter types::iP_MINUS_PET = 20
Definition at line 535 of file types.F90.
Referenced by sm_thornthwaite_mather::sm_thornthwaite_mather_UpdateSM().
integer (kind=T_INT),parameter types::iPOT_ET = 18
Definition at line 533 of file types.F90.
Referenced by sm_thornthwaite_mather::sm_thornthwaite_mather_UpdateSM().
integer (kind=T_INT),parameter types::iRECHARGE = 26
Definition at line 541 of file types.F90.
Referenced by sm_thornthwaite_mather::sm_thornthwaite_mather_UpdateSM(), swb_stats::stats_CalcMeanRecharge(), and swb_stats::stats_WriteMSBReport().
integer (kind=T_INT),parameter types::iREJECTED_RECHARGE = 15
Definition at line 530 of file types.F90.
Referenced by sm_thornthwaite_mather::sm_thornthwaite_mather_UpdateSM(), and swb_stats::stats_WriteMSBReport().
integer (kind=T_INT),parameter,public types::iROUTE_CELL_MARKED = -1
Definition at line 73 of file types.F90.
Referenced by model::model_ConfigureRunoffDownhill().
integer (kind=T_INT),parameter,public types::iROUTE_DEPRESSION = -999
Definition at line 74 of file types.F90.
Referenced by model::if_model_RunoffIteration(), model::model_DownstreamCell(), model::model_InitializeFlowDirection(), model::model_RunoffDownhill(), and sm_thornthwaite_mather::sm_thornthwaite_mather_UpdateSM().
integer (kind=T_INT),parameter,public types::iROUTE_LEFT_GRID = -1000
Definition at line 75 of file types.F90.
Referenced by model::if_model_RunoffIteration(), model::model_DownstreamCell(), model::model_InitializeFlowDirection(), model::model_RunoffDownhill(), and sm_thornthwaite_mather::sm_thornthwaite_mather_UpdateSM().
integer (kind=T_INT),parameter types::iRUNOFF_OUTSIDE = 14
Definition at line 529 of file types.F90.
Referenced by sm_thornthwaite_mather::sm_thornthwaite_mather_UpdateSM(), and swb_stats::stats_WriteMSBReport().
integer (kind=T_INT),parameter types::iSM_APWL = 23
Definition at line 538 of file types.F90.
Referenced by sm_thornthwaite_mather::sm_thornthwaite_mather_UpdateSM().
integer (kind=T_INT),parameter types::iSM_DEFICIT = 21
Definition at line 536 of file types.F90.
Referenced by sm_thornthwaite_mather::sm_thornthwaite_mather_UpdateSM().
integer (kind=T_INT),parameter types::iSM_SURPLUS = 22
Definition at line 537 of file types.F90.
Referenced by sm_thornthwaite_mather::sm_thornthwaite_mather_UpdateSM().
integer (kind=T_INT),parameter types::iSNOWCOVER = 3
Definition at line 518 of file types.F90.
Referenced by sm_thornthwaite_mather::sm_thornthwaite_mather_UpdateSM(), and swb_stats::stats_WriteMSBReport().
integer (kind=T_INT),parameter types::iSNOWFALL = 2
Definition at line 517 of file types.F90.
Referenced by sm_thornthwaite_mather::sm_thornthwaite_mather_UpdateSM(), and swb_stats::stats_WriteMSBReport().
integer (kind=T_INT),parameter types::iSNOWMELT = 9
Definition at line 524 of file types.F90.
Referenced by sm_thornthwaite_mather::sm_thornthwaite_mather_UpdateSM(), and swb_stats::stats_WriteMSBReport().
integer (kind=T_INT),parameter types::iSOIL_MOISTURE = 24
Definition at line 539 of file types.F90.
Referenced by sm_thornthwaite_mather::sm_thornthwaite_mather_UpdateSM(), and swb_stats::stats_WriteMSBReport().
integer(kind=T_INT),public types::iSTARTDATE_POS
Definition at line 84 of file types.F90.
Referenced by model::model_Solve(), and swb_stats::stats_OpenBinaryFiles().
integer(kind=T_INT),parameter types::iSTATS = 4
Definition at line 372 of file types.F90.
Referenced by swbstats().
integer (kind=T_INT),parameter types::iSTREAM_CAPTURE = 29
Definition at line 545 of file types.F90.
Referenced by sm_thornthwaite_mather::sm_thornthwaite_mather_UpdateSM(), and swb_stats::stats_WriteMSBReport().
integer (kind=T_INT),parameter types::iSUM = 4
Definition at line 512 of file types.F90.
Referenced by swb_stats::stats_DumpAnnualAccumulatorValues(), swb_stats::stats_DumpDailyAccumulatorValues(), swb_stats::stats_DumpMonthlyAccumulatorValues(), swb_stats::stats_FormatTextString(), swb_stats::stats_InitializeDailyAccumulators(), swb_stats::stats_UpdateAllAccumulatorsByCell(), swb_stats::stats_UpdateAllAccumulatorsByGrid(), swb_stats::stats_WriteMSBReport(), and swbstats().
integer (kind=T_INT),parameter,public types::iZERO = 0
Definition at line 79 of file types.F90.
logical (kind=T_LOGICAL),parameter,public types::lFALSE = .false._T_LOGICAL
Definition at line 81 of file types.F90.
Referenced by approx_equal_dbl(), approx_equal_sgl(), swbstats_support::CalcBasinStats(), Chomp(), control::control_setModelOptions(), swb_grid::grid_Conform(), swb_grid::grid_Destroy(), swb_grid::grid_Read(), swb_grid::grid_ReadArcGrid(), swb_grid::grid_ReadSurferGrid(), graph::make_shaded_contour(), graph::makegraph(), model::model_GetDailyPrecipValue(), model::model_GetDailyTemperatureValue(), model::model_GetDynamicLanduseValue(), model::model_InitializeMaxInfil(), model::model_InitializeSM(), model::model_ProcessRain(), model::model_ProcessRunoff(), model::model_ReadBasinMaskTable(), model::model_ReadLanduseLookupTable(), model::model_ReadTimeSeriesFile(), model::model_Solve(), netcdf_support::netcdf_check(), netcdf_support::netcdf_chk_extent(), netcdf_support::netcdf_info(), netcdf_support::netcdf_read(), swbstats_support::ReadBasinMaskTable(), model::rf_model_CellRunoff_GreenAmpt(), RLE::RLE_readByte(), RLE::RLE_writeByte(), runoff_curve_number::runoff_CellRunoff_CurveNumber(), sm_thornthwaite_mather::sm_thornthwaite_mather_UpdateSM(), and swb_stats::stats_InitializeVolumeConversion().
logical (kind=T_LOGICAL),parameter,public types::lTRUE = .true._T_LOGICAL
Definition at line 80 of file types.F90.
Referenced by approx_equal_dbl(), approx_equal_sgl(), Chomp(), swb_grid::grid_Conform(), swb_grid::grid_ReadArcGrid(), model::model_ConfigureRunoffDownhill(), model::model_InitializeMaxInfil(), model::model_InitializeSM(), model::model_ProcessRain(), model::model_ReadTimeSeriesFile(), netcdf_support::netcdf_chk_extent(), RLE::RLE_readByte(), RLE::RLE_writeByte(), swbread(), and swbstats().
integer (kind=T_INT),parameter,public types::LU_BIN_FILE = 106
Definition at line 35 of file types.F90.
integer (kind=T_INT),parameter,public types::LU_CONTROL = 100
Definition at line 29 of file types.F90.
Referenced by control::control_setModelOptions().
integer (kind=T_INT),parameter,public types::LU_CSV = 108
Definition at line 37 of file types.F90.
Referenced by model::model_EndOfRun(), and model::model_Solve().
integer (kind=T_INT),parameter,public types::LU_CSV_ANNUAL = 110
Definition at line 39 of file types.F90.
Referenced by model::model_EndOfRun(), and model::model_Solve().
integer (kind=T_INT),parameter,public types::LU_CSV_SERIES = 109
Definition at line 38 of file types.F90.
integer (kind=T_INT),parameter,public types::LU_GRID = 101
Definition at line 30 of file types.F90.
Referenced by swb_grid::grid_ReadArcGrid(), and swb_grid::grid_ReadSurferGrid().
integer (kind=T_INT),parameter,public types::LU_LOG = 117
Definition at line 46 of file types.F90.
Referenced by Assert(), swbstats_support::CalcBasinStats(), control::control_setModelOptions(), et_blaney_criddle::et_bc_configure(), et_blaney_criddle::et_bc_initialize(), et_hargreaves::et_hargreaves_configure(), et_hargreaves::et_hargreaves_initialize(), et_jensen_haise::et_jh_configure(), et_jensen_haise::et_jh_initialize(), et_thornthwaite_mather::et_tm_configure(), et_thornthwaite_mather::et_tm_initialize(), et_turc::et_turc_configure(), et_turc::et_turc_initialize(), swb_grid::grid_Create(), swb_grid::grid_ReadArcGrid(), model::model_ConfigureRunoffDownhill(), model::model_EndOfRun(), model::model_GetDynamicLanduseValue(), model::model_InitializeET(), model::model_InitializeFlowDirection(), model::model_InitializeMaxInfil(), model::model_InitializeSM(), model::model_ReadBasinMaskTable(), model::model_ReadLanduseLookupTable(), model::model_ReadTimeSeriesFile(), model::model_Solve(), model::model_write_NetCDF_attributes(), netcdf_support::netcdf_chk_extent(), netcdf_support::netcdf_create(), netcdf_support::netcdf_info(), netcdf_support::netcdf_open(), netcdf_support::netcdf_write_attributes(), swbstats_support::ReadBasinMaskTable(), runoff_curve_number::runoff_InitializeCurveNumber(), sm_thornthwaite_mather::sm_thornthwaite_mather_Configure(), sm_thornthwaite_mather::sm_thornthwaite_mather_Initialize(), sm_thornthwaite_mather::sm_thornthwaite_mather_UpdateSM(), swb_stats::stats_CalcBasinStats(), swb_stats::stats_CalcMeanRecharge(), swb_stats::stats_CalcMeanRechargebyLU(), swb_stats::stats_CloseBinaryFiles(), swb_stats::stats_OpenBinaryFiles(), swb_stats::stats_RewriteGrids(), swbread(), and swbstats().
integer (kind=T_INT),parameter,public types::LU_LOOKUP = 102
Definition at line 31 of file types.F90.
Referenced by model::model_ReadLanduseLookupTable().
integer (kind=T_INT),parameter,public types::LU_MASK = 111
Definition at line 40 of file types.F90.
Referenced by model::model_ReadBasinMaskTable(), and swbstats_support::ReadBasinMaskTable().
integer (kind=T_INT),parameter,public types::LU_MASK_FILE = 112
Definition at line 41 of file types.F90.
Referenced by swbstats_support::CalcBasinStats(), and swb_stats::stats_CalcBasinStats().
integer (kind=T_INT),parameter,public types::LU_MASK_STATS_CSV = 113
Definition at line 42 of file types.F90.
Referenced by swb_stats::stats_CalcBasinStats().
integer (kind=T_INT),parameter,public types::LU_MSB_REPORT = 105
Definition at line 34 of file types.F90.
Referenced by model::model_EndOfRun(), model::model_Solve(), and swb_stats::stats_WriteMSBReport().
integer (kind=T_INT),parameter,public types::LU_PEST_INS = 116
Definition at line 45 of file types.F90.
Referenced by swb_stats::stats_CalcBasinStats().
integer (kind=T_INT),parameter,public types::LU_PEST_OBS = 115
Definition at line 44 of file types.F90.
Referenced by swb_stats::stats_CalcBasinStats().
integer (kind=T_INT),parameter,public types::LU_PEST_STATS = 114
Definition at line 43 of file types.F90.
Referenced by swbstats_support::CalcBasinStats(), and swb_stats::stats_CalcBasinStats().
integer (kind=T_INT),parameter,public types::LU_ROUTING = 107
Definition at line 36 of file types.F90.
Referenced by model::model_ConfigureRunoffDownhill().
integer (kind=T_INT),parameter,public types::LU_STD_OUT = 6
I/O Units.
Definition at line 28 of file types.F90.
Referenced by Assert(), model::model_ConfigureRunoffDownhill(), model::model_Solve(), swb_stats::stats_DumpAnnualAccumulatorValues(), swb_stats::stats_DumpDailyAccumulatorValues(), swb_stats::stats_DumpMonthlyAccumulatorValues(), swbread(), and swbstats().
integer (kind=T_INT),parameter,public types::LU_TEMP = 104
Definition at line 33 of file types.F90.
Referenced by et_thornthwaite_mather::et_tm_initialize(), swb_grid::grid_WriteArcGrid(), and swb_grid::grid_WriteSurferGrid().
integer (kind=T_INT),parameter,public types::LU_TS = 103
Definition at line 32 of file types.F90.
Referenced by control::control_setModelOptions(), model::model_EndOfRun(), model::model_ReadTimeSeriesFile(), and model::model_Solve().
integer (kind=T_INT),parameter types::OUTPUT_ARC = 1
Definition at line 877 of file types.F90.
Referenced by control::control_setModelOptions(), and model::model_WriteGrids().
integer (kind=T_INT),parameter types::OUTPUT_SURFER = 0
Definition at line 876 of file types.F90.
Referenced by control::control_setModelOptions(), model::model_WriteGrids(), swb_stats::stats_RewriteGrids(), swbread(), and swbstats().
real (kind=T_SGL),parameter,public types::rBIGVAL = 1.0e20_T_SGL
Definition at line 83 of file types.F90.
Referenced by control::control_setModelOptions().
real (kind=T_DBL),parameter,public types::rC_PER_F = 5.0_T_DBL / 9.0_T_DBL
Definition at line 65 of file types.F90.
Referenced by FtoC(), FtoK(), and model::model_ProcessRain().
real (kind=T_SGL),parameter,public types::rCM_PER_INCH = 2.54_T_SGL
Definition at line 68 of file types.F90.
Referenced by model::model_ProcessRainPRMS(), and model::model_UpdateContinuousFrozenGroundIndex().
real (kind=T_DBL),parameter,public types::rD_ONE = 1.0_T_DBL
Definition at line 60 of file types.F90.
Referenced by sm_thornthwaite_mather::sm_thornthwaite_mather_Initialize().
real (kind=T_DBL),parameter,public types::rD_ZERO = 0.0_T_DBL
Definition at line 54 of file types.F90.
Referenced by model::model_ProcessRain(), model::model_ProcessRainPRMS(), sm_thornthwaite_mather::sm_thornthwaite_mather_Initialize(), and sm_thornthwaite_mather::sm_thornthwaite_mather_UpdateSM().
real (kind=T_DBL),parameter,public types::rF_PER_C = 9.0_T_DBL / 5.0_T_DBL
Definition at line 66 of file types.F90.
Referenced by CtoF().
real (kind=T_SGL),parameter,public types::rFREEZING = 32.0_T_SGL
Definition at line 61 of file types.F90.
Referenced by CtoF(), et_blaney_criddle::et_bc_ComputeET(), et_jensen_haise::et_jh_ComputeET(), et_thornthwaite_mather::et_tm_ComputeET(), et_thornthwaite_mather::et_tm_initialize(), et_turc::et_turc_ComputeET(), FtoC(), FtoK(), model::model_ProcessRain(), and model::model_UpdateContinuousFrozenGroundIndex().
real (kind=T_SGL),parameter,public types::rHALF = 0.5_T_SGL
Definition at line 57 of file types.F90.
Referenced by swb_grid::grid_ReadArcGrid().
real (kind=T_SGL),parameter,public types::rHUNDRED = 100.0_T_SGL
Definition at line 63 of file types.F90.
Referenced by et_blaney_criddle::et_bc_ComputeET(), et_jensen_haise::et_jh_ComputeET(), et_turc::et_turc_ComputeET(), runoff_curve_number::runoff_UpdateCurveNumber(), sm_thornthwaite_mather::sm_thornthwaite_mather_Initialize(), and sm_thornthwaite_mather::sm_thornthwaite_mather_UpdateSM().
real (kind=T_SGL),parameter,public types::rMM_PER_INCH = 25.4_T_SGL
Definition at line 67 of file types.F90.
Referenced by et_hargreaves::ET0_hargreaves(), et_blaney_criddle::et_bc_ComputeET(), mm_to_in(), and model::model_ProcessRain().
real (kind=T_SGL),parameter,public types::rNEAR_ZERO = 1E-9_T_SGL
Definition at line 55 of file types.F90.
Referenced by control::control_setModelOptions(), model::model_ProcessET(), model::model_ProcessRainPRMS(), model::model_RunoffDownhill(), real2char(), runoff_curve_number::runoff_UpdateCurveNumber(), sm_thornthwaite_mather::sm_thornthwaite_mather_Initialize(), sm_thornthwaite_mather::sm_thornthwaite_mather_UpdateSM(), and swb_stats::stats_FormatTextString().
real (kind=T_SGL),parameter,public types::rONE = 1.0_T_SGL
Definition at line 59 of file types.F90.
Referenced by control::control_setModelOptions(), et_jensen_haise::et_jh_ComputeET(), et_turc::et_turc_ComputeET(), swb_grid::grid_Interpolate(), swb_grid::grid_LookupColumn(), swb_grid::grid_LookupRow(), swb_grid::grid_SearchColumn(), model::model_ProcessRainPRMS(), model::model_RunoffDownhill(), meteorological_functions::net_shortwave_radiation_Rns(), netcdf_support::netcdf_write_attributes(), runoff_curve_number::prob_runoff_enhancement(), sm_thornthwaite_mather::sm_thornthwaite_mather_Initialize(), sm_thornthwaite_mather::sm_thornthwaite_mather_UpdateSM(), and swb_stats::stats_InitializeVolumeConversion().
real (kind=T_DBL),parameter,public types::rPI = 3.14159265_T_DBL
Definition at line 69 of file types.F90.
Referenced by meteorological_functions::daylight_hours(), meteorological_functions::deg2rad(), et_blaney_criddle::et_bc_ComputeET(), et_blaney_criddle::et_bc_initialize(), et_thornthwaite_mather::et_tm_ComputeET(), meteorological_functions::extraterrestrial_radiation_Ra(), netcdf_support::LLtoUTM(), model::model_UpdateContinuousFrozenGroundIndex(), meteorological_functions::rel_Earth_Sun_dist(), meteorological_functions::solar_declination(), and netcdf_support::UTMtoLL().
real (kind=T_SGL),parameter,public types::rPOINT2 = 0.2_T_SGL
Definition at line 56 of file types.F90.
Referenced by runoff_curve_number::runoff_CellRunoff_CurveNumber().
real (kind=T_SGL),parameter,public types::rPOINT8 = 0.8_T_SGL
Definition at line 58 of file types.F90.
Referenced by runoff_curve_number::runoff_CellRunoff_CurveNumber().
real (kind=T_DBL),parameter,public types::rSQM_to_SQFT = 10.76391_T_DBL
Definition at line 71 of file types.F90.
Referenced by swb_stats::stats_InitializeVolumeConversion().
real (kind=T_SGL),parameter,public types::rTEN = 10.0_T_SGL
Definition at line 62 of file types.F90.
Referenced by runoff_curve_number::runoff_CellRunoff_CurveNumber().
real (kind=T_SGL),parameter,public types::rTHOUSAND = 1000.0_T_SGL
Definition at line 64 of file types.F90.
Referenced by runoff_curve_number::runoff_CellRunoff_CurveNumber().
real (kind=T_DBL),parameter,public types::rTWOPI = 2.0_T_DBL * rPI
Definition at line 70 of file types.F90.
Referenced by et_blaney_criddle::et_bc_ComputeET(), et_blaney_criddle::et_bc_configure(), et_blaney_criddle::et_bc_initialize(), et_hargreaves::et_hargreaves_configure(), et_jensen_haise::et_jh_ComputeET(), et_jensen_haise::et_jh_configure(), et_thornthwaite_mather::et_tm_ComputeET(), et_thornthwaite_mather::et_tm_configure(), et_turc::et_turc_ComputeET(), and et_turc::et_turc_configure().
real (kind=T_SGL),parameter,public types::rZERO = 0.0_T_SGL
Some useful typed constants (to ensure accurate computations)
Definition at line 53 of file types.F90.
Referenced by control::control_setModelOptions(), et_hargreaves::ET0_hargreaves(), et_blaney_criddle::et_bc_ComputeET(), et_jensen_haise::et_jh_ComputeET(), et_thornthwaite_mather::et_tm_ComputeET(), et_thornthwaite_mather::et_tm_initialize(), et_turc::et_turc_ComputeET(), swb_grid::grid_Create(), swb_grid::grid_LookupColumn(), swb_grid::grid_LookupRow(), model::if_model_RunoffIteration(), model::model_GetDailyPrecipValue(), model::model_ProcessET(), model::model_ProcessRain(), model::model_ProcessRainPRMS(), model::model_ProcessRunoff(), model::model_Runoff_NoRouting(), model::model_RunoffDownhill(), model::model_UpdateContinuousFrozenGroundIndex(), meteorological_functions::precipitation_heat_p(), runoff_curve_number::prob_runoff_enhancement(), model::rf_model_CellRunoff(), model::rf_model_GetInterception(), runoff_curve_number::runoff_CellRunoff_CurveNumber(), runoff_curve_number::runoff_UpdateCurveNumber(), sm_thornthwaite_mather::sm_thornthwaite_mather_Initialize(), sm_thornthwaite_mather::sm_thornthwaite_mather_UpdateSM(), snow::snow_energy_balance(), swb_stats::stats_FormatTextString(), swb_stats::stats_InitializeAnnualAccumulators(), swb_stats::stats_InitializeDailyAccumulators(), swb_stats::stats_InitializeMonthlyAccumulators(), swb_stats::stats_RewriteGrids(), swbread(), and swbstats().
character (len=1),parameter,public types::sBACKSLASH = achar(92)
Definition at line 49 of file types.F90.
character (len=7),parameter types::sBLUE = char(27)//'[1;34m'
Definition at line 98 of file types.F90.
character (len=7),parameter types::sBOLDWHITE = char(27)//'[1;37m'
Definition at line 101 of file types.F90.
Referenced by model::model_Solve(), and swb_stats::stats_FormatTextString().
character (len=7),parameter types::sCLRSCR = char(27)//'[2J'
Definition at line 102 of file types.F90.
character (len=7),parameter types::sCYAN = char(27)//'[1;36m'
Definition at line 99 of file types.F90.
character (len=1),parameter,public types::sFORWARDSLASH = achar(47)
Definition at line 50 of file types.F90.
character (len=7),parameter types::sGREEN = char(27)//'[1;32m'
Definition at line 96 of file types.F90.
Referenced by swb_stats::stats_DumpMonthlyAccumulatorValues(), and swb_stats::stats_FormatTextString().
character (len=256),public types::sLogBuffer
Definition at line 342 of file types.F90.
character (len=7),parameter types::sRED = char(27)//'[1;31m'
Define ANSI.sys-like text colors.
Definition at line 95 of file types.F90.
Referenced by swb_stats::stats_FormatTextString().
character (len=1),parameter,public types::sTAB = achar(9)
Definition at line 48 of file types.F90.
Referenced by swbstats_support::CalcBasinStats(), and swb_stats::stats_CalcBasinStats().
type (T_STATS),dimension(inum_variables) types::STAT_INFO = (/ T_STATS ('GROSS_PRECIP',201,2,0,lTRUE,lTRUE, 'inches','gross precipitation', 1.,0.0, iNONE,iNONE,iNONE,iNONE), T_STATS ('SNOWFALL',202,0,1,lTRUE,lTRUE, 'inches','precipitation falling as snow', 1.,0.0, iNONE,iNONE,iNONE,iNONE), T_STATS ('SNOWCOVER',203,2,0,lFALSE,lTRUE, 'inches','water equivalent of snow cover', 1.,0.0, iNONE,iNONE,iNONE,iNONE), T_STATS ('CFGI',204,2,0,lFALSE,lFALSE, 'unitless','continuous frozen ground index', 1.,0.0, iNONE,iNONE,iNONE,iNONE), T_STATS ('MIN_TEMP',205,2,0,lFALSE,lFALSE, 'degrees F','minimum daily air temperature', 1.,0.0, iNONE,iNONE,iNONE,iNONE), T_STATS ('MAX_TEMP',206,2,0,lFALSE,lFALSE, 'degrees F','maximum daily air temperature', 1.,0.0, iNONE,iNONE,iNONE,iNONE), T_STATS ('AVG_TEMP',207,2,0,lFALSE,lFALSE, 'degrees F','mean daily air temperature', 1.,0.0, iNONE,iNONE,iNONE,iNONE), T_STATS ('CHG_IN_SNOW_COV',208,0,-1,lTRUE,lTRUE, 'inches','snowfall minus snowmelt', 1.,0.0, iNONE,iNONE,iNONE,iNONE), T_STATS ('SNOWMELT',209,2,0,lTRUE,lTRUE, 'inches','snowmelt', 1.,0.0, iNONE,iNONE,iNONE,iNONE), T_STATS ('INTERCEPTION',210,2,0,lTRUE,lTRUE, 'inches','interception', 1.,0.0, iNONE,iNONE,iNONE,iNONE), T_STATS ('NET_PRECIP',211,0,1,lTRUE,lTRUE, 'inches','gross precipitation minus interception', 1.,0.0, iNONE,iNONE,iNONE,iNONE), T_STATS ('INFLOW',212,0,1,lTRUE,lTRUE, 'inches','incoming flow from adjacent cells', 1.,0.0, iNONE,iNONE,iNONE,iNONE), T_STATS ('OUTFLOW',213,0,-1,lTRUE,lTRUE, 'inches','outgoing flow to adjacent cells', 1.,0.0, iNONE,iNONE,iNONE,iNONE), T_STATS ('RUNOFF_OUTSIDE',214,0,-1,lTRUE,lTRUE, 'inches','runoff leaving model domain', 1.,0.0, iNONE,iNONE,iNONE,iNONE), T_STATS ('REJECTED_RECHARGE',215,0,-1,lTRUE,lTRUE, 'inches','recharge exceeding max recharge rate', 1.,0.0, iNONE,iNONE,iNONE,iNONE), T_STATS ('NET_INFLOW',216,2,0,lTRUE,lTRUE, 'inches','sum of net precip and inflow', 1.,0.0, iNONE,iNONE,iNONE,iNONE), T_STATS ('NET_INFIL',217,2,0,lTRUE,lTRUE, 'inches','precip and inflow minus outflow', 1.,0.0, iNONE,iNONE,iNONE,iNONE), T_STATS ('POT_ET',218,2,0,lTRUE,lTRUE, 'inches','potential evapotranspiration', 1.,0.0, iNONE,iNONE,iNONE,iNONE), T_STATS ('ACT_ET',219,0,-1,lTRUE,lTRUE, 'inches','actual evapotranspiration', 1.,0.0, iNONE,iNONE,iNONE,iNONE), T_STATS ('P_MINUS_PET',220,2,0,lTRUE,lFALSE, 'inches','net inflow minus potential et', 1.,0.0, iNONE,iNONE,iNONE,iNONE), T_STATS ('SM_DEFICIT',221,2,0,lTRUE,lFALSE, 'inches','daily soil moisture deficit', 1.,0.0, iNONE,iNONE,iNONE,iNONE), T_STATS ('SM_SURPLUS',222,2,0,lTRUE,lFALSE, 'inches','daily soil moisture surplus', 1.,0.0, iNONE,iNONE,iNONE,iNONE), T_STATS ('SM_APWL',223,2,0,lFALSE,lFALSE, 'inches','accumulated potential water loss', 1.,0.0, iNONE,iNONE,iNONE,iNONE), T_STATS ('SOIL_MOISTURE',224,2,0,lFALSE,lTRUE, 'inches','daily soil moisture', 1.,0.0, iNONE,iNONE,iNONE,iNONE), T_STATS ('CHG_IN_SOIL_MOIS',225,0,-1,lTRUE,lTRUE, 'inches','daily change in soil moisture', 1.,0.0, iNONE,iNONE,iNONE,iNONE), T_STATS ('RECHARGE',226,0,-1,lTRUE,lTRUE, 'inches','daily potential recharge', 1.,0.0, iNONE,iNONE,iNONE,iNONE), T_STATS ('GDD',227,2,0,lFALSE,lFALSE, 'degree-day','growing degree day', 1.,0.0, iNONE,iNONE,iNONE,iNONE), T_STATS ('IRRIGATION_AMOUNT',228,0,1,lTRUE,lTRUE, 'inches','daily estimated irrigation amount', 1.,0.0, iNONE,iNONE,iNONE,iNONE) ,T_STATS ('STREAM_CAPTURE',229,0,-1,lTRUE,lTRUE, 'inches','runoff or recharge captured by a stream or fracture', 1.,0.0, iNONE,iNONE,iNONE,iNONE)/)
Definition at line 382 of file types.F90.
Referenced by control::control_setModelOptions(), model::model_EndOfRun(), model::model_ProcessRain(), model::model_ProcessRainPRMS(), model::model_Solve(), model::model_write_NetCDF_attributes(), sm_thornthwaite_mather::sm_thornthwaite_mather_UpdateSM(), swb_stats::stats_CloseBinaryFiles(), swb_stats::stats_DumpAnnualAccumulatorValues(), swb_stats::stats_DumpDailyAccumulatorValues(), swb_stats::stats_DumpMonthlyAccumulatorValues(), swb_stats::stats_FormatTextString(), swb_stats::stats_OpenBinaryFiles(), swb_stats::stats_RewriteGrids(), swb_stats::stats_WriteAnnualAccumulatorHeaderCSV(), swb_stats::stats_WriteDailyAccumulatorHeaderCSV(), swbread(), and swbstats().
integer (kind=T_INT),parameter types::STREAM_INTERACTIONS_MAX = 100
Definition at line 548 of file types.F90.
character (len=7),parameter types::sWHITE = char(27)//'[0;37m'
Definition at line 100 of file types.F90.
Referenced by model::model_Solve(), swb_stats::stats_DumpAnnualAccumulatorValues(), swb_stats::stats_DumpDailyAccumulatorValues(), swb_stats::stats_DumpMonthlyAccumulatorValues(), and swb_stats::stats_FormatTextString().
character (len=7),parameter types::sYELLOW = char(27)//'[1;33m'
Definition at line 97 of file types.F90.
Referenced by swb_stats::stats_DumpAnnualAccumulatorValues(), swb_stats::stats_DumpDailyAccumulatorValues(), and swb_stats::stats_DumpMonthlyAccumulatorValues().
integer,parameter,public types::T_BYTE = 1
Definition at line 19 of file types.F90.
integer (kind=T_INT),parameter,public types::T_CELL_GRID = 2
Definition at line 178 of file types.F90.
Referenced by control::control_setModelOptions(), swb_grid::grid_Create(), swb_grid::grid_Destroy(), graph::make_shaded_contour(), and graph::makegraph().
integer,parameter,public types::T_DBL = SELECTED_REAL_KIND(p=13, r=200)
Definition at line 25 of file types.F90.
integer,parameter,public types::T_INT = 4
Definition at line 17 of file types.F90.
Referenced by control::control_setModelOptions(), swb_grid::grid_GetGridColNum(), swb_grid::grid_GetGridRowNum(), model::model_InitializeMaxInfil(), swb_stats::stats_CalcBasinStats(), and swb_stats::stats_CalcMeanRechargebyLU().
integer (kind=T_INT),parameter,public types::T_INT_GRID = 0
Definition at line 176 of file types.F90.
Referenced by control::control_setModelOptions(), swb_grid::grid_Create(), swb_grid::grid_Destroy(), swb_grid::grid_ReadArcGrid(), swb_grid::grid_ReadSurferGrid(), graph::make_shaded_contour(), graph::makegraph(), model::model_ConfigureRunoffDownhill(), and model::model_GetDynamicLanduseValue().
integer,parameter,public types::T_LOGICAL = 4
Define the sizes of base types used in the model.
Definition at line 16 of file types.F90.
integer,parameter,public types::T_SGL = SELECTED_REAL_KIND(p=6, r=37)
Define machine-independent sizes for base types.
Definition at line 24 of file types.F90.
integer,parameter,public types::T_SGL_DISLIN = 4
Definition at line 20 of file types.F90.
integer (kind=T_INT),parameter,public types::T_SGL_GRID = 1
Definition at line 177 of file types.F90.
Referenced by control::control_setModelOptions(), swb_grid::grid_Create(), swb_grid::grid_Destroy(), swb_grid::grid_ReadArcGrid(), swb_grid::grid_ReadSurferGrid(), graph::make_shaded_contour(), graph::makegraph(), model::model_GetDailyPrecipValue(), model::model_GetDailyTemperatureValue(), netcdf_support::netcdf_read(), swbstats_support::ReadBasinMaskTable(), sm_thornthwaite_mather::sm_thornthwaite_mather_Configure(), swb_stats::stats_CalcBasinStats(), swb_stats::stats_CalcMeanRecharge(), swb_stats::stats_CalcMeanRechargebyLU(), swb_stats::stats_RewriteGrids(), swbread(), and swbstats().
integer,parameter,public types::T_SHORT = 2
Definition at line 18 of file types.F90.
type (T_MONTH),dimension(12),target types::YEAR_INFO = (/ T_MONTH('JAN','JANUARY ', 1, 31, 1, 31), T_MONTH('FEB','FEBRUARY ', 32, 59, 2, 29), T_MONTH('MAR','MARCH ', 60, 90, 3, 31), T_MONTH('APR','APRIL ', 91, 120, 4, 30), T_MONTH('MAY','MAY ', 121, 151, 5, 31), T_MONTH('JUN','JUNE ', 152, 181, 6, 30), T_MONTH('JUL','JULY ', 182, 212, 7, 31), T_MONTH('AUG','AUGUST ', 213, 243, 8, 31), T_MONTH('SEP','SEPTEMBER', 244, 273, 9, 30), T_MONTH('OCT','OCTOBER ', 274, 304, 10, 31), T_MONTH('NOV','NOVEMBER ', 305, 334, 11, 30), T_MONTH('DEC','DECEMBER ', 335, 365, 12, 31) /)
Month information.
Definition at line 327 of file types.F90.
Referenced by julian_day(), LookupMonth(), and swb_stats::stats_RewriteGrids().