program tests

  ! Driver program for FRUIT unit tests in:
  ! test_datetime.F90

  ! Generated by FRUITPy.

  use fruit
  use test_datetime

  implicit none

  call init_fruit

  call run_test_case(test_datetime_basic_dateparse,"test_datetime_basic_dateparse")

  call fruit_summary
  call fruit_finalize

end program tests