message("--------------------------------------------------------------------")
message("   Summary of CMAKE environment variables")
message("--------------------------------------------------------------------")
message("BUILD TYPE: " ${CMAKE_BUILD_TYPE})
message( " ")
message("CMAKE_HOST_WIN32: " ${CMAKE_HOST_WIN32})
message("CMAKE_HOST_APPLE: " ${CMAKE_HOST_APPLE})
message("CMAKE_Fortran_COMPILER full path: " ${CMAKE_Fortran_COMPILER})
message("Fortran compiler    : " ${Fortran_COMPILER_NAME})
message("Fortran compiler ID : " ${CMAKE_Fortran_COMPILER_ID})
message("CMAKE Fortran flags (Debug):      " ${CMAKE_Fortran_FLAGS_DEBUG})
message("CMAKE Fortran flags (Profile):      " ${CMAKE_Fortran_FLAGS_PROFILE})
message("CMAKE Fortran flags (Release):      " ${CMAKE_Fortran_FLAGS_RELEASE})
message(" ")
message("CMAKE_Fortran_COMPILER_ID:  ${CMAKE_Fortran_COMPILER_ID}")
message( " ")
MESSAGE("Install to directory: " ${CMAKE_INSTALL_PREFIX})
message(" ")
message("LD_LIBRARY_PATH    : ${LD_LIBRARY_PATH}")
message("NETCDF_LIBRARY     : ${NETCDF_LIBRARY}")
message("NETCDF4_C_ROOT     : ${NETCDF4_C_ROOT}")
message("HDF5_LIBRARY       : ${HDF5_LIBRARY}")
message("HDF5_HL_LIBRARY    : ${HDF5_HL_LIBRARY}")
message("ZLIB_LIBRARY       : ${ZLIB_LIBRARY}")
message("SZIP_LIBRARY       : ${SZIP_LIBRARY}")
message("CURL_LIBRARY       : ${CURL_LIBRARY}")
message("DISLIN_MODFILE     : ${DISLIN_MODFILE}")
message("DISLIN_LIBRARY     : ${DISLIN_LIBRARY}")
message(" ")
message("CMAKE_BINARY_DIR: " ${CMAKE_BINARY_DIR})
message("CMAKE_CURRENT_SOURCE_DIR: " ${CMAKE_CURRENT_SOURCE_DIR})
message("PROJECT_SOURCE_DIR: " ${PROJECT_SOURCE_DIR})
message( " ")
message("--------------------------------------------------------------------")
