
message("--------------------------------------------------------------------")
message("   Summary of CMAKE environment variables")
message("--------------------------------------------------------------------")
message("BUILD TYPE: " ${CMAKE_BUILD_TYPE})
message( " ")
message("CMAKE_HOST_WIN32: " ${CMAKE_HOST_WIN32})
message("CMAKE_HOST_APPLE: " ${CMAKE_HOST_APPLE})
message("CMAKE_Fortran_COMPILER full path: " ${CMAKE_Fortran_COMPILER})
message("Fortran compiler: " ${Fortran_COMPILER_NAME})
message("CMAKE Fortran flags (Debug):      " ${CMAKE_Fortran_FLAGS_DEBUG})
message("CMAKE Fortran flags (Profile):      " ${CMAKE_Fortran_FLAGS_PROFILE})
message("CMAKE Fortran flags (Release):      " ${CMAKE_Fortran_FLAGS_RELEASE})
message( " ")
MESSAGE("Install to directory: " ${CMAKE_INSTALL_PREFIX})
message(" ")
message("Include directory: ")
message(" ==> ${SWB_INCPATH}")
message("Library location for SWB external libraries:")
message(" ==> ${SWB_LIBPATH}")
message("Library locations for compiler-related external libraries:")
message(" ==> ${LIB_PATH}")

message(" ")
message("LIBRARIES (universal):")
message("  GFORTRAN  ${LIBGFORTRAN}")
message("  GCC       ${LIBGCC}")
message("  EXTERNAL_LIBS:")
message("  ${EXTERNAL_LIBS}")

message("  DISLIN    ${LIBDISLIN}")
message("    OPENGL32  ${LIBOPENGL}")
message("    GDI32     ${LIBGDI32}")
message("    Xm        ${LIBXM}")

message(" ")
message("CMAKE_BINARY_DIR: " ${CMAKE_BINARY_DIR})
message("CMAKE_CURRENT_SOURCE_DIR: " ${CMAKE_CURRENT_SOURCE_DIR})
message("PROJECT_SOURCE_DIR: " ${PROJECT_SOURCE_DIR})
message( " ")
message("--------------------------------------------------------------------")
