del /Q output\annual\*.*
del /Q output\monthly\*.*
del /Q output\daily\*.*
del /Q output\*.*
del /Q output\future\*.*
del /Q images\annual\*.*
del /Q images\monthly\*.*
del /Q images\daily\*.*
del /Q images\*.*
del /Q *.csv
del /Q *.asc
del /Q *.png
del /Q ANNUAL*.txt
del /Q SWB_LOGFILE*.txt
